New: Use database change streams when available
RocketChat/Rocket.Chat pull request #18892
Opened 2020-09-14 01:03 UTC by rodrigok

## Proposed changes

## Issue(s)

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

## Further comments

2020-09-21 21:56 UTC, sampaiodiego requested changes

2020-09-21 21:56 UTC, sampaiodiego commented on app/settings/server/observer.js
> +export const updateValue = (id, fields) => {
since the `observer` was removed from this file, this function could be moved as well and the file could be deleted..

2020-09-21 21:56 UTC, sampaiodiego commented on app/settings/server/raw.js
> +import { Settings } from '../../models/server/models/Settings';
I didn't find a `getValueById` defined at `../../models/server/models/Settings`.. is this change correct?

2020-09-21 21:56 UTC, sampaiodiego commented on app/search/server/events/events.js
> +settings.get('Search.Provider', _.debounce((key, value) => {
why isn't "lint" complaining about `key` and `value` variables not being used? 🤔

2020-09-22 01:46 UTC, sampaiodiego requested changes
* when running a mongodb version not compatible with change streams, if I don't set `MONGO_OPLOG_URL` I get the following error:
```
(node:29097) UnhandledPromiseRejectionWarning: Error: URL malformed, cannot be parsed
    at module.exports (/Users/diegosampaio/dev/Rocket.Chat/node_modules/mongodb/lib/url_parser.js:18:21)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at internal/util.js:296:12
    at app/models/server/models/_oplogHandle.ts:35:27
    at /Users/diegosampaio/.meteor/packages/promise/.0.11.2.1xavwef.9sbp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

2020-09-22 02:36 UTC, sampaiodiego approved these changes

2020-09-22 03:03 UTC, merged

2020-09-22 11:59 UTC, ankar84 commented
Looks like breaking changes improve performance a lot.
Good job!