[Apps] Add a new upload API: createUpload
RocketChat/Rocket.Chat pull request #18955
Opened 2020-09-18 15:54 UTC by lolimay

## Proposed changes

Add a new upload API `createUpload` under the upload bridge

## Issue(s)

https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/318

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

## Further comments

2020-09-18 15:55 UTC, lolimay commented
Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/318

2020-09-18 22:08 UTC, d-gubert commented on package.json
> +		"clean": "^4.0.2",
```suggestion
```

2020-09-18 22:09 UTC, d-gubert submitted a review, later dismissed

2020-09-18 23:31 UTC, d-gubert approved these changes

2020-09-21 13:18 UTC, sampaiodiego requested changes

2020-09-21 13:18 UTC, sampaiodiego commented on app/file-upload/server/lib/FileUpload.js
> +		if (canAccessRoom(room, user, file) !== true && user.type !== 'app') {
`canAccessRoom` is a heavy operation, if app users will bypass it, we can bypass calling it:
```suggestion
		if (user.type !== 'app' && canAccessRoom(room, user, file) !== true) {
```

2020-09-22 01:20 UTC, d-gubert commented
@lolimay @thassiov @sampaiodiego currently, this does **not** send a message to the specified room after the file is uploaded. Should we do this? Or should we leave it as a responsibility for the app to send it?

2020-09-22 01:53 UTC, sampaiodiego commented
> @lolimay @thassiov @sampaiodiego currently, this does **not** send a message to the specified room after the file is uploaded. Should we do this? Or should we leave it as a responsibility for the app to send it?

in rocket.chat there is no API to send a file to a room without sending a message, IMHO this behavior should be applied to the engine as well

2020-09-22 02:52 UTC, sampaiodiego approved these changes

2020-09-22 03:00 UTC, merged