[FIX][APPS] cryptic "cannot read 'data' of undefined" when listing apps in a server without internet connection
RocketChat/Rocket.Chat pull request #19088
Opened 2020-09-30 22:27 UTC by thassiov

## Proposed changes

Fixes a message that appears when the user is trying to enter the `Admin -> Apps` page in a server with no internet connection. The message "Could not reach the Marketplace to get App info" is shown to the user to inform of the situation. 

## Issue(s)

## How to test or reproduce

- Take the Rocket.Chat box offline (no internet)|
- Go to Administration -> Apps (the messages appear in the red toast)

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

## Further comments

2020-09-30 22:51 UTC, thassiov commented on app/apps/server/communication/rest.js
> +		};
Move the function up to avoid "used before declared" issues

2020-10-01 14:37 UTC, d-gubert commented
I wonder how useful it is to show this message in an airgapped env.... @RocketChat/backend @RocketChat/frontend do you have an idea of how we could ignore it properly? Assuming we can't simply not show this kind of error because it might be legit in non-airgapped envs

2020-10-01 19:25 UTC, sampaiodiego commented
maybe that's an UX issue? if instead of showing a error toast we actually show a yellow banner saying "we couldn't reach official marketplace, listing installed apps only" that can be dismissed it would be good enough?

2020-10-01 22:41 UTC, d-gubert commented
> show a yellow banner saying "we couldn't reach official marketplace, listing installed apps only" that can be dismissed

It looks like a good solution in my opinion

2020-10-19 23:04 UTC, pierre-lehnen-rc submitted a review, later dismissed

2020-10-22 14:12 UTC, sampaiodiego commented
> > show a yellow banner saying "we couldn't reach official marketplace, listing installed apps only" that can be dismissed
> 
> It looks like a good solution in my opinion

should we merge that way it is and do what was proposed here as an improvement later on?

2020-10-23 20:05 UTC, d-gubert commented
The latest changes do not apply the suggestion?

2020-10-26 14:14 UTC, sampaiodiego requested changes
During my tests in my local instance, turning off wi-fi and opening either Apps or Marketplace screens still gave me "cannot read property data of undefined"

2020-10-27 01:47 UTC, sampaiodiego approved these changes

2020-10-27 01:52 UTC, merged