[IMPROVE] display channel avatar in top bar
RocketChat/Rocket.Chat pull request #19132
Opened 2020-10-05 18:20 UTC by bhavayAnand9

## Proposed changes

channel avatar was not appearing in the top bar unlike direct message

## Issue(s)

#19083 

## How to test or reproduce

## Screenshots
![image](https://user-images.githubusercontent.com/34943807/95116583-df55d380-0764-11eb-9097-80bd01b0ca6d.png)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules

## Changelog

display channel avatar in top bar

## Further comments

2020-10-05 18:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=19132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=19132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=19132) it.</sub>

2020-10-12 16:31 UTC, bhavayAnand9 commented
Hi! @gabriellsh Can you please review this PR? Thanks

2020-10-13 15:21 UTC, ggazzo requested changes
could you remove the `isDirect` from `helpers` since we don't use anymore? thanks :)

2020-10-13 22:51 UTC, ggazzo approved these changes

2020-10-13 22:52 UTC, merged