[FIX] #19237 - Translations for select setting in App Setting
RocketChat/Rocket.Chat pull request #19238
Opened 2020-10-13 15:03 UTC by murtaza98

## Proposed changes

## Issue(s)

Fixes #19237
## How to test or reproduce

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

## Further comments

2020-10-15 18:38 UTC, d-gubert commented
Hey @murtaza98 ! This change doesn't require modifications in the Apps-Engine?

2020-10-15 18:51 UTC, murtaza98 commented
Hey @d-gubert Nopes. Translation are handled on core  so no changes to apps engine will be required 😁

2020-10-15 19:09 UTC, d-gubert commented
Ok! Can you provide an example of what the settings config in the app would look like for this to work?

2020-10-19 06:30 UTC, murtaza98 commented
Hi @d-gubert Here is a sample app zip file. Hope it helps u to understand the bug. 
[multi-select-translations-sample_0.0.1.zip](https://github.com/RocketChat/Rocket.Chat/files/5399521/multi-select-translations-sample_0.0.1.zip)

Btw, Sorry for the delay :see_no_evil:

2020-10-20 15:56 UTC, lolimay requested changes
LGTM overall 👍

2020-10-20 15:56 UTC, lolimay commented on client/admin/apps/AppSettings.js
> +	if (values) {
```suggestion
	if (values?.length) {
```

2020-10-27 22:39 UTC, d-gubert approved these changes

2021-12-09 14:57 UTC, murtaza98 commented
Closing in favour of https://github.com/RocketChat/Rocket.Chat/pull/23908

2021-12-09 14:57 UTC, closed without merging