[NEW] Replace emitter
RocketChat/Rocket.Chat pull request #19368
Opened 2020-10-26 15:47 UTC by tiagoevanp

## Proposed changes

## Issue(s)

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

## Further comments

2020-10-26 18:46 UTC, gabriellsh requested changes
Hey! You're missing the following file `client/contexts/AuthorizationContext.ts` and removing the following package: `@types/wolfy87-eventemitter`. Please update the package-lock too.

2020-10-26 20:09 UTC, tiagoevanp commented
You're right @gabriellsh.

Can you please review again now?

2020-10-26 20:10 UTC, gabriellsh submitted a review, later dismissed

2020-10-27 04:45 UTC, tassoevan requested changes

2020-10-27 04:45 UTC, tassoevan commented on client/lib/presence.js
> +		Presence.once('restart', () => { console.log('entrei'); return Presence.events().filter((e) => Boolean(e) && !['reset', 'restart', 'remove'].includes(e) && typeof e === 'string').forEach(get); });
```suggestion
		Presence.once('restart', () => Presence.events().filter((e) => Boolean(e) && !['reset', 'restart', 'remove'].includes(e) && typeof e === 'string').forEach(get));
```

2020-10-27 17:17 UTC, tassoevan approved these changes

2020-10-27 17:41 UTC, merged