[FIX] File Tab Order
RocketChat/Rocket.Chat pull request #19729
Opened 2020-12-01 19:49 UTC by MartinSchoeler

## Proposed changes

## Issue(s)
Closes https://github.com/RocketChat/Rocket.Chat/issues/17885
## How to test or reproduce

## Screenshots

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

## Further comments

2020-12-02 17:56 UTC, tassoevan submitted a review, later dismissed

2020-12-02 19:49 UTC, tassoevan requested changes

2020-12-02 19:49 UTC, tassoevan commented on app/ui-flextab/client/tabs/uploadedFilesList.js
> +		files = files.sort((a, b) => Date.parse(b.uploadedAt) - Date.parse(a.uploadedAt));
```suggestion
		const { files } = await APIClient.v1.get(`${ roomTypes[room.t] }.files?roomId=${ query.rid }&limit=${ limit }&query=${ JSON.stringify(query) }&fields=${ JSON.stringify(fields) }&sort=${ JSON.stringify({ uploadedAt: -1 }) }`);
```

It should override the default `{ name: 1 }`.

2020-12-04 12:17 UTC, ggazzo approved these changes

2020-12-04 12:17 UTC, merged