Rewrite Room Header
RocketChat/Rocket.Chat pull request #19808
Opened 2020-12-09 03:08 UTC by ggazzo

## Proposed changes

## Issue(s)

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Hotfix (a major bugfix that has to be merged asap)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Changelog

## Further comments

2020-12-10 20:57 UTC, wreiske commented
I'm not sure if this is related or not but on open.rocket.chat it looks like the user info is broken on the sidebar.

![lURXsvrzhn](https://user-images.githubusercontent.com/6295044/101829068-a97bf500-3aef-11eb-8b01-9140ca82a505.gif)

2020-12-17 20:59 UTC, tassoevan submitted a review, later dismissed

2020-12-21 21:50 UTC, MartinSchoeler requested changes
- [ ] Files List Gives this error: 
<img width="514" alt="Empty Files Bar" src="https://user-images.githubusercontent.com/20868078/102825136-f77cdc80-43bc-11eb-92b0-294bb510cac4.png">

- [ ] Some empty sidebar text misaligned: 
<img width="403" alt="Screen Shot 2020-12-21 at 6 17 24 PM" src="https://user-images.githubusercontent.com/20868078/102825251-28f5a800-43bd-11eb-97ee-a7136d1668fd.png">

- [ ] I can set a date later in `from` than in `to`:
<img width="402" alt="Screen Shot 2020-12-21 at 6 45 29 PM" src="https://user-images.githubusercontent.com/20868078/102825345-55a9bf80-43bd-11eb-8a02-c406908209b3.png">

- [ ] There seems to be an issue with turning on the autotranslate feature, nothing happens and when I refresh it turns back to disabled

- [ ] Error when setting a room moderator/owner: 
<img width="359" alt="Screen Shot 2020-12-21 at 7 25 46 PM" src="https://user-images.githubusercontent.com/20868078/102828105-9a842500-43c2-11eb-9fe5-bef638a26250.png">

2020-12-22 00:16 UTC, gabriellsh approved these changes

2020-12-22 00:45 UTC, merged