[FIX] Omnichannel Analytics Page
RocketChat/Rocket.Chat pull request #19899
Opened 2020-12-18 20:45 UTC by murtaza98

## Proposed changes (including videos or screenshots)

## Issue(s)

1. Fix layout not rendering properly. Following was the layout which was getting rendered 
    **BEFORE**
    ![image](https://user-images.githubusercontent.com/34130764/102658610-e3a75f80-419d-11eb-8c6c-ca22d4f870c1.png)
    **AFTER**
    ![image](https://user-images.githubusercontent.com/34130764/102659792-0470b480-41a0-11eb-8ac9-98d3e262ea92.png)

2. Handle some edge cases for date select
![image](https://user-images.githubusercontent.com/34130764/102658793-4698f680-419e-11eb-9546-25255d5512d6.png)

- When we select `This Month`, then it should set the end date to **current date** instead of the last date of the month
- Earlier when we were using [`date.toISOString()`](https://github.com/RocketChat/Rocket.Chat/blob/5c23deecbe95d2cfec1f76f30ede3fb6af0dfc64/client/views/omnichannel/analytics/DateRangePicker.js#L9), under my timezone it was converting start of the month incorrectly. Please have a look in the below console
![image](https://user-images.githubusercontent.com/34130764/102659395-5402b080-419f-11eb-8a8e-7c3093cad176.png)
To solve :top: error, I've converted the code to use `moment` library.

## Steps to test or reproduce

## Further comments

2020-12-18 22:53 UTC, rafaelblink approved these changes
Everything working well.

2020-12-21 21:41 UTC, renatobecker commented
![Screen Shot 2020-12-21 at 18 40 36](https://user-images.githubusercontent.com/59577424/102824711-22b2fc00-43bc-11eb-93fe-bd607a52f3a9.png)

@murtaza98 this is the design expected.

2020-12-21 21:43 UTC, renatobecker requested changes
![Screen Shot 2020-12-21 at 18 40 36](https://user-images.githubusercontent.com/59577424/102824847-5ee65c80-43bc-11eb-9af3-2849f7f34151.png)

@murtaza98 this is the design expected.

```
I20201221-18:35:31.564(-3)? Incorrect chart options
I20201221-18:35:31.571(-3)? livechat:getAnalyticsOverviewData => Invalid dates
I20201221-18:35:31.576(-3)? Incorrect analytics options
```

2021-01-13 12:55 UTC, renatobecker requested changes

2021-01-13 12:55 UTC, renatobecker commented on client/views/omnichannel/analytics/InterchangeableChart.js
> +			if (params.daterange.from && params.daterange.to) {
```suggestion
			if (!params?.daterange?.from || !params?.daterange?.to) {
				return;
			}
				
			const result = await loadData(params);
			if (!result?.chartLabel || !result?.dataLabels !! !result?.dataPoints)) {
				return console.log('livechat:getAnalyticsChartData => Missing Data');
			}

			context.current = await drawLineChart(canvas.current, context.current, [result.chartLabel], result.dataLabels, [result.dataPoints]);

```

2021-01-13 12:55 UTC, renatobecker commented on client/views/omnichannel/analytics/InterchangeableChart.js
> +					return console.log('livechat:getAnalyticsChartData => Missing Data');
There is no reason to display this message on the console log, if something went wrong we should alert the user via notification.

2021-01-14 12:25 UTC, renatobecker commented
@murtaza98 I'm still facing this inconsistency

![Screen Shot 2021-01-14 at 09 22 10](https://user-images.githubusercontent.com/59577424/104590667-6a8b1300-564a-11eb-945b-864cfea9f858.png)

2021-01-14 17:23 UTC, murtaza98 commented
> @murtaza98 I'm still facing this inconsistency
> 
> ![Screen Shot 2021-01-14 at 09 22 10](https://user-images.githubusercontent.com/59577424/104590667-6a8b1300-564a-11eb-945b-864cfea9f858.png)

@renatobecker This bug hasn't been fixed yet. I wasn't able to determine the issue :disappointed: . I'll still need to do some more debugging specifically with mongo queries.

2021-01-14 19:52 UTC, renatobecker approved these changes

2021-01-14 19:54 UTC, merged