[IMPROVE] Adds tooltip for sidebar header icons
RocketChat/Rocket.Chat pull request #19934
Opened 2020-12-22 09:50 UTC by RonLek

## Proposed changes (including videos or screenshots)

Previously the header icons in the sidebar didn't show a tooltip when hovered over. This PR fixes that.

![Screenshot from 2020-12-22 15-17-41](https://user-images.githubusercontent.com/28918901/102874804-f2756700-4468-11eb-8324-b7f3194e62fe.png)

## Issue(s)

Closes #19908

2020-12-22 09:52 UTC, RonLek commented
@dougfabris do you think it would be a good idea to replace the sort icon with something more intuitive since it represents more than just sort (for example, view modes and group by)? Would love to hear your thoughts on this.

2020-12-22 12:19 UTC, dougfabris requested changes
> @dougfabris do you think it would be a good idea to replace the sort icon with something more intuitive since it represents more than just sort (for example, view modes and group by)? Would love to hear your thoughts on this.

Well, for now, we shouldn't replace the icon. Just replace the title for **Filters**, I think it can be more descriptive.

2020-12-22 12:19 UTC, dougfabris commented on client/sidebar/header/index.js
> +					<CreateRoom title='Create' data-qa='sidebar-create' />
I think it's better to use "Create Room"

2020-12-22 14:51 UTC, RonLek commented
Thanks! @dougfabris. Made the changes.

2020-12-22 17:09 UTC, dougfabris commented
@RonLek Thank you for helping us =)

2020-12-22 17:12 UTC, dougfabris approved these changes

2020-12-22 23:48 UTC, ggazzo requested changes
hey thanks for your time, can I ask you to use translations instead of the raw text? 

look for `useTranslation`

2020-12-23 06:15 UTC, RonLek commented
@ggazzo Definitely! For the ones not already having translations in languages other than English should I add them in this PR itself or raise a different one similar to [this](https://github.com/RocketChat/Rocket.Chat/pull/19916)?

2020-12-25 23:32 UTC, dougfabris commented
@RonLek as these translations are related to the fix I think it's no problem to add in this PR.

2020-12-27 19:59 UTC, RonLek commented
Thanks! @dougfabris . Added translations in this PR itself : )

2021-01-04 15:08 UTC, RonLek commented
@dougfabris @ggazzo do let me know if any changes required. 

Even though the translations are double-checked should translations be done only in English for the time being in this PR since we're taking in native speakers' contributions for translations? 

Awaiting your views on this one : )

2021-01-12 14:09 UTC, ggazzo commented
@RonLek  I would ask you to do not create one more key, please use `Create_A_New_Channel` instead of `Create_Room `

2021-01-12 15:20 UTC, RonLek commented
Thanks @ggazzo! I've made the changes  :)

2021-01-12 18:15 UTC, RonLek commented
Thanks @ggazzo. I've made the changes. Please review.

2021-01-26 11:52 UTC, RonLek commented
@dougfabris @ggazzo please take a look :)

2021-02-09 13:03 UTC, ggazzo commented
@RonLek can I ask you from where did you get the translations? I'm not very fluent in some of them :p just to be sure that makes sense

2021-02-09 15:34 UTC, RonLek commented
@ggazzo Definitely! All of the translations have been taken up from Google Translate after a double-check. 

What I mean by a double-check is that if "Home" translates to "Casa" in Spanish, then I've reverse translated "Casa" to English and seen if that checks out back to "Home" and only then inserted the translation for the word (skipped in cases it didn't). The reason for this is that I'm aware Google Translate might not capture the context of the word when just a single word is entered for translation but doing a reverse-check confirms if the translation was correct.

Let me know what you think : )

2021-02-09 17:04 UTC, ggazzo commented
Ok, `casa` in portuguese means home as well but still I'm not sure if is a common usage for that word... but no problem thanks

2021-02-09 17:04 UTC, merged