Title for user avatar change buttons
RocketChat/Rocket.Chat pull request #20083
Opened 2021-01-06 15:08 UTC by sushant52

## Proposed changes (including videos or screenshots)

Made user avatar change buttons to be descriptive of what they do.

## Issue(s)

Closes Issue [#20082](https://github.com/RocketChat/Rocket.Chat/issues/20082) 

####Initially
![gif_without_title](https://user-images.githubusercontent.com/54909147/103783758-218dfa00-505f-11eb-955d-c2deb50590d8.gif)

####Finally
![gif_with_title](https://user-images.githubusercontent.com/54909147/103783779-26eb4480-505f-11eb-8248-bdcf1fc55f33.gif)

2021-01-06 17:04 UTC, gabriellsh requested changes

2021-01-06 17:04 UTC, gabriellsh commented on client/components/avatar/UserAvatarEditor.js
>  						<Button square mis='none' onClick={clickReset} disabled={disabled} mie='x4'>
```suggestion
						<Button square mis='none' onClick={clickReset} disabled={disabled} mie='x4' title={t('Accounts_SetDefaultAvatar')}>
```

Can you add this title too? Thanks!

2021-01-06 18:23 UTC, sushant52 commented
@gabriellsh Done. Have a look!

2021-01-06 22:02 UTC, gabriellsh approved these changes

2021-01-12 14:27 UTC, ggazzo approved these changes

2021-01-12 14:27 UTC, merged