[FIX] Missing English translation keywords
RocketChat/Rocket.Chat pull request #20131
Opened 2021-01-09 17:39 UTC by Karting06

## Proposed changes (including videos or screenshots)

Add missing translation keys in `en.i18n.json` to be able to translate them via Lingohub.

## Issue(s)

Those translation keys were missing from the English JSON which led to untranslated strings in other languages. 

## Steps to test or reproduce

Use Rocket.Chat in another language and notice the missing translations.

## Further comments

2021-01-11 13:27 UTC, sampaiodiego requested changes
thanks @Karting06 for your contribution.. most of the terms shouldn't be translated because they're actually names and not words.

@ggazzo I saw most of those missing keywords were recently added during the React rewrite. can you please make sure to always add the keys to the English translation files as well? thx

2021-01-11 13:27 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Zapier": "Zapier"
Zapier is the name of a company/product, it shouldn't be translated.

2021-01-11 13:27 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Curl": "Curl",
`curl` is a command, it shouldn't be translated.

2021-01-11 13:27 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "HTML": "HTML",
`HTML` is a markup language and should not be translated

2021-01-11 13:27 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "JSON": "JSON",
`JSON` stands for JavaScript Object Notation and should not be translated.

2021-01-11 13:27 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "OpLog": "OpLog",
`oplog` is MongoDB feature and shouldn't be translated.

2021-01-11 13:27 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "ID": "ID",
`ID` is the contraction for "identifier", not sure it should be translated.

2021-01-11 13:27 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "PID": "PID",
`PID` stands for "process ID" .. not sure it should be translated.

2021-01-11 17:08 UTC, Karting06 commented
Yeah, I know those terms. 
@sampaiodiego, I added them because I found similar terms in the list (`SMTP`, `SAML`). 
I will change it then.

2021-01-15 11:13 UTC, Karting06 commented
Hi @sampaiodiego,
I don't know how to change the `change requested` status. I committed the new changes. 
Should I do somethinge else?

2022-07-29 17:37 UTC, merged