[IMPROVE] Rewrite Announcement as React component
RocketChat/Rocket.Chat pull request #20172
Opened 2021-01-12 15:41 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-01-14 14:48 UTC, gabriellsh requested changes
![image](https://user-images.githubusercontent.com/40830821/104606127-230e8200-565e-11eb-8f10-b66517a5bd2f.png)

![image](https://user-images.githubusercontent.com/40830821/104606207-3f122380-565e-11eb-85cf-18f7f740e67e.png)

Clicking doensn't open the stream.

2021-01-14 14:52 UTC, gabriellsh requested changes
If there's no announcement, and one is added, it's necessary to refresh the page for it to appear.

2021-01-14 15:10 UTC, gabriellsh commented on client/views/room/Announcement/Announcement.js
> +	return announcement && <Announcement onClickOpen={handleClick}>{announcement}</Announcement>;
Missed adding `<Markdown>` here

2021-01-19 16:50 UTC, ggazzo approved these changes

2021-01-19 17:33 UTC, ggazzo approved these changes

2021-01-19 17:35 UTC, merged