[FIX] Added Bio Structure for UserCard, rendering Skeleton View on loading Instead of [Object][Object]
RocketChat/Rocket.Chat pull request #20305
Opened 2021-01-21 17:39 UTC by yash-rajpal

- [x] I have read the Contributing Guide 
  - [x] I have signed the CLA 
  - [x] Lint and unit tests pass locally with my changes
  - I have added tests that prove my fix is effective or that my feature works (if applicable)
  - I have added necessary documentation (if applicable)
  - Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Added Bio Structure for rendering Skeleton View on loading UserCard.

## Issue(s)

fix #20283 
## Steps to test or reproduce

Check the Issue
## Further comments

Until UserCard received bio, it was passing Skeleton as content to Markdown, so it was returning [Object][Object], which was shown to user. So Made one more entity called as bioStructure, now if bio is present, bio will be passed to markdown and everything would work as it is supposed to, but if bio is not present, bioStructure would be rendered as skeletonView.

2021-01-21 18:25 UTC, yash-rajpal commented
I hope the change is visible in GIF.
![bio-structure-after](https://user-images.githubusercontent.com/58601732/105394839-14b6fc00-5c44-11eb-903c-266dd250e44e.gif)

2021-01-22 07:14 UTC, pratyaksh123 commented
You could also do this way :+1: 
`{ bio && (
			<Info withTruncatedText={false} style={clampStyle} height='x60'>
				{typeof bio === 'string' ? <MarkdownText content={bio} /> : bio}
			</Info>
		)}`

2021-01-22 17:52 UTC, MartinSchoeler requested changes
Requested some changes, pratyaksh123 have some neat ideas to handling this. Thanks!

2021-01-22 17:52 UTC, MartinSchoeler commented on client/components/UserCard.js
> +		{bio !== undefined ? bio && <Info withTruncatedText={false} style={clampStyle} height='x60'><MarkdownText content={bio}/></Info> : <Info withTruncatedText={false} style={clampStyle} height='x60'>{b
Maybe instead of doing this ternary, we can check the type of the bio variable inside of the info element?

2021-01-22 18:01 UTC, yash-rajpal commented
@MartinSchoeler Thanks, will do changes asap.

2021-01-25 13:25 UTC, MartinSchoeler approved these changes
Looks good to me!

2021-01-26 15:58 UTC, yash-rajpal commented
@ggazzo Please review. :)

2021-01-27 18:32 UTC, MartinSchoeler commented
@yash-rajpal please be patient, we are currently on a _feature-freeze_ so pull requests that are not directly related to the ones done in the current release, can only be merged on the next release (don't worry we are almost at the end of the _featrue-freeze_).

Mentioning other members of the team will not make it go faster 🙂 

Thanks!

2021-02-02 02:06 UTC, merged