[NEW] Button to unset Slackbridge's importIds
RocketChat/Rocket.Chat pull request #20549
Opened 2021-02-02 02:24 UTC by pierre-lehnen-rc

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-02-12 20:30 UTC, sampaiodiego requested changes
Looks like it is working as expected, except that the button description is not showing on the Admin screen.

2021-02-12 20:30 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "SlackBridge_Remove_Channel_Links_description": "Remove the internal link between Rocket.Chat channels and Slack channels. The links will afterwards be recreated based on the channel names.",
Took me a while to find out why the description was not showing on Settings screen
```suggestion
  "SlackBridge_Remove_Channel_Links_Description": "Remove the internal link between Rocket.Chat channels and Slack channels. The links will afterwards be recreated based on the channel names.",
```

2021-02-12 20:30 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/pt-BR.i18n.json
> +  "Remove_Channel_Links": "Remover relação entre canais",
since you added this one, can you please add a translation for `SlackBridge_Remove_Channel_Links_Description` as well? thx

2021-02-19 13:54 UTC, KevLehman approved these changes

2021-02-19 13:59 UTC, merged