[FIX] Added markdown to custom status in UserInfo
RocketChat/Rocket.Chat pull request #20562
Opened 2021-02-02 12:23 UTC by yash-rajpal

- [x] I have read the Contributing Guide 
  - [x] I have signed the CLA 
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Added markdown to custom status in Memberlist/userInfo

## Issue(s)

N/A
## Steps to test or reproduce

## Further comments

![image](https://user-images.githubusercontent.com/58601732/106599811-99c4de00-657f-11eb-800a-4247e698d7cf.png)

2021-02-04 18:05 UTC, yash-rajpal commented
@ggazzo @MartinSchoeler Please Review. :)

2021-02-19 19:04 UTC, yash-rajpal commented
@ggazzo @dougfabris Please have a look, Thanks :)

2021-03-22 23:46 UTC, ggazzo requested changes

2021-03-22 23:46 UTC, ggazzo commented on client/views/room/contextualBar/UserInfo/index.js
> +			<Info withTruncatedText={false}><MarkdownText content={customStatus} withRichContent={false}/></Info>
```suggestion
			<Info withTruncatedText={false}><MarkdownText content={customStatus}  variant='inline' /></Info>
```

2021-03-23 19:46 UTC, yash-rajpal commented on client/views/room/contextualBar/UserInfo/index.js
> +			<Info withTruncatedText={false}><MarkdownText content={customStatus} withRichContent={false}/></Info>
Done sir. :)

2021-12-01 14:16 UTC, dougfabris approved these changes

2021-12-17 17:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=20562) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=20562) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yash-rajpal<br/>:x: dougfabris<br/><hr/>**dougfabris** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=20562) it.</sub>

2022-04-05 21:03 UTC, yash-rajpal commented
Done!

2022-04-05 21:03 UTC, closed without merging