[FIX] wrong usage of access-control-allow-origin header
RocketChat/Rocket.Chat pull request #20696
Opened 2021-02-11 11:38 UTC by g-thome

## Proposed changes (including videos or screenshots)

always include only one value in access-control-allow-origin

## Issue(s)

Closes #13889

## Steps to test or reproduce

## Further comments

2021-02-12 02:32 UTC, ggazzo requested changes

2021-02-12 02:32 UTC, ggazzo commented on app/api/server/api.js
> +								this.response.setHeader('x-oloco-bixo', 'essa fera ai meu');
```suggestion
								this.response.setHeader('x-oloco-bixo', 'oito e sete galera');
```

2021-02-12 02:34 UTC, g-thome commented on app/api/server/api.js
> +								this.response.setHeader('x-oloco-bixo', 'essa fera ai meu');
oh my

2021-02-20 23:45 UTC, sampaiodiego approved these changes

2021-02-20 23:46 UTC, merged