CSP wip
RocketChat/Rocket.Chat pull request #20724
Opened 2021-02-12 00:38 UTC by ggazzo

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-06-17 20:43 UTC, sampaiodiego requested changes

2021-06-17 20:43 UTC, sampaiodiego commented on app/lib/server/startup/settings.js
> +		secret: true,
```suggestion
```

2021-06-17 20:43 UTC, sampaiodiego commented on app/ui-master/server/inject.ts
> +	if (!content.trim) {
```suggestion
	if (!content.trim()) {
```

2021-06-17 20:43 UTC, sampaiodiego commented on app/ui-master/server/inject.ts
> +	if (!content.trim) {
```suggestion
	if (!content.trim()) {
```

2021-06-17 20:43 UTC, sampaiodiego commented on app/ui-master/server/inject.ts
> +		injectIntoHead(key, '');
```suggestion
		injectIntoHead(`${ key }.css`, '');
```

2021-06-17 20:43 UTC, sampaiodiego commented on app/ui-master/server/inject.ts
> +		injectIntoHead(key, '');
```suggestion
		injectIntoHead(`${ key }.js`, '');
```

2021-06-20 18:33 UTC, sampaiodiego approved these changes

2021-06-20 18:33 UTC, merged

2021-08-16 13:04 UTC, DocDocTeam commented
Updated to 3.16. There was an error Content-Security-Policy 
"Refused to load the script 'https://lib.usedesk.ru/secure.usedesk.ru/widget_111111.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback."

While disabled in the general settings Content-Security-Policy.
The documentation is empty https://github.com/RocketChat/docs/blob/master/guides/administration/administration/settings/setup-wizard.md

1. You write "basically the inline scripts were moved to a js file" - in which one?
2. How do I whitelist my script?