[FIX]Fixed send to channel checkbox in thread.
RocketChat/Rocket.Chat pull request #20721
Opened 2021-02-11 20:50 UTC by Darshilp326

## Proposed changes (including videos or screenshots)

Send to channel checkbox will not be ticked even in the first message of the thread.

https://user-images.githubusercontent.com/55157259/107697008-aad8c200-6cd8-11eb-94b6-2590f52e6de4.mp4

## Issue(s)

Closes #20695 
## Steps to test or reproduce

## Further comments

2021-02-12 00:22 UTC, ggazzo submitted a review, later dismissed
Please create setting under `admin -> threads` and let the old behavior enabled by default

2021-02-12 05:21 UTC, Darshilp326 commented
@ggazzo By old behaviour do you mean to send to the channel by default?

2021-02-25 17:12 UTC, dougfabris commented
> @ggazzo By old behaviour do you mean to send to the channel by default?

@Darshilp326 yeah! he wanted to mean to stay 'send to the channel' by default and create an option on  `admin -> threads` to have a behavior like you did if the admin wants to. Can you help us with that?

2021-02-26 08:15 UTC, Darshilp326 commented
@dougfabris Yes, I would love to work on this issue.

2021-02-26 19:19 UTC, Darshilp326 commented
@dougfabris Please review :smile:

2021-03-04 14:42 UTC, dougfabris commented
> @dougfabris Please review 😄

@Darshilp326 It's not what we need 😟
The setting you used is for another thing. What we need is a new setting on `admin -> threads` that add control to "Also send to channel". This new setting has to be checked by default so we'll get always the checkbox checked. If the admin wants to he can uncheck and then every new thread will come with the checkbox unchecked. Let me know if you're interested to continue improving this fix and feel free to contact me for more details! 
Thanks for helping us! 😁

2021-03-04 17:00 UTC, Darshilp326 commented
> > @dougfabris Please review smile
> 
> @Darshilp326 It's not what we need. The setting you used is for another thing 
> What we need is a new setting on `admin -> threads` that add control to "Also send to channel". This new setting has to be checked by default so we'll get always the checkbox checked. If the admin wants to he can uncheck and then every new thread will come with the option unchecked.
> 
> Let me know if you're interested to continue improving this fix and feel free to contact me for more details!
> Thanks for helping us!

Ohk got your point. Working on it! :sweat_smile:

2021-03-04 20:30 UTC, Darshilp326 commented
https://user-images.githubusercontent.com/55157259/110026378-8f505c80-7d56-11eb-8350-7fbdfdd6f570.mp4

2021-03-09 17:49 UTC, Darshilp326 commented
@dougfabris Had made the requested changes! :smiley:

2021-03-30 14:36 UTC, dougfabris approved these changes

2021-03-30 14:53 UTC, zdumitru approved these changes

2021-12-17 17:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=20721) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=20721) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Douglas Fabris<br/>:x: Darshilp326<br/><hr/>**Douglas Fabris** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=20721) it.</sub>

2022-04-13 20:23 UTC, dougfabris approved these changes

2022-04-13 20:25 UTC, dougfabris approved these changes

2022-04-13 21:17 UTC, ggazzo requested changes

2022-04-13 21:17 UTC, ggazzo commented on apps/meteor/app/threads/server/settings.ts
> +	this.add('Also_send_to_channel_default', true, {
```suggestion
	this.add('Also_send_to_channel_by_default', true, {
```

2022-04-14 10:29 UTC, Weterok commented
really need this feature

2022-06-08 14:54 UTC, dougfabris commented
> How long for wait for a review? This is a very necessary feature and it's frozen...

@zhq745w We're planning to have this on the next major release, this month!

2022-06-24 20:07 UTC, dougfabris commented
Hey @Darshilp326
After a long time discussing internally we decided to move forward with the solution here #26002, thanks a lot for your help!

2022-06-24 20:07 UTC, closed without merging

2022-08-21 02:35 UTC, ulope commented
How is #26002 a solution? Removing the preference does not solve the issue on an organisation wide level.

2022-08-22 18:32 UTC, dougfabris commented
@ulope As I described in the breaking change message: "In the past, we used the `show message in main thread` as a solution to help users to understand the thread feature, as this feature is now mature enough there's no reason to maintain this preference." which causes confusion in a lot of users and customers. Additionally, we introduced a new preference allowing users to control the behavior of Also send to channel checkbox, so you users can choose or not to send the messages in the main message