[NEW] teams.addRoom, teams.updateRoom, teams.removeRoom and teams.listRooms API endpoints
RocketChat/Rocket.Chat pull request #21085
Opened 2021-03-11 20:06 UTC by r0zbot

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-03-12 19:21 UTC, sampaiodiego requested changes

2021-03-12 19:21 UTC, sampaiodiego commented on app/authorization/server/startup.js
> +		{ _id: 'view-all-team-channels', roles: ['admin', 'team-owner', 'team-moderator'] },
only team owners should be able to see all channels 
```suggestion
		{ _id: 'view-all-team-channels', roles: ['admin', 'team-owner'] },
```

2021-03-12 19:21 UTC, sampaiodiego commented on server/services/team/service.ts
> +		this.RoomsModel.updateOne({ _id: room._id }, { $unset: { teamId, teamDefault: '' } });
use a specific model method for operations like this. this one could be called:

```
this.RoomsModel.unsetTeamById(room._id);
```

2021-03-12 19:21 UTC, sampaiodiego commented on server/sdk/types/ITeamService.ts
> +	listRooms(uid: string, teamId: string): Promise<Array<IRoom>>;
please use a return can be used for pagination (like `list` and `listAll`)
```suggestion
	listRooms(uid: string, teamId: string): Promise<IRecordsWithTotal<IRoom>>;
```

2021-03-12 19:21 UTC, sampaiodiego commented on app/api/server/v1/teams.ts
> +		return API.v1.success({ rooms });
pleas add support for pagination, like `teams.list` and `teams.listAll`

2021-03-12 19:21 UTC, sampaiodiego commented on server/services/team/service.ts
> +		const hasPermission = await Authorization.hasPermission(uid, 'add-team-channel');
please move the permission check to the endpoint, see `teams.listAll`

2021-03-15 03:31 UTC, sampaiodiego requested changes

2021-03-15 03:31 UTC, sampaiodiego commented on app/models/server/raw/Rooms.js
> +				{ 'u._id': uid },
on *rooms* collection the field `u._id` represents the room creator, but looks like this is not what you is trying to find, right?

2021-03-15 03:31 UTC, sampaiodiego commented on server/services/team/service.ts
> +			cursor = this.RoomsModel.findByTeamIdAndUserId(uid, teamId, { limit: count, skip: offset });
as I mentioned on the Rooms model, this action is actually querying room's creator, but instead I'd say you can do:

- get the list of rooms from the team
- check which rooms of those rooms the user has a *Subscription* (for example: `Subscription.find({ 'u._id': uid, rid: { $in: listOfRoomIdsFromTeam } })`)
- return only rooms returned from previous query

2021-03-16 15:28 UTC, pierre-lehnen-rc requested changes
I'll split this PR in two to merge the stuff that is working and fix the listRooms method separately

2021-03-16 15:28 UTC, pierre-lehnen-rc commented on server/services/team/service.ts
> +		const teamRoomsCursor = this.RoomsModel.findByTeamId(teamId, { limit: count, skip: offset });
You're using the same count/offset for 3 different queries on this method

2021-03-16 18:35 UTC, pierre-lehnen-rc approved these changes

2021-03-16 18:46 UTC, merged