[FIX] Unexpected open or close visitor info
RocketChat/Rocket.Chat pull request #21094
Opened 2021-03-12 16:43 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

The VisitorInfo component closes or open every time a new message was sent, this PR fix that.

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-03-12 19:31 UTC, tassoevan requested changes

2021-03-12 19:31 UTC, tassoevan commented on app/ui/client/views/app/room.js
>  			if (room?.t === 'l') {
```suggestion
			if (room?.t === 'l') {
				room = Tracker.nonreactive(() => Rooms.findOne({ _id: rid }));
```

2021-03-16 09:30 UTC, rm-yakovenko commented
The milestone for this PR is 3.13. Could it be included in 3.12.x?

2021-03-16 17:10 UTC, tassoevan approved these changes

2021-03-18 02:05 UTC, merged