[FIX] Userinfo shows full name instead of the username
RocketChat/Rocket.Chat pull request #21148
Opened 2021-03-16 20:36 UTC by shrinish123

## Proposed changes (including videos or screenshots)

The user info now shows the full name instead of username. 

![final_full name](https://user-images.githubusercontent.com/56491104/111374899-a92d6000-86c3-11eb-81f3-5aab731913f0.png)

## Issue(s)

Closes #21129 

## Steps to test or reproduce

Go to any room and check the user info 

## Further comments

From the code, it is pretty evident that this was not a bug or a mistake and was done on purpose. And the full name is not shown if the setting 'Use Real Name' is turned off. 
But the point is if we go to the member's list from a room's action bar we see that the full name is displayed even if the setting 'Use Real Name ' is turned off. So if anyway the identity is revealed there then I think we should provide the full name in the user info too. Also, there were arguments for this 'use real name' setting on issue #21129 by the issue author. please suggest what's the right thing to do. Thanks

2021-03-22 21:08 UTC, ggazzo requested changes
I think you are ignoring the possibility of the name being blank.

2021-03-24 15:21 UTC, shrinish123 commented
Hi I tried to create what you were saying but the problem is that we cannot create a account with the name being blank. Hence I am not able to replicate your case 

![Screenshot (15)](https://user-images.githubusercontent.com/56491104/112335929-a5f92c00-8ce2-11eb-8fd1-da85bb8f7583.png)

Please if you can elaborate check this @ggazzo

2021-12-17 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=21148) it.</sub>

2022-11-09 23:35 UTC, juliajforesti commented
Closing this in favor of an older solution https://github.com/RocketChat/Rocket.Chat/pull/20459
Thanks for your help @shrinish123 :)

2022-11-09 23:35 UTC, closed without merging