[FIX] Fixing the option to audio and video call yourself
RocketChat/Rocket.Chat pull request #21172
Opened 2021-03-17 23:56 UTC by shrinish123

## Proposed changes (including videos or screenshots)

The option to audio and video call yourself are disabled as shown below 

Before : 

![action_intial](https://user-images.githubusercontent.com/56491104/111552400-3fd34d00-87a8-11eb-9516-ab1a9a138f0e.png)

After : 

![action_after](https://user-images.githubusercontent.com/56491104/111552418-4a8de200-87a8-11eb-935e-41b7dc00f615.png)

## Issue(s)

Closes #21170 

## Steps to test or reproduce

Go to your user info and check the option to audio and video call yourself

## Further comments

2021-03-18 08:44 UTC, shrinish123 commented
@dougfabris Please Review

2021-04-30 14:49 UTC, ggazzo requested changes
why not, pass `action` as `null` and make the tests one component above?

2021-12-17 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21172) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21172) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=21172) it.</sub>

2024-01-12 13:45 UTC, dougfabris commented
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it was already fixed in another one.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

2024-01-12 13:45 UTC, closed without merging