[IMPROVE] The three dots in the SearchList are now functional
RocketChat/Rocket.Chat pull request #21185
Opened 2021-03-18 15:35 UTC by PiyushDhamane

## Proposed changes (including videos or screenshots)

https://user-images.githubusercontent.com/63646834/111652858-6d160e80-882d-11eb-9b4a-2442950ca15c.mp4

The three dots were not functional before, but now they are

## Issue(s)

#21152  fixed
## Steps to test or reproduce

## Further comments

2021-03-18 16:14 UTC, ak2783934 commented
@PiyushDhamane On clicking the 3 dots, it shouldn't open that chat right? it should just display the options no?

2021-03-18 16:56 UTC, PiyushDhamane commented
> @PiyushDhamane On clicking the 3 dots, it shouldn't open that chat right? it should just display the options no?

Yes, that's the ideal case, but here in the searchList, the Box is a whole single component, hence clicking on the smaller icon, clicks fires both the events. So maybe once this minor change is merged, we can look at this issue as the next step.

2021-03-22 21:03 UTC, ggazzo requested changes
please check you code, looks you inserted too many changes there. thanks

2021-12-17 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21185) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21185) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=21185) it.</sub>

2022-06-09 15:15 UTC, closed without merging