[Regression] Allow editing Rooms and Contact in the Chat Room
RocketChat/Rocket.Chat pull request #21315
Opened 2021-03-26 07:40 UTC by murtaza98

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-03-26 14:02 UTC, renatobecker requested changes
The `Edit Contact` action works like a charm, but the `Edit Room` action doesn't. This is what I get:

![Screen Shot 2021-03-26 at 10 59 55 AM](https://user-images.githubusercontent.com/59577424/112643023-aac4f980-8e22-11eb-92be-2c60c0736291.png)

2021-03-26 17:53 UTC, murtaza98 commented
> The `Edit Contact` action works like a charm, but the `Edit Room` action doesn't. This is what I get:
> 
> ![Screen Shot 2021-03-26 at 10 59 55 AM](https://user-images.githubusercontent.com/59577424/112643023-aac4f980-8e22-11eb-92be-2c60c0736291.png)

@renatobecker Sorry I wasn't able to reproduce this error. Could you please check again ?

2021-03-27 12:25 UTC, renatobecker commented
@murtaza98 the implementation fixes the issues, however, it's clear that both `Contact` and `Room` contextual bar are placed in the wrong folder ->   `client/omnichannel/directory/`.

Since those components are used in different areas of the product, they should be placed in a "global" folder, not inside the "directory" folder.

@rafaelblink please, help us reviewing this PR. Thanks.

2021-03-27 19:57 UTC, murtaza98 commented
> @murtaza98 the implementation fixes the issues, however, it's clear that both `Contact` and `Room` contextual bar are placed in the wrong folder -> `client/omnichannel/directory/`.
> 
> Since those components are used in different areas of the product, they should be placed in a "global" folder, not inside the "directory" folder.
> 
> @rafaelblink please, help us reviewing this PR. Thanks.

@renatobecker I've moved out the files. Could you please review it again? Thanks

2021-03-27 23:57 UTC, renatobecker reviewed
Where are we checking permissions for room editing and contact editing? I didn't find it.
This is how we used to check it on the old version:

https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/client/views/app/tabbar/visitorInfo.js#L184-L189

Also, we can't just add a permission check for rendering the button or not because the user can access the route through the URL, so the permission needs to allow/deny accessing the edit form(room or contact) anyways.

2021-03-28 18:59 UTC, murtaza98 commented
@renatobecker For Room i've implemented the same logic as [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/client/views/app/tabbar/visitorInfo.js#L184-L189).

However I'm not sure what permission to use for Contact edit? Should I create a new global permission `edit-contacts` and by default apply this permission to agents and managers?

2021-03-28 23:13 UTC, renatobecker commented
> Should I create a new global permission `edit-contacts`

`edit-omnichannel-contact`

> and by default apply this permission to agents and managers?

Yes.

2021-03-29 13:24 UTC, murtaza98 commented
> > Should I create a new global permission `edit-contacts`
> 
> `edit-omnichannel-contact`
> 
> > and by default apply this permission to agents and managers?
> 
> Yes.

Hey @renatobecker, This part is complete

2021-03-30 16:17 UTC, renatobecker requested changes

2021-03-30 18:10 UTC, murtaza98 commented on app/authorization/server/startup.js
> -		{ _id: 'view-livechat-manager',              roles: ['livechat-manager', 'admin'] },
Sorry that was by mistake. Glad you caught it :raised_hands:

2021-03-31 18:08 UTC, murtaza98 commented on app/ui/client/views/app/room.js
> +			if (room?.t === 'l') {
@renatobecker I forgot to revert this change in the previous commit. So I'm doing it here

2021-03-31 18:09 UTC, murtaza98 commented on app/ui/client/views/app/room.js
> +			if (room?.t === 'l') {
Since we don't have a `Chat History` button in contacts directory, this is no longer needed

2021-04-01 01:57 UTC, renatobecker approved these changes

2021-04-01 03:03 UTC, merged