[NewShow isLastOwner property on listRoomsOfUser endpoint
RocketChat/Rocket.Chat pull request #21323
Opened 2021-03-26 17:14 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-03-29 17:39 UTC, sampaiodiego requested changes
I'm really not sure about taking some shortcuts, but let me know what you think:

calling `getRoomRoles` for every room in `availableRoomsCursor` will cause at least two additional find for every record. but to know if the user is the last owner, we can use `subscriptionsCursor` to get the user's role and, it he is an owner, we'd just need a single additional find to check if there is another owner for the same room.. this is actually what `getSubscribedRoomsForUserWithDetails` does: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/functions/getRoomsWithSingleOwner.js#L9

2021-03-30 14:55 UTC, KevLehman commented
> I'm really not sure about taking some shortcuts, but let me know what you think:
> 
> calling `getRoomRoles` for every room in `availableRoomsCursor` will cause at least two additional find for every record. but to know if the user is the last owner, we can use `subscriptionsCursor` to get the user's role and, it he is an owner, we'd just need a single additional find to check if there is another owner for the same room.. this is actually what `getSubscribedRoomsForUserWithDetails` does: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/functions/getRoomsWithSingleOwner.js#L9

I was looking exactly for something that makes that calculation in less calls, and this is actually a good way. I think that I'll add an extra param on that function, to not to try to calculate a new owner. Thanks for the hint!

2021-03-30 20:20 UTC, KevLehman commented on server/services/team/service.ts
> +		const roomData = getSubscribedRoomsForUserWithDetails(userId);
It can be possible, yeah. Let me do the change 🪂

2021-03-31 21:35 UTC, sampaiodiego approved these changes

2021-04-01 00:01 UTC, sampaiodiego approved these changes

2021-04-01 00:42 UTC, merged