[FIX][APPS] First iteration of recurring tasks does not repect given interval
RocketChat/Rocket.Chat pull request #21353
Opened 2021-03-29 19:49 UTC by thassiov

## Proposed changes (including videos or screenshots)

Create and schedule a task manually at `scheduleRecurring` method so the first iteration runs after the configured interval

## Issue(s)

## Steps to test or reproduce

## Further comments

Added a lot of documentation and make the module log errors properly using the official logger

2021-04-06 19:52 UTC, d-gubert requested changes

2021-04-06 19:52 UTC, d-gubert commented on app/apps/server/bridges/scheduler.js
> +			job.repeatEvery(interval, { skipImmediate: true });
Hard coding the option limits the apps, it would be better if we added a `skipImmediate` when scheduling in the app side

2021-04-06 19:55 UTC, d-gubert requested changes

2021-04-06 19:55 UTC, d-gubert commented on app/apps/server/bridges/scheduler.js
> +		this.scheduler.on('fail', (job, err) => this.orch.getRocketChatLogger().error(`Job ${ job.attrs.name } has failed: ${ err.message } `));
I'm not sure about this 🤔  We've had complaints about the Apps-Engine polluting the server's log too much, and people asking to disable it (which is currently unavailable). I'd say we should keep this change for when we add the possibility of configuring the log levels of the Apps-Engine independently.

2021-04-12 13:42 UTC, thassiov commented
Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/403

2021-04-12 17:38 UTC, lolimay submitted a review, later dismissed

2021-04-15 00:10 UTC, d-gubert approved these changes

2021-04-21 05:07 UTC, d-gubert approved these changes

2021-04-21 05:15 UTC, merged