Regression: Fix reactivity on teamsMembers and roomMembers
RocketChat/Rocket.Chat pull request #21366
Opened 2021-03-30 19:00 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-03-30 19:01 UTC, dougfabris commented on client/views/room/hooks/useUserInfoActions.js
> +				onConfirm={async (rooms) => {
@ggazzo IDK but... there's a better approach to use here instead of the async function?

2021-03-30 21:15 UTC, gabriellsh requested changes
UI crashes when "too-many-requests" is displayed

2021-03-31 23:54 UTC, ggazzo approved these changes

2021-04-01 00:00 UTC, ggazzo approved these changes

2021-04-01 00:40 UTC, merged