Fixes #21033 - Fix CORS error while interacting with any action button on Livechat
RocketChat/Rocket.Chat pull request #21406
Opened 2021-04-01 12:38 UTC by murtaza98

## Proposed changes (including videos or screenshots)

## Issue(s)

#21033

## Steps to test or reproduce

## Further comments

2021-04-05 12:51 UTC, lolimay submitted a review, later dismissed

2021-04-05 13:00 UTC, d-gubert commented on app/apps/server/communication/uikit.js
> +	const whitelistOrigins = CORSOriginSetting
I'd suggest not using `blacklist/whitelist` names  and instead using the more "modern" approach to naming it as `blocklist/allowlist` 😉

2021-04-06 19:46 UTC, d-gubert commented
It looks good to me, I'd just like to get the eyes of @sampaiodiego to check on the use of the Settings 🙂

2021-04-11 11:36 UTC, murtaza98 commented
> the only issue I'm seeing is that if the settings are updated the new values are not read, so it would require a server restart to get updates CORS values.

Thanks this was helpful! :smile: Done with this change

2021-04-15 13:10 UTC, sampaiodiego requested changes
Thanks @murtaza98 the code looks better now, but while testing I was getting "Not allowed by CORS" even with CORS disabled and using from same domain (using from rocket.chat web client actually).

can you take a look on that pls? thx

2021-04-19 19:50 UTC, murtaza98 commented
> Thanks @murtaza98 the code looks better now, but while testing I was getting "Not allowed by CORS" even with CORS disabled and using from same domain (using from rocket.chat web client actually).
> 
> can you take a look on that pls? thx

Hey @sampaiodiego I was able to solve this issue by adding a new check there in callback `origin === settings.get('Site_Url')`. Could you please review it again? Thanks :smile:

2021-04-28 20:20 UTC, sampaiodiego commented
hi @murtaza98 .. I tested it again and even with CORS disabled I'm not able to use `/poll` due to CORS erros, as you can see on attachments below:

![image](https://user-images.githubusercontent.com/8591547/116467330-f285d900-a845-11eb-95dd-16d2c1b3e8c1.png)

![image](https://user-images.githubusercontent.com/8591547/116467382-fc0f4100-a845-11eb-9914-6bc5497755cb.png)

![image](https://user-images.githubusercontent.com/8591547/116467409-03364f00-a846-11eb-920b-b8bd7a77c5b9.png)

2021-05-24 08:29 UTC, murtaza98 commented
Hey @sampaiodiego There was an issue within the condition over [here](https://github.com/RocketChat/Rocket.Chat/pull/21406/files#diff-f1739e229241c8ae25c7d00c680d188e45f9552c3a5d9c17c11610191fb385c9R29) due to which you were getting the error. I've now updated the logic to handle this. Request you to please review it again. Thanks!

2021-05-24 11:21 UTC, murtaza98 commented
Guys, Some of the builds are failing here and the error is not related to this PR. The error was being caused by some of the merge changes I made in this PR. Due to this, I decided to close this PR and create a new PR with only relevant change. 

NEW PR: #22121

2021-05-24 11:21 UTC, closed without merging