[IMPROVE] remove meteor dependency from room service
RocketChat/Rocket.Chat pull request #21449
Opened 2021-04-05 13:11 UTC by g-thome

## Proposed changes (including videos or screenshots)

create method from room service no longer relies on meteor code.

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-04-30 18:17 UTC, KevLehman requested changes

2021-04-30 19:18 UTC, g-thome commented on app/lib/server/functions/createDirectRoom.ts
> +	const usernames = sortedMembers.map((m) => m.username).filter((u): u is string => !!u);
`filter(Boolean)` seems to cast each username as possibly undefined

[here's a demo](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIFUDO1kG8BQyRyArtlCHALYQD8AXMpmFKAOb4C+++CA9iGbIaVAEbRMjDOQDaAXWQBeZDNylylGowDkcECBQwoegNbbOAGjzromiDoAmfEm3NW1ZW9XvJtBgJ5UcFBu1p4U3jrAeqEeGpG+bHxQTiDIRhAQQSDmcrwCQuF2mErCWeJQmAB0QQAOABT1VACUSgB8wlVF3s1VMMAANpBQ9QBCfHwDEHrNANxAA)

2021-05-03 14:55 UTC, KevLehman commented on app/lib/server/functions/createDirectRoom.ts
> +	const usernames = sortedMembers.map((m) => m.username).filter((u): u is string => !!u);
Ah, that's really weird, but I think it's ok. Ignore this thread 😬

2021-12-17 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21449) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21449) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=21449) it.</sub>

2024-09-25 01:45 UTC, closed without merging