[FIX] Wrong user in user info
RocketChat/Rocket.Chat pull request #21451
Opened 2021-04-05 19:53 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-04-05 20:07 UTC, dougfabris commented on client/views/room/MemberListRouter.js
> +	// Self DMs used to be created with the userId duplicated.
Remove the comments on the code and use this nice information on the PR's description

2021-04-05 20:09 UTC, dougfabris requested changes
Remove the comments on the code and use this nice information on the PR's description.

2021-04-05 20:47 UTC, gabriellsh commented
> Remove the comments on the code and use this nice information on the PR's description.

IMHO, this information is relevant enough to be in the code. I fear someone might want to change this without the proper consideration. WDYT?

I can add it to the PR also though, no problem.

2021-04-05 21:11 UTC, dougfabris commented
> > Remove the comments on the code and use this nice information on the PR's description.
> 
> IMHO, this information is relevant enough to be in the code. I fear someone might want to change this without the proper consideration. WDYT?
> 
> I can add it to the PR also though, no problem.

If you think it's a piece of relevant information to be there, go ahead!

2021-04-05 21:11 UTC, dougfabris submitted a review, later dismissed

2021-04-05 21:24 UTC, gabriellsh commented
I agree! We shouldn't need to explain code, I'm all for that. But I think in specific cases it's needed, since we can't fix the "root" problem and this is a workaround. The comments don't explain the code itself, as it's pretty clear what it does. It explains why that was the choice.

I'm not trying to justify the comments BTW, thats just my opinion. Maybe @ggazzo can comment about this too, since both our POVs are relevant in this case.

2021-04-16 04:38 UTC, ggazzo approved these changes

2021-04-16 04:38 UTC, merged