[IMPROVE] Add support to queries in the `im.members` endpoint
RocketChat/Rocket.Chat pull request #21471
Opened 2021-04-07 01:14 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Add support to queries within the `name`, `username` and `status` parameters.

## Issue(s)

[Task - ClickUp](https://app.clickup.com/t/433kv3)

## Steps to test or reproduce

**Example input (using cURL):**
```
curl -G 'http://localhost:3000/api/v1/im.members?roomId=C54E8R3WgShxQ5Tmi&username=some.user&status[]=online&status[]=away&status[]=busy' \
  -H 'X-Auth-Token: c3rQDH_Fpa7JHSgUrWvlpxwIi1AAu4qTnfAF4SFgWkB' \
  -H 'X-User-Id: dizcH9Edm8hC7ziDX' \
  -H 'Content-Type: application/json'
```

## Further comments

2021-04-29 16:53 UTC, KevLehman requested changes

2021-04-29 16:53 UTC, KevLehman commented on app/api/server/v1/im.js
>  		const cursor = Subscriptions.findByRoomId(findResult.room._id, {
Add a projection to fetch only the `u` prop, since you're not using the rest of the result

2021-05-03 18:59 UTC, matheusbsilva137 commented
@KevLehman , regarding the addition of support to regex in the `im.members` endpoint, some changes would need to be applied in the [findOneByIdOrName](https://github.com/RocketChat/Rocket.Chat/blob/042f3182c6568aa03ae49363c9e136a21d3db756/app/models/server/models/Rooms.js#L36) method. Since this method is used in many places, I think this could bring some unexpected behaviors 🤔 (or maybe this would be a breaking change), wdyt?

2021-05-13 20:46 UTC, sampaiodiego approved these changes

2021-05-14 13:43 UTC, merged