[FIX] Unable to edit a 'direct' room setting in the admin due to the name
RocketChat/Rocket.Chat pull request #21636
Opened 2021-04-18 15:23 UTC by Jeanstaquet

## Proposed changes (including videos or screenshots)

When you are in the admin and want to change a room 'd' setting, it doesn't work because it takes into account the name that is set automatically and therefore tries to save that name. Since the name is not valid and should not be registered, we cannot change the setting for the 'd' room. 
I made sure that when you want to change a setting in a 'd' room, that you don't take the name into account

https://user-images.githubusercontent.com/45966964/115150790-3f112d80-a06a-11eb-9814-c9bfa209226e.mp4
Behind the scene, the name is not saved

## Issue(s)

Fixes #21635 
## Steps to test or reproduce

## Further comments

2021-04-19 17:12 UTC, KevLehman approved these changes

2021-04-28 20:44 UTC, sampaiodiego requested changes
IMHO a proper fix for this issue would be changing the frontend to actually not send the room name on payload since that was not changed (the field is event disabled). if the name is sent on the payload, the backend should validate it, otherwise let's say someone uses the endpoint providing *only* the room name, the endpoint will return success but nothing will be done, which I'd consider a bug.

2021-04-28 20:50 UTC, Jeanstaquet commented
@sampaiodiego alright, i will do the changes ASAP 👍

2021-04-28 23:59 UTC, Jeanstaquet commented
Proof that it works:
https://user-images.githubusercontent.com/45966964/116486676-72d02c80-a88e-11eb-8afe-448e8fe6f59a.mp4

2021-04-29 14:02 UTC, merged