[FIX] Take the permission to set ReadOnly and put on the create room modal
RocketChat/Rocket.Chat pull request #21773
Opened 2021-04-23 12:12 UTC by Jeanstaquet

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-04-23 19:58 UTC, KevLehman requested changes
The console.log :)

2021-04-23 19:58 UTC, KevLehman commented on client/sidebar/header/CreateChannel.js
> +	console.log(canSetReadOnly)
Remove the console.log pls

2021-04-23 20:11 UTC, Jeanstaquet commented on client/sidebar/header/CreateChannel.js
> +	console.log(canSetReadOnly)
Sorry, I missed it.

2021-12-17 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21773) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21773) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=21773) it.</sub>

2022-11-03 19:12 UTC, gabriellsh requested changes
I tried fixing the conflicts and pushing to your branch, but that doesn't seem to be possible. Can you fix them? That file doesn't exist anymore, was renamed to be CreateChannel.tsx

2022-11-22 18:24 UTC, closed without merging