[FIX]Sorting functionality in team channel while leaving a team
RocketChat/Rocket.Chat pull request #21790
Opened 2021-04-25 06:59 UTC by sumukhah

Before:

https://user-images.githubusercontent.com/23723464/115983909-c65a2600-a5c1-11eb-8fa4-5ca6dd01a006.mov

After:

https://user-images.githubusercontent.com/23723464/115983889-a7f42a80-a5c1-11eb-9271-72fa26a3dbd0.mov

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-12-17 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21790) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=21790) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=21790) it.</sub>

2022-11-03 18:54 UTC, gabriellsh requested changes
Additionaly, there's conflicts that need to be solved.

2022-11-03 18:54 UTC, gabriellsh commented on client/views/teams/contextualBar/ChannelDesertionTable.js
> +	const getSortedChannels = useCallback(() => {
This could be moved to outside the function in order to avoid using `useCallback`. Then you could call `getSortedChannels(rooms, sort)`.

2022-11-22 04:18 UTC, ggazzo submitted a review, later dismissed

2022-11-22 04:36 UTC, ggazzo approved these changes

2022-11-22 15:20 UTC, merged