[FIX] Fixing Jitsi call ended Issue.
RocketChat/Rocket.Chat pull request #21808
Opened 2021-04-26 15:30 UTC by yash-rajpal

- [x] I have read the Contributing Guide
  - [x] I have signed the CLA
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

The new rewrite in react of contextual call component broke the Jitsi "click to join" messages. The issue being after 10 seconds of initiating the call, the message "click to join" always returned "Call Ended" even if the call was still going on.
This was due to the fact that after closing the contextual bar, the react component gets unmounted and we are not able to keep track of ongoing call and increase jitsi room timeout. 

This PR solves this issue by using the setInterval methods on component will unmount. When the call component unmounts, we keep on checking the state of jitsi call and based on conditions increase the jitsi room timeout. After the call is ended all setInterval calls are closed.

This PR also removes the implementation of HEARTBEAT events of JitsiBridge. This is because this is no longer needed and all logic is being taken care of by the unmount function.

## Issue(s)

#21055 
## Steps to test or reproduce

## Further comments

2021-04-26 15:51 UTC, yash-rajpal commented
@tiagoevanp Please review it. :)

2021-04-27 04:41 UTC, emikolajczak commented
Hi, is it possible to drop it on open.rocket.chat for tests?

2021-04-28 07:03 UTC, emikolajczak commented
I don't know if this is deployed on https://open.rocket.chat , but still no working there. Not possible to join. Detail on movie below

https://user-images.githubusercontent.com/50440047/116360686-73ba7d00-a800-11eb-8e30-ccb3256373d7.mp4

2021-04-28 07:14 UTC, yash-rajpal commented
@emikolajczak This fix isn't released yet, as this pull request is not merged.

This fix will be available to test on open rocket chat server after this pr is merged and released.

2021-04-28 07:17 UTC, emikolajczak commented
Understand. Do you know when can we expect release this?

2021-04-28 07:42 UTC, yash-rajpal commented
No, thats not in my hands, I can't say anything on this.

Its upon Rocket Chat team to review this pr and merge it if it looks good. After that we can expect it to be released in some release candidate, after that happens we will be able to test it on open rocket chat workspace.

2021-04-28 07:43 UTC, emikolajczak commented
Thanks for explanation. I will wait.

2021-04-28 18:47 UTC, yash-rajpal commented
@tiagoevanp @ggazzo @sampaiodiego This seems like a useful pr and lots of community members are facing a problem due to this, please have a look. Thanks :)

Adding proof that this pr solves the problem.
![Jitsi-call-ended-issue-fixed](https://user-images.githubusercontent.com/58601732/116456234-a5265d80-a87f-11eb-9166-af71b43fd24c.gif)

Due to current issue, the button after 10 seconds tells that call ended, but by above GIF we can see that button is now functional and works as expected. I tested it thoroughly and everything seems to work as expected.
After ending the call button gives output call ended, which is the desired output.

@emikolajczak can you confirm if this is the required fix?

2021-04-28 20:58 UTC, HiveMindNet commented
> @tiagoevanp @ggazzo @sampaiodiego This seems like a useful pr and lots of community members are facing a problem due to this, please have a look. Thanks :)
> 
> Adding proof that this pr solves the problem.
> ![Jitsi-call-ended-issue-fixed](https://user-images.githubusercontent.com/58601732/116456234-a5265d80-a87f-11eb-9166-af71b43fd24c.gif)
> 
> Due to current issue, the button after 10 seconds tells that call ended, but by above GIF we can see that button is now functional and works as expected. I tested it thoroughly and everything seems to work as expected.
> After ending the call button gives output call ended, which is the desired output.
> 
> @emikolajczak can you confirm if this is the required fix?

That's great work @yash-rajpal - it would be fantastic if the main guys could finish checks on this and include it in the main code @sampaiodiego

2021-05-03 16:54 UTC, sandrotanner commented
whats the internal timeline to review this? @sampaiodiego 

and in what time frame can we expect this to be merged? will there be a PATCH for all supported versions? or will it be in the next minor release? maybe in the version after the next?

This information could prove to be insightful in determining weather we want to wait or if it's better to patch it on our own for our server until it finds it's way into the official codebase.

2021-05-06 07:39 UTC, ankar84 commented
Waiting that PR to be reviewed and then merged.
Thank you, @yash-rajpal

2021-05-20 16:21 UTC, ggazzo requested changes
hey @yash-rajpal thanks for your pr, I'm afraid the `HEARTBEAT` cannot be removed.
I mean this 'protocol' was not meant for "you", but to inform other users that never opened the contextualbar if the call is still alive

could you review the fix and keep it? thanks

2021-05-20 17:41 UTC, yash-rajpal commented
@ggazzo Can you please clarify more on your comment, on what has to be done? This PR fixes that issue only, to let other users know if call is still active or not, which is currently broken.

Do you want me to use JitsiBridge's implementation, rather my own in the component?

2021-05-21 04:46 UTC, ggazzo approved these changes

2021-05-21 04:48 UTC, ggazzo commented
please ignore my comment, and sorry i was running out of time for the release so i ended up changing the code a little bit.

2021-05-21 04:49 UTC, merged