[FIX] Prevent the app from crashing when there a no custom fields defined
RocketChat/Rocket.Chat pull request #22034
Opened 2021-05-14 02:15 UTC by Jeanstaquet

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-05-14 13:43 UTC, ggazzo requested changes
I think we should insert a try catch here, just in case we insert an invalid json.

 If I'm not wrong there is one more place that we could insert this test ,could you check please? thanks

2021-05-14 16:56 UTC, Jeanstaquet commented
> I think we should insert a try catch here, just in case we insert an invalid json.
> 
> If I'm not wrong there is one more place that we could insert this test ,could you check please? thanks

Hello @ggazzo, 
Many thanks for your review and advice. However after your comment I have done multiple tests, and searched in many places, I don't see where I can add to the other similar test. Do you have any details on adding the extra test you mention? 
Thanks  a lot

2021-05-14 17:23 UTC, ggazzo commented
by bad I thought we had this in two places

2021-05-17 13:05 UTC, ggazzo approved these changes

2021-05-17 13:10 UTC, merged