[IMPROVE] Add modal to close chats when tags/comments are not required
RocketChat/Rocket.Chat pull request #22096
Opened 2021-05-20 22:42 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

When neither tags or comments are required to close a livechat, show this modal instead: 
![Screen Shot 2021-05-20 at 7 33 19 PM](https://user-images.githubusercontent.com/20868078/119057741-6af23c80-b9a3-11eb-902f-f8a7458ad11c.png)

## Issue(s)

Reiteration of https://github.com/RocketChat/Rocket.Chat/issues/21468

2021-05-21 19:04 UTC, rafaelblink submitted a review, later dismissed

2021-05-31 16:17 UTC, renatobecker requested changes

2021-05-31 16:17 UTC, renatobecker commented on client/components/Omnichannel/modals/CloseChatModal.js
> +	if (!commentRequired && !tagRequired) {
`tagRequired` is always returning **false**, but I have defined **true** on the department.

2021-05-31 16:18 UTC, renatobecker commented
@rafaelblink I was not able to test this PR properly, were you?

2021-05-31 20:24 UTC, renatobecker requested changes

2021-05-31 20:24 UTC, renatobecker commented on client/views/room/Header/Omnichannel/QuickActions/QuickActions.tsx
> +		const departmentId = room.departmentId || room.department;
`department` field is not a valid field for Omnichannel rooms.

2021-05-31 20:24 UTC, renatobecker commented on definition/IRoom.ts
> +	department?: string;
`department` field is not a valid field for Omnichannel rooms.

2021-06-01 20:26 UTC, renatobecker commented
The issue related to the required tags feature has not been fixed yet.
The default modal always shows up, even when tags are required.

2021-06-04 15:42 UTC, closed without merging