[FIX] status message render for other users
RocketChat/Rocket.Chat pull request #22110
Opened 2021-05-21 21:52 UTC by g-thome

- add a react component to render the status message
- delete helper function in blaze template

## Proposed changes (including videos or screenshots)

replace the current blaze block that queries the local session store by a react component that fetches memoized user data

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-06-18 01:02 UTC, wreiske commented
Resolves: #22089

2021-06-18 16:59 UTC, geekgonecrazy commented
Added to PR body.

Any reason for us not to merge this one for this release?  @RocketChat/frontend  ?

2021-06-25 19:22 UTC, gabriellsh requested changes

2021-06-25 19:22 UTC, gabriellsh commented on client/components/Message/StatusMessage.tsx
> +		<button className='message-custom-status' title={data.statusText}>
I don't think this should be a button if it does nothing when clicked. I'd also prefer the use of the Icon component istead of an ASCII character.

Another thing is, I believe we should deprecate the use of old classnames. Perhaps style a box component to do this work?

2021-07-16 20:05 UTC, gabriellsh submitted a review, later dismissed

2021-07-20 20:00 UTC, dougfabris approved these changes

2021-07-21 03:51 UTC, merged