[IMPROVE] Paginated department select on forward chat
RocketChat/Rocket.Chat pull request #22123
Opened 2021-05-24 14:07 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

Changes the department dropdown to use the new paginated selects, allowing for searching and displaying more than 50 departments

2021-06-04 20:42 UTC, tiagoevanp commented on client/components/Omnichannel/modals/ForwardChatModal.js
> +		departmentName: '',
This can be removed, there is no use, right?

2021-06-04 20:45 UTC, tiagoevanp commented on client/components/Omnichannel/modals/ForwardChatModal.js
> +		onForward(department?.value, userId, comment);
isn't department a string?

2021-06-04 20:53 UTC, tiagoevanp commented on client/components/Omnichannel/hooks/useDepartmentsList.ts
> +	const endpoint = `livechat/department`;
linter didn't catch this? single quotes...

2021-06-04 20:57 UTC, tiagoevanp requested changes
The file `client/views/hooks/useDepartmentsList.ts` is too similar to `client/components/Omnichannel/hooks/useDepartmentsList.ts`... is that ok?

2021-06-04 20:57 UTC, tiagoevanp commented on client/components/Omnichannel/modals/ForwardChatModal.js
> +		departmentName: '',
departmentName

2021-06-10 20:18 UTC, MartinSchoeler commented on client/components/Omnichannel/modals/ForwardChatModal.js
> +		onForward(department?.value, userId, comment);
nope that was `DepartmentName`

2021-06-11 03:37 UTC, tiagoevanp approved these changes

2021-06-11 04:19 UTC, merged