[FIX] Missing visual validation and users selection field on creating team modal
RocketChat/Rocket.Chat pull request #22332
Opened 2021-06-12 20:14 UTC by dougfabris

## Proposed changes (including videos or screenshots)

- Added visual validation if the team's name is missing:
![image](https://user-images.githubusercontent.com/27704687/121788036-726ec500-cba0-11eb-92f4-1d65fdf13f91.png)

- Fix: add members breaking when searching users

![image](https://user-images.githubusercontent.com/27704687/121788070-b792f700-cba0-11eb-92b9-5833e1213c74.png)

### Additional Improvements:
- Brand new `UserAutoCompleteMultiple.tsx` mixed with `UsersInput.tsx `. I realized they are very similar components so I mixed them into a new unique component, now if we want to get the users by id we can pass simply a prop to him

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-06-17 23:26 UTC, tassoevan requested changes

2021-06-17 23:26 UTC, tassoevan commented on client/views/teams/CreateTeamModal/CreateTeamModal.tsx
```suggestion
```

2021-06-18 01:07 UTC, tassoevan requested changes

2021-06-18 01:07 UTC, tassoevan commented on client/views/teams/CreateTeamModal/CreateTeamModal.tsx
> +					<UserAutoCompleteMultiple handleById value={members} onChange={onChangeMembers} />
Please, try to get rid of `handleById` prop. I believe it's achievable by using a custom callback signature for `onChange` (e.g. `onChange(username, uid)`).

2021-12-17 13:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=22332) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=22332) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: dougfabris<br/>:x: tassoevan<br/><hr/>**dougfabris** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=22332) it.</sub>

2022-02-19 16:18 UTC, dougfabris commented
Closing this one in favor of #24529

2022-02-19 16:18 UTC, closed without merging