[IMPROVE] Rewrite Save Encryption Password Modal
RocketChat/Rocket.Chat pull request #22447
Opened 2021-06-22 18:34 UTC by dougfabris

## Proposed changes (including videos or screenshots)

### before
![image](https://user-images.githubusercontent.com/27704687/122980201-c337a800-d36e-11eb-8e2b-68534cea8e1e.png)

### after
![image](https://user-images.githubusercontent.com/27704687/122980409-f8dc9100-d36e-11eb-9c15-aff779c84a91.png)

## Issue(s)

## Steps to test or reproduce

- Go to MyAccount 
- Go to the security menu
- Reset the E2E Key on the E2E Encryption tab
- After reloading the page you will able to see the banner "Save Your Encryption Password"
- Click on it to open the new Modal

## Further comments

2021-06-25 18:10 UTC, gabriellsh requested changes

2021-06-25 18:10 UTC, gabriellsh commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "I_ll_do_it_later": "Do It Later",
As we talked in private, I think that when translations change drasticaly like this, we should change the key also, in order to create a demand for new translations for other languages.

2021-07-05 21:31 UTC, gabriellsh requested changes

2021-07-05 21:31 UTC, gabriellsh commented on app/e2e/client/rocketchat.e2e.js
> +							children: <div dangerouslySetInnerHTML={{ __html: passwordRevealText }} />,
As we agreed previously, we should avoid JSX at all costs when dealing with legacy files. Let's keep JSX for pure React files.

2021-07-06 18:33 UTC, gabriellsh submitted a review, later dismissed

2021-07-06 21:24 UTC, tassoevan approved these changes

2021-07-06 22:20 UTC, merged