[FIX] Quote message not working for Livechat visitors
RocketChat/Rocket.Chat pull request #22586
Opened 2021-07-06 10:19 UTC by murtaza98

(cherry picked from commit 4fa4f66663d83ea57cb492b11ea0a71d6cd137b2)

## Proposed changes (including videos or screenshots)

### Before:
![image](https://user-images.githubusercontent.com/34130764/124583613-de2b1180-de70-11eb-82aa-18564b317626.png)
### After:
![image](https://user-images.githubusercontent.com/34130764/124583775-12063700-de71-11eb-8ab5-b0169fac2d40.png)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-07-07 22:12 UTC, KevLehman submitted a review, later dismissed

2021-07-21 03:53 UTC, ggazzo requested changes

2021-07-21 03:53 UTC, ggazzo commented on app/oembed/server/jumpToMessage.js
> +		const canAccessRoomForUser = canAccessRoom(room, currentUser) || isLiveChatRoomVisitor;
```suggestion
		const isLiveChatRoomVisitor = !!msg.token && !!room.v?.token && msg.token === room.v.token;
		const canAccessRoomForUser = isLiveChatRoomVisitor || canAccessRoom(room, currentUser);
```

2021-07-28 13:26 UTC, KevLehman approved these changes

2021-07-29 21:37 UTC, merged