[NEW] Collect data about LDAP, SAML, CAS and OAuth usage.
RocketChat/Rocket.Chat pull request #22719
Opened 2021-07-20 20:36 UTC by pierre-lehnen-rc

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-07-20 20:50 UTC, ggazzo requested changes
almost there ;)

2021-07-20 20:50 UTC, ggazzo commented on app/models/server/models/Users.js
> +		query[`services.${ serviceName }`] = { $exists: true };
```suggestion
			roles: { $ne: ['guest'] },
			[`services.${ serviceName }`]:  { $exists: true }
		};
```

2021-07-20 20:50 UTC, ggazzo commented on app/statistics/server/lib/getServicesStatistics.ts
> +export function getServicesStatistics(): Record<string, any> {
provide something more specific than `any`, if you really dont know, use `unknown` but try to provide some kind of structure

2021-07-21 03:28 UTC, ggazzo approved these changes

2021-07-21 03:46 UTC, merged

2021-07-22 20:27 UTC, geekgonecrazy commented on app/statistics/server/lib/getServicesStatistics.ts
> +	return Object.fromEntries(customOatuh.map(({ key, value }) => [key, {
is this not a typo that will prevent from working @pierre-lehnen-rc ?

2021-07-22 20:31 UTC, geekgonecrazy commented
At some point we really should consider making that entire payload a type.  It would make it much easier to work with.  Right now to determine what type the value is supposed to be is a really involved exercise