[Fix] Cannot set property 'canViewAllInfo' of undefined
RocketChat/Rocket.Chat pull request #22875
Opened 2021-08-05 21:43 UTC by Fluffy-

Fixes #22874 

We're getting an error ( Cannot set property 'canViewAllInfo' of undefined ) when calling the /api/v1/users.info endpoint when searching for a user that does not exist.

Cannot set property 'canViewAllInfo' of undefined users.info

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-08-28 17:46 UTC, debdutdeb approved these changes

2021-08-30 23:56 UTC, dougfabris requested changes

2021-08-30 23:56 UTC, dougfabris commented on app/lib/server/functions/getFullUserData.js
> +	if(user){
```suggestion
	if (user) {
```

2021-11-22 15:21 UTC, dougfabris commented
@Fluffy- Thanks for your contribution! The issue is already fixed: #23372

2021-11-22 15:21 UTC, closed without merging