[FIX] Discussion search doesn't work after making a search without results
RocketChat/Rocket.Chat pull request #22914
Opened 2021-08-12 17:01 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Fix discussions list.

## Issue(s)

[Task - ClickUp](https://app.clickup.com/t/6ewnp5)

## Steps to test or reproduce

Enter a room and open the "Discussions" side bar (using the tab bar icon). Insert a text in order to get _no results_ and then erase the text and make a new search (which should return results).
**Expected behavior:** all the results should be displayed in the second search (after the search with no results).

## Further comments

2021-08-12 18:15 UTC, dougfabris requested changes
Could you take a look at the `chat.getDiscussions` endpoint? It seems the text parameter is not working properly.

2021-08-17 21:04 UTC, g-thome reviewed
Backend seems fine to me. But it would be nice if you could add tests for chat.getThreadsList to guarantee that the text argument works as expected

2021-08-17 22:39 UTC, dougfabris approved these changes

2021-08-23 23:37 UTC, g-thome approved these changes

2021-08-23 23:40 UTC, merged