[FIX] Bad words falling if message is empty
RocketChat/Rocket.Chat pull request #22930
Opened 2021-08-13 22:37 UTC by ggazzo

## Issue(s)

In some places like Ominichannel channels creation was failing if the bad words is activated.
`sendMessage(guest, { t: 'livechat-started', msg: '', groupable: false }, room);`

## Steps to test or reproduce

## Further comments

2021-08-16 16:22 UTC, sampaiodiego requested changes

2021-08-16 16:22 UTC, sampaiodiego commented on app/lib/server/methods/filterBadWords.ts
> +		const allowBadWordsFilter = settings.get('AllowBadWordsFilter');
```suggestion
		const allowBadWordsFilter = settings.get('Message_AllowBadWordsFilter');
```

2021-08-17 00:55 UTC, Shailesh351 commented
Reverting back to `bad-words` version `3.0.3` worked for me. 

In the `bad-words` repo some users have reported similar issue for other cases as well. Like adding ":)" or "[" also causes the similar issue.

https://github.com/web-mech/badwords/issues/103 https://github.com/web-mech/badwords/pull/95

So, IMO it's better to use current stable version `"bad-words": "3.0.3",`

2021-08-20 21:01 UTC, sampaiodiego approved these changes

2021-08-20 21:06 UTC, merged