[FIX] Error getting default agent when routing system algorithm is Auto Selection
RocketChat/Rocket.Chat pull request #22976
Opened 2021-08-19 20:56 UTC by renatobecker

## Proposed changes (including videos or screenshots)
When the Omnichannel routing system algorithm is **Auto Selection** (Community version) an error is raised when getting the default agent. The cause of the issue was a wrong implementation of a callback method.
Another issue has been found and fixed: Guests associated with a department that no longer exists were not routed properly since the routing system was trying to find available agents associated with a department that doesn't exist anymore.

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-08-19 23:41 UTC, KevLehman submitted a review, later dismissed
Tried on community, autoselection algorithm is no longer returning errors. However, there's still an issue with the routing itself (that afaik, won't be handled in this same PR)

2021-08-20 00:23 UTC, ggazzo requested changes

2021-08-20 00:23 UTC, ggazzo commented on app/livechat/server/hooks/beforeDelegateAgent.js
> +callbacks.add('livechat.beforeDelegateAgent', (agent, department) => {
I think it's best to keep using a key value object, if you need another different item, it won't break everywhere. This change actually doenst fix or solves anything
```suggestion
callbacks.add('livechat.beforeDelegateAgent', (agent, { department }) => {
```

2021-08-20 00:23 UTC, ggazzo commented on app/livechat/server/lib/RoutingManager.js
> +		const defaultAgent = callbacks.run('livechat.beforeDelegateAgent', agent, inquiry?.department);
```suggestion
		const defaultAgent = callbacks.run('livechat.beforeDelegateAgent', agent, { department: inquiry?.department });
```

2021-08-20 01:04 UTC, renatobecker commented
Suggestions applied.

2021-08-20 01:12 UTC, KevLehman submitted a review, later dismissed

2021-08-23 12:39 UTC, ggazzo approved these changes

2021-08-23 12:39 UTC, merged