[IMPROVE] Livechat logging on critical parts of code
RocketChat/Rocket.Chat pull request #22977
Opened 2021-08-19 23:20 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Pls let me know if there are any other places where we can add more logs 😬

2021-08-20 02:47 UTC, renatobecker requested changes
I'm missing logs on https://github.com/RocketChat/Rocket.Chat/blob/develop/ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js

2021-08-20 02:47 UTC, renatobecker commented on app/livechat/server/lib/Livechat.js
> +		Livechat.logger.debug(`Attempting to send a message by visitor ${ guest._id } on room ${ room._id }`);
We don't need to log this event.

2021-08-20 02:47 UTC, renatobecker commented on app/livechat/server/lib/Livechat.js
> +		Livechat.logger.debug(`Attempting to update a message by visitor ${ guest._id }`);
We don't need to log this event.

2021-08-20 02:47 UTC, renatobecker commented on app/livechat/server/lib/QueueManager.js
> +	logger.debug(`Delegating inquiry with id ${ inquiry._id } to agent ${ defaultAgent?._id }`);
I think this method should be called after:
`const inquiryAgent = RoutingManager.delegateAgent(defaultAgent, inquiry);`

2021-08-20 02:47 UTC, renatobecker commented on app/livechat/server/lib/RoutingManager.js
>  			agent = await this.getNextAgent(department);
There's a log missing after this line.

2021-08-20 11:41 UTC, renatobecker approved these changes

2021-08-20 20:52 UTC, renatobecker approved these changes

2021-08-20 21:55 UTC, merged

2021-09-18 22:58 UTC, pierre-lehnen-rc commented on ee/app/livechat-enterprise/server/lib/LivechatEnterprise.js
> +	routingSupportsAutoAssign ? queueWorker.start() : queueWorker.stop();
This queueWorker is running even when omnichannel is disabled and it's generating a lot of useless debug logs every second.