[FIX] Remove doubled "Canned Responses" strings
RocketChat/Rocket.Chat pull request #23056
Opened 2021-08-27 19:02 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Remove doubled canned response setting introduced in #22703 (by setting id change);
 - Update "Canned Responses" keys to "Canned_Responses".

## Issue(s)

[Task - ClickUp](https://app.clickup.com/t/7084cm)

## Steps to test or reproduce

Go to Administration and search for 'Canned Responses'. Only **one** setting (menu) should be displayed in the sidebar.

## Further comments

2021-08-30 16:53 UTC, pierre-lehnen-rc submitted a review, later dismissed

2021-08-30 17:58 UTC, ggazzo requested changes
Could we check and mention where this duplication was introduced? and btw I think we have some bad translations "Canned Responses" instead "Canned_Responses", could you use this issue and fix together?

2021-08-30 21:42 UTC, matheusbsilva137 commented
> Could we check and mention where this duplication was introduced? and btw I think we have some bad translations "Canned Responses" instead "Canned_Responses", could you use this issue and fix together?

I've just updated all the "Canned Responses" keys to "Canned_Responses" (keeping the _best_ translations for each language).
This duplication has been introduced in #22703 (in the `ee/app/canned-responses/server/settings.js` file changes).

2021-08-31 15:09 UTC, KevLehman reviewed
Thanks for fixing this :) (there's a conflict on the migration btw)

2021-08-31 15:09 UTC, KevLehman commented on packages/rocketchat-i18n/i18n/es.i18n.json
> +  "Canned_Responses": "Respuesta predefinida",
```suggestion
  "Canned_Responses": "Respuestas predefinidas",
```

2021-09-16 21:55 UTC, tassoevan approved these changes

2021-09-23 19:09 UTC, tassoevan approved these changes

2021-09-23 19:09 UTC, merged