[NEW] New Message Parser and Adding code languages by demand
RocketChat/Rocket.Chat pull request #23232
Opened 2021-09-20 01:58 UTC by ggazzo

## Proposed changes (including videos or screenshots)

We are moving with the new Message Parser that should replace marked and original.
If you are coming from a new fresh install there is nothing to do. If you are upgrading from an old version just reset the setting `Accounts_Default_User_Preferences_enableMessageParserEarlyAdoption` or set to `true`

We are keeping the old libraries for now in case we have any bugs or missing cases, since we don't want any sad users, so you can keep using the old options for now. But most likely we will be removing it in the next major release.

Now we have this setting called 'Message_Code_highlight' where you can insert the languages that you want loaded by default. if you want to some that is not set, just insert on the beginning of the codeblock and than the language will be loaded "```yourlanguage........"

## Issue(s)

closes #20766
close https://github.com/RocketChat/Rocket.Chat/issues/8989
closes https://github.com/RocketChat/Rocket.Chat/issues/21184
closes https://github.com/RocketChat/Rocket.Chat/issues/7707
closes https://github.com/RocketChat/Rocket.Chat/issues/21184
closes https://github.com/RocketChat/Rocket.Chat/issues/5218
## Steps to test or reproduce

## Further comments

2021-09-20 09:27 UTC, ankar84 commented
probably closes https://github.com/RocketChat/Rocket.Chat/issues/22280

2021-09-22 18:38 UTC, sampaiodiego requested changes

2021-09-22 18:38 UTC, sampaiodiego commented on app/lib/server/startup/settings.js
> +		i18nDescription: 'Message_Code_highligh_Description',
missing i18n

2021-09-23 14:15 UTC, sampaiodiego commented
![image](https://user-images.githubusercontent.com/8591547/134523715-513cd726-dda8-44b9-b88e-9136787c5ac3.png)

maybe it is a good time do update?

2021-09-23 14:34 UTC, sampaiodiego requested changes
functionality wise it seems good.

I'll just reinforce the need of an upgrade.. current version is also showing a message on browser's console:
![image](https://user-images.githubusercontent.com/8591547/134527123-33fb500d-1125-4fda-be00-a590132c489e.png)

2021-09-23 14:34 UTC, sampaiodiego commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Message_Code_highlight": "Message Code highlight",
I don't think this is explanatory enough to admins..

I'd consider something like "Code languages highlights"
And also add a description to explain better what it does, like "Comma separated list of languages (link to list of supported languages https://github.com/highlightjs/highlight.js/tree/9.18.5#supported-languages ) that will be used to highlight code blocks"

2021-09-23 21:11 UTC, sampaiodiego approved these changes

2021-09-23 22:07 UTC, merged