[FIX][ENTERPRISE] OAuth "Merge Roles" removes roles from users
RocketChat/Rocket.Chat pull request #23588
Opened 2021-10-28 20:20 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

- Fix OAuth "Merge Roles": the "Merge Roles" option now synchronize only the roles described in the "**Roles to Sync**" setting available in each Custom OAuth settings' group (instead of replacing users' roles by their OAuth roles);
- Fix "Merge Roles" and "Channel Mapping" not being performed/updated on OAuth login.

## Issue(s)

Fix #14454
Fix #15225
Fix #19304
Fix #14559
[Task - ClickUp](https://app.clickup.com/t/1t4ck4)

## Steps to test or reproduce

Described in #14559 and #17466 

## Further comments

2021-11-04 22:01 UTC, pierre-lehnen-rc requested changes

2021-11-04 22:01 UTC, pierre-lehnen-rc commented on ee/server/lib/oauth/Manager.ts
> +			const toAdd = rolesFromSSO.filter((val: any) => !user.roles.includes(val) && rolesToSync.includes(val));
If the list is empty we can let it add any valid role to the user. 

```suggestion
			const toAdd = rolesFromSSO.filter((val: any) => !user.roles.includes(val) && (!rolesToSync.length || rolesToSync.includes(val)));
```

2021-11-05 14:38 UTC, matheusbsilva137 commented on app/lib/server/startup/oAuthServicesUpdate.js
> +					rolesToSync: process.env[`${ serviceKey }roles_to_sync`],
Tkss (dangerous one 😬 )

2021-11-10 06:44 UTC, pierre-lehnen-rc approved these changes

2021-11-22 18:58 UTC, pierre-lehnen-rc approved these changes

2021-11-22 19:45 UTC, merged