[FIX] bug showing "undefined" as channel name in Room Info action Modals
RocketChat/Rocket.Chat pull request #23760
Opened 2021-11-20 06:16 UTC by kulkarnigaurav38

- [X] I have read the Contributing Guide
  - [X] I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
  - [X] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

### BEFORE
https://user-images.githubusercontent.com/59637086/142716598-d45a4054-63ff-40e8-8b3f-bb11b6994142.mp4

### AFTER
https://user-images.githubusercontent.com/59637086/142716500-64a6a686-97d5-4725-b894-6acf15387ef6.mp4

## Issue(s)

Closes issue: #23759 
## Steps to test or reproduce
 Mentioned in the issue.

## Further comments

2021-12-01 13:19 UTC, ujorgeleite approved these changes

2021-12-06 04:56 UTC, ggazzo requested changes
Please the check your solution with discussions and multiple DMs, I'm afraid it will not work as expected.

2021-12-17 13:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23760) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=23760) it.</sub>

2022-11-03 20:50 UTC, dougfabris requested changes

2022-11-03 20:50 UTC, dougfabris commented on apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfoWithData.js
> +	const { type, name, prid, joined = true } = room; // TODO implement joined
```suggestion
	const { type, fname, name, prid, joined = true } = room; // TODO implement joined
```

2022-11-03 20:50 UTC, dougfabris commented on apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfoWithData.js
> +				text={t(warnText, name)}
```suggestion
				text={t(warnText, fname | name)}
```

2022-11-03 20:50 UTC, dougfabris commented on apps/meteor/client/views/room/contextualBar/Info/RoomInfo/RoomInfoWithData.js
> +				text={t(warnText, name)}
```suggestion
				text={t(warnText, fname | name)}
```

2022-11-03 23:43 UTC, dougfabris commented
Closing this one in favor of an older solution #20459
Thanks a lot for helping us @kulkarnigaurav38

2022-11-03 23:43 UTC, closed without merging