Chore: PoC prettier
RocketChat/Rocket.Chat pull request #23792
Opened 2021-11-25 19:50 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-11-26 14:57 UTC, ggazzo commented
❤️ 

my little secret: 
![image](https://user-images.githubusercontent.com/5263975/143599020-7be9ca38-d162-4297-a5f0-97aa11720cc3.png)
I have been using for a while, I'm 100% with you

2021-12-16 15:34 UTC, sampaiodiego requested changes
have you tried using the client's prettier config? https://github.com/RocketChat/Rocket.Chat/blob/develop/client/.prettierrc

or maybe another question, should we use the same config for the entire repo?

2021-12-16 15:54 UTC, KevLehman commented
> I have been using for a while, I'm 100% with you

I knew your formatting was too perfect <3 

> or maybe another question, should we use the same config for the entire repo?

Well that's a good question. I don't know 😬 should we? Would be good to have an "standard" style for the whole codebase, but, FE & BE may have different needs (?) (not sure tho)

2021-12-16 16:05 UTC, sampaiodiego commented
I think it works if we have a `.prettierrc` on root and others with specific rules in different folders.. maybe you can try that? 😬

2021-12-16 16:18 UTC, KevLehman commented
> I think it works if we have a .prettierrc on root and others with specific rules in different folders.. maybe you can try that? 😬

That could be, any rule you want in particular for BE? Maybe Gazzo can share his prettier 👀 (for reference purposes only)

2021-12-16 16:59 UTC, sampaiodiego commented
I guess you can move the one from `/client/.prettierrc` to root and see what happens 😬

2021-12-17 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23792) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23792) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=23792) it.</sub>

2021-12-29 14:59 UTC, closed without merging