[FIX] Sidebar context menu in searchList
RocketChat/Rocket.Chat pull request #23830
Opened 2021-11-30 21:32 UTC by Aman-Maheshwari

- [x]  I have read the Contributing Guide 
  - [x] I have signed the CLA 
  - [x] Lint and unit tests pass locally with my changes
  - [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
  - [ ] I have added necessary documentation (if applicable)
  - [ ] Any dependent changes have been merged and published in downstream modules

## Proposed changes (including videos or screenshots)

Removed onClose function from the Box Component inside `searchList.js`  as this component wraps the complete list which is rendered and when clicked on the any rendered row inside the component it closes the searchList preventing the context menu to be displayed.
Also added `usePreventDefault` hook.
## Before

https://user-images.githubusercontent.com/50165440/144127826-9b6d3e5e-9442-49dc-89c8-b604b910be4c.mp4

## After

https://user-images.githubusercontent.com/50165440/144127815-d60e1026-a0eb-4e9b-a7f3-fe80dd06a2d8.mp4

## Issue(s)

#22146 

## Steps to test or reproduce

Mentioned in the issue
## Further comments

This PR solves this [issue](#22146) but In this PR 
User can close the searchList only by clicking out somewhere which is handled via `useOutsideClick` hook or by clicking on the cross icon in the search box. Also this gives user a chance to handle multiple search results inside searchList unlike everytime clicking the search icon on sidebar and perform action to a individual searched room or a user.
Before this PR selecting a room or a user also closed the searchList but this action also prevented the context menu to get open as the searchList was closed immediately after clicking.

2021-12-01 06:01 UTC, ankar84 commented
Nice fix!

2021-12-01 06:08 UTC, Aman-Maheshwari commented
Thank you @ankar84 :smile:

2021-12-17 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23830) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23830) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=23830) it.</sub>

2022-04-11 12:53 UTC, dougfabris requested changes
@Aman-Maheshwari Nice fix, thanks for your help. In touch with our product team, we decided we should keep closing the spotlight after selecting a room. Also there's some conflicts, could you check it?

2022-11-18 17:43 UTC, dougfabris approved these changes

2022-11-18 20:21 UTC, merged