[FIX] Toolbox render item
RocketChat/Rocket.Chat pull request #23862
Opened 2021-12-04 00:19 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2021-12-06 00:06 UTC, ggazzo submitted a review, later dismissed

2021-12-06 00:07 UTC, ggazzo requested changes
try to update fuselage to the last version before ant then check the resulto

2021-12-06 13:27 UTC, dougfabris commented
> try to update fuselage to the last version before ant then check the resulto

@ggazzo Even using the latest version we need this fix

2021-12-06 15:05 UTC, ggazzo commented
> @ggazzo @dougfabris
> 
> I'm mad. This component has a insane amount of crappy code at first glance:
> 
> * code commented out without, ironically, any remarks why is deactivated;
> * atrociously large render props;
> * `memo` for _two_ properties;
> * `useMutableCallback` for a value that _may_ be used as default value;
> * Enough logic to be put in a separate hook;
> * `any`, too much `any`, even an `any` assertion.
> 
> And above it all, I don't know what `id` and `value` mean to even review it. Please folks, fix it.

I'm pretty sure you are aware this component was created based on the `Menu` (and that component is a mess as well), and the intention for this pull request is only "fit" the type introduced on `fuselage`

but you are 100% right there are a lot of space to improvements

2021-12-07 22:50 UTC, ggazzo approved these changes

2021-12-07 22:50 UTC, merged