[FIX] Popover position for arabic languages
RocketChat/Rocket.Chat pull request #23888
Opened 2021-12-07 13:47 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

- change the RC language to some arabic language.
- Userdrop down goes out of the screen on rightside

## Further comments

2021-12-10 15:20 UTC, dougfabris requested changes

2021-12-10 15:20 UTC, dougfabris commented on app/ui-utils/client/lib/popover.js
> +	this.observer && this.observer.disconnect();
```suggestion
	this.observer?.disconnect();
```

2021-12-10 20:08 UTC, dougfabris approved these changes

2021-12-10 20:14 UTC, ali-alhaidary commented
https://github.com/RocketChat/Rocket.Chat/issues/23599

2021-12-10 20:19 UTC, ali-alhaidary commented
https://github.com/RocketChat/Rocket.Chat/issues/22923

2021-12-14 01:49 UTC, merged

2021-12-29 05:39 UTC, ali-alhaidary commented
Still in v4.3.0

2021-12-30 14:26 UTC, dougfabris commented
> Still in v4.3.0

Can you provide more details? It's working fine here: 
![image](https://user-images.githubusercontent.com/27704687/147760413-45c60e34-1444-4e46-aabf-800137e2b15f.png)

2022-01-13 05:06 UTC, ali-alhaidary commented
> > Still in v4.3.0
> 
> @ali-alhaidary Can you provide more details? It's working fine here: ![image](https://user-images.githubusercontent.com/27704687/147760413-45c60e34-1444-4e46-aabf-800137e2b15f.png)

https://github.com/RocketChat/Rocket.Chat/issues/23599

still in 4.3.1

2022-01-13 16:54 UTC, dougfabris commented
@ali-alhaidary Please, provide some screenshots or logs. We couldn't reproduce it anymore!!

2022-01-14 17:32 UTC, JeroenAdam commented
I can confirm this is solved. Upgraded from 4.2.2 to 4.3.1.

2022-01-20 01:35 UTC, ali-alhaidary commented
https://github.com/RocketChat/Rocket.Chat/issues/23599
Still in v4.3.2

2022-01-20 19:56 UTC, dougfabris commented
@ali-alhaidary As I'm trying to say to you I'm not able to reproduce the error. Just sending us that the issue remains won't help us at all. Please, provide more details!
The screenshot above is an attempt to reproduce. Am I missing something?
![image](https://user-images.githubusercontent.com/27704687/150411875-ea69b4ee-f3c1-4647-9bd8-aed75a731833.png)

2022-03-10 06:51 UTC, ali-alhaidary commented
still in 4.5.1

2022-03-19 11:58 UTC, ali-alhaidary commented
still in 4.4.2