[Fix] Fixed the issue of owner not being able to leave team when he is the only participant
RocketChat/Rocket.Chat pull request #23976
Opened 2021-12-16 20:57 UTC by aswinidev

Fixes #23956 

## Proposed changes (including videos or screenshots)

## Issue(s)

Fixes #23956 

## Steps to test or reproduce

Mentioned in the issue

## Further comments

2021-12-16 21:02 UTC, aswinidev commented
This is an initial commit i need to make some changes like the sidebar menu option is still having the same issue but the leave option from the team info menu is fixed now.

2021-12-17 13:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23976) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=23976) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=23976) it.</sub>

2022-11-09 11:19 UTC, gabriellsh commented
This looks super weird TBH. You click `Leave` and endup in a modal that'll delete the channel, even though there's no clear indicative of that (e.g. the title is very misleading). Feels like bad UX.

It is way better than just locking the user, but I think we can do better. Maybe we could have a warning modal with an action button to open the delete modal. WDYT?

2022-11-09 11:45 UTC, gabriellsh requested changes

2022-11-09 11:45 UTC, gabriellsh commented on apps/meteor/client/views/teams/contextualBar/info/TeamsInfoWithData.js
> +	const { value } = useEndpointData(
Use `useQuery` instead.

2022-11-09 15:03 UTC, dougfabris commented
> This looks super weird TBH. You click `Leave` and endup in a modal that'll delete the channel, even though there's no clear indicative of that (e.g. the title is very misleading). Feels like bad UX.
> 
> It is way better than just locking the user, but I think we can do better. Maybe we could have a warning modal with an action button to open the delete modal. WDYT?

@gabriellsh I'm planning to do the last option.

2026-08-17 19:43 UTC, gabriellsh commented
Closing for the same reason as in https://github.com/RocketChat/Rocket.Chat/issues/23956#issuecomment-5319323558

2026-08-17 19:43 UTC, closed without merging