[FIX] for keeping messages when Message Erasure Type is set to 'Keep'
RocketChat/Rocket.Chat pull request #24024
Opened 2021-12-25 12:54 UTC by arshxyz

## Proposed changes
Check thread on https://github.com/RocketChat/Rocket.Chat/issues/23896

## Issue(s)
https://github.com/RocketChat/Rocket.Chat/issues/23896

2021-12-27 11:27 UTC, murtaza98 requested changes
Hey @arshxyz I feel the first approach you mentioned [here](https://github.com/RocketChat/Rocket.Chat/issues/23896#issuecomment-988779797) looks more elegant since there is no need to send a broadcast in case the event is not valid. I'd recommend using that solution instead. Thanks!!

2021-12-29 20:15 UTC, arshxyz commented
I've made the changes accordingly, thanks

2021-12-30 03:54 UTC, murtaza98 commented on server/modules/listeners/listeners.module.ts
> +		service.onEvent('user.deleted', ({ _id: userId }, keepMessages) => {
Do we still need this change?

2021-12-30 03:54 UTC, murtaza98 commented on server/sdk/lib/Events.ts
> +	'user.deleted'(user: Partial<IUser>, keepMessages: boolean): void;
Same goes here

2021-12-30 06:01 UTC, arshxyz commented on server/sdk/lib/Events.ts
> +	'user.deleted'(user: Partial<IUser>, keepMessages: boolean): void;
nope, both changes have been removed

2021-12-30 06:01 UTC, arshxyz commented on server/sdk/lib/Events.ts
> +	'user.deleted'(user: Partial<IUser>, keepMessages: boolean): void;
should be fine now

2021-12-30 13:44 UTC, murtaza98 approved these changes

2021-12-30 13:52 UTC, merged