[IMPROVE] Add user to room on "Click to Join!" button press
RocketChat/Rocket.Chat pull request #24041
Opened 2021-12-28 18:22 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

- Add user to room on "Click to Join!" button press;
- Display the "Join" button in discussions inside channels (keeping the behavior consistent with discussions inside groups).

## Issue(s)

Fix #19420

## Steps to test or reproduce

1. Start a new Jitsi call in a channel or discussion (logged in as a member of the room). Then, access the room as another user and press the "Click to Join!" button. **_Expected behavior:_** the user should join the room (if they're not already a member).
2. Access a discussion inside a **channel** (public room). **_Expected behavior:_** If the user is not a member of the discussion, a "Join" button should be displayed in the message box.

## Further comments

2022-01-06 14:45 UTC, tassoevan submitted a review, later dismissed

2022-01-06 14:45 UTC, tassoevan commented on app/videobridge/client/actionLink.js
> +			if (room && room?.muted?.includes(username)) {
```suggestion
			if (room?.muted?.includes(username)) {
```

2022-01-06 14:45 UTC, tassoevan commented on app/videobridge/client/actionLink.js
> +			const jitsiTimeout = new Date((room && room.jitsiTimeout) || currentTime).getTime();
```suggestion
			const jitsiTimeout = room ? new Date(room.jitsiTimeout).getTime() : currentTime;
```

2022-01-06 14:45 UTC, tassoevan commented on app/videobridge/client/actionLink.js
> +					setTimeout(() => openVideoCall(rid), 2000);
Why 2 seconds?

2022-01-12 17:07 UTC, matheusbsilva137 commented on app/videobridge/client/actionLink.js
> +
```suggestion
	const userId = Meteor.userId();
	const sub = Subscriptions.findOne({ rid, 'u._id': userId });
	if (!sub) {
		Meteor.call('joinRoom', rid);
	}

```
I think we should add the user to the room here, right? If so, we should also add the `Subscriptions` import
Currently, the user is able to join the call, but they don't join the room while doing so.

2022-02-09 19:19 UTC, ostjen requested changes

2022-02-09 19:19 UTC, ostjen commented on app/action-links/server/lib/actionLinks.js
> +function getMessage(messageId) {
I think it'd be better to change this function name, because `getMessage` already exists in the `actionLinks` namespace

2022-02-10 13:26 UTC, ostjen requested changes

2022-02-10 13:26 UTC, ostjen commented on server/lib/messages/getMessageForUser.ts
> +	const room = await Rooms.findOne(message.rid);
I'll merge canAccessRoomId today, just wait a little bit and make the changes 😀

2022-02-10 18:49 UTC, ostjen approved these changes
lgtm

2022-02-10 20:43 UTC, merged