[FIX] Subscription roles can be removed even if they are being used
RocketChat/Rocket.Chat pull request #24052
Opened 2021-12-29 13:58 UTC by pierre-lehnen-rc

2022-01-11 19:59 UTC, matheusbsilva137 submitted a review, later dismissed

2022-01-13 15:51 UTC, dougfabris requested changes
After updating some role it generates a new one with the same `_id` 
Reloading the page, it works normally 🤔 

![Kapture 2022-01-13 at 12 49 53](https://user-images.githubusercontent.com/27704687/149362979-f2dd7d1d-0d8c-42f8-8a8a-70dd691799b5.gif)

2022-01-20 17:18 UTC, dougfabris submitted a review, later dismissed

2022-03-16 22:56 UTC, matheusbsilva137 requested changes

2022-03-16 22:56 UTC, matheusbsilva137 commented on server/lib/roles/addUserRoles.ts
> +		throw new Error('error-invalid-user');
Maybe we should throw `MeteorError`s instead to assure they are shown in the UI.

2022-03-16 22:56 UTC, matheusbsilva137 commented on server/lib/roles/removeUserFromRoles.ts
> +		throw new Error('error-invalid-user');
Maybe it'd also be good to throw `MeteorError`s here

2022-03-20 22:29 UTC, pierre-lehnen-rc commented on app/api/server/v1/roles.ts
> +			const existingUsers = await Roles.findUsersInRole(role._id);
The second param expects a room id, not a role scope. By sending undefined, it will search in all rooms.

2022-03-21 16:38 UTC, pierre-lehnen-rc commented on app/authorization/server/functions/hasRole.ts
> +	}
Both functions on this file can be called externally, so they both need to validate the input.

2022-03-22 19:22 UTC, ggazzo commented on server/methods/afterVerifyEmail.ts
> +// Shouldn't this respect role settings?
```suggestion
```

2022-03-22 19:26 UTC, ggazzo commented on server/startup/migrations/v258.ts
> +		);
```suggestion
		const roleMap = Object.fromEntries(filteredRoles.map(
			(prev: Record<IRole['name'], IRole['_id']>, { _id, name }) => ([name,  _id]),
		));
```

2022-03-22 19:33 UTC, ggazzo requested changes

2022-03-22 19:33 UTC, ggazzo commented on server/startup/migrations/v258.ts
> +		).toArray();
try to avoid toArray for large collections

2022-03-22 21:42 UTC, ggazzo approved these changes

2022-03-22 21:46 UTC, merged