[IMPROVE] Throw 404 error in invalid endpoints
RocketChat/Rocket.Chat pull request #24053
Opened 2021-12-29 15:46 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

- Throw 404 error when trying to call invalid endpoints.

## Issue(s)

## Steps to test or reproduce

**_Expected output to an invalid endpoint:_**
```
{
  "statusCode": 404,
  "body": {
    "success": false,
    "error": "Resource not found"
  }
}
```

## Further comments

2021-12-29 17:42 UTC, sampaiodiego requested changes
You'll need to fix new eslint/prettier rules 😬

2021-12-29 17:42 UTC, sampaiodiego commented on app/api/server/api.js
> +		'Access-Control-Allow-Origin': '*',
I don't think this header is needed 🤔

2021-12-30 14:25 UTC, matheusbsilva137 commented on app/api/server/api.js
> +		'Access-Control-Allow-Origin': '*',
Yeah, it isn't. Removed 🙂

2021-12-30 15:22 UTC, pierre-lehnen-rc submitted a review, later dismissed

2021-12-30 19:54 UTC, pierre-lehnen-rc approved these changes

2021-12-30 19:58 UTC, merged