[FIX] Workaround for use of the default settings collection
RocketChat/Rocket.Chat pull request #24095
Opened 2022-01-03 20:36 UTC by MartinSchoeler

This is a workaround for us to swiftly be able to use the default settings collection and system.

This will allow us to use the default settings ui for now, after the MVP we will discuss again a better way to maintain traceability.

2022-01-03 20:42 UTC, ggazzo requested changes
use return first

2022-01-06 16:59 UTC, tiagoevanp approved these changes

2022-01-12 14:35 UTC, sampaiodiego requested changes

2022-01-12 14:35 UTC, sampaiodiego commented on server/services/voip/service.ts
> +		} as IVoipServerConfig;
looks like the type casting is not needed.
```suggestion
		};
```

2022-01-12 14:35 UTC, sampaiodiego commented on server/services/voip/service.ts
> +			_id: '',
looks like `IVoipServerConfig` doesn't need extend `IRocketChatRecord` anymore.. so you don't need to provide `_id: ''` (which doesn't make sense anyways)

2022-01-12 14:35 UTC, sampaiodiego commented on server/services/voip/service.ts
> +			_updatedAt: new Date(),
same as before, not extending `IRocketChatRecord` this is not required

2022-01-13 16:26 UTC, sampaiodiego approved these changes
oh, not sure how my suggestions didn't break other parts of the code.. 🙊  I see `IVoipServerConfig` still being used as a type for a database record, like on this model: 
https://github.com/RocketChat/Rocket.Chat/blob/780dabee9d3d15b2b30876a6d6adadf76f52f628/app/models/server/raw/VoipServerConfiguration.ts#L4

I'll approve this PR anyways as it seems that there still work needed to make this "voip server config" thing to work, and I think it can be done on the target branch.

2022-01-21 20:14 UTC, merged