[IMPROVE] Team system messages feedback
RocketChat/Rocket.Chat pull request #24209
Opened 2022-01-18 19:04 UTC by ostjen

## Proposed changes (including videos or screenshots)

- Delete some keys that aren't being used (eg: User_left_female).
- Add new Teams' system messages:
    - `added-user-to-team`: **added** @\user to this Team;
    - `removed-user-from-team`: **removed** @\user from this Team;
    - `user-converted-to-team`: **converted** #\room to a Team;
    - `user-converted-to-channel`: **converted** #\room to a Channel;
    - `user-removed-room-from-team`: **removed** @\user from this Team;
    - `user-deleted-room-from-team`: **deleted** #\room from this Team;
    - `user-added-room-to-team`: **deleted** #\room to this Team;
- Add the corresponding options to hide each new system message and the missing `ujt` and `ult` hide options.

## Issue(s)

Closes #22420

## Steps to test or reproduce

## Further comments

2022-01-21 15:23 UTC, tassoevan approved these changes

2022-01-21 17:15 UTC, dougfabris requested changes
Missing some sys messages!

2022-02-16 22:24 UTC, dougfabris requested changes
@matheusbsilva137 mgs id to check in `cronProcessDownload`:
- `user-removed-room-from-team`
- `user-deleted-room-from-team`
- `user-added-room-to-team`
- `ujt`
- `ult`

2022-02-17 11:23 UTC, dougfabris submitted a review, later dismissed
LGTM thanks a lot @matheusbsilva137

2022-02-18 00:35 UTC, dougfabris approved these changes

2022-02-18 00:37 UTC, merged