[FIX] Issues on selecting users when importing CSV
RocketChat/Rocket.Chat pull request #24253
Opened 2022-01-21 16:37 UTC by guijun13

## Proposed changes (including videos or screenshots)

* Fix users selecting by fixing their _id
* Add condition to disable 'Start importing' button if `usersCount`, `channelsCount` and `messagesCount` equals 0
* Remove `disabled={usersCount === 0}` on user Tab

## Steps to test or reproduce

### For user selection error fix:
1. Create a CSV file (e.g. users.csv) with the following content:
```
bradley.hilton,bradley.hilton@example.com,Bradley Hilton
billy.bob, billy.bob@example.com, Billy Bob Jr.
graywolf336,graywolf336@example.com,GrayWolf336
```
2. Create a ZIP file containing only the CSV file you created in the previous step;

3. Go to Administration > Import > Import New File, then choose CSV as the Import Type and upload the ZIP file from your computer;

4. Click on Import. Expected behavior: 3 users should be displayed with all the info given in the CSV file.

5. Click on Start Importing. Expected behavior: all 3 users should be successfully imported with their corresponding real names (what can be checked in Administration > Users);

6. Delete the 3 users and repeat this process using a CSV with a single user. No error should be displayed in the whole process.

### For disabled 'Start Importing' button:

1. Repeat steps 1 to 4 on the previous task.
2. Unselect all 3 users. Expected behavior: the 'Start Importing' button should be unable to click. Can also test with channels.

### For removed `disabled={usersCount === 0}` on user Tab:

1. Create a CSV file (e.g. users.csv) with the following content:
```
bradley.hilton,bradley.hilton@example.com,Bradley Hilton
billy.bob, billy.bob@example.com, Billy Bob Jr.
graywolf336,graywolf336@example.com,GrayWolf336
```
2. Create a CSV file (e.g. channels.csv) with the following content:
```
"general","bradley.hilton","public",""
"otherChannelName","billy.bob","public",""
"random","bradley.hilton","public","billy.bob;graywolf336"
"privateArea","bradley.hilton","private","graywolf336"
```

3. Create a ZIP file containing both CSVs file you created (users.csv and channels.csv) in the previous step;

4. Go to Administration > Import > Import New File, then choose CSV as the Import Type and upload the ZIP file from your computer;

5. Click on Import. Expected behavior: 3 users and 4 channels should be displayed with all the info given in the CSV file (in different tabs);

6. Unselect all users. Expect behavior: the 'users' tab should not be disabled.

## Further comments

2022-01-21 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=24253) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=24253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=24253) it.</sub>

2022-01-27 13:38 UTC, matheusbsilva137 approved these changes

2022-02-01 15:21 UTC, tassoevan requested changes

2022-02-01 15:21 UTC, tassoevan commented on app/importer/server/classes/ImportDataConverter.ts
> +		users.forEach(({ data: u, _id }) => {
Better keep it as `data` to rhyme with the property `IImportRecord['data']`.

2022-02-01 21:32 UTC, tassoevan approved these changes

2022-02-08 16:43 UTC, pierre-lehnen-rc approved these changes

2022-02-08 20:40 UTC, merged