[FIX] VRecDialog Camera Permission Issue Resolved
RocketChat/Rocket.Chat pull request #24280
Opened 2022-01-25 10:17 UTC by nishant23122000

## Proposed changes (including videos or screenshots)

Mention in issue #24279

After resolving thee bug:

https://user-images.githubusercontent.com/53515714/150957806-99c1c7cf-bc99-4619-9e5e-fbbe678c1225.mp4

## Issue(s)
 #24279

## Steps to test or reproduce
available in issue number #24279

## Further comments

2022-01-25 13:35 UTC, debdutdeb requested changes

2022-01-25 13:35 UTC, debdutdeb commented on packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Camera_is_blocked":"Camers is blocked, change the browser setting to allow it",
```suggestion
  "Camera_is_blocked": "Camera is blocked, change the browser setting to allow it",
```

2022-01-26 13:10 UTC, nishant23122000 commented
Hi @murtaza98  Can you merge this PR?

2022-03-11 12:54 UTC, murtaza98 approved these changes
LGTM!

2022-04-21 13:15 UTC, murtaza98 commented
Hi @nishant23122000 Some tests are failing here. Do u mind taking a look?

2022-04-21 13:23 UTC, nishant23122000 commented
Ok let me check

2022-04-21 14:23 UTC, nishant23122000 commented
Hi, @murtaza98 Please check now.

2022-06-13 15:39 UTC, dougfabris requested changes

2022-06-13 15:39 UTC, dougfabris commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Camera_is_blocked":"Camers is blocked, change the browser setting to allow it",
```suggestion
  "Camera_blocked_change_browser_setting_to_allow": "Camera is blocked, change the browser setting to allow it",
```

2022-06-13 15:39 UTC, dougfabris commented on apps/meteor/app/ui-message/client/messageBox/messageBoxActions.js
> +		if (permissionStatus.state === 'denied') return dispatchToastMessage({ type: 'error', message: t('Camera_is_blocked') });
```suggestion
		if (permissionStatus.state === 'denied') return dispatchToastMessage({ type: 'error', message: t('Camera_blocked_change_browser_setting_to_allow') });
```

2022-06-14 05:37 UTC, nishant23122000 commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Camera_is_blocked":"Camers is blocked, change the browser setting to allow it",
Done

2022-06-14 05:37 UTC, nishant23122000 commented on apps/meteor/app/ui-message/client/messageBox/messageBoxActions.js
> +		if (permissionStatus.state === 'denied') return dispatchToastMessage({ type: 'error', message: t('Camera_is_blocked') });
Hey @dougfabris Done, Thanks

2022-06-14 13:31 UTC, nishant23122000 commented
check now 🙂

2023-02-15 05:44 UTC, murtaza98 commented
Thanks, @nishant23122000. Please confirm if this PR is still relevant in light of the most recent modifications to message composer. If so, kindly assist us in resolving the conflicts so that this PR can be moved for review once more :pray:

2023-03-01 16:33 UTC, closed without merging