fix for issue 21659
RocketChat/Rocket.Chat pull request #24326
Opened 2022-01-28 07:31 UTC by dpanchuk

This is fix for search checkbox.
The problem was in giving "global search enabled" option value to "search all" payload by default.
#21659

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-01-28 07:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=24326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=24326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=24326) it.</sub>

2022-01-28 07:50 UTC, glebPo commented
👍

2022-01-28 07:56 UTC, serjotaylor commented
finally!!!

2022-02-03 06:56 UTC, ankar84 commented
@ggazzo please take a look at that fix
cc @dudanogueira @debdutdeb

2022-02-03 06:57 UTC, ankar84 commented
There is another community fix https://github.com/RocketChat/Rocket.Chat/pull/20594

2022-09-14 18:34 UTC, debdutdeb requested changes
HI @dpanchuk thanks for this PR!

Initially I was thinking about changing the element to reflect what actually is being done (i.e. keep it checked instead of unchecked if global search is enabled).

BUT, I like the idea of not defaulting to that behaviour but leave it as a toggle for the users to switch manually, who actually is meaning to use it.

2022-09-14 18:34 UTC, debdutdeb commented on app/search/client/provider/result.js
> +	this.data.parentPayload.searchAll = (!!this.globalSearchEnabled && !!this.data.parentPayload.searchAll);
```suggestion
	this.data.parentPayload.searchAll = false;
```
You can just set it to false

2022-09-20 16:46 UTC, dudanogueira commented
Hi! Thanks for your contribution. We will close this PR in favor of 
https://github.com/RocketChat/Rocket.Chat/pull/25568

2022-09-20 16:46 UTC, closed without merging