[IMPROVE] Skip encryption for slash commands in E2E rooms
RocketChat/Rocket.Chat pull request #24475
Opened 2022-02-10 20:07 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

Currently Slash Commands don't work in an E2EE room, as we encrypt the message before slash command is detected by the server, So removed encryption for slash commands in e2e rooms.

## Issue(s)

## Steps to test or reproduce

- Create an E2EE room
- Try to execute any slash command in it.
- Slash command sent as normal encrypted message.

## Further comments

### Before
![image](https://user-images.githubusercontent.com/58601732/153487577-51ff16e6-b8be-4b89-a52c-725030c20884.png)

### After
![image](https://user-images.githubusercontent.com/58601732/153487959-08ea5d47-89c8-4e1d-85bd-ec3ab0dd3152.png)

2022-02-11 17:42 UTC, albuquerquefabio requested changes

2022-02-11 17:42 UTC, albuquerquefabio commented on client/startup/e2e.ts
> +			if (!(await e2eRoom.shouldConvertSentMessages(message))) {
```suggestion
                        const isConvert = await e2eRoom.shouldConvertSentMessages(message)
			if (!isConvert) {
```

2022-02-11 20:47 UTC, yash-rajpal commented on client/startup/e2e.ts
> +			if (!(await e2eRoom.shouldConvertSentMessages(message))) {
Done! Thanks!

2022-02-18 19:32 UTC, albuquerquefabio approved these changes

2022-02-21 18:14 UTC, merged