Chore: added instances endpoint types
RocketChat/Rocket.Chat pull request #24507
Opened 2022-02-14 20:42 UTC by felipe-rod123

## Proposed changes (including videos or screenshots)

Created typing for endpoint definitions on `instances.ts`.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-02-16 13:12 UTC, sampaiodiego requested changes
looks like the typings for an "Instance" object is really messed up 🙈 

if you look the [endpoint code](https://github.com/RocketChat/Rocket.Chat/blob/d42f1643f1b6ceff55ae079509879a4433741ffb/app/api/server/v1/instances.ts#L20), it returns 
```
{
  ...instance,
  connection,
}
```

`instance` is `IInstanceStatus` - but `IInstanceStatus` is missing a lot of properties on the type definition
`connection` is the return of [getConnection](https://github.com/RocketChat/Rocket.Chat/blob/d42f1643f1b6ceff55ae079509879a4433741ffb/server/stream/streamBroadcast.js#L296) which is essentially an `IInstance` object.

maybe this PR is a good opportunity to get all this types fixed? 👀

2022-03-10 17:20 UTC, ggazzo commented on app/api/server/v1/instances.ts
> +					const connection = getInstanceConnection(instance) as IInstanceStatus;
create a `d.ts` definition

2022-03-10 17:22 UTC, ggazzo commented on definition/IInstance.ts
> +/*
delete the file

2022-03-10 17:22 UTC, ggazzo commented on definition/IInstanceStatus.ts
> +	// IInstance props
```suggestion
```

2022-03-10 17:24 UTC, ggazzo requested changes
Please check the comments ;)

2022-03-11 12:15 UTC, ggazzo approved these changes

2022-03-11 12:15 UTC, merged