[IMPROVE] OTR refactoring
RocketChat/Rocket.Chat pull request #24757
Opened 2022-03-08 20:04 UTC by albuquerquefabio

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-05-11 19:11 UTC, debdutdeb commented on apps/meteor/app/otr/client/IOTR.ts
> +import { OtrRoomState } from './OtrRoomState';
ahh - didn't look there 🙈

2022-05-18 15:07 UTC, tassoevan requested changes

2022-05-18 15:07 UTC, tassoevan commented on packages/core-typings/src/IMessage/IMessage.ts
> -	temp?: boolean;
Keep it; there are other situations beyond OTR were a message is temporary (e.g. network latency).

2022-07-26 22:32 UTC, tassoevan approved these changes

2022-08-09 18:03 UTC, merged