[IMPROVE] Standarize queue behavior for managers and agents when subscribing
RocketChat/Rocket.Chat pull request #24837
Opened 2022-03-15 20:03 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-03-16 17:38 UTC, tiagoevanp requested changes

2022-03-16 17:38 UTC, tiagoevanp commented on app/livechat/server/api/lib/inquiries.js
> +			// Add _always_ the "public queue" to returned list of inquiries (task: 26uu9ep)
remove clickup task reference on comment

2022-03-16 20:38 UTC, KevLehman commented on app/livechat/server/api/lib/inquiries.js
> +			// Add _always_ the "public queue" to returned list of inquiries (task: 26uu9ep)
Fixed!

2022-03-17 13:30 UTC, tiagoevanp approved these changes

2022-03-17 14:22 UTC, merged