[FIX] Regression: re-adding team statistics and new omnichannel statistic
RocketChat/Rocket.Chat pull request #25012
Opened 2022-03-31 16:31 UTC by cauefcr

Sorry data team, the missing stats are on me.

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-03-31 23:13 UTC, KevLehman approved these changes

2022-04-01 02:43 UTC, sampaiodiego requested changes

2022-04-01 02:43 UTC, sampaiodiego commented on app/statistics/server/lib/statistics.ts
> +				statistics.totalOTRRooms = Rooms.find({ createdOTR: true }).count();
the field `createdOTR` is missing an index and this query should be inside the model.. the method can be named liked `Rooms.findByCreatedOTR()`

2022-04-01 02:43 UTC, sampaiodiego commented on app/statistics/server/lib/statistics.ts
> +			new Promise<void>((resolve) => {
there is no need for this promise.

2022-04-01 02:43 UTC, sampaiodiego commented on ee/app/license/server/getStatistics.ts
> +			statistics.businessHourType = settings.get('Livechat_business_hour_type');
this doesn't need to be in a promise.

2022-04-01 17:05 UTC, KevLehman requested changes
Can you create an index on `message.t`? Looks like we don't have one and that may affect perf (since messages collection is the biggest one)

2022-08-16 13:26 UTC, closed without merging