Feat/new user events app
RocketChat/Rocket.Chat pull request #25234
Opened 2022-04-19 19:36 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

[Rocket.chat.Apps-engine PR](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/500)

2022-05-03 20:31 UTC, AllanPazRibeiro submitted a review, later dismissed
LGTM

2022-05-16 00:28 UTC, d-gubert requested changes

2022-05-16 00:28 UTC, d-gubert commented on apps/meteor/app/authentication/server/startup/index.js
> +	}
This might not be the case when the user is logging-in by using third-party services (e.g. Google, Facebook, etc.). Let's review this part

2022-05-22 21:41 UTC, d-gubert approved these changes

2022-05-22 21:41 UTC, merged

2022-05-23 22:16 UTC, wreiske commented
Yes! Yes! And YES! Thank you for this PR and the other PRs related to user events. You guys rock!!