[IMPROVE] Pinned Messages in E2E rooms
RocketChat/Rocket.Chat pull request #25325
Opened 2022-04-27 18:12 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

### Before
<img width="630" alt="Screenshot 2022-04-27 at 11 08 59 PM" src="https://user-images.githubusercontent.com/58601732/165591760-ab535329-05c9-4097-879c-1c4cdd57da1d.png">

### After
<img width="460" alt="Screenshot 2022-04-27 at 11 09 15 PM" src="https://user-images.githubusercontent.com/58601732/165591881-339694b8-f056-4c68-8704-2f86aafa11ab.png">

In Pinned Messages contextual bar -
<img width="414" alt="Screenshot 2022-04-27 at 11 29 25 PM" src="https://user-images.githubusercontent.com/58601732/165591936-610ebdff-41b3-4e6b-a80a-b2d32b4571f4.png">

If we don't have E2EE keys - 
<img width="831" alt="Screenshot 2022-04-27 at 11 08 44 PM" src="https://user-images.githubusercontent.com/58601732/165592021-3bf12df2-6b9e-4b3b-a48f-d88291c1f30e.png">

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-23 15:28 UTC, hugocostadev requested changes
Instead of passing the prop `rid` to be used to decrypt the message, try to use one of the existing hooks to get the `rid` , `useUserRoom` or `useRoom`

You can also detach the `useRoom` hook from `RoomContext` if needed

2022-08-23 21:09 UTC, yash-rajpal commented on apps/meteor/client/components/message/Attachments/DefaultAttachment.tsx
> +							<AttachmentText>{applyMarkdownIfRequires(attachment.mrkdwn_in, 'text', decryptedAttachmentText, 'document')}</AttachmentText>
Discussed this internally and decided that its not worth the hassle.

2022-08-25 10:52 UTC, hugocostadev approved these changes

2022-09-15 04:25 UTC, ggazzo requested changes

2022-09-15 04:25 UTC, ggazzo commented on apps/meteor/client/components/message/Attachments/DefaultAttachment.tsx
> +	const attachmentMessage = useDecryptedMessage({ ...attachment, msg: attachment.text, rid } as IMessage);
this is supposed to be only the visual component, we should not include "hard logic here", also useOpenedRoom requires a RoomContext, and we want render messages outside room (like message auditing).

why not decrypt the message just after fetch/receive ?

2022-09-22 12:03 UTC, hugocostadev approved these changes

2024-06-20 13:11 UTC, closed without merging