Chore: convert invites, misc and subscriptions to TS and create definitions
RocketChat/Rocket.Chat pull request #25350
Opened 2022-04-30 03:16 UTC by felipe-rod123

## Proposed changes (including videos or screenshots)

Converted `apps/meteor/app/api/server/v1/invites.js`, `misc.js` and `subscriptions.js` to Typescript and created their endpoint definitions on the rest-typings folder.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-05-24 02:33 UTC, ggazzo requested changes
Please create the json schema for each endpoint

2022-06-07 16:21 UTC, pierre-lehnen-rc commented on packages/rest-typings/src/v1/misc.ts
> +
```suggestion

```

2022-06-07 16:24 UTC, pierre-lehnen-rc commented on apps/meteor/app/api/server/v1/misc.ts
> +
```suggestion

```

2022-06-07 16:28 UTC, pierre-lehnen-rc approved these changes

2022-06-07 20:11 UTC, ggazzo approved these changes

2022-06-07 20:12 UTC, merged