[CHORE]: Convert assets endpoint to Typescript
RocketChat/Rocket.Chat pull request #25358
Opened 2022-05-02 00:22 UTC by MarcosSpessatto

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-05-04 18:19 UTC, ggazzo commented on apps/meteor/app/api/server/v1/assets.ts
> +			const isValidAsset = Object.keys(RocketChatAssets.assets).includes(assetName as string);
what about insert a proper test to guarantee this is actually a string?

2022-05-06 19:25 UTC, sampaiodiego requested changes
as a rule of thumb, when I see a type casting, I think there is something wrong.. I'd ask to avoid as must as possible. I've made several change requests and questions on most of them.

2022-05-06 19:25 UTC, sampaiodiego commented on apps/meteor/app/assets/server/assets.ts
> +		const asset = settings.get<Record<string, any>>(assetName);
this returns a `IRocketChatAsset` right?
```suggestion
		const asset = settings.get<IRocketChatAsset>(assetName);
```

2022-05-06 19:25 UTC, sampaiodiego commented on apps/meteor/app/assets/server/assets.ts
> +		} as Record<string, any>,
any special reason that you had to add this? is complaining some options are not in `ISettingAddOptions`? maybe the best should be adding them there.

2022-05-06 19:25 UTC, sampaiodiego commented on apps/meteor/app/assets/server/assets.ts
> +	const currentValue = settings.get<Record<string, any>>(key);
same as before
```suggestion
	const currentValue = settings.get<IRocketChatAsset>(key);
```

2022-05-06 19:25 UTC, sampaiodiego commented on apps/meteor/app/assets/server/assets.ts
> +		if (getAssetByKey(asset).constraints.extensions.includes(extension as string) === false) {
I saw the return of `mime.extension` can actually be a `boolean`, do you know when it can return a `boolean`? and what we should do in that case?

2022-05-06 19:25 UTC, sampaiodiego commented on apps/meteor/app/assets/server/assets.ts
> +		const file = getAssetByKey(params.asset) && getAssetByKey(params.asset).cache;
why not store `getAssetByKey(params.asset)` in a variable and use it in the rest of the function? you checking if it has values in a lot of places

2022-05-06 19:25 UTC, sampaiodiego commented on apps/meteor/app/assets/server/assets.ts
> +	}) as any,
is this really needed?

2022-05-09 13:52 UTC, MarcosSpessatto commented on apps/meteor/app/api/server/v1/assets.ts
> +			const isValidAsset = Object.keys(RocketChatAssets.assets).includes(assetName as string);
For some reason the type for this property is `string | undefined` 🤔

2022-05-09 13:54 UTC, MarcosSpessatto commented on apps/meteor/app/assets/server/assets.ts
> +		const _hasPermission = hasPermission(Meteor.userId() as string, 'manage-assets');
The validation is already there. But even with the validation, I need to cast it, any other idea?

2022-05-11 17:00 UTC, ggazzo commented on apps/meteor/app/api/server/v1/assets.ts
> +API.v1.addRoute<'assets.unsetAsset', { authRequired: true }>(
```suggestion
API.v1.addRoute(
```

2022-05-11 17:08 UTC, ggazzo submitted a review, later dismissed

2022-06-17 14:55 UTC, ggazzo approved these changes

2022-06-17 16:22 UTC, merged