[FIX] UI/UX issues on Live Chat widget
RocketChat/Rocket.Chat pull request #25407
Opened 2022-05-05 12:23 UTC by MartinSchoeler

- [x] Quick reply buttons don't fit the UI/Message container
- [X] Rocket.chat logo is not the latest one

*Will be ready to review as soon as https://github.com/RocketChat/Rocket.Chat/pull/25312 is merged*

2022-05-11 15:39 UTC, KevLehman approved these changes

2022-05-12 15:06 UTC, KevLehman reviewed
If you're not using the logo, maybe you can remove it from the widget files too 👀

2022-05-12 15:06 UTC, KevLehman commented on packages/livechat/src/components/Footer/index.js
> +			{/* <Logo className={createClassName(styles, 'powered-by__logo')} width={60} height={60 * 272 / 1500} role='img' aria-label='Rocket.Chat' /> */}
👀

2022-05-12 17:44 UTC, KevLehman submitted a review, later dismissed

2022-05-12 21:44 UTC, dougfabris approved these changes

2022-05-13 16:57 UTC, dougfabris requested changes

2022-05-13 16:57 UTC, dougfabris commented on packages/livechat/src/components/Footer/index.js
> +		<a style={{ height: '10px', display: 'inline-flex', alignItems: 'center' }} href='https://rocket.chat' target='_blank' rel='noopener noreferrer'>
inline style? 😢 
shouldn't be in gray as the previous one?

2022-05-16 14:34 UTC, dougfabris approved these changes

2022-05-16 19:10 UTC, merged