Chore: Rewrite autotranslate to ts
RocketChat/Rocket.Chat pull request #25425
Opened 2022-05-06 19:40 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-05-09 12:38 UTC, sampaiodiego commented on packages/core-typings/src/IMessage/MessageAttachment/MessageAttachmentBase.ts
> +	text?: string;
I see `text` is already defined at `MessageAttachmentDefault` , so not sure it should be moved to here or we should keep it there..

idk why having both types "Default" and "Base" for "MessageAttachment" to be honest.. 🤔  maybe @ggazzo can give some background on why both exists.

2022-05-09 12:45 UTC, sampaiodiego requested changes

2022-05-11 17:01 UTC, KevLehman commented on apps/meteor/client/contexts/ServerContext/methods.ts
> +	'autoTranslate.getProviderUiMetadata': (...args: any[]) => [string, { name: string; displayName: string }];
Didn't see the fromEntries 😬

2022-05-20 19:23 UTC, ggazzo approved these changes

2022-05-20 19:24 UTC, merged