[NEW] Adding app action button on room sidebar
RocketChat/Rocket.Chat pull request #25463
Opened 2022-05-10 21:31 UTC by AllanPazRibeiro

## Proposed changes (including videos or screenshots)

This PR adds the possibility  for an App to add buttons on the room sidebar menu, as the below screenshot shows:
![sidebar](https://user-images.githubusercontent.com/35040806/167725156-367456e2-045d-4a71-929e-0051071c7b34.png)

As you can see there will be a section for the apps to add buttons to do stuff like open modals, open contextual bar, and so on.

## Issue(s)

## Steps to test or reproduce

In order to add a button on the room sidebar menu, just create an app and add this snippet on `extendConfiguration` (main class method)

```typescript
     configuration.ui.registerButton({
            actionId: 'openModal',
            labelI18n: 'OPEN MODAL',
            context: UIActionButtonContext.ROOM_SIDEBAR_ACTION, 
            when: {
                roomTypes: [
                    RoomTypeFilter.DIRECT,
                ],
            },
        });
```

## Further comments

2022-05-12 19:36 UTC, tapiarafael submitted a review, later dismissed

2022-05-17 14:19 UTC, d-gubert requested changes

2022-06-27 12:41 UTC, ggazzo requested changes

2022-06-27 12:41 UTC, ggazzo commented
It would be great if we have the CI passing too

2026-01-20 16:45 UTC, closed without merging