[FIX] Add max width to Uikit component wrapper
RocketChat/Rocket.Chat pull request #25493
Opened 2022-05-12 19:03 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Fix uikit elements with full width

Before:
![Screenshot from 2022-05-12 15-58-51](https://user-images.githubusercontent.com/9275105/168149322-2e023e4f-b01e-4317-b2ae-00caf93d62c0.png)

After:
![Screenshot from 2022-05-12 15-59-08](https://user-images.githubusercontent.com/9275105/168149366-0faf7e81-293d-4111-bf4c-776aad984d56.png)

2022-05-20 13:04 UTC, gabriellsh approved these changes

2022-05-21 03:00 UTC, ggazzo requested changes

2022-05-21 03:00 UTC, ggazzo commented on apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
> +			)}
create a proper style inside fuselage for message block for that case, pay attention other blocks should stay as  100% width

2022-05-30 15:06 UTC, ggazzo approved these changes

2022-05-30 16:50 UTC, closed without merging