[FIX] Ordered and unordered list styles, Line breaks.
RocketChat/Rocket.Chat pull request #25494
Opened 2022-05-12 19:37 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

Also removed the message.md cache from server, since changes in the parser might break messages in the future (and will in this specific case).

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-05-12 21:58 UTC, ggazzo requested changes

2022-05-12 21:58 UTC, ggazzo commented on apps/meteor/client/views/room/MessageList/components/EncryptedMessageRender.tsx
> +	const tokens = useParsedMessage(message.msg);
if this message is encrypted there is a place were we decrypt, why not parse this value there?

2022-05-20 05:49 UTC, tassoevan requested changes

2022-05-20 05:49 UTC, tassoevan commented on apps/meteor/ee/server/services/package.json
> +		"@rocket.chat/message-parser": "0.31.12-dev.10",
```suggestion
		"@rocket.chat/message-parser": "next",
```

2022-05-23 12:48 UTC, ggazzo approved these changes

2022-05-23 12:55 UTC, merged