Chore: SlashCommand
RocketChat/Rocket.Chat pull request #25630
Opened 2022-05-25 13:52 UTC by ggazzo

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-05-27 12:37 UTC, tassoevan commented on apps/meteor/app/slashcommand-asciiarts/lib/shrug.ts
> +	(_command: 'shrug', params, item): void => {
An anonymous function is harder to debug.

2022-05-27 12:37 UTC, tassoevan commented on apps/meteor/app/slashcommand-asciiarts/lib/tableflip.ts
> +	(_command, params, item): void => {
An anonymous function is harder to debug.

2022-05-27 12:51 UTC, tassoevan requested changes

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-archiveroom/server/server.ts
> +	function Archive(_command, params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-create/server/server.ts
> +	function Create(_command: 'create', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-create/server/server.ts
> +		function getParams(str: string): string[] {
`nitpick` Maybe move it to the outer scope.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-help/server/server.ts
> +	function Help(_command, _params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-hide/server/hide.ts
> +	(_command: 'hide', param, item): void => {
An anonymous function is harder to debug.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-invite/server/server.ts
> +	(_command: 'invite', params, item): void => {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-join/server/server.ts
> +	(_command: 'join', params, item): void => {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-leave/server/leave.ts
> +const Leave: SlashCommand<'leave'>['callback'] = function Leave(_command, _params, item): void {
Redundant type function declaration.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-me/server/me.ts
> +	function Me(_command: 'me', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-msg/server/server.ts
> +	function Msg(_command: 'msg', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-mute/server/mute.ts
> +	function Mute(_command: 'mute', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-mute/server/unmute.ts
> +	function Unmute(_command, params, item): void | Promise<void> {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-open/client/client.ts
> +	function Open(_command, params): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-status/client/status.ts
> +	function Status(_command, params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-status/server/status.ts
> +	function Status(_command: 'status', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-topic/client/topic.ts
> +	function Topic(_command: 'topic', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-topic/server/topic.ts
> +	function Topic(_command: 'topic', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-05-27 12:51 UTC, tassoevan commented on apps/meteor/app/slashcommands-unarchiveroom/server/server.ts
> +	function Unarchive(_command: 'unarchive', params, item): void {
Nesting this function declaration as a parameter expression damages readability, as evidenced by the indentation increase.

2022-06-02 18:15 UTC, juliajforesti approved these changes

2022-06-03 15:58 UTC, merged

2022-06-03 15:58 UTC, ggazzo commented
if I do it the other way, it will force me to type the functions, which is a dynamic type, and it looks horrible @tassoevan