Chore: Update text from `Layout_Home_Body`
RocketChat/Rocket.Chat pull request #25711
Opened 2022-06-01 16:49 UTC by LucianoPierdona

## Proposed changes (including videos or screenshots)

Update `Layout_Home_Body` default text and add `blocked` field in it

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-07 12:03 UTC, matheusbsilva137 commented on apps/meteor/server/startup/migrations/v267.ts
> +		await Settings.updateMany(
```suggestion
		await Settings.updateOne(
```
Since only one setting will be updated, we could use `updateOne` here instead of `updateMany`.

2022-06-09 18:55 UTC, matheusbsilva137 requested changes
The changes applied to the `Layout_Home_Body` look fine. We still need to update the new `Layout_Custom_Body` setting, though
Maybe you could use ` Settings.getValueById('Layout_Home_Body')` before updating the `Layout_Home_Body` setting's value so that you know if `Layout_Custom_Body` should be true or false.

2022-06-13 14:23 UTC, gabriellsh reviewed
BTW, you forgot to import the migration in the index :p. I'm testing it so I'll fix it.

2022-06-13 14:56 UTC, gabriellsh submitted a review, later dismissed

2022-06-13 14:56 UTC, gabriellsh commented on apps/meteor/server/startup/migrations/v268.ts
> +					value: newValue,
We need to ALWAYS update the `packageValue` to be the new value. This ensures that when we click the `reset setting` button (red backwards arrow)  the text resets to the new value.

2022-06-14 19:55 UTC, matheusbsilva137 approved these changes

2022-06-14 20:00 UTC, gabriellsh approved these changes

2022-06-14 20:01 UTC, merged