[FIX] Wrong argument name preventing Omnichannel Chat Forward to User
RocketChat/Rocket.Chat pull request #25723
Opened 2022-06-02 13:18 UTC by dudanogueira

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce
Wrong argument passed to users.info api (userName instead of username) that prevents forwarding chat to agents.

## Further comments

2022-06-02 13:45 UTC, KevLehman commented
Hey, can you modify the typings for the endpoint `users.info` on `packages/rest-typings/src/v1/users.ts` too? That way, the build won't fail 😬 
On L5 of that file, you have: `GET: (params: { userId?: IUser['_id']; userName?: IUser['username'] }) => {` that should be `GET: (params: { userId?: IUser['_id']; username?: IUser['username'] }) => {`

2022-06-02 17:01 UTC, KevLehman requested changes

2022-06-02 17:08 UTC, dudanogueira commented on apps/meteor/client/components/Omnichannel/modals/ForwardChatModal.tsx
> +				const { user } = await getUserData({ username: username });
added!! Thanks!

2022-06-08 03:00 UTC, ggazzo approved these changes

2022-06-08 13:49 UTC, KevLehman approved these changes

2022-06-08 18:22 UTC, merged