[FIX] Broken Omnichannel>Agents page
RocketChat/Rocket.Chat pull request #25731
Opened 2022-06-02 18:13 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-02 18:15 UTC, KevLehman commented on apps/meteor/client/views/omnichannel/agents/AgentsRoute.tsx
> +	// }
👀

2022-06-02 18:27 UTC, tiagoevanp commented on apps/meteor/client/views/omnichannel/agents/AgentsRoute.tsx
> +	// }
ouch!

2022-06-02 20:19 UTC, MartinSchoeler requested changes

2022-06-02 20:19 UTC, MartinSchoeler commented on apps/meteor/client/components/FilterByText.tsx
> -		setFilter({ text });
Isn’t `setFilter` a required prop? It should never be undefined, if it is happening, we should fix the place that is not setting the prop

Or make it optional.

2022-06-02 20:32 UTC, ggazzo commented on apps/meteor/client/views/omnichannel/agents/AgentsRoute.tsx
> +				{context === 'edit' && id && <AgentEditWithData uid={id} reload={reload} />}
```suggestion
				{context === 'edit' && (id ? <AgentEditWithData uid={id} reload={reload} />: <SomeErrorPage />}
```

2022-06-02 20:51 UTC, tiagoevanp commented on apps/meteor/client/views/omnichannel/agents/AgentsRoute.tsx
> +				{context === 'edit' && id && <AgentEditWithData uid={id} reload={reload} />}
ok

2022-06-07 12:07 UTC, MartinSchoeler requested changes

2022-06-07 13:06 UTC, murtaza98 commented
@tiagoevanp Just a suggestion to add a basic test case for this page to verify if this page is getting loaded or not - just so we can avoid this type of issue in future

2022-06-07 13:29 UTC, tiagoevanp commented
> 

Yes, thanks for the comment Murtaza. I know that we have different teams working on tests outside of our main team at rocket.chat... Probably this case will be covered by them.

2022-06-07 16:38 UTC, MartinSchoeler approved these changes

2022-06-07 21:04 UTC, merged