Chore: Split useUserInfoActions into small hooks
RocketChat/Rocket.Chat pull request #25747
Opened 2022-06-03 15:31 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-10 20:37 UTC, gabriellsh approved these changes

2022-06-11 01:08 UTC, ggazzo requested changes
![image](https://user-images.githubusercontent.com/5263975/173166752-6483eee3-889e-4a9f-ad76-ddab6621a52d.png)
missing actions for user card and contextualbar

2022-06-17 14:49 UTC, ggazzo requested changes

2022-06-17 14:49 UTC, ggazzo commented on apps/meteor/client/views/room/lib/getRoomDirectives.ts
> +export const getRoomDirectives = (room: IRoom): { [key: string]: boolean } => {
explicit put the keys here

2022-06-17 17:57 UTC, d-gubert commented
It doesn't seem that us from @RocketChat/apps can contribute in reviewing this PR 🤔

2022-06-17 18:00 UTC, dougfabris commented
@d-gubert it was automatic for some reason, code owners 👀

2022-06-17 18:01 UTC, d-gubert commented
> @d-gubert it was automatic for some reason, code owners 👀

I thought so, but I can't even see anything we're owners of 👀  Weird stuff

2022-06-17 18:35 UTC, ggazzo approved these changes

2022-06-17 18:38 UTC, merged