[NEW][ENTERPRISE] New/mdm admin table
RocketChat/Rocket.Chat pull request #25773
Opened 2022-06-06 16:22 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-21 00:52 UTC, dougfabris requested changes
Awesome job here, congrats!
Some points to take a look at:
1. There's an overall issue related to TOTP when listing (`sessions/list.all`) and when getting info about the device (`sessions/info.admin`) it returning bad requests for some reason even when I set the TOTP auth, I would suggest taking a look on how it behaves without TOTP configured as well.

2. I'm missing the empty state when there are no devices. Additionally, I would suggest taking a look at the filter, the query is not filtering properly
![Screen Shot 2022-06-20 at 21 49 56](https://user-images.githubusercontent.com/27704687/174694108-054a9fcd-292e-43e0-bd17-0f3d037faa3a.png)

2022-06-21 00:52 UTC, dougfabris commented on apps/meteor/ee/client/views/admin/deviceManagement/DevicesTable.tsx
> +								deviceName={session?.device?.name || ''}
we should check which values should be required and try to not just pass empty strings for all these.

2022-06-21 00:52 UTC, dougfabris commented on apps/meteor/ee/client/startup/deviceManagement.ts
> +				i18nLabel: 'Device Management',
```suggestion
				i18nLabel: 'Device_Management',
```

2022-06-21 00:52 UTC, dougfabris commented on apps/meteor/ee/client/startup/deviceManagement.ts
> +			unregisterAdminSidebarItem('Device Management');
```suggestion
			unregisterAdminSidebarItem('Device_Management');
```

2022-06-21 00:52 UTC, dougfabris commented on apps/meteor/ee/client/views/admin/deviceManagement/DeviceInfoContextualBar.tsx
> +	const { username, name } = _user;
if there's no user, it's going to break the page, we should prevent it even in the render

2022-06-21 00:52 UTC, dougfabris commented on apps/meteor/ee/client/views/admin/deviceManagement/DeviceInfoContextualBar.tsx
> +	const closeContextualBar = useCallback((): void => deviceManagementRouter.push({}), [deviceManagementRouter]);
```suggestion
	const handleCloseContextualBar = useCallback((): void => deviceManagementRouter.push({}), [deviceManagementRouter]);
```

2022-06-21 00:52 UTC, dougfabris commented on apps/meteor/ee/client/views/admin/deviceManagement/DevicesRow.tsx
> +				<Menu
Would be nice to have, rendering the `Menu` only if there's more than one action if just one renders just the button!

2022-06-21 00:52 UTC, dougfabris commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Clients": "Clients",
```suggestion

```

2022-06-21 15:25 UTC, dougfabris commented on apps/meteor/ee/client/views/admin/deviceManagement/DevicesTable.tsx
> +					{phase === AsyncStatePhase.LOADING && <GenericTableLoadingTable headerCells={6} />}
*product team decided to move with generic one*

2022-06-21 16:51 UTC, yash-rajpal commented on apps/meteor/ee/client/views/admin/deviceManagement/DeviceIcon.tsx
> +const DeviceIcon = ({ deviceType }: { deviceType: string }): ReactElement => (
I agree with you, but I checked with the backend friends, they need this type to be string, its scope is bigger than MDM, and we extract the deviceType from userAgent so its difficult to restrict this type.

2022-06-22 11:41 UTC, dougfabris commented on apps/meteor/ee/client/views/admin/deviceManagement/DeviceIcon.tsx
> +const DeviceIcon = ({ deviceType }: { deviceType: string }): ReactElement => (
got it! 👍

2022-06-22 14:54 UTC, yash-rajpal commented on apps/meteor/ee/client/views/admin/deviceManagement/DeviceManagementRoute.tsx
> +	const canViewDeviceManagement = usePermission('view-engagement-dashboard');
Ouch!!

2022-06-22 17:35 UTC, dougfabris approved these changes

2022-06-22 18:29 UTC, merged