Chore: Change AddUsers to TS
RocketChat/Rocket.Chat pull request #25830
Opened 2022-06-10 16:19 UTC by csuadev

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-10 16:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=25830) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=25830) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=25830) it.</sub>

2022-06-10 22:21 UTC, ggazzo approved these changes

2022-06-14 13:18 UTC, dougfabris requested changes

2022-06-14 13:18 UTC, dougfabris commented on apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
> +				{onClickBack && <VerticalBar.Back onClick={onClickBack} name='arrow-back' />}
```suggestion
				{onClickBack && <VerticalBar.Back onClick={onClickBack} />}
```

2022-06-14 13:18 UTC, dougfabris commented on apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
> +	value: string[];
I would suggest to use the type from `IUser`

2022-06-14 15:57 UTC, dougfabris commented on apps/meteor/client/views/room/contextualBar/RoomMembers/AddUsers/AddUsers.tsx
> +				{onClickBack && <VerticalBar.Back onClick={onClickBack} name='arrow-back' />}
@csuadev fixed 😄

2022-06-15 17:20 UTC, dougfabris approved these changes

2022-06-20 04:57 UTC, yash-rajpal approved these changes

2022-06-20 07:33 UTC, merged