Chore: convert apps/meteor/app/api/server/lib/ files to TS
RocketChat/Rocket.Chat pull request #25840
Opened 2022-06-13 11:59 UTC by felipe-rod123

## Proposed changes (including videos or screenshots)

This pull request converts files on `apps/meteor/app/api/server/lib/` to Typescript.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-13 16:56 UTC, ggazzo commented on apps/meteor/app/api/server/lib/rooms.ts
> +		.map((item: IMessage) => item.rid);
`ISubscription `

2022-06-13 16:57 UTC, ggazzo commented on apps/meteor/app/api/server/lib/rooms.ts
> +		.map((item: IMessage) => item.rid);
```suggestion
		.map((item: ISubscription) => item.rid);
```

2022-06-13 16:57 UTC, ggazzo commented on apps/meteor/app/api/server/lib/emoji-custom.ts
> +	query: {};
```suggestion
	query: FilterQuery...;
```

2022-06-13 16:58 UTC, ggazzo requested changes
please check the suggestions

2022-06-14 04:21 UTC, KevLehman requested changes

2022-06-14 04:21 UTC, KevLehman commented on apps/meteor/app/api/server/lib/messages.ts
> +	const cursor = await Messages.findVisibleByMentionAndRoomId((user as IUser).username, roomId, {
What if you put this (as IUser) in line 25 instead? The type of `user` there should be IUser | null

2022-06-14 04:21 UTC, KevLehman commented on apps/meteor/app/api/server/lib/rooms.ts
> +		.map((item: ISubscription) => item.rid);
For consistency, this is not a complete ISubscription object, it's `Pick<ISubscription, 'rid'>`

2022-06-14 04:21 UTC, KevLehman commented on apps/meteor/app/api/server/lib/rooms.ts
> +		.map((item: ISubscription) => item.rid);
For consistency, this is not a complete ISubscription object, it's `Pick<ISubscription, 'rid'>`

2022-06-14 04:21 UTC, KevLehman commented on apps/meteor/app/api/server/lib/rooms.ts
> +		.map((item: ISubscription) => item.rid);
For consistency, this is not a complete ISubscription object, it's `Pick<ISubscription, 'rid'>`

2022-06-14 04:21 UTC, KevLehman commented on apps/meteor/app/api/server/lib/users.ts
> +export function getInclusiveFields(query: Query): {} {
🤔 this should be something like `{} | { [k; keyof typeof Query]: 1 }`

2022-06-14 04:21 UTC, KevLehman commented on apps/meteor/app/api/server/lib/users.ts
> +export function getNonEmptyQuery(query: Query): unknown {
This will return something different from unknown 👀

2022-06-15 13:00 UTC, ggazzo approved these changes

2022-06-15 17:26 UTC, merged