[FIX] add image format validation
RocketChat/Rocket.Chat pull request #25912
Opened 2022-06-17 17:16 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Add validation to prevent the 'heic' format to be uploaded on the room and user's avatar.
This format is not supported on the browsers and meteor.

Before:
<img width="417" alt="Screen Shot 2022-06-17 at 14 13 49" src="https://user-images.githubusercontent.com/9275105/174346567-30c669c9-2724-4392-ae32-34789edb59bf.png">
<img width="307" alt="Screen Shot 2022-06-17 at 14 14 13" src="https://user-images.githubusercontent.com/9275105/174346579-991d4bfb-b44f-4f99-aefb-35de3dd25d28.png">

After:
<img width="420" alt="Screen Shot 2022-06-17 at 14 15 06" src="https://user-images.githubusercontent.com/9275105/174346771-ddbb12fa-9a0f-45ca-8afe-4f6b5dc95ec7.png">
<img width="931" alt="Screen Shot 2022-06-17 at 14 16 01" src="https://user-images.githubusercontent.com/9275105/174346774-fdb4a33a-aaf2-4561-aee5-e501e87aa6c5.png">

2022-06-22 20:00 UTC, tassoevan submitted a review, later dismissed

2022-06-23 13:43 UTC, ggazzo requested changes
I still thinks this is something that the sever should handle @tassoevan wyt?

2022-06-23 13:54 UTC, filipemarins commented
> I still thinks this is something that the sever should handle @tassoevan wdyt?

I believe this is work for both sides because the browser will try to render this image and we will get an error, for now, we don't handle this kind of error and the user doesn't have proper feedback on what is happening. And make a request to server just to validate the format and return feedback to the client will be more expensive than treating on front.

2022-06-29 17:53 UTC, guijun13 approved these changes

2022-07-26 17:57 UTC, guijun13 submitted a review, later dismissed

2022-08-17 20:43 UTC, gabriellsh approved these changes

2022-08-18 16:11 UTC, merged