[NEW] Create releases tab in the marketplace app info page
RocketChat/Rocket.Chat pull request #25965
Opened 2022-06-22 19:44 UTC by rique223

## Proposed changes (including videos or screenshots)

To be written...

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-27 20:05 UTC, graywolf336 requested changes
Can we please have it only load the release tab and not cause the entire page to seem like it is loading? I expect to have it only load the tab information whenever I click on a tab when that app information is already there.

2022-06-28 15:55 UTC, rique223 commented
> Can we please have it only load the release tab and not cause the entire page to seem like it is loading? I expect to have it only load the tab information whenever I click on a tab when that app information is already there.

This was a little bug because of a misuse of the router functions, should be solved after this last commit.

2022-06-28 15:57 UTC, rique223 commented on apps/meteor/app/apps/server/communication/rest.js
> +						console.log('Rest js versions', result);
Solved

2022-06-28 16:09 UTC, rique223 commented
> Awesome, can you update the demo gif?

Sure can do

2022-06-28 20:11 UTC, ggazzo commented on packages/rest-typings/src/apps/index.ts
> +			success: boolean;
```suggestion
```

2022-06-28 20:11 UTC, ggazzo submitted a review, later dismissed

2022-06-29 15:24 UTC, graywolf336 requested changes
When no update information has been provided, let's provide a generic text saying "no release information was provided". You can get with the designers to see what they think would be better.

2022-06-29 19:22 UTC, graywolf336 approved these changes
Looks good!

2022-06-29 20:00 UTC, graywolf336 approved these changes

2022-06-29 22:28 UTC, ggazzo approved these changes

2022-06-29 22:52 UTC, merged