[NEW] Device Selection
RocketChat/Rocket.Chat pull request #25966
Opened 2022-06-22 20:31 UTC by MartinSchoeler

Conflicts:
	apps/meteor/client/contexts/CallContext.ts
	apps/meteor/client/lib/voip/VoIPUser.ts
	apps/meteor/client/providers/CallProvider/CallProvider.tsx
	apps/meteor/client/providers/MeteorProvider.tsx

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-24 19:39 UTC, sampaiodiego submitted a review, later dismissed

2022-06-28 14:55 UTC, KevLehman submitted a review, later dismissed

2022-06-28 16:05 UTC, KevLehman commented
This one, again, will be tested as part of full Outbound Calls feature

2022-06-28 16:55 UTC, aleksandernsilva requested changes

2022-06-28 16:55 UTC, aleksandernsilva commented on apps/meteor/ee/client/hooks/useDevicesMenuOption.tsx
> +	const isEnterprise = useHasLicense('livechat-enterprise');
`voip-enterprise`

2022-06-28 16:55 UTC, aleksandernsilva commented on apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
> +	);
Are we going to use the `useDevicesMenuOption` somewhere else? 
Because as I see we could have one `useDevicesMenusOptions` that does everything.

2022-06-28 16:55 UTC, aleksandernsilva commented on apps/meteor/client/sidebar/footer/voip/VoipFooter.tsx
> +							)}
You could use only one component:
`<Icon name='pause-unfilled' color={paused ? 'neutral-500' : 'info'} size='x24' />`

2022-06-28 16:55 UTC, aleksandernsilva commented on apps/meteor/client/sidebar/sections/components/OmnichannelMakeCall.tsx
> +export const OmnichannelMakeCall = (): ReactElement => {
This component needs to be removed. It has already been removed in the original branch.

2022-06-28 16:55 UTC, aleksandernsilva commented on apps/meteor/client/sidebar/sections/OmnichannelSection.tsx
> +				{isCallEnabled && isCallReady && isEnterprise && <OmnichannelMakeCall />}
This needs to be removed. It has already been removed in the original branch.

2022-06-28 19:29 UTC, KevLehman approved these changes

2022-06-28 19:36 UTC, aleksandernsilva submitted a review, later dismissed

2022-06-28 20:05 UTC, aleksandernsilva approved these changes

2022-06-28 20:14 UTC, KevLehman approved these changes

2022-06-28 21:25 UTC, merged