[IMPROVE] VoIP admin page cleanup: remove unused settings
RocketChat/Rocket.Chat pull request #25993
Opened 2022-06-23 21:48 UTC by cauefcr

## Proposed changes (including videos or screenshots)

https://app.clickup.com/t/2n4m61m

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-24 06:10 UTC, murtaza98 requested changes
@cauefcr  Overall looks good to me. I just had a couple of suggestions regarding the new DB model package and a missing type check. Added those in this PR: https://github.com/RocketChat/Rocket.Chat/pull/25998

2022-06-27 21:16 UTC, KevLehman approved these changes

2022-06-28 02:06 UTC, ggazzo approved these changes

2022-06-28 02:06 UTC, ggazzo commented on packages/core-typings/src/IVoipExtension.ts
> +	prop.hasOwnProperty('callServerConfig') && prop.hasOwnProperty('extensionDetails');
```suggestion
	'callServerConfig' in prop &&  'extensionDetails' in prop;
```

2022-06-28 04:10 UTC, murtaza98 submitted a review, later dismissed

2022-06-28 15:28 UTC, KevLehman approved these changes

2022-06-28 16:33 UTC, aleksandernsilva submitted a review, later dismissed

2022-06-28 17:14 UTC, KevLehman approved these changes

2022-06-28 20:02 UTC, KevLehman approved these changes

2022-06-29 02:36 UTC, ggazzo approved these changes

2022-06-29 02:41 UTC, merged