Fix: Unable to close chats when comments is disabled
RocketChat/Rocket.Chat pull request #26057
Opened 2022-06-29 09:19 UTC by murtaza98

## Proposed changes (including videos or screenshots)

Fixes https://github.com/RocketChat/Rocket.Chat/issues/25954

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-30 05:08 UTC, KevLehman commented
This is not a regression per se, but this would be a really annoying issue 😬 to keep on 5.0. 

@ggazzo , agree on put this as "regression" (it will go through normal QA anyways, but since the fix is pretty self contained, we should be good)

2022-06-30 11:04 UTC, murtaza98 commented
Yeah, I agree @KevLehman. And considering the release candidate deadline was extended we should have some time to get it reviewed and qa'd.

2022-06-30 21:54 UTC, MartinSchoeler requested changes
No need to add a new callback just for this, I think it would be better to do it inline

2022-06-30 21:54 UTC, MartinSchoeler commented on apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
> +			onConfirm={onSubmitWithoutCommentsAndTags}
```suggestion
			onConfirm={(): void => onConfirm()}
```

2022-06-30 21:54 UTC, MartinSchoeler commented on apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
> +
```suggestion
	
```

2022-07-01 03:10 UTC, murtaza98 commented on apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
> +
```suggestion
```

2022-07-01 06:16 UTC, murtaza98 commented
> No need to add a new callback just for this, I think it would be better to do it inline

Done :heavy_check_mark: , please check

2022-07-01 15:50 UTC, aleksandernsilva approved these changes

2022-07-01 16:07 UTC, merged