[NEW][ENTERPRISE] Introducing dial pad component into sidebar, calls table, contextual bar
RocketChat/Rocket.Chat pull request #26081
Opened 2022-06-30 18:07 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

This PR adds a new call button that can be used from Sidebar & Contact Center. This also enables Omnichannel agents to make outbound calls from within Rocket.Chat.

Depending on your server and call server configuration, you can do international calling, national and domestic calling.

The buttons on Contact Center allows an agent to call an existing number without having to type the number again. 

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-06-30 22:01 UTC, ggazzo requested changes

2022-06-30 23:04 UTC, ggazzo commented
I could not finish the call as well

2022-07-01 17:13 UTC, ggazzo submitted a review, later dismissed

2022-07-01 19:31 UTC, ggazzo submitted a review, later dismissed

2022-07-01 20:42 UTC, tiagoevanp approved these changes

2022-07-01 20:46 UTC, KevLehman submitted a review, later dismissed

2022-07-01 23:01 UTC, ggazzo approved these changes

2022-07-01 23:19 UTC, KevLehman approved these changes

2022-07-02 00:37 UTC, tiagoevanp approved these changes

2022-07-02 01:10 UTC, ggazzo approved these changes

2022-07-02 01:10 UTC, merged