Regression: Unavailable devices in unsupported browsers
RocketChat/Rocket.Chat pull request #26174
Opened 2022-07-07 14:34 UTC by MartinSchoeler

This PR disables device changes in browsers that not support the `setSinkId` method, and therefore does not support device changes directly from the browser

![Screen Shot 2022-07-07 at 11 18 10 AM](https://user-images.githubusercontent.com/20868078/177799024-8838e3be-b330-4604-a7bf-490944734da1.png)

I've decided to test if the `setSinkId` is available instead of listing browsers that supported or not, this way if a browser starts/stops supporting it, we don't have to do anything, and there is also firefox, where you can enable it as an optional feature.

2022-07-07 14:35 UTC, ggazzo requested changes

2022-07-07 14:38 UTC, ggazzo commented on apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
> +	const setSinkIdAvailable = useMemo(() => isSetSinkIdAvailable(), []);
```suggestion
	const [setSinkIdAvailable] = useState(() => isSetSinkIdAvailable());
```

2022-07-08 19:28 UTC, KevLehman requested changes

2022-07-08 19:28 UTC, KevLehman commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Device_Changes_Not_Available": "Device changes not available in this browser. For garanteed availability, please use Rocket.Chat's official desktop app.",
```suggestion
  "Device_Changes_Not_Available": "Device changes not available in this browser. For guaranteed availability, please use Rocket.Chat's official desktop app.",
```

2022-07-08 19:30 UTC, KevLehman commented
🤔 since the description goes to release, can you put a note mentioning that there's "experimental" support for the feature on Firefox through flags? https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId. Not recommended for longer use, but at least for trying out.

2022-07-08 19:53 UTC, MartinSchoeler commented
> 🤔 since the description goes to release, can you put a note mentioning that there's "experimental" support for the feature on Firefox through flags? https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId. Not recommended for longer use, but at least for trying out.

I wanted to avoid talking about browsers though, since today is experimental but tomorrow it might change

2022-07-11 15:02 UTC, KevLehman commented on apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
> +							{t('Desktop_App_Download')}
```suggestion
							{t('Download_Destkop_App')}
```

2022-07-11 15:11 UTC, KevLehman approved these changes

2022-07-11 16:26 UTC, KevLehman commented on apps/meteor/ee/client/voip/modals/DeviceSettingsModal.tsx
> +						<Box is='a' href='https://rocket.chat/download'>
```suggestion
						<Box is='a' href='https://rocket.chat/download' target='_blank' rel='noopener noreferrer'>
```

2022-07-11 17:06 UTC, aleksandernsilva approved these changes

2022-07-12 20:56 UTC, merged