Chore: Remove method meteor call on message action
RocketChat/Rocket.Chat pull request #26213
Opened 2022-07-11 13:06 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Remove method call on the message action component

2022-07-11 18:38 UTC, ggazzo requested changes

2022-07-11 18:38 UTC, ggazzo commented on apps/meteor/app/ui-utils/client/lib/MessageAction.ts
> +};
we were rejecting if there was an error, and where we are suppressing the error, is that correct?

2022-08-17 17:37 UTC, yash-rajpal approved these changes

2022-08-18 16:56 UTC, yash-rajpal approved these changes

2022-12-06 02:30 UTC, merged