Regression: User avatar not updating on new message template
RocketChat/Rocket.Chat pull request #26236
Opened 2022-07-12 17:46 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Fixes:
Message sequential after message thread preview
Avatar not updating after new message template

Passing an etag to user avatar component will force the re-render when avatar etag change.

Before (message sequential):
![image](https://user-images.githubusercontent.com/9275105/167900144-cd70d31c-1c9b-485c-bb0a-1818d3a91ac7.png)

After (message sequential):
![image](https://user-images.githubusercontent.com/9275105/167899989-1115f78c-b097-46ea-be32-d48706a0da06.png)

2022-07-13 18:02 UTC, gabriellsh requested changes

2022-07-13 18:31 UTC, filipemarins commented on apps/meteor/client/components/avatar/RoomAvatar.tsx
> +	const { avatarETag } = usePresence(room.uids?.filter((uid) => uid !== room.u?._id)[0]) || room;
Yes, this is the Room avatar, but this is the component used to handle the direct messages. I am getting the user id of the room, jus to get the user presence.

2022-07-14 11:48 UTC, hugocostadev requested changes
Hi @filipemarins ,

I found some issues... 

1. Using the hook `usePresence` only trigger if the user is not offline, if the user is offline we found several inconsistence in user Avatar, including on uploading a new one

2. Because of the limitation of usePresence, I suggest creating a hook only for avatar that gets the `avatarEtag` somehow through another origin, and always that the avatar changes, the hook will trigger all places that the avatar should change.

3. With your current solution  (when the user is online) the avatars got updated but one place did not... View profile through a room still shows the previous avatar

4. Also, be careful when using array index as a `key` prop, sometimes the original order could change and you lose reference

2022-07-14 17:45 UTC, gabriellsh requested changes

2022-07-14 17:45 UTC, gabriellsh commented on apps/meteor/client/components/RoomAutoComplete/Avatar.tsx
> +	type: RoomType;
Please, use `IRoom['type']` from `@rocket.chat/core-typings`. This type is from apps-engine.

2022-07-14 17:45 UTC, gabriellsh commented on apps/meteor/client/components/avatar/DirectRoomAvatar.tsx
> +	const { value: data } = useEndpointData(
I think we are better of using the usePresence hook. Even though it only brings offline users, getting the info from the endpoint won't be reactive, and we'll have the same problem again.

2022-07-14 17:45 UTC, gabriellsh commented on apps/meteor/client/components/avatar/UserAvatar.tsx
> +	const { value: data } = useEndpointData(
same here

2022-07-21 15:14 UTC, ggazzo commented
PARA DE ATUALIZAR SEU DOENTE

2022-07-21 15:14 UTC, ggazzo commented
E REVISA

2022-07-21 17:41 UTC, ggazzo commented
I'm closing this pr because it didn't fix the problem, and we already have a new solution in progress.

2022-07-21 17:41 UTC, closed without merging