Regression: Remove 4.0 version banner
RocketChat/Rocket.Chat pull request #26251
Opened 2022-07-13 15:12 UTC by hugocostadev

## Proposed changes (including videos or screenshots)

Created a migration to disable and dismiss for all users the old 4.0 version banner.
It happened when a new admin user has been added.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-07-14 20:52 UTC, filipemarins approved these changes

2022-07-15 18:07 UTC, sampaiodiego requested changes
I'm sorry, but where is this banner coming from?

I'd like to understand as this doesn't look like to be the best implementation for this purpose.

2022-07-18 10:54 UTC, hugocostadev commented
> I'm sorry, but where is this banner coming from?
> 
> I'd like to understand as this doesn't look like to be the best implementation for this purpose.

Hi @sampaiodiego, this banner was added in a previous migration ([v231](https://github.dev/RocketChat/Rocket.Chat/blob/4.8.1/apps/meteor/server/startup/migrations/v231.ts)) and the migration [v232](https://github.dev/RocketChat/Rocket.Chat/blob/4.8.1/apps/meteor/server/startup/migrations/v232.ts) tried to dismiss, but the problem is that the v232 migration just dismisses for admins if a user is added as admin after this migration execution the user is able to see the banner. This issue can be verified at:  https://unstable.rocket.chat/

2022-07-18 18:48 UTC, sampaiodiego commented on apps/meteor/server/startup/migrations/v278.ts
> +		const banners = users.map((a) => Promise.await(Banner.getBannersForUser(a._id, BannerPlatform.Web))).flat();
we also should avoid queries in loops like whenever it is possible.. in this case, after fetching 500k+ users, a new query will be performed for every user, synchronously (due to `Promise.await`).. so let's say the query takes only 20ms to execute, for 500k users this loop would take at least 10.000 seconds.

2022-07-18 18:49 UTC, sampaiodiego commented on apps/meteor/server/startup/migrations/v278.ts
> +		users.map((a) => Banner.dismiss(a._id, authBanner._id));
same as before, but in this case it is a write operation, that should take more than 20ms to execute.

2022-07-18 18:51 UTC, sampaiodiego requested changes
I've explained what we should avoid and why.. 

so please, you can change everything starting from line 26, and perform only the `Banner` from my previous comment:

```ts
Banners.updateOne({
  'view.blocks.0.text.text': /authentication\-changes/,
  active: { $ne: false }
}, {
  $set: {
    active: false,
    inactivedAt: new Date(),
  },
})
```

2022-07-19 11:34 UTC, hugocostadev commented
> I've explained what we should avoid and why..
> 
> so please, you can change everything starting from line 26, and perform only the `Banner` from my previous comment:
> 
> ```ts
> Banners.updateOne({
>   'view.blocks.0.text.text': /authentication\-changes/,
>   active: { $ne: false }
> }, {
>   $set: {
>     active: false,
>     inactivedAt: new Date(),
>   },
> })
> ```

Perfect Diego, I got it! Thanks so much for your explanations, indeed this is a much cleaner and wise solution

2022-07-19 15:04 UTC, sampaiodiego approved these changes

2022-07-19 17:11 UTC, merged