[Improve] Quotes on E2EE Messages
RocketChat/Rocket.Chat pull request #26303
Opened 2022-07-19 16:16 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

This PR provides basic quoting to E2EE messages, it doesn't support multiple chaining of quotes messages.

<img width="725" alt="Screenshot 2022-07-19 at 9 42 19 PM" src="https://user-images.githubusercontent.com/58601732/179798812-c0d092f1-388a-4d46-bb1d-9c332d14cc77.png">

## Issue(s)

#19110 
#16148 
## Steps to test or reproduce

## Further comments

2022-08-08 14:20 UTC, gabriellsh requested changes
I'd like to see e2e-ui tests for this too.

2022-08-08 14:20 UTC, gabriellsh commented on apps/meteor/app/e2e/client/rocketchat.e2e.js
> +			const quoteAttachment = {
I think we do something similar in backend for regular messages, right? Is there any possibility we could implement a function to generate an attachment from a message and use it in both places? We could event unit test this function after...

2022-10-19 15:42 UTC, gabriellsh approved these changes

2022-11-01 21:00 UTC, merged

2022-11-04 12:43 UTC, sampaiodiego commented on apps/meteor/app/e2e/client/rocketchat.e2e.ts
> +		console.log('before quote', decryptedMessage);
oopsie.. can someone pls remove these? 🙈

2022-11-07 20:19 UTC, yash-rajpal commented on apps/meteor/app/e2e/client/rocketchat.e2e.ts
> +		console.log('before quote', decryptedMessage);
Removed here - https://github.com/RocketChat/Rocket.Chat/pull/27092/commits/2d4f247bce23cf3e9728caab348665eb58a3bebb

Thanks!

2022-11-30 20:24 UTC, KamilSucharski commented
@yash-rajpal You linked this issue for this PR https://github.com/RocketChat/Rocket.Chat/issues/24721 , but it also requires working attachment previews in E2E to be closed. Is that included, or did you only modify quoting?