[FIX] UI fixes on dropdown titles
RocketChat/Rocket.Chat pull request #26318
Opened 2022-07-20 15:54 UTC by guijun13

## Proposed changes (including videos or screenshots)

- Add paddings on profile dropdown title
- Fix paddings on 'sort' and 'create new' dropdown titles

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-07-20 15:59 UTC, dougfabris commented on apps/meteor/client/components/SortList/ViewModeList.tsx
>  const style = {
I suggest removing this inline style and extending the component to receive these props, if the design team wants this flexibility on the title

2022-07-20 16:00 UTC, dougfabris requested changes

2022-07-20 16:00 UTC, dougfabris commented on apps/meteor/client/sidebar/header/actions/CreateRoomList.tsx
> +	paddingBlockEnd: '0.25rem',
same as I said above!

2022-07-20 16:00 UTC, dougfabris commented on apps/meteor/client/components/SortList/ViewModeList.tsx
>  const style = {
I suggest removing this inline style and extending the component to receive these props, if the design team wants this flexibility on the title

2022-08-12 11:16 UTC, dougfabris approved these changes

2022-08-18 18:59 UTC, ggazzo approved these changes

2022-08-18 18:59 UTC, merged