[FIX] undefined error toast message on user-edit admin view
RocketChat/Rocket.Chat pull request #26320
Opened 2022-07-20 17:41 UTC by debdutdeb

* `handleError` handles all property checks and casting (if necessary)

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-07-20 17:48 UTC, debdutdeb commented
ignore the very incorrect branch name 🙈

2022-08-10 13:00 UTC, tassoevan requested changes
I screwed up big time in this one.

However, I don't like the idea of slapping `any` at the caught errors... I believe a better approach for it is introducing a new function that takes an `unknown`-type error and uses `dispatchToastMessage` under the hood to figure the "stringification" out.

2022-08-15 13:37 UTC, ggazzo approved these changes

2022-08-16 13:16 UTC, murtaza98 approved these changes

2022-08-16 15:25 UTC, d-gubert approved these changes
Looking good on the Apps-Engine side

2022-08-16 16:22 UTC, merged