[FIX] livechat/department validatiors
RocketChat/Rocket.Chat pull request #26357
Opened 2022-07-25 16:22 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-07-25 16:48 UTC, KevLehman commented on apps/meteor/app/api/server/api.d.ts
> +	validateParams?: ValidateFunction | { [key in Method]?: ValidateFunction };
@ggazzo , the idea is to have `validateParams: { GET: xxxx, POST: xxxx }` so individual handlers can have its own validator

2022-07-26 13:57 UTC, KevLehman commented on apps/meteor/tests/end-to-end/api/livechat/10-departments.ts
> +describe.only('LIVECHAT - Departments', function () {
```suggestion
describe('LIVECHAT - Departments', function () {
```

2022-07-26 19:14 UTC, KevLehman commented on packages/rest-typings/src/v1/omnichannel.ts
> +		},
```suggestion
		agents: {
			type: 'array',
			items: {
				type: 'object',
				properties: {
					agentId: {
						type: 'string',
					},
				},
				required: ['agentId'],
				additionalProperties: false,
			},
			nullable: true,
		},
```

2022-07-29 10:59 UTC, murtaza98 commented on apps/meteor/app/livechat/server/api/lib/departments.ts
>  	uid: string;
```suggestion
```

2022-07-29 10:59 UTC, murtaza98 commented on apps/meteor/app/livechat/server/api/lib/departments.ts
>  	uid: string;
This param is no longer required here so we can delete it

2022-07-29 11:28 UTC, murtaza98 commented on packages/rest-typings/src/v1/omnichannel.ts
> +				},
This has a couple of more props namely `count` & `order`. Added them over here -> https://github.com/RocketChat/Rocket.Chat/pull/26410

2022-07-29 11:29 UTC, murtaza98 requested changes
@KevLehman FYI: Left some suggestions over here -> https://github.com/RocketChat/Rocket.Chat/pull/26410

2022-08-01 12:27 UTC, ggazzo approved these changes

2022-08-01 12:39 UTC, merged