Chore: create removeWebdavAccount endpoint
RocketChat/Rocket.Chat pull request #26393
Opened 2022-07-28 17:18 UTC by felipe-rod123

## Proposed changes (including videos or screenshots)

Created the '/v1/webdav.removeWebdavAccount' endpoint for the `apps/meteor/client/views/account/integrations/AccountIntegrationsPage.tsx` file, and added Ajv validations.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-11 22:19 UTC, dougfabris requested changes

2022-08-11 22:19 UTC, dougfabris commented on apps/meteor/tests/end-to-end/api/17-webdav.js
> +		// it('should return my webdav accounts', (done) => {
we should remove this commented test and add a success test as well

2022-08-18 19:21 UTC, dougfabris approved these changes

2022-08-19 21:10 UTC, ggazzo approved these changes

2022-08-19 21:10 UTC, merged