Allow to check permissions per method and specify if all or any are r…
RocketChat/Rocket.Chat pull request #26419
Opened 2022-07-29 19:26 UTC by KevLehman

…equired

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-10 14:59 UTC, sampaiodiego requested changes
picky comments can be addressed in a future engineering day =)

2022-08-10 14:59 UTC, sampaiodiego commented on apps/meteor/app/livechat/imports/server/rest/rooms.js
> +	{ authRequired: true, permissionsRequired: { GET: { permissions: ['view-livechat-rooms', 'view-l-room'], operation: 'hasAny' } } },
you didn't remove the checks from endpoint code

2022-08-10 14:59 UTC, sampaiodiego commented on apps/meteor/app/livechat/imports/server/rest/users.js
> +				if (!(await hasAtLeastOnePermission(this.userId, ['transfer-livechat-guest', 'edit-omnichannel-contact']))) {
either `await` for the `async` version or don't use `await`
```suggestion
				if (!(await hasAtLeastOnePermissionAsync(this.userId, ['transfer-livechat-guest', 'edit-omnichannel-contact']))) {
```

2022-08-10 14:59 UTC, sampaiodiego commented on apps/meteor/app/api/server/api.js
> +const checkPermisisonsForInvocation = (userId, permissionsPayload, requestMethod) => {
(picky alert)

we might need a better definition on these, but I think we should use more named functions.. 

maybe the definition could be: use arrow functions only when creating local/scoped functions, like a function inside another function. wdyt?

2022-08-10 14:59 UTC, sampaiodiego commented on apps/meteor/app/api/server/api.js
> +	checkPermissions(options) {
(pick alert 2)

this method could be a function in file's scope right?

I'd also recommend not changing the `options` param, but instead having  the `permissionRequired` as the return value.

having this function in TS and having a unit test would also be good

2022-08-10 17:38 UTC, sampaiodiego commented on apps/meteor/app/api/server/api.js
> +const checkPermisisonsForInvocation = (userId, permissionsPayload, requestMethod) => {
yep, I think we're missing a standard.. I'm worried about two things specifically:

- hoist variables and how that affects gc
- better stack traces

2022-08-12 06:50 UTC, murtaza98 commented on apps/meteor/app/livechat/imports/server/rest/users.js
> +			},
I believe there's a small issue here which changes the permission checks for this endpoint. If we take an example of agents (i.e. `:type=agent`), right now any user with **one of these 3 permission** is allowed to query this endpoint

- 'manage-livechat-agents'
- 'transfer-livechat-guest'
- 'edit-omnichannel-contact'

But with this new logic, the user will always need to have 'manage-livechat-agents' role & users with who don't have this role but do have the other 2 roles won't be able to access this endpoint

2022-08-12 06:51 UTC, murtaza98 commented on apps/meteor/app/livechat/imports/server/rest/users.js
> +			},
I believe there's a small issue here which changes the permission checks for this endpoint. If we take an example of agents (i.e. `:type=agent`), right now any user with **one of these 3 permission** is allowed to query this endpoint

- 'manage-livechat-agents'
- 'transfer-livechat-guest'
- 'edit-omnichannel-contact'

But with this new logic, the user will always need to have 'manage-livechat-agents' role & users who don't have this role but do have the other 2 roles won't be able to access this endpoint

2022-08-12 07:13 UTC, murtaza98 commented on apps/meteor/app/livechat/imports/server/rest/users.js
> +			},
FYI: fixed this here https://github.com/RocketChat/Rocket.Chat/pull/26552

2022-08-12 07:14 UTC, murtaza98 commented on apps/meteor/app/livechat/imports/server/rest/users.js
> +			},
FYI: fixed this here https://github.com/RocketChat/Rocket.Chat/pull/26552

2022-08-12 07:17 UTC, murtaza98 commented
Hey @KevLehman This looks really good :tada: I've left just a few suggestions over here https://github.com/RocketChat/Rocket.Chat/pull/26552 - they are mostly removing some permission checks which aren't required now & addressing the issue I mentioned above

2022-08-13 03:56 UTC, murtaza98 submitted a review, later dismissed
LGTM :tada:

2022-08-15 21:31 UTC, sampaiodiego approved these changes

2022-08-16 04:38 UTC, murtaza98 approved these changes

2022-08-16 16:38 UTC, KevLehman commented
@sampaiodiego @murtaza98 , you'll have to re-approve this one since there's a conflict :cry:

2022-08-16 16:49 UTC, KevLehman commented
btw, can we skip QA on this one? :eyes:

2022-08-16 16:51 UTC, sampaiodiego approved these changes

2022-08-16 16:52 UTC, sampaiodiego commented
since the endpoints changed are all omnichannel, I'll let you guys decide if you want to skip QA.

2022-08-17 05:55 UTC, murtaza98 approved these changes

2022-08-22 09:49 UTC, murtaza98 commented on apps/meteor/app/api/server/api.js
> +						console.log(result);
```suggestion
```

2022-08-22 09:51 UTC, murtaza98 approved these changes

2022-08-22 14:16 UTC, sampaiodiego approved these changes

2022-08-23 13:41 UTC, murtaza98 approved these changes

2022-08-23 21:18 UTC, merged