[FIX] return type and conditional
RocketChat/Rocket.Chat pull request #26425
Opened 2022-07-30 01:51 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-01 15:01 UTC, ggazzo requested changes
I think we have some issues opened related to that issue, could you mention them with 'closes'?


btw, could you create some test reproducing the steps to get stuck in this situation?

thanks

2022-08-01 17:48 UTC, gabriellsh requested changes

2022-08-01 17:48 UTC, gabriellsh commented on apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.js
> +	if (element) {
I believe this will reintroduce the previous bug of not scrolling to the correct message when following a URL.

2022-08-01 17:49 UTC, gabriellsh commented on apps/meteor/app/ui-utils/client/lib/RoomHistoryManager.js
> +	if (element) {
maybe we need to test `typeof element`? I remember when first resolving the issue I mentioned, `document.querySelector` was bringing an "empty" element that was not falsy.

2022-08-02 17:51 UTC, filipemarins commented
> I think we have some issues opened related to that issue, could you mention them with 'closes'?
> 
> btw, could you create some test reproducing the steps to get stuck in this situation?
> 
> thanks

Already have a [mention](https://github.com/RocketChat/Rocket.Chat/issues/26361#issuecomment-1200611347) for it.

I added a unit test to this method, I had to use the `jsdom` library inside the test to mock the `MutationObserver` class. The `jsdom-global` doesn't export the `MutationObserver` class.

2022-08-02 19:42 UTC, gabriellsh approved these changes
LGTM! I tested the old behaviour related to the message URLs and it doesn't seem to be happening. We should keep an eye open for it though.

2022-08-09 13:53 UTC, merged