Chore/ee models to raw
RocketChat/Rocket.Chat pull request #26544
Opened 2022-08-11 15:05 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-12 07:59 UTC, murtaza98 commented on apps/meteor/ee/server/models/raw/LivechatPriority.ts
> +
Indexes are missing for this collection

2022-08-12 10:50 UTC, murtaza98 commented on apps/meteor/ee/server/models/raw/LivechatUnitMonitors.ts
> +// Fix this to use the right typing
I believe we can remove this file now :) https://github.com/RocketChat/Rocket.Chat/blob/chore/ee-models-to-raw/apps/meteor/ee/app/models/server/models/LivechatUnitMonitors.js#L0-L1

2022-08-12 11:02 UTC, murtaza98 commented on apps/meteor/ee/app/models/server/index.js
>  import LivechatUnitMonitors from './models/LivechatUnitMonitors';
Do we still need this?

2022-08-12 11:14 UTC, murtaza98 commented on apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
> +		Promise.await(updateInquiryQueuePriority(room._id));
If syncronization isn't required, then maybe we can benifit from Promise.all() here

2022-08-12 11:14 UTC, murtaza98 commented on apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
> +		Promise.await(updateInquiryQueuePriority(room._id, priority));
If syncronization isn't required, then maybe we can benifit from Promise.all() here

2022-08-12 11:15 UTC, murtaza98 commented on apps/meteor/ee/app/livechat-enterprise/server/lib/Helper.js
>  	LivechatRooms.findOpenByPriorityId(priorityId).forEach((room) => {
There is not definition for `LivechatRooms.findOpenByPriorityId`

2022-08-18 18:00 UTC, sampaiodiego requested changes

2022-08-18 18:00 UTC, sampaiodiego commented on apps/meteor/ee/server/models/raw/LivechatUnit.ts
> +		return _.extend(record, { _id });
let's reduce `underscore` usage 😬 
```suggestion
		return { ...record, _id };
```

2022-10-14 17:29 UTC, closed without merging