[FIX] Team name validation failing always.
RocketChat/Rocket.Chat pull request #26574
Opened 2022-08-15 21:29 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-15 21:29 UTC, LucianoPierdona approved these changes

2022-08-16 13:06 UTC, ggazzo requested changes
could you create a test for this case? just to be sure we never gonna repeat this mistake again :x

2022-08-16 13:08 UTC, ggazzo approved these changes

2022-08-16 13:09 UTC, ggazzo commented
I heard @souzaramon is covering this test case so we are good to go

2022-08-16 13:09 UTC, merged