Chore: Create tests for admin add a custom fild
RocketChat/Rocket.Chat pull request #26609
Opened 2022-08-18 17:13 UTC by weslley543

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-18 17:14 UTC, souzaramon approved these changes

2022-08-22 14:44 UTC, souzaramon submitted a review, later dismissed

2022-08-25 17:43 UTC, tassoevan requested changes

2022-08-25 17:43 UTC, tassoevan commented on apps/meteor/tests/e2e/omnichannel-custom-fields.spec.ts
> +	test('expect add  new  "custom field"', async ({ page }) => {
```suggestion
	test('expect add new "custom field"', async ({ page }) => {
```

2022-08-25 17:43 UTC, tassoevan commented on apps/meteor/tests/e2e/omnichannel-custom-fields.spec.ts
> +	});
No cleanup of the new custom field after all tests?

2022-08-25 20:10 UTC, tassoevan approved these changes

2022-08-25 22:08 UTC, merged