[FIX] added message.replies property checks in the new message template
RocketChat/Rocket.Chat pull request #26640
Opened 2022-08-20 22:40 UTC by krenuser

## Proposed changes (including videos or screenshots)

[FIX] fixed new message template issue for some rooms, which is related to `message.replies` property usage without pre-check.

## Issue(s)

This fixes #26639 

## Steps to test or reproduce

_(Mentioned on issue page)_

## Further comments

2022-08-21 08:17 UTC, debdutdeb requested changes

2022-08-21 08:17 UTC, debdutdeb commented on apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
> +					following={Boolean(mineUid && message && message.replies && message?.replies.indexOf(mineUid) > -1)}
```suggestion
					following={Boolean(mineUid && message?.replies?.indexOf(mineUid) > -1)}
```

2022-08-21 08:17 UTC, debdutdeb commented on apps/meteor/client/views/room/MessageList/components/MessageContent.tsx
> +					participants={message && message.replies ? message?.replies.length : 0}
```suggestion
					participants={message?.replies?.length || 0}
```

2022-08-21 11:59 UTC, debdutdeb approved these changes
Lgtm

2022-08-21 12:53 UTC, krenuser commented
Can't understand what has failed during build job. 
Is it my fault? Should I fix something?

2022-08-22 16:08 UTC, filipemarins commented
We have a [pr with unit test](https://github.com/RocketChat/Rocket.Chat/pull/26652).

2022-08-22 16:08 UTC, closed without merging