[NEW] Message Forwarding
RocketChat/Rocket.Chat pull request #26662
Opened 2022-08-23 13:24 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-24 06:18 UTC, ankar84 commented
Wait for that feature a lot!

2023-01-27 18:42 UTC, ggazzo requested changes

2023-01-27 18:42 UTC, ggazzo commented on apps/meteor/client/providers/TooltipProvider.tsx
> +			};
nop, there reason to to this? I'm afraid this going to pollute the html and it doesnt work like before

2023-01-27 19:26 UTC, ggazzo approved these changes

2023-03-15 17:59 UTC, ggazzo requested changes

2023-03-15 17:59 UTC, ggazzo commented on apps/meteor/client/views/room/modals/ShareMessageModal/ShareMessageModal.tsx
> +	const handleShareMessage: MouseEventHandler<HTMLFormElement> = async (e) => {
use useMutation here to prevent user from submit multiple times

2023-03-15 22:07 UTC, ggazzo approved these changes

2023-03-15 22:34 UTC, merged