[NEW] URI allowed schemes
RocketChat/Rocket.Chat pull request #26697
Opened 2022-08-26 11:45 UTC by Chirtep

## Proposed changes (including videos or screenshots)

1. This feature by itself simply adds the ability to expand the scheme of working protocols (schemes), but does not add a new single scheme by default, which means no affect on security of app.

2. Feature allows the admin to add certain schemes in the settings (section "messages - markdown"). The admin himself is responsible for his server and must understand what he is doing and what it can lead to.

![image](https://user-images.githubusercontent.com/77800075/186895888-53a8facd-c241-43a1-a547-7b39d5799ca0.png)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-08-26 11:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=26697) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=26697) before we can accept your contribution.<br/><hr/>**Raweater** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=26697) it.</sub>

2022-11-11 02:08 UTC, filipemarins commented on apps/meteor/client/components/MarkdownText.tsx
> +				`${settings.get('Markdown_URIAllowedSchemes')}` +
```suggestion
				`${settings.get('Markdown_SupportSchemesForLink').split(',').join('|')}` +
```

I don't think we should create a new preference just for this case... We could use the `Markdown_SupportSchemesForLink` setting.

2022-11-11 02:11 UTC, filipemarins requested changes
Could you please also sign the [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=26697)?

2022-11-11 14:21 UTC, gabriellsh commented
Hi @Chirtep ! Thanks for your contribution!

Unfortunately, this will no longer be useful since we now only offer proper support to our own parser (https://github.com/RocketChat/fuselage/tree/develop/packages/message-parser).

Also, the place you modified only affects a few spare places that use the MarkdownText component. This meaning most important places (such as the message) would not change in any way.

Our new parser is way more permissive in regards of link protocols, and we're actively working to make it better. I'll be closing this for now, but again, thanks a lot for the effort!

2022-11-11 14:21 UTC, closed without merging

2022-11-11 18:43 UTC, gabriellsh commented
I made a very similar but yet different fix here: https://github.com/RocketChat/Rocket.Chat/pull/27245