Chore: collect coverage from backend
RocketChat/Rocket.Chat pull request #26712
Opened 2022-08-26 19:25 UTC by weslley543

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-09-02 12:59 UTC, souzaramon approved these changes

2022-09-16 16:46 UTC, ggazzo requested changes

2022-09-16 16:46 UTC, ggazzo commented on .github/workflows/build_and_test.yml
> +          yarn build
can I ask you why you are skipping the cache for this build?

2022-09-16 16:46 UTC, ggazzo commented on .github/workflows/build_and_test.yml
> +          yarn testunit:coverage --api="http://127.0.0.1:9080" --token="${{ secrets.TURBO_SERVER_TOKEN }}" --team='rc'
I dont think yarn testunit:coverage uses those params

2023-11-07 14:18 UTC, closed without merging