[FIX] Asset settings description not showing
RocketChat/Rocket.Chat pull request #26755
Opened 2022-08-30 21:16 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

Go to Administration > Settings > Assets is not showing the setting description

## Further comments

What:
Remove validation to check if the translation key exists to fulfill the settings label.

Why: 
After a [typescript rewrite](https://github.com/RocketChat/Rocket.Chat/pull/25572/files#diff-7251944fd19efbd942b887850f940cbdf6e571997147ab67375ae2d1680f5542R90) was added validation to check if translation key exists, but some settings label doesn't have a translation key, in this case, the label value was  `undefined`. I

2022-09-01 17:14 UTC, LucianoPierdona submitted a review, later dismissed

2022-09-05 11:45 UTC, gabriellsh requested changes

2022-09-05 11:45 UTC, gabriellsh commented on apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
> +								<Icon name='trash' data-qa-setting-delete-id={_id} />
why not `data-qa-type='delete-asset' data-qa-id={_id}`?

2022-09-05 11:45 UTC, gabriellsh commented on apps/meteor/client/views/admin/settings/inputs/AssetSettingInput.tsx
> +							data-qa-setting-id='assets-preview'
this could be `data-qa-type='asset-preview' since it's not an ID.

2022-09-06 18:37 UTC, gabriellsh approved these changes

2022-09-08 12:51 UTC, ggazzo requested changes

2022-09-08 12:51 UTC, ggazzo commented on apps/meteor/client/views/admin/settings/Setting.tsx
> +	const label = (i18nLabel && t(i18nLabel as TranslationKey)) || (_id && t(_id as TranslationKey));
```suggestion
	const label = (t.has(i18nLabel) && t(i18nLabel)) || (t.has(_id) && t(_id)) || i18nLabel || _id
```

2022-09-15 13:09 UTC, ggazzo approved these changes

2022-09-15 15:25 UTC, merged