[FIX] [Livechat] Unread messages badge
RocketChat/Rocket.Chat pull request #26843
Opened 2022-09-09 20:00 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

Even if the page was reopening, Livechat will inform unread messages

## Issue(s)

#25529

## Steps to test or reproduce

## Further comments

2022-09-12 14:37 UTC, aleksandernsilva submitted a review, later dismissed
Could you add e2e tests to prevent this issue from happening again?

2022-09-16 19:18 UTC, MartinSchoeler requested changes
Just some grammar suggestions on the tests nomenclature

2022-09-16 19:18 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
> +			test('expect message is sended by livechat', async () => {
```suggestion
			test('Expect message to be sent by livechat', async () => {
```

😃

2022-09-16 19:18 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
> +			test('expect message is received by agent', async () => {
```suggestion
			test('expect message to be received by agent', async () => {
```

2022-09-16 19:18 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
> +			test('expect message is sended by agent', async () => {
```suggestion
			test('Expect message to be sent by agent', async () => {
```

2022-09-16 19:18 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
> +			test("expect after user minimize livechat screen don't show composer", async () => {
```suggestion
			test("Expect when user minimizes the livechat screen, the composer should be hidden", async () => {
```

2022-09-16 19:18 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
> +			test('expect message is received by minimized livechat', async () => {
```suggestion
			test('expect message to be received by minimized livechat', async () => {
```

2022-09-16 19:18 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/omnichannel-livechat.spec.ts
> +			test('expect unread messages be visible after a reload', async () => {
```suggestion
			test('expect unread messages to be visible after a reload', async () => {
```

2022-09-16 19:40 UTC, MartinSchoeler submitted a review, later dismissed

2022-09-21 18:43 UTC, tiagoevanp commented on apps/meteor/client/components/Omnichannel/modals/CloseChatModal.tsx
> +					<Button role='button' type='submit' disabled={cannotSubmit} primary>
```suggestion
					<Button type='submit' disabled={cannotSubmit} primary>
```

2022-09-21 19:25 UTC, aleksandernsilva approved these changes

2022-09-21 22:31 UTC, ggazzo commented on packages/livechat/src/i18n/en.json
> +				"unread_messages_count_other": "{{count}} unread messages",
👀

2022-09-21 22:31 UTC, ggazzo approved these changes

2022-09-22 03:11 UTC, merged