[FIX] Scrollable report message
RocketChat/Rocket.Chat pull request #26853
Opened 2022-09-12 20:25 UTC by yasemincidem

## Proposed changes (including videos or screenshots)
The ellipsis is used to specify that some text has overflown in report message modal instead of scrolling all the content inside the modal.

<img width="615" alt="Screen Shot 2022-09-12 at 10 46 43 PM" src="https://user-images.githubusercontent.com/5556159/189751933-71dff444-7a8d-4ed6-a6fd-ec0b95cdc96c.png">

## Issue(s)
Fixes: #26837

## Steps to test or reproduce

## Further comments

2022-09-12 20:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=26853) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=26853) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=26853) it.</sub>

2022-09-28 11:56 UTC, dougfabris requested changes
you missed the margin prop 😅

2022-09-28 11:56 UTC, dougfabris commented on apps/meteor/client/views/room/modals/ReportMessageModal/ReportMessageModal.tsx
> +			<Box className={wordBreak}>{messageText}</Box>
```suggestion
			<Box className={wordBreak} mbe='x24'>{messageText}</Box>
```

2022-09-28 17:54 UTC, yasemincidem commented
> you missed the margin prop 😅

oops. That is right :)

2022-09-28 18:35 UTC, dougfabris approved these changes

2022-11-22 13:48 UTC, merged