Chore: create eraseRoom endpoint
RocketChat/Rocket.Chat pull request #26866
Opened 2022-09-14 01:09 UTC by felipe-rod123

## Proposed changes (including videos or screenshots)

Created the 'teams.eraseRoom' endpoint for the `apps/meteor/client/views/admin/rooms/EditRoom.tsx` file.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-09-21 12:55 UTC, ggazzo requested changes

2022-09-21 12:55 UTC, ggazzo commented on packages/rest-typings/src/v1/teams/index.ts
> +	'/v1/teams.eraseRoom': {
move to room

2022-09-21 12:55 UTC, ggazzo commented on packages/rest-typings/src/v1/teams/index.ts
> +	'/v1/teams.eraseRoom': {
/v1/room.erase

2022-09-28 13:19 UTC, ggazzo requested changes
pleas check comments bellow

2022-10-05 13:01 UTC, ggazzo approved these changes

2022-10-05 13:21 UTC, ggazzo commented
> any special reason to not follow the same pattern as `POST users.delete` ?

since we have no ~good~pattern defined I decided to follow the world convention (RestFul) and apply the http methods usage properly, maybe we could keep both (one because our ancient patterns and the right one) what do you think ?

2022-10-05 13:35 UTC, sampaiodiego commented
my suggestion is to use the same pattern we use on other endpoints, so for this one it would be `POST rooms.delete { roomId: 'ID-TO-DELETE' }` .. I know it is not the best pattern, but it is the one we use, so it is somewhat predictable if you're already familiar with Rocket.Chat API.

2022-10-18 19:17 UTC, sampaiodiego submitted a review, later dismissed

2022-11-01 18:02 UTC, sampaiodiego approved these changes

2022-11-01 19:53 UTC, merged