[FIX] Message sequential after message thread preview
RocketChat/Rocket.Chat pull request #26900
Opened 2022-09-19 14:38 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Message sequential after message thread preview

Before:
![Screen Shot 2022-09-19 at 11 37 36](https://user-images.githubusercontent.com/9275105/191043772-b390807f-1780-4968-afea-20d96d09171d.png)

After:
![Screen Shot 2022-09-19 at 11 37 09](https://user-images.githubusercontent.com/9275105/191043807-7e92d423-90d3-445d-b3d8-b5c8fb4cc97f.png)

2022-09-19 21:51 UTC, guijun13 submitted a review, later dismissed
LGTM

2022-09-20 11:19 UTC, hugocostadev requested changes

2022-09-20 11:19 UTC, hugocostadev commented on apps/meteor/client/views/room/MessageList/lib/isMessageSequential.spec.ts
>  });
Hi @filipemarins , if you check the file `.mocha.client.js` you will notice that just test files that are inside `tests/unit/**/*` are included in the pipeline, so you need to change to the expected path.
<img width="462" alt="Screen Shot 2022-09-20 at 8 18 40 AM" src="https://user-images.githubusercontent.com/20212776/191244518-6334a559-6a88-497d-9cbb-d24d5fef0ba8.png">

I already did in [this PR](https://github.com/RocketChat/Rocket.Chat/pull/26751) but it's not merged yet.

2022-09-20 14:19 UTC, hugocostadev submitted a review, later dismissed

2022-09-21 19:27 UTC, ggazzo requested changes

2022-09-21 19:27 UTC, ggazzo commented on apps/meteor/client/views/room/MessageList/lib/isMessageSequential.ts
> +	if (isThreadMessage(previous) && previous.tshow) {
what about create something like 'isThreadAnswer'

2022-09-22 03:13 UTC, ggazzo requested changes

2022-09-22 03:13 UTC, ggazzo commented on apps/meteor/client/views/room/MessageList/lib/isMessageSequential.ts
> +	}
please break this test into another function, in that way its not possible to use this function inside threads for example

2022-09-22 20:34 UTC, ggazzo approved these changes

2022-09-22 23:14 UTC, merged