Chore: Rewrite AppLogs to TS
RocketChat/Rocket.Chat pull request #26938
Opened 2022-09-23 18:29 UTC by rique223

## Proposed changes (including videos or screenshots)

Rewrote the AppLogs component to TS. Also, improved some error handling logic.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-09-27 18:13 UTC, rique223 commented on apps/meteor/client/views/admin/apps/AppLogs.tsx
> +	const getAppLogs = useEndpoint('GET', `/apps/${id}/logs`) as any;
I am not really sure. I've spent a lot of time on this and wasn't able to come up with a way for it to stop breaking when I don't type it like this.

2022-09-30 17:38 UTC, rique223 commented on apps/meteor/client/views/admin/apps/AppLogs.tsx
> +	const getAppLogs = useEndpoint('GET', `/apps/${id}/logs`) as any;
Solved

2022-10-04 13:51 UTC, dougfabris requested changes

2022-10-04 13:51 UTC, dougfabris commented on packages/rest-typings/src/apps/index.ts
> +import type { ILogItem } from '@rocket.chat/core-typings/src/ILogs';
You should add the `ILogs.ts` type file on the index to get the types from the root
```suggestion
import type { ILogItem } from '@rocket.chat/core-typings';
```

2022-10-04 13:51 UTC, dougfabris commented on apps/meteor/client/views/admin/apps/LogItem.tsx
> +import { ILogEntry } from '@rocket.chat/core-typings/src/ILogs';
```suggestion
import { ILogEntry } from '@rocket.chat/core-typings';
```

2022-10-04 13:51 UTC, dougfabris commented on apps/meteor/client/views/admin/apps/AppLogs.tsx
> +	const { value, phase: logsPhase, error } = useEndpointData(`/apps/${id}/logs`);
Why not `react-query`??

2022-10-05 17:08 UTC, dougfabris requested changes

2022-10-05 17:08 UTC, dougfabris commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Unknown_error": "An Unknown Error occured",
```suggestion

```

2022-10-05 17:27 UTC, juliajforesti approved these changes

2022-10-05 18:20 UTC, dougfabris approved these changes

2022-10-15 02:09 UTC, merged