Chore: create refreshClients endpoint
RocketChat/Rocket.Chat pull request #26956
Opened 2022-09-27 11:28 UTC by felipe-rod123

## Proposed changes (including videos or screenshots)

Created the 'assets.refreshClients' endpoint for the `apps/meteor/client/views/admin/settings/groups/AssetsGroupPage.tsx` file.

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-09-28 13:07 UTC, ggazzo approved these changes

2022-10-18 20:12 UTC, sampaiodiego requested changes
@ggazzo should we remove this functionality completely? the button "apply and refresh clients" doesn't work at all.. no reason to keep it there.

2022-11-21 18:44 UTC, ggazzo commented on packages/rest-typings/src/v1/assets.ts
> +	};
```suggestion
```

2022-11-21 18:44 UTC, ggazzo commented on apps/meteor/tests/end-to-end/api/14-assets.js
> +	});
```suggestion
```

2022-11-21 18:45 UTC, ggazzo commented on apps/meteor/client/views/admin/settings/groups/AssetsGroupPage.tsx
> +		<GroupPage _id={_id} {...group} headerButtons={<></>}>
```suggestion
		<GroupPage _id={_id} {...group}>
```

2022-11-21 18:45 UTC, ggazzo commented on apps/meteor/app/api/server/v1/assets.ts
> +);
```suggestion
```

2022-11-21 18:46 UTC, ggazzo commented on apps/meteor/app/api/server/v1/assets.ts
> +import { methodDeprecationLogger } from '../../../lib/server/lib/deprecationWarningLogger';
```suggestion
```

2022-11-21 18:51 UTC, ggazzo approved these changes

2022-11-22 00:43 UTC, merged