[FIX] Uncaught error by listening stream-notify-room without subscription
RocketChat/Rocket.Chat pull request #27020
Opened 2022-10-06 15:43 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

fix this:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/17487063/194358060-7d0fb534-9d04-4af8-abd9-fa2bd79b66c0.png">

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-10-06 16:49 UTC, aleksandernsilva approved these changes

2022-10-06 23:05 UTC, KevLehman commented
@sampaiodiego you're more familiar with this code, can you help us reviewing? 🙏

2022-10-07 14:15 UTC, sampaiodiego requested changes

2022-10-07 14:15 UTC, sampaiodiego commented on apps/meteor/server/modules/notifications/notifications.module.ts
> +			const canAccess = await Authorization.canAccessRoom(room, { _id: this.userId }, extraData);
since you have only `rid`, you can use `Authorization.canAccessRoomId` , so you don't  need to add the query added on line 164.

2022-10-07 14:16 UTC, sampaiodiego commented
can you also please create a test for this fix?

2022-10-17 22:24 UTC, tassoevan approved these changes

2022-10-18 02:13 UTC, merged