Chore: Add tests for omni-jobs & add more context in system messages for jobs
RocketChat/Rocket.Chat pull request #27048
Opened 2022-10-11 12:24 UTC by murtaza98

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-10-14 17:28 UTC, KevLehman requested changes

2022-10-17 13:38 UTC, murtaza98 commented on apps/meteor/ee/app/livechat-enterprise/server/lib/AutoCloseOnHoldScheduler.ts
> +	private async getSchedulerUser(): Promise<IUser> {
This was an existing logic so even I'm not entirely sure :sweat_smile: But it seems to me like it is trying to cache the user's object in the memory :eyes:

2022-10-20 11:38 UTC, murtaza98 commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Closed_automatically_because_chat_was_onhold_for_seconds": "Closed automatically because chat was On Hold for __onHoldTime__ seconds",
Hey @KevLehman Got those new messages reviewed by Faria. Can you please check this again?

2022-11-01 20:07 UTC, KevLehman approved these changes

2022-11-03 13:50 UTC, sampaiodiego approved these changes

2022-11-03 19:32 UTC, aleksandernsilva approved these changes

2022-11-17 11:23 UTC, merged