[FIX] Delete first message when initializing thread returns black screen
RocketChat/Rocket.Chat pull request #27117
Opened 2022-10-20 18:03 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

Error deleting the first message when initializing a thread returns a black screen. (the thread should have only the main message)

## Steps to test or reproduce

1. Write a message in a group
2. Click "Reply In Thread" in message actions
3. Click "Delete" in the message actions for the first message within the thread view

## Further comments

The thread template was rendering the message component without checking if the data exist. 

Also added a new behavior to close the threads when doesn't exist messages in the thread anymore.

2022-11-03 21:49 UTC, guijun13 approved these changes

2022-11-10 15:45 UTC, ggazzo requested changes

2022-11-10 15:45 UTC, ggazzo commented on apps/meteor/app/threads/client/flextab/thread.ts
> +					instance.closeThread();
could be possible by any way to cover this case with some test?

2022-11-18 12:12 UTC, gabriellsh requested changes
Added tests are failing

2022-11-21 18:14 UTC, ggazzo approved these changes

2022-11-21 18:14 UTC, merged