fix: change email after provider change the user email
RocketChat/Rocket.Chat pull request #27148
Opened 2022-10-28 22:52 UTC by carlosrodrigues94

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-11-18 19:21 UTC, pierre-lehnen-rc requested changes
You'll also need to change the conditional in line 348 so it doesn't skip the whole thing if only the email is different.

2022-11-18 19:21 UTC, pierre-lehnen-rc commented on apps/meteor/app/custom-oauth/server/custom_oauth_server.js
> +						email: serviceData.email,
`email` is not an attribute on IUser, the email addresses are stored in the `emails` list.
It should also only be changed if the keyfield is set to username.

```suggestion
						...(this.keyField === 'username' && serviceData.email && { emails: [{ address: serviceData.email, verified: true }] }),
```

2022-11-23 17:51 UTC, matheusbsilva137 submitted a review, later dismissed

2022-11-23 18:54 UTC, pierre-lehnen-rc requested changes

2022-11-23 18:54 UTC, pierre-lehnen-rc commented on apps/meteor/app/custom-oauth/server/custom_oauth_server.js
> +					user.email === serviceData.email
```suggestion
					(this.keyField === 'email' || user.emails?.find(({address}) => address === serviceData.email))
```
`user.email` doesn't exist.

2022-11-23 21:17 UTC, pierre-lehnen-rc approved these changes

2022-11-24 01:12 UTC, merged