[IMPROVE] VideoConf Miss Config Modal
RocketChat/Rocket.Chat pull request #27153
Opened 2022-10-31 16:28 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-11-04 18:10 UTC, ggazzo approved these changes

2022-11-04 19:17 UTC, debdutdeb requested changes
Small typo 🙂

2022-11-04 19:17 UTC, debdutdeb commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Open-souce_conference_call_solution": "Open-souce conference call solution.",
```suggestion
  "Open-source_conference_call_solution": "Open-source conference call solution.",
```

2022-11-04 19:17 UTC, debdutdeb commented on apps/meteor/client/views/room/contextualBar/VideoConference/VideoConfConfigModal.tsx
> +						{t('Open-souce_conference_call_solution')}
```suggestion
						{t('Open-source_conference_call_solution')}
```

2022-11-10 14:24 UTC, ggazzo approved these changes

2022-11-10 16:06 UTC, debdutdeb approved these changes

2022-11-22 04:23 UTC, merged