Chore: Create new endpoint for test webhooks and deprecate meteor method
RocketChat/Rocket.Chat pull request #27160
Opened 2022-11-01 13:16 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-11-03 13:41 UTC, sampaiodiego requested changes

2022-11-03 13:41 UTC, sampaiodiego commented on apps/meteor/app/livechat/server/api/v1/webhooks.ts
> +				Livechat.logger.error(`Error testing webhook: ${error}`);
```suggestion
				Livechat.logger.error({ msg: 'Error testing webhook', err: error });
```

2022-11-10 16:36 UTC, aleksandernsilva submitted a review, later dismissed

2022-11-11 18:01 UTC, cauefcr approved these changes
Much needed change, it would be nice to have something similar for the e-mail client.

2022-11-22 03:27 UTC, ggazzo approved these changes

2022-11-22 03:27 UTC, merged