[IMPROVE] Add searchTerm support for livechat/rid/messages API
RocketChat/Rocket.Chat pull request #27214
Opened 2022-11-08 18:27 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-11-10 16:46 UTC, MartinSchoeler requested changes

2022-11-10 16:46 UTC, MartinSchoeler commented on apps/meteor/tests/end-to-end/api/livechat/00-rooms.ts
> +				.query({ searchTerm: 'ndo' })
Can you add a test for `{ searchTerm: '' }`?

2022-11-11 13:02 UTC, cauefcr approved these changes
LGTM.

2022-11-21 18:13 UTC, ggazzo approved these changes

2022-11-21 18:13 UTC, merged