[IMPROVE] Add update option to app list AppMenu
RocketChat/Rocket.Chat pull request #27246
Opened 2022-11-11 20:04 UTC by rique223

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-11-17 14:44 UTC, dougfabris requested changes
holding the review to discuss the update button's redundancy with the design team!

2022-11-17 20:51 UTC, rique223 commented
> holding the review to discuss the update button's redundancy with the design team!

The design team has decided, there should be no redundancy.

2022-11-21 21:09 UTC, juliajforesti submitted a review, later dismissed

2022-11-22 14:16 UTC, dougfabris approved these changes

2022-11-22 16:24 UTC, merged