[FIX] Usernames are shown instead of real names in reactions
RocketChat/Rocket.Chat pull request #27383
Opened 2022-11-28 16:19 UTC by henit-chobisa

## Issue
Rocket.Chat has a setting where the user can select if the server should `Real Names` or `Usernames`, hence when the `usernames` is turned on, the server should use real names everywhere including emojis, but this is not happening.

## Steps to test or reproduce
1. Go to Administration - Settings - Layout - User Interface
2. Set Use Real Name

## Technical Reasoning
The main problem I think is the way the messages' reactions are filtered, which should include both the usernames and names of the person reacting to it.
- ### Issue : 
   - After a good research I found that my thoughts are correct and the way reactions are filtered is the actual issue.
   -  In `Message.ts` (packages / core-typings / src / IMessage ), message `reactions` was considered as an *ARRAY* but the `reactions` property is of type **INDEX SIGNATURE** which can be accessed by **keys, not by index** 
    - <img width="1077" alt="image" src="https://user-images.githubusercontent.com/72302948/204360941-10deb2a9-2a12-454e-bb17-76e73e3f164a.png">
     - <img width="931" alt="Screenshot 2022-11-29 at 12 34 18 AM" src="https://user-images.githubusercontent.com/72302948/204360075-321ceb95-5ee5-431a-8478-fdcdbdacc9c4.png">
     - For both the client side and server side, while updating the reactions, the `names` property for each reaction is not considered which means that *name of the person reacting, is not pushed to the `names ` array in a particular reaction* object, only the username is pushed to the `usernames` array, which led to inconsistency in both the `usernames` and `names` array.
     For such a setting of `USE_REAL_NAME`, Inside names and usernames array of a reaction object, we must have a name for a particular username, and vice-versa, so we can use them interchangeably, when toggled.

- ### Solution : 
  - I consider extracting keys and values separately and fulfilling the objective of the `normalizer` function, resolving the issue.
  - <img width="1077" alt="Screenshot 2022-11-29 at 12 38 38 AM" src="https://user-images.githubusercontent.com/72302948/204360745-f02ebdc4-a485-4c1e-9f6c-8122fc868b32.png">
  - The client side and the server side is modified to resolve the following issue, whenever a particular reaction is triggered, both the name and usernames would be pushed to their respective arrays.

- ## Preview : 
 ### Before : 

<img width="1502" alt="Screenshot 2022-11-29 at 2 01 48 AM" src="https://user-images.githubusercontent.com/72302948/204375357-b6ab8aa8-c740-439d-aac9-51ecd1d1a9aa.png">

 ### After applying the above change : 
![usernamesRealNames](https://user-images.githubusercontent.com/72302948/205024673-21d3a3f9-6e39-48fa-8d95-59c9244c9a31.gif)
![usernames](https://user-images.githubusercontent.com/72302948/205024693-7c76c17c-cdcd-4fd4-8cb0-fb8db6c9eead.gif)
<img width="650" alt="Screenshot 2022-12-01 at 3 22 28 PM" src="https://user-images.githubusercontent.com/72302948/205024908-b218ce68-8a00-4e70-95e4-305b15085be5.png">
<img width="650" alt="Screenshot 2022-12-01 at 3 20 57 PM" src="https://user-images.githubusercontent.com/72302948/205024972-47366a43-719e-4cea-b845-0fc09c4eda74.png">

## Issue(s)
Closes #27378

2022-11-28 20:39 UTC, henit-chobisa commented
Hey @dudanogueira, @ggazzo & @debdutdeb, I proposed a solution for the above issue by means of this PR, 
I would be more than grateful if you can please review it and give your suggestions on this, 
Thanks You!

2022-11-29 14:55 UTC, henit-chobisa commented
Hey @debdutdeb, I have fixed the linter issues, this should resolve the failed test.

2022-11-30 14:45 UTC, henit-chobisa commented
Hello Everyone, On talking with my amazing reviewer @debdutdeb, I concluded that this PR needs more work to be done, else the following state will create regression. Hence, I am declaring it as *Work In Progress* again and make more changes to avoid regression and inconsistency.

2022-12-01 14:44 UTC, henit-chobisa commented
Hii @debdutdeb, I have made all the necessary changes and resolved the issue, 
Kindly review, thank you so much!

2022-12-01 17:35 UTC, henit-chobisa commented
Hello @debdutdeb, I have made the necessary changes for resolving the issues that you suggested on this one.
I have attached some more screenshots and added more points in the reasoning section, for a better explanation of my view and approach. 📜

Thank you so much for your support and guidance, I'm really grateful to it 🙏

2022-12-29 09:54 UTC, debdutdeb requested changes
Couple changes considering the path we're [we'll be] taking; filling those entries are not necessary for now.

And, two nits.

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/client/methods/setReaction.js
> +
Let's take this out since we're planning on changing the outline anyway.

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/client/methods/setReaction.js
> +					names: [],
```suggestion
```
Same here

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/client/methods/setReaction.js
> +			message.reactions[reaction].names.push(user.name);
```suggestion
```
Same here

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/server/setReaction.js
> +const removeUserReaction = (message, reaction, username, name) => {
```suggestion
```

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/server/setReaction.js
> +	message.reactions[reaction].names.splice(message.reactions[reaction].names.indexOf(name), 1);
```suggestion
```

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/server/setReaction.js
> +		removeUserReaction(message, reaction, user.username, user.name);
```suggestion
```

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/server/setReaction.js
> +				names: [],
```suggestion
```

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/app/reactions/server/setReaction.js
> +		message.reactions[reaction].names.push(user.name);
```suggestion
```

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
> +	const displayName = user?.name;
```suggestion
	const realName = user?.name;
```

2022-12-29 09:54 UTC, debdutdeb commented on apps/meteor/client/views/room/MessageList/providers/MessageListProvider.tsx
> +							return message.reactions[reaction].names.filter((user) => user !== displayName);
```suggestion
							return message.reactions[reaction].names.filter((user) => user !== realName);
```

2022-12-29 09:54 UTC, debdutdeb commented on packages/core-typings/src/IMessage/IMessage.ts
> +		'reactions' in message && message.reactions && Object.keys(message.reactions)[0] && 'names' in Object.values(message.reactions)[0],
```suggestion
		'reactions' in message && message.reactions && Object.keys(message.reactions).length && 'names' in Object.values(message.reactions)[0],
```

2022-12-29 09:55 UTC, debdutdeb commented on apps/meteor/app/reactions/client/methods/setReaction.js
> +
```suggestion
```

2022-12-30 07:30 UTC, debdutdeb approved these changes
we can come back to it later if needed;

2022-12-30 07:31 UTC, merged