[IMPROVE] Authorize search of custom fiels on `users.list`
RocketChat/Rocket.Chat pull request #27423
Opened 2022-12-01 16:48 UTC by LucianoPierdona

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-12-16 03:17 UTC, matheusbsilva137 requested changes

2022-12-16 14:19 UTC, LucianoPierdona commented on apps/meteor/tests/end-to-end/api/01-users.js
> +					.expect(200)
@matheusbsilva137 updated!

2022-12-19 15:34 UTC, matheusbsilva137 approved these changes

2022-12-20 13:18 UTC, sampaiodiego approved these changes

2022-12-20 19:18 UTC, merged