Chore: Update eslint-config package manifest
RocketChat/Rocket.Chat pull request #27619
Opened 2022-12-22 22:24 UTC by d-gubert

## Proposed changes (including videos or screenshots)

Updated the `eslint-config` package manifest to include `dependencies` instead of `devDependencies` - this way, when the package is installed in another project, dependencies are installed along with it. The way it is currently on `develop`, you have to run `npm install` manually for all dependencies if you want to use the package

## Issue(s)

## Steps to test or reproduce

## Further comments

It might mess a bit with how `yarn` keeps things organized? Not sure if the impact is meaningful though

2022-12-23 02:16 UTC, tassoevan requested changes

2022-12-23 02:16 UTC, tassoevan commented on packages/eslint-config/package.json
>  		"@types/prettier": "^2.6.3",
`@types/*` dependencies must be dev-dependencies, but in this case (`@types/prettier`) it not even be needed here.

2023-06-20 19:21 UTC, sampaiodiego submitted a review, later dismissed

2023-08-08 21:04 UTC, tassoevan approved these changes

2023-08-09 14:40 UTC, sampaiodiego approved these changes

2023-08-09 16:46 UTC, pierre-lehnen-rc approved these changes

2023-08-21 14:48 UTC, merged