[FIX] responsiveness of NEW INTEGRATION (#27634)
RocketChat/Rocket.Chat pull request #27645
Opened 2022-12-26 20:18 UTC by adijr9487

## Proposed changes (including videos or screenshots)

Improved the responsiveness by adding maxWidth property.
![image](https://user-images.githubusercontent.com/56039219/209580942-87a4b889-069d-4521-9380-056f5a39f146.png)

## Issue(s)

#27634 
## Steps to test or reproduce

Switch to chrome dev tool and test it below 600px width.
## Further comments

## Reviewer
@dudanogueira

2022-12-28 18:29 UTC, ggazzo requested changes

2022-12-28 18:29 UTC, ggazzo commented on apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js
> +			// mi='neg-x24'
Remove comments

2022-12-28 20:53 UTC, adijr9487 commented on apps/meteor/client/views/admin/integrations/IncomingWebhookForm.js
> +			// mi='neg-x24'
Removed !! @ggazzo

2022-12-29 17:14 UTC, adijr9487 commented
@dougfabris Please review

2023-04-13 17:07 UTC, dougfabris approved these changes

2023-04-13 17:41 UTC, merged