[FIX] Remove invalid settings at startup
RocketChat/Rocket.Chat pull request #27653
Opened 2022-12-27 14:01 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2022-12-27 14:12 UTC, murtaza98 approved these changes

2022-12-27 14:15 UTC, aleksandernsilva submitted a review, later dismissed

2022-12-27 14:47 UTC, sampaiodiego requested changes

2022-12-27 14:47 UTC, sampaiodiego commented on apps/meteor/app/livechat/server/settingsRegenerator.ts
> +		await Settings.deleteMany({ _id: { $in: invalidSettings.map(({ _id }) => _id) } });
a warn with only ids would be weird.. it is better to add them to the same log with a msg:
```suggestion
		const ids = invalidSettings.map(({ _id }) => _id);
		logger.warn({ msg: `Found ${invalidSettings.length} invalid settings on DB. Deleting them...`, ids });
		await Settings.deleteMany({ _id: { $in: ids } });
```

2022-12-27 14:47 UTC, sampaiodiego commented on apps/meteor/app/livechat/server/settingsRegenerator.ts
> +	}).toArray();
```suggestion
	}, {
		projection: { _id: 1 }
	}).toArray();
```

2022-12-27 14:47 UTC, sampaiodiego commented on apps/meteor/app/livechat/server/settingsRegenerator.ts
> +	}).toArray();
because
```suggestion
	}, {
		projection: { _id: 1 }
	}).toArray();
```

2022-12-27 14:48 UTC, sampaiodiego commented on apps/meteor/app/livechat/server/settingsRegenerator.ts
> +export async function settingsRegenerator() {
as previously discussed as well, it would be good to move this function to a "global" namespace

2022-12-28 13:54 UTC, sampaiodiego approved these changes

2022-12-28 13:59 UTC, ggazzo approved these changes

2022-12-28 14:28 UTC, merged