[IMPROVE] SMTP warning for invitations
RocketChat/Rocket.Chat pull request #27713
Opened 2023-01-10 15:09 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-01-16 13:00 UTC, hugocostadev requested changes
The text should be centered:
![image](https://user-images.githubusercontent.com/20212776/212683867-751711dc-778d-4cb0-b7ee-1028426725c1.png)

2023-01-17 13:19 UTC, hugocostadev submitted a review, later dismissed

2023-01-19 17:04 UTC, LucianoPierdona submitted a review, later dismissed

2023-01-19 19:29 UTC, tassoevan commented on apps/meteor/client/components/VerticalBar/VerticalBarText.tsx
> +	<Box flexShrink={1} flexGrow={1} withTruncatedText data-qa-type='VerticalBarText' {...props} />
It wasn't?

2023-01-20 16:34 UTC, yash-rajpal commented on apps/meteor/client/components/VerticalBar/VerticalBarText.tsx
> +	<Box flexShrink={1} flexGrow={1} withTruncatedText data-qa-type='VerticalBarText' {...props} />
Fixed.

2023-01-20 17:51 UTC, hugocostadev approved these changes

2023-01-24 13:10 UTC, hugocostadev approved these changes

2023-01-25 12:48 UTC, LucianoPierdona approved these changes

2023-01-26 16:29 UTC, tassoevan approved these changes

2023-02-01 12:22 UTC, hugocostadev approved these changes

2023-02-02 16:54 UTC, hugocostadev approved these changes

2023-02-03 16:17 UTC, gabriellsh submitted a review, later dismissed

2023-02-03 18:54 UTC, yash-rajpal commented on apps/meteor/packages/rocketchat-i18n/i18n/en.i18n.json
> +  "Send_Email_SMTP_Warning": "To send this email you need to <a href=\"admin/settings/Email\">setup SMTP emailing server</a>",
If we use markdown, it will cause the page to reload or open admin panel in a new tab. Or maybe should we use router in this case? What do you think?

2023-02-06 10:55 UTC, hugocostadev approved these changes

2023-02-06 15:07 UTC, tassoevan approved these changes

2023-02-07 18:59 UTC, rodrigok commented
@yash-rajpal please update the description, the method was removed, not deprecated

2023-02-07 20:25 UTC, merged