[NEW] Matrix search UI
RocketChat/Rocket.Chat pull request #27770
Opened 2023-01-16 23:50 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-01-24 18:48 UTC, hugocostadev requested changes

2023-01-24 18:48 UTC, hugocostadev commented on apps/meteor/client/sidebar/header/MatrixFederationSearch/FederatedRoomList.tsx
> +	);
Maybe create two different hooks, one for the query and other for the Mutation, what do you think? 
That way these hooks can be used elsewhere

2023-01-24 18:58 UTC, hugocostadev commented
Feedback:

1. The margin-bottom seems to be smaller in the design
2. the button should have some paddings according to prototype 

![image](https://user-images.githubusercontent.com/20212776/214383803-256a2703-53f3-46ab-999b-432321fef59a.png)

2023-01-24 19:01 UTC, hugocostadev commented
The user icon is not aligned correctly:

![image](https://user-images.githubusercontent.com/20212776/214383996-e1ae277c-79d2-4a2b-ace2-99d5425ce9b6.png)

The scrollbar overlaps the Join button
![image](https://user-images.githubusercontent.com/20212776/214384090-edd41848-a2a0-46c6-8065-7dfa8145a44f.png)

The modal should have 664px and it has 608px
![image](https://user-images.githubusercontent.com/20212776/214384269-01f8b4f7-4c30-411e-8ab3-bd28949f2b50.png)

2023-01-25 16:04 UTC, MarcosSpessatto commented
> Is it necessary to repeat the channel's name in the server indicator? I think that we could remove it.
I'd say this is necessary, since it's not a repetition only, the second information is what Matrix call canonical_alias, if you create the channel from Element, you can define the canonical_alias for the channel which can different from the name, once it's unique per server you can have a canonical_alias different from the room name.

2023-05-02 13:57 UTC, hugocostadev approved these changes

2023-05-02 14:44 UTC, ggazzo approved these changes

2023-05-02 14:44 UTC, merged