[Fix] Broken settings check for updates
RocketChat/Rocket.Chat pull request #27779
Opened 2023-01-17 16:50 UTC by geekgonecrazy

## Proposed changes (including videos or screenshots)

If someone choses not to register but still want to find out about new versions, or critical vulnerabilities this code would never fire.  

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-01-17 16:59 UTC, debdutdeb requested changes

2023-01-17 16:59 UTC, debdutdeb commented on apps/meteor/app/version-check/server/index.ts
> +settings.watchMultiple(['Update_EnableChecker'], () => {
```suggestion
settings.watch('Update_EnableChecker', () => {
```

2023-01-17 18:05 UTC, debdutdeb approved these changes
makes sense to me :)

2023-02-10 16:06 UTC, KevLehman approved these changes
Should this have any form of QA?

2023-02-11 01:15 UTC, debdutdeb commented
I honestly don't see the need for this patch 😬 idk

2023-02-14 01:34 UTC, merged