[FIX] Add support for non-alphanumeric letters in LDAP Sync
RocketChat/Rocket.Chat pull request #27819
Opened 2023-01-23 20:31 UTC by LucianoPierdona

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-01-25 14:34 UTC, pierre-lehnen-rc requested changes

2023-01-25 19:46 UTC, LucianoPierdona commented on apps/meteor/server/lib/ldap/Manager.ts
> +		const username =
updated!

2023-01-26 11:15 UTC, matheusbsilva137 submitted a review, later dismissed

2023-05-05 21:32 UTC, pierre-lehnen-rc approved these changes

2023-05-11 16:27 UTC, matheusbsilva137 approved these changes

2023-05-11 18:12 UTC, merged