[NEW] Add omnichannel preferences and check permission to show itens
RocketChat/Rocket.Chat pull request #27824
Opened 2023-01-24 12:17 UTC by filipemarins

## Proposed changes (including videos or screenshots)

Add `omnichannelTranscriptEmail` and `omnichannelTranscriptPDF` account preferences;
Add a new omnichannel account page;
Add options to change the setting when wrapping up the conversation.

## Issue(s)

oc-598 oc-599 oc-600

## Steps to test or reproduce

## Further comments

![Screenshot 2023-01-23 at 18 40 44](https://user-images.githubusercontent.com/9275105/214289546-86be0eca-e20f-48b0-be8d-46267154c8f3.png)
![Screenshot 2023-01-23 at 18 40 54](https://user-images.githubusercontent.com/9275105/214289566-7721d5fc-8511-4ae0-9dd8-6a8411c08891.png)

2023-01-24 12:39 UTC, murtaza98 commented on apps/meteor/app/lib/server/startup/settings.ts
> +		});
Can you please move this to `apps/meteor/ee/app/livechat-enterprise/server/settings.ts`, so this setting gets created only when the license is present?

2023-01-30 12:16 UTC, murtaza98 approved these changes

2023-01-31 18:09 UTC, KevLehman approved these changes

2023-02-02 13:06 UTC, aleksandernsilva requested changes

2023-02-02 13:30 UTC, KevLehman commented on apps/meteor/app/livechat/server/api/v1/room.ts
> +			await LivechatTyped.closeRoom({ visitor, room, comment });
If it throws an error, it will return the error to the client
Otherwise, will succeed and return 200

2023-02-02 13:30 UTC, KevLehman commented on apps/meteor/app/livechat/server/methods/removeAllClosedRooms.ts
>  			count++;
👀 lets see

2023-02-02 21:54 UTC, merged