[NEW] Added omnichannel sorting disclaimer to SortModeList menu
RocketChat/Rocket.Chat pull request #27913
Opened 2023-01-31 18:33 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

![Screen Shot 2023-01-31 at 15 32 07](https://user-images.githubusercontent.com/6494543/215851034-133fda9c-d4d1-451b-a47e-03e9e897b670.png)

## Issue(s)

## Steps to test or reproduce

## Further comments

OC-568

2023-02-02 17:57 UTC, filipemarins approved these changes

2023-02-02 18:02 UTC, ggazzo requested changes
please check the comments

2023-02-02 18:02 UTC, ggazzo commented on apps/meteor/client/components/Omnichannel/OmnichannelSortingDisclaimer.tsx
> +	});
there is no need to translate all the keys just to pick one later

2023-02-02 18:02 UTC, ggazzo commented on apps/meteor/client/components/Omnichannel/OmnichannelSortingDisclaimer.tsx
> +		</Box>
I'm sure this should not be a `LI` and this item should be the `aria-describedby` for the sorting option

2023-02-02 18:02 UTC, ggazzo commented on apps/meteor/client/components/SortList/SortModeList.tsx
> +				<OmnichannelSortingDisclaimer />
why not just render this IF you are a agent/manager and the omnichannel is enabled?

2023-02-02 18:06 UTC, ggazzo commented on apps/meteor/client/components/Omnichannel/OmnichannelSortingDisclaimer.tsx
> +	const sortingMechanism = useSetting('Omnichannel_sorting_mechanism') as OmniSortingType;
```suggestion
	const sortingMechanism = useSetting<OmniSortingType>('Omnichannel_sorting_mechanism');
```

2023-02-08 01:09 UTC, KevLehman commented on apps/meteor/client/components/Omnichannel/OmnichannelSortingDisclaimer.tsx
> +			{t('Omnichannel_sorting_disclaimer', { sortingMechanism: t(type) })}
Isn't this an EE only disclaimer? Priorities don't exist on CE

2023-02-10 15:58 UTC, merged