[FIX] Adjusted priority icon positioning and added spacing
RocketChat/Rocket.Chat pull request #27910
Opened 2023-01-31 17:19 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

Old:
![Screen Shot 2023-01-31 at 14 17 47](https://user-images.githubusercontent.com/6494543/215835003-1ac4f3ce-5d9b-47c4-b344-0946050ea43c.png)

New:
![Screen Shot 2023-01-31 at 14 17 17](https://user-images.githubusercontent.com/6494543/215835065-f3241da1-722e-4b5c-8688-37de690e19ad.png)

## Issue(s)

## Steps to test or reproduce

## Further comments

OC-585

2023-02-02 18:13 UTC, filipemarins approved these changes

2023-02-02 18:17 UTC, ggazzo requested changes

2023-02-02 18:17 UTC, ggazzo commented on apps/meteor/client/sidebar/RoomList/SideBarItemTemplateWithData.tsx
> +			{isOmnichannelRoom(room) && room.priorityWeight && <PriorityIcon mis='8px' level={room.priorityWeight} />}
I'm against to style directly on the component: `mis='8px'`

2023-02-10 16:44 UTC, MartinSchoeler approved these changes

2023-02-10 18:26 UTC, merged