[NEW] Add system message upon Priority and SLA change
RocketChat/Rocket.Chat pull request #27919
Opened 2023-02-01 10:51 UTC by murtaza98

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-02-06 14:43 UTC, KevLehman commented on apps/meteor/server/startup/migrations/v285.ts
> +import { Messages } from '@rocket.chat/models';
@sampaiodiego , can you help us to validate the migration?

My question is: do we need 2 queries for doing that? I think we can get everything on the updateMany call 👀

2023-02-06 15:20 UTC, KevLehman requested changes

2023-02-07 10:24 UTC, murtaza98 commented on apps/meteor/ee/app/livechat-enterprise/server/api/lib/priorities.ts
> +import { addPriorityChangeHistoryToRoom } from '../../lib/SlaNPriorityHelper';
Sure, let me separate them

2023-02-07 20:24 UTC, KevLehman approved these changes

2023-02-07 21:12 UTC, KevLehman commented
Beware this migration might conflict with the migration on the facebook removal PR (since they hold same number)

Let's see which one goes to develop first

2023-02-07 21:12 UTC, merged