[IMPROVE] Audit
RocketChat/Rocket.Chat pull request #27994
Opened 2023-02-10 19:46 UTC by tassoevan

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-02-10 20:59 UTC, hugocostadev requested changes
Avoid duplicated entries 

![image](https://user-images.githubusercontent.com/20212776/218196124-120758f7-e2db-4553-8cf1-35fced944ed5.png)

2023-02-10 20:59 UTC, hugocostadev commented on apps/meteor/ee/client/views/audit/components/tabs/UsersTab.tsx
> +
```suggestion

		if (value.includes(currentUsername)) {
			return;
		}

```

2023-02-10 20:59 UTC, hugocostadev commented on apps/meteor/ee/client/views/audit/components/tabs/DirectTab.tsx
> +
```suggestion

		if (value.includes(currentUsername)) {
			return;
		}

```

2023-02-11 01:24 UTC, ggazzo approved these changes

2023-02-11 03:53 UTC, merged