[FIX] trigger info not updating when clicking on another trigger
RocketChat/Rocket.Chat pull request #28014
Opened 2023-02-13 16:22 UTC by FabioCavaleti

## Proposed changes (including videos or screenshots)

- Fix the bug in omnichannel triggers that the trigger info was not updating when switching the one that the info is displayed
- Refactor using react hook forms
- Typescript conversion
- Replace deprecated useEndpointData
- Added test to verify if the bug happens again

## Issue(s)

## Steps to test or reproduce

## Further comments

OC-591

2023-02-27 14:59 UTC, filipemarins commented on apps/meteor/client/views/omnichannel/triggers/TriggersFormWithData.tsx
> +};
```suggestion
	return (<TriggersForm initialValues={getInitialValues(data.trigger)} onSave={onSave} />);
};
```
Is the fragment still required?

2023-02-27 21:21 UTC, filipemarins requested changes
The pagination and link stopped working :/

![Screenshot 2023-02-27 at 18 20 35](https://user-images.githubusercontent.com/9275105/221688247-4a803ffd-5ce4-47e7-9e24-275af98ab670.png)

2023-02-28 09:54 UTC, filipemarins commented on apps/meteor/client/views/omnichannel/triggers/TriggersTableContainer.tsx
> +	const { data, refetch, isError } = useQuery(['/v1/livechat/triggers'], () => getTriggers({ offset: current, count: itemsPerPage }));
```suggestion
	const { data, refetch, isError } = useQuery(['/v1/livechat/triggers', current, itemsPerPage], () =>
		getTriggers({ offset: current, count: itemsPerPage }),
	);
```

I believe that you will need to pass the `current` and `itemPerPage` here as a key.

2023-02-28 09:54 UTC, filipemarins commented on apps/meteor/client/views/omnichannel/triggers/TriggersTableContainer.tsx
> +			totalTriggers={data?.triggers.length || 0}
```suggestion
			totalTriggers={data?.total || 0}
```
This one has the correct total items. Also, you will need to update the `'/v1/livechat/triggers'` endpoint type return to add the `total: number` there.

2023-02-28 13:59 UTC, filipemarins approved these changes

2023-03-01 20:51 UTC, sampaiodiego requested changes
Are you guys really confident all these file migrations are just "regressions"?

I mean, rewriting a JS file into TS will never a fix for a regression.. other than that, we've seen many bugs being introduced by such rewrites.

so should a real regression be done instead? and let the file conversion to a separate PR?

2024-11-25 13:53 UTC, dougfabris commented
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it was already fixed in another one.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

2024-11-25 13:53 UTC, closed without merging