[REGRESSION] Show messages instead of the composer when there is no action available on federated rooms
RocketChat/Rocket.Chat pull request #28093
Opened 2023-02-17 19:22 UTC by MarcosSpessatto

## Proposed changes (including videos or screenshots)

Rules:
If the federation module is disabled within the workspace: **do not show the composer and show a message instead**;

If the federation module is enabled, the user is not part of the room, and the workspace is a CE environment: **do not show the composer and show a message instead.**

If the federation module is enabled, the is not part of the room, but the workspace is an EE environment: **show the composer with the Join button**

If everything is enabled, and the user is already part of the room: **show the normal composer**

Jira: FED-82

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-02-17 20:07 UTC, ggazzo requested changes

2023-02-18 03:09 UTC, ggazzo commented on apps/meteor/client/views/room/components/body/composer/ComposerContainer.tsx
> +		// return handleFederation(room, federationEnabled, federationModuleEnabled, { children, ...props });
```suggestion
```

2023-02-18 11:03 UTC, ggazzo approved these changes

2023-02-27 14:10 UTC, dougfabris requested changes

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
> +								disabled={isRecording}
```suggestion
								disabled={isRecording || !canSend}
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
> +						<MessageComposerAction icon='emoji' disabled={!useEmojis || isRecording} onClick={handleOpenEmojiPicker} title={t('Emoji')} />
```suggestion
						<MessageComposerAction icon='emoji' disabled={!useEmojis || isRecording || !canSend} onClick={handleOpenEmojiPicker} title={t('Emoji')} />
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBox.tsx
> +					disabled={isRecording}
```suggestion
					disabled={isRecording || !canSend}
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
> +		<VideoMessageAction key='video' collapsed={variant === 'small'} isRecording={isRecording} />,
```suggestion
		<VideoMessageAction key='video' collapsed={variant === 'small'} isRecording={!canSend || isRecording} />,
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
> +		<FileUploadAction key='file' collapsed={variant === 'small'} isRecording={isRecording} />,
```suggestion
		<FileUploadAction key='file' collapsed={variant === 'small'} disabled={!canSend || isRecording} />,
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
> +const FileUploadAction = ({ collapsed, chatContext, disabled, isRecording, ...props }: FileUploadActionProps) => {
```suggestion
const FileUploadAction = ({ collapsed, chatContext, disabled, ...props }: FileUploadActionProps) => {
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
> +	isRecording: boolean;
```suggestion

```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/FileUploadAction.tsx
> +				disabled={!fileUploadEnabled || isRecording}
```suggestion
				disabled={!fileUploadEnabled || disabled}
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
> +	isRecording: boolean;
```suggestion

```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
> +const VideoMessageAction = ({ collapsed, chatContext, isRecording, disabled, ...props }: VideoMessageActionProps) => {
```suggestion
const VideoMessageAction = ({ collapsed, chatContext, disabled, ...props }: VideoMessageActionProps) => {
```

2023-02-27 14:10 UTC, dougfabris commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/VideoMessageAction.tsx
> +			disabled={!enableVideoMessage || isRecording}
```suggestion
			disabled={!enableVideoMessage || disabled}
```

2023-02-28 14:23 UTC, dougfabris approved these changes

2023-02-28 19:22 UTC, dougfabris submitted a review, later dismissed

2023-02-28 21:54 UTC, ggazzo approved these changes

2023-02-28 22:55 UTC, merged