[FIX]: Enable unlimited apps button on installation modal doesn't do anything
RocketChat/Rocket.Chat pull request #28132
Opened 2023-02-23 14:32 UTC by AllanPazRibeiro

## Proposed changes (including videos or screenshots)
This PR fixes all buttons on the "Enable unlimited apps" modal, and the problems were:

- Close button: This button was just a 'placebo', now it's calling the `setModal(null)` properly inside a useCallback, which I noticed is a good practice and used on most of our modals.
- Contact sellers: This one was concatenating with the server's current path, so it was pointing to a non-existent URL like: http://localhost:3000/app/admin/go.rocket.chat /contact-sellers. In order to fix it I change it to an HTTPS URL having the target `_blank`.
- Start trial: Last but not least, this one was having a very similar problem to the previous one, but the redirect was faster than some requests so the application was not been able to check the permissions to show the page and at the same time the modal was not been closed. In order to fix it, I replace the Flowrouter to a more native approach (window), so now the page is refreshing and getting all the permissions needed.

## Issue(s)
![MKP-246](https://user-images.githubusercontent.com/35040806/220936543-bc7af2a2-f892-4bb6-a51d-5ecaf0bb6166.gif)

## Steps to test or reproduce

## Further comments

2023-02-24 20:26 UTC, d-gubert approved these changes

2023-02-24 20:26 UTC, d-gubert commented on apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
> +		talkToSales: 'https://www.rocket.chat/sales-contact',
We need to keep the `go.rocket.chat` URL here, it helps us visualize access
```suggestion
		talkToSales: 'https://go.rocket.chat/i/contact-sales',
```

2023-02-24 20:26 UTC, d-gubert commented on apps/meteor/client/views/marketplace/UnlimitedAppsUpsellModal.tsx
> +		window.open(urls.goFullyFeaturedRegistered, '_self');
We need to use the internal routing system for that instead, try following the example in `apps/meteor/client/views/invite/SecretURLPage.tsx`

2023-02-24 20:26 UTC, d-gubert requested changes
Approved by mistake 😬 Previous comments must be solved

2023-02-27 22:38 UTC, rique223 submitted a review, later dismissed

2023-02-28 14:26 UTC, d-gubert approved these changes

2023-02-28 18:44 UTC, rique223 approved these changes

2023-02-28 20:53 UTC, merged