[FIX] Denied Microphone perms disables composer
RocketChat/Rocket.Chat pull request #28133
Opened 2023-02-23 14:50 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

ARCH-147

2023-02-24 02:38 UTC, ggazzo requested changes

2023-02-24 02:38 UTC, ggazzo commented on apps/meteor/client/views/room/components/body/composer/messageBox/MessageBoxActionsToolbar/actions/AudioMessageAction.tsx
> +			title={!isAllowed ? t('Microphone_access_not_allowed') : t('Audio_message')}
what about informing the user why the button is disabled 'file upload disabled'

2023-02-28 16:33 UTC, dougfabris approved these changes

2023-02-28 17:21 UTC, ggazzo approved these changes

2023-02-28 19:34 UTC, merged