chore: add auto translate to live chat room
RocketChat/Rocket.Chat pull request #28139
Opened 2023-02-23 19:43 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-02-27 14:52 UTC, aleksandernsilva requested changes

2023-02-27 14:52 UTC, aleksandernsilva commented on apps/meteor/app/autotranslate/client/lib/actionButton.ts
> +					const differentUser = message?.u && message.u._id !== user._id;
nit picking, but you should probably name this var as `isDifferentUser` for consistency.

2023-02-27 16:17 UTC, aleksandernsilva approved these changes

2023-03-01 20:10 UTC, ggazzo approved these changes

2023-03-01 21:16 UTC, merged