Chore: Show username instead of the name of the user in app request messages
RocketChat/Rocket.Chat pull request #28200
Opened 2023-02-27 23:40 UTC by rique223

## Proposed changes (including videos or screenshots)

Stopped using the name of users that requested apps and now the app request messages show their usernames instead.
Demo image:
![image](https://user-images.githubusercontent.com/43561537/221714243-9c6bb295-42ed-4449-8fb7-59c37637011a.png)

## Issue(s)

## Steps to test or reproduce

1. Request an app in an account that doesn't have manage-app permission;
2. Logout of that account and login into an account that has manage-app permission;
3. Click on the rocket.cat message;

## Further comments

2023-02-28 19:53 UTC, PedroRorato approved these changes

2023-02-28 21:04 UTC, ggazzo requested changes
did you try create a mention instead? just the raw username is not much better the name

2023-02-28 21:33 UTC, ggazzo commented on apps/meteor/ee/server/apps/communication/rest.js
> +									user_name: this.user.username,
```suggestion
									user_name: `@${this.user.username}`,
```

2023-02-28 22:27 UTC, rique223 commented on apps/meteor/ee/server/apps/communication/rest.js
> +									user_name: this.user.username,
Solved

2023-03-01 00:10 UTC, ggazzo approved these changes

2023-03-01 20:00 UTC, merged