Regression:  Image size in small screens are not respecting container boundary
RocketChat/Rocket.Chat pull request #28332
Opened 2023-03-08 19:43 UTC by hugocostadev

## Proposed changes (including videos or screenshots)

 Attachment Image or Image Preview size in small screens are not respecting container boundaries
 
 **Before:**
![image](https://user-images.githubusercontent.com/20212776/223826977-507e0b57-aba1-471d-a901-30198a51d82f.png)

**NOW:**
![image](https://user-images.githubusercontent.com/20212776/223826829-7c6006bd-0738-4cd4-acc6-ba8b8c274e3b.png)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-08 20:55 UTC, ggazzo requested changes
is this not enough ?
```css
.gallery-item {
    max-width: 100%;

}
```

2023-03-08 20:58 UTC, tassoevan submitted a review, later dismissed

2023-03-08 20:58 UTC, tassoevan commented on apps/meteor/client/components/message/content/urlPreviews/UrlImagePreview.tsx
> +		<Box maxHeight={oembedMaxHeight} maxWidth={'100%'}>
Why not set `width='100%'` and keep `maxWidth={oembedMaxWidth}`?

2023-03-08 22:50 UTC, ggazzo submitted a review, later dismissed

2023-03-09 00:32 UTC, KevLehman reviewed
Ia the .eslintcache file needed?

2023-03-09 00:38 UTC, ggazzo commented
> Ia the .eslintcache file needed?

if we want to speedup CI task and use the lint. yes it is

and it mean @hugocostadev has run at least once the eslint on his machine

2023-03-09 00:38 UTC, ggazzo approved these changes

2023-03-09 00:40 UTC, merged