Regression: Bring unseen app requests badge back and minor refactors
RocketChat/Rocket.Chat pull request #28348
Opened 2023-03-09 22:12 UTC by rique223

## Proposed changes (including videos or screenshots)

Brought back the unseen app requests badge that disappeared due to a development oversight and fixed some typos and style issues.

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-22 20:50 UTC, tiagoevanp requested changes

2023-03-22 20:50 UTC, tiagoevanp commented on apps/meteor/client/views/marketplace/sidebarItems.tsx
>  const MarketplaceRequestBadge = () => {
Instead of passing a Component to the child, how about to pass the data and let the child component import and use <Badge /> properly?

2023-03-23 19:18 UTC, rique223 commented on apps/meteor/client/views/marketplace/sidebarItems.tsx
>  const MarketplaceRequestBadge = () => {
Solved

2023-03-23 22:50 UTC, tiagoevanp approved these changes

2023-03-24 00:09 UTC, merged