28324_Not_redirecting_to_home_when_hiding_channel
RocketChat/Rocket.Chat pull request #28371
Opened 2023-03-11 05:17 UTC by tabareslorenzo

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-11 05:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=28371) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=28371) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=28371) it.</sub>

2023-03-14 16:55 UTC, hugocostadev approved these changes

2023-03-14 16:56 UTC, hugocostadev commented
Thanks for your contribution!

2023-03-14 18:17 UTC, dougfabris requested changes
I'm planning a bunch of unified hooks for Room actions to use here also. 
When it gets merged I will sync it with this PR and we'll be able to merge this one to fix. 
Thanks

2023-03-15 19:08 UTC, dougfabris commented
Redirecting to the home route after hiding a room isn't a behavior we want here.
Thanks for your contribution @tabareslorenzo

2023-03-15 19:08 UTC, closed without merging