fix: sound notification for queued chats with manual routing
RocketChat/Rocket.Chat pull request #28411
Opened 2023-03-14 10:34 UTC by filipemarins

## Proposed changes (including videos or screenshots)

Don't play notification sound for disabled agents and also respect the `poolMaxIncoming` setting to play or not the notification.

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-14 17:03 UTC, aleksandernsilva requested changes

2023-03-14 17:48 UTC, filipemarins commented on apps/meteor/app/livechat/client/lib/stream/queueManager.ts
> +		}
yep, unfortunately, we play the inquiry sound after every insertion on the live chat inquiry stream, without this conditional we will be ignoring the `poolMaxIncoming` setting, that way the agent will keep receiving notifications without chat available on the sidebar.

2023-03-15 15:21 UTC, aleksandernsilva approved these changes

2023-03-27 20:21 UTC, sampaiodiego approved these changes

2023-03-27 21:14 UTC, merged