refactor: `Subscriptions` - 3
RocketChat/Rocket.Chat pull request #28538
Opened 2023-03-21 22:05 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-24 16:34 UTC, sampaiodiego requested changes

2023-03-24 16:34 UTC, sampaiodiego commented on apps/meteor/app/slashcommands-join/server/server.ts
> +// TODO: remove promise.await when slashcommands can be async
```suggestion

```

2023-03-24 18:06 UTC, sampaiodiego submitted a review, later dismissed

2023-03-26 00:24 UTC, rodrigok approved these changes

2023-03-26 18:23 UTC, rodrigok submitted a review, later dismissed

2023-03-26 22:37 UTC, rodrigok approved these changes

2023-03-26 22:38 UTC, merged