refactor(models): Use Messages Raw model (4/N)
RocketChat/Rocket.Chat pull request #28558
Opened 2023-03-22 18:27 UTC by sampaiodiego

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-22 18:32 UTC, KevLehman commented on .github/workflows/new-build.yml
🤔

2023-03-22 18:38 UTC, sampaiodiego commented on .github/workflows/new-build.yml
there is nothing here =)

2023-03-22 21:52 UTC, KevLehman requested changes

2023-03-22 21:52 UTC, KevLehman commented on apps/meteor/app/threads/server/hooks/aftersavemessage.js
> +				return Promise.await(processThreads(message, room));
callbacks are async now :)

2023-03-23 00:20 UTC, KevLehman approved these changes

2023-03-23 01:00 UTC, merged