fix: Livechat not working with Bot agent
RocketChat/Rocket.Chat pull request #28574
Opened 2023-03-23 13:22 UTC by murtaza98

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-23 13:25 UTC, cauefcr submitted a review, later dismissed

2023-03-23 22:25 UTC, KevLehman requested changes

2023-03-23 22:25 UTC, KevLehman commented on apps/meteor/app/livechat/server/lib/Livechat.js
> +			console.log('botAgents', botAgents);
😬

2023-03-24 05:35 UTC, murtaza98 commented on apps/meteor/app/livechat/server/lib/Livechat.js
> +			console.log('botAgents', botAgents);
```suggestion
```

2023-03-24 14:38 UTC, thassiov submitted a review, later dismissed

2023-03-27 09:00 UTC, closed without merging