fix: Members/Channels list infinite scroll
RocketChat/Rocket.Chat pull request #28636
Opened 2023-03-27 10:40 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

TC-553

2023-04-17 16:52 UTC, gabriellsh requested changes

2023-04-17 16:52 UTC, gabriellsh commented on apps/meteor/client/views/teams/contextualBar/channels/BaseTeamsChannels.js
Maybe have you forgot to remove this file?

2023-04-18 03:47 UTC, guijun13 submitted a review, later dismissed

2023-04-27 18:52 UTC, guijun13 approved these changes

2023-05-17 14:31 UTC, gabriellsh approved these changes

2023-05-17 16:36 UTC, merged