refactor: Remove Users Model from fibers 2N
RocketChat/Rocket.Chat pull request #28660
Opened 2023-03-28 13:52 UTC by MarcosSpessatto

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-03-28 15:39 UTC, KevLehman requested changes

2023-03-30 17:47 UTC, ggazzo requested changes

2023-03-30 17:47 UTC, ggazzo commented on apps/meteor/app/api/server/v1/users.ts
> +		const user = await getUserForCheck(userId || '');
dont use `SPACE/empty strings` to cheat on the user.username typings
there is a test exactly on the line below to prevent that

2023-03-31 02:19 UTC, ggazzo approved these changes

2023-03-31 02:19 UTC, merged