fix: team channel reload error message
RocketChat/Rocket.Chat pull request #28667
Opened 2023-03-28 17:52 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

1. create a team - A
2. create a channel - B.
3. Add existing channel B to team A.
4. Red toast bar appears
## Further comments

[TC-432]

[TC-432]: https://rocketchat.atlassian.net/browse/TC-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-29 23:16 UTC, dougfabris requested changes
Dude, I would like to ask you to hold this PR until I got this one merged: #28666

2023-04-12 14:10 UTC, dougfabris requested changes
@yash-rajpal let's avoid doing some assertions using the `ToastBar` just verify if the room is on the list, is enough!

2023-04-12 17:09 UTC, dougfabris submitted a review, later dismissed

2023-04-12 17:10 UTC, juliajforesti approved these changes

2023-04-12 18:03 UTC, tassoevan approved these changes

2023-04-14 20:18 UTC, merged