fix: User Mentioning when prepending the username with >
RocketChat/Rocket.Chat pull request #28875
Opened 2023-04-11 21:47 UTC by ayush3160

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-04-12 20:06 UTC, ayush3160 commented
@hugocostadev Can you please review this PR.

2023-04-13 18:44 UTC, hugocostadev commented
Some tests are failing due to the changes, please, take a look

2023-04-15 09:30 UTC, ayush3160 commented
@hugocostadev , Please have a look.

2023-04-20 14:00 UTC, hugocostadev requested changes
I don't think that it's good to check the specific char `>`
Let's think, why `>` ?  Is there a reason for that?  

I was checking here and the `>` char it's often used for quotes, maybe the purpose of that Regex it's to accept mentions inside quotes, the same way that it's done with room mentions... That said, check how the room regex is done and let's compare it with the user's mention, there is a difference between those. 

If we change the user mention regex to match the room regex and test it we will see that this fixes the issue without creating a conditional operation in the `getUserMentions` method

What do you think?  
If you agree and test it locally you can accept my suggestions and change `userMentionRegex` function like this:

```js
	get userMentionRegex() {
		return new RegExp(`(^|\\s|>)@(${this.pattern}(@(${this.pattern}))?(:([0-9a-zA-Z-_.]+))?)`, 'gm');
	}
```

Output: 
![image](https://user-images.githubusercontent.com/20212776/233387694-c907f2b5-22cf-46fd-b2e7-ad073bdf3049.png)

2023-04-21 19:51 UTC, ayush3160 commented
@hugocostadev , Thanks for the detailed explanation and help. I applied your suggestion and also tested , it is working fine with '>' char also, Please have a look.

Also let me know if we should add a unit test case for this particular case.

Thanks.

2023-04-21 19:51 UTC, ayush3160 commented on apps/meteor/app/mentions/lib/MentionsParser.js
> +		});
Done

2023-04-24 13:06 UTC, hugocostadev approved these changes

2023-07-04 12:29 UTC, hugocostadev approved these changes

2023-08-22 00:44 UTC, merged