refactor(oauth-server): Import code, convert to TS and update dependency
RocketChat/Rocket.Chat pull request #28882
Opened 2023-04-12 14:48 UTC by rodrigok

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-04-13 01:42 UTC, KevLehman approved these changes

2023-04-19 18:50 UTC, KevLehman submitted a review, later dismissed

2023-04-20 16:59 UTC, sampaiodiego requested changes

2023-04-20 16:59 UTC, sampaiodiego commented on apps/meteor/server/startup/migrations/v293.ts
since we're avoiding migrations between minor releases, just making sure we're ok having this one and shipping the next version as a major one..

2023-04-20 19:46 UTC, KevLehman commented on apps/meteor/server/oauth2-server/oauth.ts
> +		config.debug = true;
Probably not intended but, What if we keep debug enabled while we test the whole thing?

2023-04-21 20:29 UTC, KevLehman approved these changes

2023-04-21 21:34 UTC, merged