fix: External avatar url provider for rooms not respected.
RocketChat/Rocket.Chat pull request #28910
Opened 2023-04-13 17:58 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

Closes #28351

## Steps to test or reproduce

- Get a link to an image
- go to `Admin -> Settings -> Accounts -> Avatar -> Room Avatar External Provider URL`
- paste the link there
- save

All rooms should have this link as avatar.
## Further comments

2023-04-13 18:03 UTC, tassoevan requested changes

2023-04-13 18:03 UTC, tassoevan commented on apps/meteor/app/utils/lib/getRoomAvatarURL.ts
> +	if (roomId == null) {
This conditional is too old-fashioned and not type-safe.

2023-04-13 18:03 UTC, tassoevan commented on apps/meteor/client/lib/rooms/roomTypes/private.ts
> +			return getRoomAvatarURL({ roomId: room._id, cache: room.avatarETag }) as string;
Why do it need to assert to `string`?

2023-04-13 18:03 UTC, tassoevan commented on apps/meteor/client/lib/rooms/roomTypes/public.ts
> +			return getRoomAvatarURL({ roomId: room._id, cache: room.avatarETag }) as string;
Why do it need to assert to `string`?

2023-04-14 19:20 UTC, tassoevan approved these changes

2023-05-02 17:30 UTC, merged

2023-06-17 11:18 UTC, amirAlamian commented
did this feature merge into master branch?