chore: Improve microservice deserialization of Buffer values
RocketChat/Rocket.Chat pull request #28958
Opened 2023-04-18 17:30 UTC by d-gubert

## Proposed changes (including videos or screenshots)

Currently, if a service sends a Buffer in a method call or expects a buffer as the return value of a call, the serializer returns a `Uint8Array` instead, as that's how EJSON handles these cases.

This PR changes any `Uint8Array` sent as params of service calls or as a result value back into a Buffer, so the services don't need to change their expected values.

## Issue(s)

## Steps to test or reproduce

## Further comments

There are services in the upcoming Apps-Engine microservices migration that handle Buffers, this PR is required for those services to operate correctly

2023-06-07 18:58 UTC, ggazzo commented on apps/meteor/ee/server/startup/broker.ts
> +	rebufferize(obj: unknown): any {
```suggestion
	private rebufferize(obj: unknown): any {
```

2023-06-09 14:27 UTC, tassoevan requested changes
`Serialized` is used by client (web/browser) code too, therefore `Buffer` cannot be used here. Keeping it as `Uint8Array` fits a little bit more, however I'm not 100% sure if we're assuming `Serialized` is JSON or EJSON decoded after encoded.

2023-06-09 21:12 UTC, ggazzo requested changes
also looking at your case, you claim that serialized keeps the buffer structure, but Date does not. The curious thing is that EJSON.parse keeps the dates, so something leads me to believe that you want to to use serialized in the wrong place

2023-06-09 21:15 UTC, ggazzo commented on apps/meteor/ee/server/startup/broker.ts
> +		return obj;
this can also cause performance issues it is preferable perform such cases on the "application/function" level

2023-06-14 17:57 UTC, closed without merging