fix: Removed agent access to already taken rooms
RocketChat/Rocket.Chat pull request #28979
Opened 2023-04-19 19:30 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

## Issue(s)

[OC-680](https://rocketchat.atlassian.net/browse/OC-680)
[OC-873](https://rocketchat.atlassian.net/browse/OC-873)
## Steps to test or reproduce

## Further comments

2023-04-20 14:16 UTC, tassoevan submitted a review, later dismissed

2023-04-20 14:18 UTC, KevLehman submitted a review, later dismissed

2023-04-20 14:19 UTC, KevLehman commented
Should this go to develop? Or should go to 6.2 branch?

2023-05-08 20:51 UTC, MartinSchoeler approved these changes

2023-05-15 12:24 UTC, ggazzo requested changes
I don't think it's a good solution. the extremely specific code, happening inside a generic provider doing something that is considered at least "weird". Is the only solution in the frontend? Is there nothing the backend can do to prohibit this operation?

2023-05-25 17:02 UTC, closed without merging

2023-06-05 18:13 UTC, ggazzo approved these changes