refactor: Move apps.engine settings to its own file
RocketChat/Rocket.Chat pull request #29029
Opened 2023-04-24 19:28 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-04-26 14:09 UTC, KevLehman requested changes

2023-04-26 14:09 UTC, KevLehman commented on apps/meteor/app/apps/server/settings.ts
> +	void settingsRegistry.addGroup('General', async function () {
```suggestion
export async function addAppsSettings() {
	await settingsRegistry.addGroup('General', async function () {
```

2023-04-26 14:09 UTC, KevLehman commented on apps/meteor/ee/server/apps/startup.ts
> +addAppsSettings();
```suggestion
await addAppsSettings();
```

2023-04-28 17:22 UTC, d-gubert commented on apps/meteor/ee/server/apps/startup.ts
> +addAppsSettings();
NO TOP-LEVEL AWAITS

2025-02-23 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=29029) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=29029) before we can accept your contribution.<br/><hr/>**Rafael Tapia** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=29029) it.</sub>

2026-04-23 21:33 UTC, d-gubert commented
Closing this in favor of new initiative

2026-04-23 21:33 UTC, closed without merging