refactor: `MonitorsPage` to typescript
RocketChat/Rocket.Chat pull request #29043
Opened 2023-04-25 14:26 UTC by MartinSchoeler

This PR does
 - [x] Convert monitors page to `TS`
 - [x] Convert monitors table to `V2`
 - [x] Convert `useEndpointData` to `useEndpoint` 
 - [x] Add new `GenericNoResults` to empty table

![Captura de Tela 2023-04-25 às 11 26 13](https://user-images.githubusercontent.com/20868078/234308436-b8229bdb-b4ec-4754-af1f-b071aa99fb63.png)

 Requires https://github.com/RocketChat/Rocket.Chat/pull/29007

OC-770
OC-813

2023-04-26 17:47 UTC, aleksandernsilva requested changes

2023-04-26 17:47 UTC, aleksandernsilva commented on apps/meteor/ee/client/omnichannel/monitors/MonitorsPage.tsx
> +					) : (
What do you think about making this part of the `MonitorsTable` component?

2023-04-26 17:47 UTC, aleksandernsilva commented on apps/meteor/ee/client/omnichannel/monitors/MonitorsTable.tsx
> +	data?: { monitors: ILivechatMonitor[]; count?: number; offset?: number; total: number };
`data: PaginatedResult<{ monitors: ILivechatMonitor[]; }>`

2023-04-27 17:17 UTC, dougfabris submitted a review, later dismissed

2023-05-09 17:54 UTC, aleksandernsilva submitted a review, later dismissed

2023-05-09 18:04 UTC, ggazzo commented on apps/meteor/ee/client/omnichannel/monitors/MonitorsTable.tsx
> +	const handleAdd = async () => {
useMutation

2023-05-09 19:41 UTC, aleksandernsilva approved these changes

2023-05-10 12:10 UTC, merged