new: Livechat Implementation
RocketChat/Rocket.Chat pull request #29098
Opened 2023-04-28 22:06 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-05-08 21:25 UTC, ggazzo submitted a review, later dismissed

2023-05-09 12:45 UTC, aleksandernsilva requested changes

2023-05-09 12:45 UTC, aleksandernsilva commented on packages/ddp-client/src/livechat/LivechatClientImpl.ts
> +// }
Should we leave this here?

2023-05-09 12:45 UTC, aleksandernsilva commented on packages/livechat/src/lib/room.js
> +	// Livechat.unsubscribeAll();
Are these comments necessary?

2023-05-09 13:32 UTC, aleksandernsilva submitted a review, later dismissed

2023-05-10 12:17 UTC, ggazzo approved these changes

2023-06-06 16:39 UTC, ggazzo approved these changes

2023-06-06 16:39 UTC, ggazzo approved these changes

2023-06-06 16:40 UTC, aleksandernsilva approved these changes

2023-06-06 18:02 UTC, KevLehman approved these changes
The changeset :)

2023-06-06 18:41 UTC, merged