improve use Stream Typings
RocketChat/Rocket.Chat pull request #29128
Opened 2023-05-02 21:55 UTC by ggazzo

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-05-16 13:15 UTC, ggazzo commented on apps/meteor/client/startup/incomingMessages.ts
> +			if ('ignored' in sub) {
```suggestion
			if ('ignored' in sub && sub.ignored) {
```

2023-05-16 13:21 UTC, ggazzo commented on apps/meteor/client/startup/incomingMessages.ts
> +					...('ignored' in sub ? { 'u._id': { $nin: sub.ignored } } : { ignored: { $exists: true } }),
```suggestion
					...('ignored' in sub && sub.ignored ? { 'u._id': { $nin: sub.ignored } } : { ignored: { $exists: true } }),
```

2023-05-17 02:03 UTC, ggazzo commented on apps/meteor/app/authorization/server/methods/removeUserFromRole.ts
> +	async 'authorization:removeUserFromRole'(roleId, username, scope = 'Users') {
```suggestion
	async 'authorization:removeUserFromRole'(roleId, username, scope) {
```

2023-05-18 19:44 UTC, sampaiodiego requested changes

2023-05-18 19:44 UTC, sampaiodiego commented on apps/meteor/app/livechat/client/lib/stream/queueManager.ts
> +	const { departments } = await APIClient.get(`/v1/livechat/agents/${userId}/departments`, { enabledDepartmentsOnly: 'true' });
any reason to not use `sdk.rest` here?

2023-05-18 19:44 UTC, sampaiodiego commented on apps/meteor/server/modules/notifications/notifications.module.ts
> +// a.notifyUserInThisInstance('asda', 'webrtc', 'a', 'b', 'c');
```suggestion
```

2023-05-18 19:44 UTC, sampaiodiego commented on apps/meteor/server/modules/watchers/watchers.module.ts
> +		}
```suggestion
		if (clientAction === 'removed') {
			void broadcast('watch.roles', {
				clientAction: 'removed',
				role: {
					_id: id,
					name: id,
				},
			});
			return;
		}

		const role = data || (await Roles.findOneById(id));
```

2023-05-18 19:44 UTC, sampaiodiego commented on apps/meteor/app/livechat/client/lib/stream/queueManager.ts
> +	const { departments } = await APIClient.get(`/v1/livechat/agents/${userId}/departments`, { enabledDepartmentsOnly: 'true' });
```suggestion
	const { departments } = await sdk.rest.get(`/v1/livechat/agents/${userId}/departments`, { enabledDepartmentsOnly: 'true' });
```

2023-05-18 19:44 UTC, sampaiodiego requested changes
look files

2023-05-18 21:25 UTC, sampaiodiego approved these changes

2023-05-18 22:03 UTC, merged