Fix Member list is randomly sorted #22145
RocketChat/Rocket.Chat pull request #29307
Opened 2023-05-20 16:11 UTC by Keanby

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-05-20 16:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=29307) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=29307) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=29307) it.</sub>

2023-05-22 16:28 UTC, debdutdeb requested changes
Should return a sorted list from the be already, configurable by some sort param.

Please check many of our other endpoint code that accepts a sort parameter which then returns a sorted list based on the key to the client.

2023-05-23 22:17 UTC, KevLehman commented on apps/meteor/client/views/room/contextualBar/RoomMembers/RoomMembersWithData.tsx
>  	}
Shouldn't this sort be made on server?

2023-05-23 22:17 UTC, KevLehman requested changes
See comments

2023-05-23 22:25 UTC, KevLehman commented
Thanks! I'll close this one in favor of #29228 :)

2023-05-23 22:25 UTC, closed without merging