chore: replace meteor.call -> sdk.call
RocketChat/Rocket.Chat pull request #29318
Opened 2023-05-22 18:30 UTC by ggazzo

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-05-23 12:31 UTC, sampaiodiego requested changes

2023-05-23 12:31 UTC, sampaiodiego commented on apps/meteor/app/message-mark-as-unread/client/actionButton.ts
> +				.then(async () => {
since you change `action` to `async`, why are you using `then` instead of `await`?

2023-06-06 19:46 UTC, sampaiodiego approved these changes

2023-06-06 20:06 UTC, KevLehman approved these changes

2023-06-06 22:20 UTC, merged