Fix/skeleton loading
RocketChat/Rocket.Chat pull request #29379
Opened 2023-05-26 19:28 UTC by Kishn0109

## Proposed changes (including videos or screenshots)

## Issue(s)

#29181 
## Steps to test or reproduce

## Further comments

I have to create a different branch with the same changes as in my preview MR I did this because I was facing a problem to signing the CLA agreement and I tried to match my commiter name with author name in between that my previews PR hade so many mistakes and result closed by the rocket chatbot. Please consider it and I apologize for the inconvenience

2023-06-05 04:57 UTC, Kishn0109 commented
Hi, @KevLehman I resolved this issue a week ago still it is in status QA needed, if there are some problems please let me I will be happy to fix them thank you

2023-06-16 04:39 UTC, KevLehman approved these changes

2023-07-16 11:47 UTC, Kishn0109 commented
Hi team can this MR get reviewed? I Merge branch 'develop' into fix/skeleton-loading by mistake because of that   the previous review got dismissed

2023-07-16 14:47 UTC, KevLehman commented
Let me try to move this forward on Monday :)

2023-07-18 23:26 UTC, dougfabris requested changes
@Kishn0109 Thanks for your contribution, could you replace the `Box` usage with `ContextualbarContent` as a wrapper to the `FormSkeleton`?

2023-07-19 13:04 UTC, aleksandernsilva submitted a review, later dismissed

2023-07-19 13:04 UTC, aleksandernsilva commented on apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactEditWithData.js
> +				<FormSkeleton />;
```suggestion
				<FormSkeleton />
```

2023-07-24 17:45 UTC, Kishn0109 commented
I really appreciate your suggestions! I have made the changes you asked for based on your feedback. Instead of using the Box component, I have used ContextualbarContent as a wrapper around FormSkeleton, as you suggested.

2023-07-24 18:03 UTC, KevLehman requested changes

2023-07-24 18:03 UTC, KevLehman commented on apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactEditWithData.js
> +			<ContextualbarContent p={'x24'}>
```suggestion
			<ContextualbarContent p='x24'>
```

2023-07-24 18:03 UTC, KevLehman commented on apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
> +			<ContextualbarContent p={'x24'}>
```suggestion
			<ContextualbarContent p='x24'>
```

2023-07-24 20:28 UTC, KevLehman submitted a review, later dismissed

2023-07-26 16:24 UTC, dougfabris requested changes

2023-07-26 16:24 UTC, dougfabris commented on apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactEditWithData.js
> +			<ContextualbarContent p='x24'>
```suggestion
			<ContextualbarContent>
```

2023-07-26 16:24 UTC, dougfabris commented on apps/meteor/client/views/omnichannel/directory/contacts/contextualBar/ContactNewEdit.tsx
> +			<ContextualbarContent p='x24'>
```suggestion
			<ContextualbarContent>
```

2023-08-24 19:56 UTC, dougfabris approved these changes

2023-08-25 03:27 UTC, merged