fix: Importer crashes when sending the "active status" e-mail notification to users
RocketChat/Rocket.Chat pull request #29401
Opened 2023-05-30 12:31 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Fix `getImportProgress` endpoint returning incorrect count info (`total: 0, completed: 0`);
 - Fix server crash when sending the "active status" e-mail notification to users on import.

## Issue(s)

## Steps to test or reproduce

## Further comments

TC-727

2023-05-30 17:24 UTC, gabriellsh approved these changes
Frontend LGTM!

2023-05-30 17:27 UTC, sampaiodiego requested changes

2023-05-30 17:27 UTC, sampaiodiego commented on apps/meteor/app/lib/server/functions/setUserActiveStatus.ts
> +	if (!user.emails) {
should this be a short circuit for all other empty possibilities as well? like:

```suggestion
	if (!user.emails || !Array.isArray(user.emails) || user.emails.length === 0) {
```

if so, the `Array.isArray` can be removed from line 123

2023-05-30 20:44 UTC, sampaiodiego approved these changes

2023-06-01 15:56 UTC, sampaiodiego approved these changes

2023-06-01 17:12 UTC, gabriellsh approved these changes
Not sure why it's pending a FE review, but here you go

2023-06-01 18:08 UTC, merged