fix:
RocketChat/Rocket.Chat pull request #29497
Opened 2023-06-07 21:17 UTC by totoi690

## Proposed changes (including videos or screenshots)

Search dm's by it's members and not by the roomId (using users' _id to compose the room _id is deprecated)

## Steps to test or reproduce
- Send a GET request to `im.messages` or `im.files` using the `username={your_own_username}`

### Current behavior
This error: `{'error': 'The required "roomId" param provided does not match any direct message [error-room-not-found]', 'errorType': 'error-room-not-found', 'success': False}`

### Expected behaviour
Should return all messages from your self dm

TC-724

2023-06-07 22:27 UTC, matheusbsilva137 requested changes

2023-06-07 22:27 UTC, matheusbsilva137 commented on apps/meteor/app/lib/server/functions/getRoomByNameOrIdWithOptionToJoin.ts
> +		room = isObject(roomUser) ? await Rooms.findOneDirectRoomContainingAllUserIDs([...new Set([user._id, roomUser._id])]) : null;
```suggestion
		room = isObject(roomUser) ? await Rooms.findOneDirectRoomContainingAllUserIDs([...new Set([user._id, roomUser._id])]) : Rooms.findOneById(rid);
```
if `roomUser` doesn't exist, then the `roomId` has been provided (and not the username)

2023-06-13 13:03 UTC, matheusbsilva137 submitted a review, later dismissed

2023-06-13 22:51 UTC, pierre-lehnen-rc submitted a review, later dismissed

2023-06-16 14:41 UTC, matheusbsilva137 submitted a review, later dismissed

2023-06-19 21:54 UTC, pierre-lehnen-rc approved these changes

2023-06-22 02:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=29497) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=29497) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: matheusbsilva137<br/>:white_check_mark: totoi690<br/>:white_check_mark: gabriellsh<br/>:x: scuciatto<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=29497) it.</sub>

2023-06-22 11:59 UTC, merged