fix: Canned responses filter not working
RocketChat/Rocket.Chat pull request #29565
Opened 2023-06-16 14:23 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

## Issue(s)

[OC-1045](https://rocketchat.atlassian.net/browse/OC-1045)

## Steps to test or reproduce

## Further comments

2023-06-19 18:05 UTC, MartinSchoeler submitted a review, later dismissed
LGTM, I would ask for tests, but we are currently refactoring that page, so the tests can go with the refactor PR :)

2023-06-20 03:57 UTC, ggazzo requested changes

2023-06-20 03:57 UTC, ggazzo commented on apps/meteor/ee/client/omnichannel/cannedResponses/CannedResponsesRoute.tsx
> +		['canned-responses', '/v1/canned-responses', debouncedText, debouncedSort, debouncedParams, sharing, createdBy],
```suggestion
		['canned-responses', '/v1/canned-responses', { debouncedText, debouncedSort, debouncedParams, sharing, createdBy }],
```

2023-06-20 16:26 UTC, KevLehman approved these changes

2023-06-20 17:04 UTC, merged