feat: return all broken password policies at once
RocketChat/Rocket.Chat pull request #29593
Opened 2023-06-20 20:48 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

Return all broken password policies at once in the HTTP response.
![image](https://github.com/RocketChat/Rocket.Chat/assets/18501599/2788c855-7eb1-42c2-86f1-396af47a4a0f)

## Issue(s)

## Steps to test or reproduce

## Further comments

[WM-63](https://rocketchat.atlassian.net/browse/WM-63)

2023-06-26 14:45 UTC, hugocostadev approved these changes
Approved, but check with @rique223 how to handle that in frontend

2023-06-30 18:56 UTC, KevLehman requested changes

2023-06-30 18:56 UTC, KevLehman commented on apps/meteor/tests/data/user.ts
> -export const adminUsername = 'rocketchat.internal.admin.test';
Hmmmmm

2023-07-04 14:03 UTC, KevLehman requested changes

2023-07-04 18:37 UTC, KevLehman approved these changes
Tests side we're good

I don't know about the use case so I'll let someone from the squad to take a look 👀

2023-07-07 21:31 UTC, matheusbsilva137 approved these changes

2023-07-21 11:24 UTC, merged