Chore/new dropdown multiselect
RocketChat/Rocket.Chat pull request #29613
Opened 2023-06-21 20:47 UTC by felipe-rod123

## Proposed changes (including videos or screenshots)

* Created a new multi-select dropdown component (`apps/meteor/client/views/admin/rooms/DropDown/CustomDropDown.tsx`) to add section titles and other features, as needed. This could be reused to create more variants in the future, or even a new component on Fuselage, maybe.

* This new component can be easily grouped with other dropdowns instances, to create a complex multi-select filter.

* Created a new custom hook to filter rooms, using a Set object to store unique values inside an array, instead of creating a custom function to remove duplicates.

* Removed previous checkbox filters, and added two new multi-select dropdowns to the Admin Rooms page (`apps/meteor/client/views/admin/rooms/RoomsTable.tsx`)

![](https://github.com/RocketChat/Rocket.Chat/assets/84182706/400c637e-a986-413d-b1a0-d7a80a54faa0)

## Issue(s)

Jira task: [WM-25](https://rocketchat.atlassian.net/browse/WM-25?atlOrigin=eyJpIjoiZjU5ZGJmMDQxMmIzNDgyOWJlM2EzMzY0Y2I4ZDUwMDgiLCJwIjoiaiJ9)

## Steps to test or reproduce

Navigate to: Home → Workspace → Rooms.

## Further comments

WM-25

2023-06-26 19:59 UTC, dougfabris requested changes

2023-06-26 20:12 UTC, hugocostadev commented on yarn.lock
> -"@babel/core@npm:^7.1.0, @babel/core@npm:^7.11.6, @babel/core@npm:^7.12.10, @babel/core@npm:^7.12.3, @babel/core@npm:^7.7.5":
Why did you have to update the `yarn.lock` , is that correct?

2023-06-26 20:17 UTC, felipe-rod123 commented on apps/meteor/client/providers/LayoutProvider.tsx
> +						contextualBar: breakpoints.includes('sm') ? '380px' : '100%',
Hmm, I think this was a mistake. I had several conflicts in this PR a few days ago, maybe this got merged by accident... I'll fix that!

2023-06-29 13:28 UTC, hugocostadev requested changes
Comparing with the Figma design:
![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/319f81ab-e4bf-465e-9d9b-b5ea1e601f16)

I think that the inputs on this page should be smaller and the options should take the entire input, WDYT?

2023-07-20 19:07 UTC, hugocostadev requested changes

2023-07-20 19:07 UTC, hugocostadev commented on .changeset/dropdown.md
> +- created a new component for the multiselect dropdown.
This should be user-friendly and release focus.

```suggestion
New filters to the Rooms Table at `Workspace > Rooms`
```

2023-07-24 12:28 UTC, hugocostadev approved these changes

2023-07-25 16:46 UTC, rique223 requested changes

2023-07-25 16:46 UTC, rique223 commented on apps/meteor/client/views/admin/rooms/RoomsTable.tsx
> +	function intersect(array1: IRoom[], array2: IRoom[]) {
Please, give this function a more descriptive name. Something like removeDuplicateRooms.

2023-07-25 16:46 UTC, rique223 commented on apps/meteor/client/views/admin/rooms/RoomsTable.tsx
> +		return [...new Set(array1)].filter((x) => set2.has(x));
Don't use single letter variable names.

2023-07-25 16:46 UTC, rique223 commented on packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx
> +// ];
If this type is not implementable right now, remove it please.

2023-07-25 16:46 UTC, rique223 commented on packages/ui-client/src/components/MultiSelectCustom/MultiSelectCustom.tsx
> + */
Place this documentation above DropDownProps please.

2023-07-31 16:09 UTC, rique223 approved these changes
LGTM!

2023-08-11 18:43 UTC, rique223 approved these changes

2023-08-11 18:43 UTC, merged