feat: add support for threads on federation (WIP)
RocketChat/Rocket.Chat pull request #29655
Opened 2023-06-27 15:53 UTC by MarcosSpessatto

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-07-12 23:26 UTC, lmauromb commented on apps/meteor/server/services/federation/application/room/input/RoomReceiverDto.ts
> +	};
should we define a thread type to use?

```typescript
type Thread {
  rootEventId: string;
  replyToEventId: string;
}
```

2023-07-12 23:50 UTC, lmauromb approved these changes

2023-07-12 23:50 UTC, lmauromb commented on apps/meteor/tests/unit/server/federation/infrastructure/rocket-chat/converters/RocketTextParser.spec.ts
> +		});
nice 👍

2023-07-28 03:44 UTC, debdutdeb requested changes

2023-07-28 03:44 UTC, debdutdeb commented on apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
> +		}
this masks the actual error. in many scenarios can make troubleshooting a nightmare, might even impossible

2023-07-28 03:44 UTC, debdutdeb commented on apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
> +		}
same here, can we log the actual error before returning?

2023-07-28 03:44 UTC, debdutdeb commented on apps/meteor/server/services/federation/infrastructure/matrix/Bridge.ts
> +		}
same

2023-08-22 00:41 UTC, merged