chore: `Livechat` forms rewrite
RocketChat/Rocket.Chat pull request #29668
Opened 2023-06-28 13:54 UTC by MartinSchoeler

2023-07-03 16:42 UTC, aleksandernsilva requested changes

2023-07-03 16:42 UTC, aleksandernsilva commented on packages/livechat/src/components/Form/HookFormExample/stories.tsx
> +		// watch,
Remove the comments if they're unnecessary.

2023-07-03 16:42 UTC, aleksandernsilva commented on packages/livechat/src/routes/Register/index.tsx
> +										// onInput={(target: HTMLInputElement) => setName(target.value)}
Remove comment if not necessary.

2023-07-03 16:42 UTC, aleksandernsilva commented on packages/livechat/src/routes/Register/index.tsx
> +	}) => {
Create a named type for this to improve legibility.

2023-07-03 16:42 UTC, aleksandernsilva commented on packages/livechat/src/routes/Register/index.tsx
> +					disabled={!isDirty || !isValid || loading || isSubmitting || Object.keys(errors).length > 0}
`Object.keys(errors)` is redundant since you're already checking `isValid`

2023-07-03 16:42 UTC, aleksandernsilva commented on packages/livechat/src/routes/Register/index.tsx
> +	});
This can be its own component `<CustomFields />`. We should also re-use the `Controller` for both field types.

2023-07-03 16:42 UTC, aleksandernsilva commented on packages/livechat/src/components/Form/DateInput/index.tsx
This prop `field` plus the ternary does not seem like a good idea 🤔. The better solution is probably to explicitly receive what you need instead of being completely tied to the `react-hook-form` lib. Take what you need (Ex.: `onChange`), ignore the rest.

2023-07-26 18:58 UTC, KevLehman submitted a review, later dismissed
Can't provide much value on the client side, but unlocking BE review

2023-08-02 17:55 UTC, tassoevan requested changes

2023-08-02 17:55 UTC, tassoevan commented on packages/livechat/src/components/ButtonGroup/index.tsx
> +		{toChildArray(children).map((child) => cloneElement(child as VNode, { className: createClassName(styles, 'button-group__item') }))}
What if `child` is a valid child that is not a `VNode`, like a string?

2023-08-02 17:55 UTC, tassoevan commented on packages/livechat/src/components/Form/CustomFields/index.tsx
> +										options={(options as string[])?.map((option: string) => ({ value: option, label: option }))}
```suggestion
										options={options?.map((option: string) => ({ value: option, label: option })) ?? []}
```

2023-08-07 15:47 UTC, tassoevan approved these changes

2023-08-08 12:58 UTC, aleksandernsilva requested changes

2023-08-08 12:58 UTC, aleksandernsilva commented on packages/livechat/src/routes/LeaveMessage/index.tsx
> +							// defaultValue={guestName}
Is this something that should be included or removed?

2023-08-08 12:58 UTC, aleksandernsilva commented on packages/livechat/src/routes/LeaveMessage/index.tsx
> +							// defaultValue={guestEmail}
Is this something that should be included or removed?

2023-08-08 12:58 UTC, aleksandernsilva commented on packages/livechat/src/routes/LeaveMessage/index.tsx
I noticed you used controller for every field, was this a choice? I believe using `register` is possible in some of these cases.

2023-08-08 12:58 UTC, aleksandernsilva commented on packages/livechat/src/routes/Register/index.tsx
> +						onSubmit={handleSubmit(onSubmit as SubmitHandler<FieldValues>) as unknown as JSXInternal.GenericEventHandler<HTMLFormElement>}
🤔

2023-08-09 15:11 UTC, aleksandernsilva submitted a review, later dismissed

2023-08-18 13:18 UTC, aleksandernsilva submitted a review, later dismissed

2023-08-21 12:55 UTC, tassoevan approved these changes

2023-08-21 13:17 UTC, aleksandernsilva approved these changes

2023-08-21 18:48 UTC, MarcosSpessatto approved these changes

2023-08-21 19:33 UTC, merged