feat: Add Toolbox to VideoConf message block
RocketChat/Rocket.Chat pull request #29679
Opened 2023-06-29 19:44 UTC by PedroRorato

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-06-29 20:18 UTC, dougfabris commented
isn't missing the removal videoconf's check on `getMessageContext`?

2023-07-05 21:48 UTC, dougfabris approved these changes

2023-07-20 17:54 UTC, tassoevan submitted a review, later dismissed

2023-08-07 19:54 UTC, dougfabris requested changes
I'm missing the fix on the `getMessageContext` and missing the changeset as well

2023-08-07 21:34 UTC, dougfabris requested changes

2023-08-07 21:34 UTC, dougfabris commented on apps/meteor/client/components/message/variants/ThreadMessage.tsx
> +	const messageContext: MessageActionContext = message.t === 'videoconf' ? 'videoconf-threads' : 'threads';
```suggestion
	const messageContext: MessageActionContext = isVideoConfMessage(message) ? 'videoconf-threads' : 'threads';
```

2023-08-08 13:50 UTC, dougfabris approved these changes

2023-08-08 13:50 UTC, merged