fix: Omnichannel Visitor Abandonment feature not working for apps
RocketChat/Rocket.Chat pull request #29724
Opened 2023-07-05 07:08 UTC by murtaza98

## Proposed changes (including videos or screenshots)

Visitor abandonment feature used to rely on `room.v.lastMessageTs` property to calculate the predicted time when the chat should be considered abandoned. Now when apps were updating the room properties like customFields, then the app converters were overriding lastMessageTs property ( [reference](https://github.com/RocketChat/Rocket.Chat/blob/74aa6770881eb620a2275b84c55465d7552e4597/apps/meteor/app/apps/server/converters/rooms.js#L41) ), thus making this abandonment feature not work for rooms created from apps. 

So to solve this, I've moved the `lastMessageTs` prop out of `room.v`, and instead I'm storing it as `room.contactLastMessageTs`. This will prevent the app's engine to override this prop, thus fixing the main issue due to which app's room were not being abandoned automatically.

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-07-05 13:57 UTC, KevLehman requested changes
What about compatibility with old rooms that have `v.lastMessage`? Since we're changing the property where we take info, we do need to make sure we keep compatibility with them. 

Or we can create a single shot function that moves `v.lastMessage` to `contactLastMessage`

2023-07-05 15:07 UTC, KevLehman submitted a review, later dismissed

2023-07-06 12:58 UTC, KevLehman submitted a review, later dismissed

2023-07-06 18:18 UTC, ggazzo requested changes

2023-07-06 18:18 UTC, ggazzo commented on apps/meteor/server/models/raw/LivechatRooms.ts
> +				contactLastMessageAt,
what is the point of adding this field? is this really necessary to fix the problem? or its like a improvement/refactor?
I could not find the exact line that actually fixes the problem

2023-07-06 19:25 UTC, sampaiodiego submitted a review, later dismissed
if you were able to pin point the problem root (https://github.com/RocketChat/Rocket.Chat/blob/74aa6770881eb620a2275b84c55465d7552e4597/apps/meteor/app/apps/server/converters/rooms.js#L41), why not fixing the code only there? I mean, all these changes are just an alternative solution, but it doesn't fix the root cause of the problem, right?

2023-07-06 19:30 UTC, ggazzo submitted a review, later dismissed
Great explanation @murtaza98, but I would like to enforce: on patches keep your changes small as possible, if you are fixing something focus on the fix, if you are refactoring something try to refactor without change any behavior, if you are creating something new, avoid fixes and code changes that dont are directly related with the new feature


about your change in specific I think its only about change the bridge as you mentioned. that would be a great fix (2..3 lines of code) 

if you are planning to replace some field or optimize any message let this to another pull request

2023-07-07 08:12 UTC, murtaza98 commented
Thanks for the feedback everyone :raised_hands: As per your suggestions, I've created a separate PR with changes only to app's bridges which should fix the original issue -> https://github.com/RocketChat/Rocket.Chat/pull/29756
Wrt this PR, I'd still like to keep this it has some improvement to the system messages, so I've renamed it accordingly.

2023-07-10 18:26 UTC, KevLehman requested changes

2023-07-10 18:26 UTC, KevLehman commented on apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
> +		this.logger.debug(`Getting default abandoned custom message for ${abandonmentAction}`);
```suggestion
```

2023-07-10 18:26 UTC, KevLehman submitted a review, later dismissed

2023-07-12 13:41 UTC, KevLehman requested changes

2023-07-12 13:41 UTC, KevLehman commented on apps/meteor/ee/app/livechat-enterprise/server/lib/VisitorInactivityMonitor.ts
> +		const visitor = await LivechatVisitors.findOneById(visitorId, {
```suggestion
		const visitor = await LivechatVisitors.findOneById<Pick<ILivechatVisitor, 'name' | 'username'>>(visitorId, {
```

2023-07-12 15:54 UTC, KevLehman approved these changes

2023-07-13 07:25 UTC, merged