fix: check if 2FA is enabled to allow TOTP and E2E Key reset
RocketChat/Rocket.Chat pull request #29723
Opened 2023-07-04 20:45 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

Verify if two-factor authentication is enabled in order to allow resetting TOTP or E2E key.

### Current behavior
Users are allowed to reset TOTP and E2E key even if 2FA is disabled.

### Expected behavior
When the Two Factor Authentication is disabled the options Reset e2e and TOTP should not appear

## Issue(s)

## Steps to test or reproduce
01. Go to workspace > settings > account > two factor authentication
02. Enable Two Factor Authentication 
03. Save changes
04. GO to users
05. Choose the users
06. click on the three dots
07. Reset e2e and Reset TOTP options are available.

08. Go to workspace > settings > account > two factor authentication 
09. Disable Two Factor Authentication 
10. Save changes
11. Go to users
12. Click on three dots

## Further comments

[SUP-277](https://rocketchat.atlassian.net/browse/SUP-277)

2023-07-10 13:37 UTC, matheusbsilva137 approved these changes
LGTM

2023-07-25 15:22 UTC, matheusbsilva137 submitted a review, later dismissed

2023-07-31 15:13 UTC, rique223 approved these changes

2023-07-31 15:45 UTC, pierre-lehnen-rc requested changes

2023-07-31 15:45 UTC, pierre-lehnen-rc commented on apps/meteor/app/api/server/v1/users.ts
> +
E2E can be used regardless of 2FA status. Blocking the reset E2E option when 2FA is disabled makes no sense.

2023-08-03 20:12 UTC, pierre-lehnen-rc approved these changes

2023-08-04 19:49 UTC, rique223 approved these changes

2023-08-04 19:49 UTC, merged