Regression: Hide tags to which livechat-monitor does not have access
RocketChat/Rocket.Chat pull request #29772
Opened 2023-07-10 04:50 UTC by murtaza98

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-07-10 16:24 UTC, KevLehman submitted a review, later dismissed

2023-07-11 13:45 UTC, KevLehman requested changes
Can we have at least 2 tests 🙏🏽

2023-07-11 14:08 UTC, murtaza98 commented on apps/meteor/ee/app/livechat-enterprise/server/api/lib/tags.ts
> +			});
sure done :)

2023-07-12 16:30 UTC, KevLehman approved these changes

2023-07-13 23:36 UTC, KevLehman approved these changes

2023-07-13 23:52 UTC, merged