chore: move some functions to a (new) user service
RocketChat/Rocket.Chat pull request #29800
Opened 2023-07-12 16:09 UTC by MarcosSpessatto

## Proposed changes (including videos or screenshots)

I'm moving those functions to this service because the Federation module depends on those functions, and since we are moving the module to an external service, we need to enable the dependencies via service methods.

FED-114
## Issue(s)

## Steps to test or reproduce

## Further comments

2023-07-21 14:23 UTC, ggazzo approved these changes

2023-07-21 14:24 UTC, ggazzo requested changes
instead of creating a new user service one this should not be related to accounts?

2023-07-31 19:37 UTC, pierre-lehnen-rc requested changes

2023-08-03 20:08 UTC, pierre-lehnen-rc submitted a review, later dismissed

2024-12-17 12:15 UTC, closed without merging