fix: show requested filters only on requested apps view
RocketChat/Rocket.Chat pull request #29819
Opened 2023-07-13 20:23 UTC by csuadev

Remove requested filters from the explorer view and showing them only on the requested view. 

## Proposed changes (including videos or screenshots)
Explorer view: 
<img width="1230" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/72958726/0c5ee668-9bd8-4632-a5f1-8430e633fe97">

Requested view:
<img width="434" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/72958726/32d493f9-cfe0-4caf-8eda-8090f4eec311">

## Issue(s)
[https://rocketchat.atlassian.net/browse/AECO-47](https://rocketchat.atlassian.net/browse/AECO-47)

## Steps to test or reproduce

## Further comments

2023-07-17 13:49 UTC, tassoevan requested changes

2023-07-17 13:49 UTC, tassoevan commented on .changeset/silver-mugs-unite.md
> +"@rocket.chat/meteor": minor
```suggestion
"@rocket.chat/meteor": patch
```

2023-07-17 19:32 UTC, tiagoevanp approved these changes

2023-07-18 00:11 UTC, tassoevan approved these changes

2023-07-20 17:53 UTC, AllanPazRibeiro approved these changes
LGTM

2023-07-20 19:11 UTC, merged