fix: put actual user status on omnichannel queue view
RocketChat/Rocket.Chat pull request #29844
Opened 2023-07-17 18:40 UTC by KevLehman

OC-203

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-07-20 13:16 UTC, murtaza98 approved these changes

2023-07-20 13:17 UTC, murtaza98 commented on apps/meteor/client/views/omnichannel/queueList/QueueListTable.tsx
> +	const getUserStatus = (status?: string) => {
```suggestion
	const getUserStatus = (status?: UserStatus) => {
```

2023-07-20 13:18 UTC, murtaza98 commented on apps/meteor/client/views/omnichannel/queueList/QueueListTable.tsx
> +			case 'online':
```suggestion
			case UserStatus.ONLINE:
```

2023-07-20 13:18 UTC, murtaza98 commented on apps/meteor/client/views/omnichannel/queueList/QueueListTable.tsx
> +			case 'away':
```suggestion
			case UserStatus.AWAY:
```

2023-07-20 13:18 UTC, murtaza98 commented on apps/meteor/client/views/omnichannel/queueList/QueueListTable.tsx
> +			case 'busy':
```suggestion
			case UserStatus.BUSY:
```

2023-07-20 13:18 UTC, murtaza98 commented on apps/meteor/client/views/omnichannel/queueList/QueueListTable.tsx
> +			case 'offline':
```suggestion
			case UserStatus.OFFLINE:
```

2023-07-20 13:19 UTC, murtaza98 requested changes
A small suggestion to use enums

2023-07-25 16:16 UTC, murtaza98 approved these changes

2023-08-14 05:16 UTC, murtaza98 approved these changes

2023-08-14 13:19 UTC, aleksandernsilva approved these changes

2023-08-22 05:00 UTC, merged