fix: Avoid blank spaces being sent as comment when comment is required
RocketChat/Rocket.Chat pull request #29868
Opened 2023-07-19 14:29 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-07-19 14:42 UTC, murtaza98 approved these changes

2023-08-14 05:09 UTC, murtaza98 approved these changes

2023-08-14 15:50 UTC, murtaza98 approved these changes

2023-08-16 16:31 UTC, MarcosSpessatto submitted a review, later dismissed

2023-08-16 16:32 UTC, aleksandernsilva approved these changes

2023-08-17 10:26 UTC, murtaza98 approved these changes

2023-08-17 16:39 UTC, MarcosSpessatto requested changes
@murtaza98 Sorry, I think I don't express myself correctly, I was talking about creating a test case for the problem we are solving here.

It's good to have the test case you created, let's keep that as well, but I believe we should create a test case sending the comment as an empty string with one or more blank(s) space(s) in it.

Something like:
```
it('should not close a room without comment', async () => {
			await restorePermissionToRoles('close-others-livechat-room');
			const visitor = await createVisitor();
			const { _id } = await createLivechatRoom(visitor.token);
			const response = await request.post(api('livechat/room.closeByUser')).set(credentials).send({ rid: _id, comment: '  ' }).expect(400);

			expect(response.body).to.have.property('success', false);
			expect(response.body).to.have.property('error', 'error-comment-is-required');
		});
```

2023-08-18 13:59 UTC, murtaza98 approved these changes

2023-08-18 17:30 UTC, MarcosSpessatto approved these changes

2023-08-18 18:00 UTC, ggazzo approved these changes

2023-08-21 05:33 UTC, merged