regression: close message menu on option click
RocketChat/Rocket.Chat pull request #29904
Opened 2023-07-24 19:22 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-07-24 19:45 UTC, juliajforesti requested changes
working good for all actions **but** _Add reaction_  🥲

2023-07-24 19:58 UTC, guijun13 approved these changes

2023-08-07 16:49 UTC, sampaiodiego requested changes
looks like the conflicts were not correctly solved.. 🤔

2023-08-09 18:33 UTC, milton-rucks commented
Resolved by another PR

2023-08-09 18:33 UTC, closed without merging