fix: login blocked after block time
RocketChat/Rocket.Chat pull request #30018
Opened 2023-08-04 18:13 UTC by sampaiodiego

## Proposed changes (including videos or screenshots)

## Issue(s)

Closes #27212
Closes #26828
[TC-183](https://rocketchat.atlassian.net/browse/TC-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)

## Steps to test or reproduce

## Further comments

2023-08-11 13:30 UTC, MarcosSpessatto approved these changes

2023-08-16 12:43 UTC, matheusbsilva137 approved these changes

2023-08-18 18:11 UTC, heitortanoue requested changes

2023-08-18 18:11 UTC, heitortanoue commented on apps/meteor/app/authentication/server/lib/restrictLoginAttempts.ts
> +	// succesful logins should reset the counter
```suggestion
	// successful logins should reset the counter
```

2023-08-18 18:12 UTC, heitortanoue approved these changes

2023-08-18 19:30 UTC, matheusbsilva137 approved these changes

2023-08-18 20:08 UTC, heitortanoue approved these changes

2023-08-18 20:33 UTC, ggazzo approved these changes

2023-08-18 20:35 UTC, merged