fix: user creation using ADMIN_* variables
RocketChat/Rocket.Chat pull request #30015
Opened 2023-08-04 11:24 UTC by debdutdeb

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-08-04 15:41 UTC, MarcosSpessatto requested changes

2023-08-04 15:41 UTC, MarcosSpessatto commented on apps/meteor/server/startup/initialData.js
> +
Can we remove this?

2023-08-04 15:41 UTC, debdutdeb commented on apps/meteor/server/startup/initialData.js
> +
```suggestion
```

2023-08-04 15:50 UTC, pierre-lehnen-rc approved these changes

2023-08-08 20:15 UTC, MarcosSpessatto approved these changes

2023-08-08 21:31 UTC, merged