fix: remove code that was setting mail_url to 'undefined'
RocketChat/Rocket.Chat pull request #30055
Opened 2023-08-09 20:43 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

Remove code that was setting the env `MAIL_URL` to `'undefined'`. 
This causes an error since the lib `meteor/email` validates if the host is set before sending the email. By setting it as `'undefined'` instead of `undefined`, the lib tried to send the email to the host 'undefined' resulting in the error: 
`Error trying to send email: Invalid URL: undefined [error-email-send-failed]`.

## Issue(s)

## Steps to test or reproduce
1. Go to workspace > users > edit user;
2. Change the email to anything valid;
3. Save the changes;

## Further comments

[WM-151](https://rocketchat.atlassian.net/browse/WM-151)

2023-08-10 01:18 UTC, pierre-lehnen-rc requested changes
Good catch!
But in order to ensure the MAIL_URL gets cleared when the setting is removed, use this instead of the old assignment.

```js
delete process.env.MAIL_URL;
```

2023-08-10 13:16 UTC, pierre-lehnen-rc approved these changes

2023-08-10 19:17 UTC, sampaiodiego approved these changes

2023-08-10 19:24 UTC, sampaiodiego requested changes
can you please add a changeset for the fix? thx

2023-08-10 20:21 UTC, sampaiodiego submitted a review, later dismissed

2023-08-11 19:07 UTC, sampaiodiego approved these changes

2023-08-11 19:07 UTC, merged