fix: unmuting on read only rooms
RocketChat/Rocket.Chat pull request #30050
Opened 2023-08-09 17:09 UTC by heitortanoue

## Proposed changes (including videos or screenshots)

Users can no longer send messages in a read only room if they are not unmuted by an admin. 
Unmuting an user doesn't add it to the `unmuted` array anymore, just removing it from the `muted` array

## Issue(s)
#15378 

## Steps to test or reproduce

Action | Effect | read-only | muted | unmuted
------------ | ------------- | ------------- | ------------- | -------------
Chat `x` has participant `random-dude` (it's newly created) | Everybody can send messages | `false` | `[]` | `[]`
`random-dude` sends spam & therefore gets muted | Everybody but the `random-dude` can send messages | `false` | `['random-dude']` | `[]`
After stopping spamming, `random-dude` gets re-activated | Everybody can send messages  | `false` | `[]` | `['random-dude']` ❗️
Now, the entire chat needs to be muted for some time -> moderator sets it to read-only |  Nobody except the `random-dude` ❗️ can send messages | `true` | `[]` | `['random-dude']`

For testing the unmuting on the read only rooms I recommend being in an admin account and using the slash command `/unmute <username>`.

## Further comments

TC-815

2023-08-09 17:22 UTC, pierre-lehnen-rc reviewed
Can you apply the same change to the `muteUserInRoom` method?

Otherwise if a user loses the permission to speak on a readonly room, they'll remain muted if the room stops being readonly.

2023-08-14 15:31 UTC, gabriellsh submitted a review, later dismissed
LGTM

2023-08-28 14:20 UTC, MarcosSpessatto requested changes

2023-08-28 14:20 UTC, MarcosSpessatto commented on apps/meteor/server/models/raw/Rooms.ts
> +	muteReadOnlyMutedUsernameByRoomId(_id: IRoom['_id'], username: IUser['username']): Promise<UpdateResult> {
Would it not be better to be `muteReadOnlyUsernameByRoomId`?

2023-08-28 14:20 UTC, MarcosSpessatto commented on apps/meteor/server/models/raw/Rooms.ts
> +		const query: Filter<IRoom> = { _id };
Doesn't it make sense to query also by readonly here just to make sure and to make the method name make more sense? `const query: Filter<IRoom> = { _id, ro: true };`

2023-08-28 14:20 UTC, MarcosSpessatto commented on apps/meteor/server/models/raw/Rooms.ts
> +	unmuteReadOnlyUsernameByRoomId(_id: string, username: string): Promise<UpdateResult> {
I think we could also add the `{ to: true }` flag here as well, just to reflect the method name.

2023-08-29 20:00 UTC, matheusbsilva137 approved these changes

2023-08-30 15:49 UTC, MarcosSpessatto approved these changes
It'd be nice if we could add a test to cover this scenario, We can add that in a subsequent PR.

2023-08-30 16:03 UTC, KevLehman approved these changes

2023-08-31 18:28 UTC, merged