feat: apply group filter to sync process
RocketChat/Rocket.Chat pull request #30088
Opened 2023-08-15 19:32 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-08-15 22:11 UTC, pierre-lehnen-rc commented on apps/meteor/ee/server/lib/ldap/Manager.ts
> +					return membersOfGroupFilter.includes(data.importIds[0]);
You need to use the value of the `LDAP_Group_Filter_Group_Member_Format` setting here.

2023-08-16 16:14 UTC, pierre-lehnen-rc requested changes

2023-08-16 16:14 UTC, pierre-lehnen-rc commented on apps/meteor/ee/server/lib/ldap/Manager.ts
> +						.replace(/#{userdn}/g, options?.dn as string);
The `username` may be undefined here. `dn` will never be with the current implementation, but it's worth validating it to be safe.

2023-08-16 17:50 UTC, pierre-lehnen-rc commented on apps/meteor/ee/server/lib/ldap/Manager.ts
> +				converter.addUserSync(userData, { dn: ldapUser.dn, username: this.getLdapUsername(data) });
```suggestion
				converter.addUserSync(userData, { dn: ldapUser.dn, username: this.getLdapUsername(ldapUser) });
```

my bad.

2023-08-16 18:06 UTC, pierre-lehnen-rc commented on apps/meteor/server/lib/ldap/Connection.ts
> +		return membersBuffer.map((member) => member.toString());
```suggestion
		return this.extractLdapAttribute(result[0].raw[this.options.groupFilterGroupMemberAttribute]);
```

2023-08-17 03:51 UTC, pierre-lehnen-rc commented on apps/meteor/server/lib/ldap/Connection.ts
> +
```suggestion
		const members = this.extractLdapAttribute(result[0].raw[this.options.groupFilterGroupMemberAttribute]) as string | string[];

```

2023-08-17 18:43 UTC, pierre-lehnen-rc approved these changes

2023-08-21 17:58 UTC, tassoevan approved these changes

2023-08-21 20:47 UTC, merged