fix: SAML login not working on mobile app
RocketChat/Rocket.Chat pull request #30128
Opened 2023-08-21 14:16 UTC by pierre-lehnen-rc

## Proposed changes (including videos or screenshots)

Backwards compatibility with mobile app.

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-08-21 14:37 UTC, tapiarafael approved these changes

2023-08-21 15:22 UTC, matheusbsilva137 submitted a review, later dismissed

2023-08-21 15:57 UTC, sampaiodiego requested changes
any way of adding some tests to this to prevent further regressions?

2023-08-21 15:57 UTC, sampaiodiego requested changes

2023-08-21 15:57 UTC, sampaiodiego commented on apps/meteor/app/meteor-accounts-saml/server/lib/SAML.ts
> +				const url = `${Meteor.absoluteUrl('saml')}/${credentialToken}?saml_idp_credentialToken=${credentialToken}`;
it is never too late:
```suggestion
				const url = Meteor.absoluteUrl(`saml/${credentialToken}?saml_idp_credentialToken=${credentialToken}`);
```

2023-08-21 17:21 UTC, tapiarafael approved these changes

2023-08-21 20:36 UTC, pierre-lehnen-rc commented
> any way of adding some tests to this to prevent further regressions?

We're working on getting the CI SAML environment ready for such tests. No test on the core could have caught this specific regression though.

2023-08-21 21:55 UTC, pierre-lehnen-rc commented on apps/meteor/tests/unit/app/meteor-accounts-saml/server.tests.ts
> +				`saml/${credentialToken}?saml_idp_credentialToken=${credentialToken}`,
```suggestion
				// the saml_idp_credentialToken param is needed by the mobile app
				`saml/${credentialToken}?saml_idp_credentialToken=${credentialToken}`,
```

2023-08-21 21:56 UTC, pierre-lehnen-rc commented on apps/meteor/app/meteor-accounts-saml/server/lib/Utils.ts
> +		return `saml/${credentialToken}?saml_idp_credentialToken=${credentialToken}`;
```suggestion
		// the saml_idp_credentialToken param is needed by the mobile app
		return `saml/${credentialToken}?saml_idp_credentialToken=${credentialToken}`;
```

2023-08-21 22:17 UTC, sampaiodiego submitted a review, later dismissed

2023-08-22 14:41 UTC, casalsgh submitted a review, later dismissed
Approving here based on Diego Sampaio having approved it before and no significant changes happening afterwards (just conflicts and due to me moving PR from develop to 6.3.0 branch).

2023-08-22 14:44 UTC, sampaiodiego requested changes
I just realized it is missing a changeset

2023-08-22 17:48 UTC, pierre-lehnen-rc commented
> I just realized it is missing a changeset

I've added the changeset now. Also tested with all platforms to ensure the problem is fixed.

2023-08-22 18:26 UTC, sampaiodiego approved these changes

2023-08-22 18:35 UTC, merged