chore: move team mentions to ce
RocketChat/Rocket.Chat pull request #30175
Opened 2023-08-25 11:29 UTC by heitortanoue

## Proposed changes (including videos or screenshots)
Move the Team Mentions feature to the RC Community Edition

## Issue(s)

## Steps to test or reproduce

Without the EE license, try to use the team mention feature by sending a message with `@team`, all team members should be notified.

## Further comments

TC-901

2023-08-28 23:47 UTC, yash-rajpal submitted a review, later dismissed
LGTM

2023-08-29 00:15 UTC, KevLehman requested changes

2023-08-29 00:15 UTC, KevLehman commented on apps/meteor/app/mentions/server/getMentionedTeamMembers.ts
> +	const members: ITeamMember[] = await Team.getMembersByTeamIds(teamIds, { projection: { userId: 1 } });
Don't you get the type from getMembersByTeamIds?

2023-08-29 00:15 UTC, KevLehman commented on apps/meteor/app/mentions/server/getMentionedTeamMembers.ts
> +		...new Set(members.map(({ userId }: { userId: string }) => userId).filter((userId: string) => !mentionIds.includes(userId))),
`members` already has a type, so it should be inferred here 👀

2023-08-29 12:15 UTC, matheusbsilva137 requested changes
I guess we should also remove `'teams-mention'` from `BundleFeature` and from the enterprise bundle (in `bundles.ts`), shouldn't we? :thinking:

2023-08-30 12:38 UTC, matheusbsilva137 approved these changes

2023-09-11 21:57 UTC, merged