chore: swap flaky current chats e2e tests for unit tests
RocketChat/Rocket.Chat pull request #30182
Opened 2023-08-25 20:44 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-08-25 22:40 UTC, ggazzo approved these changes

2023-08-25 22:46 UTC, dougfabris requested changes
Blocking it caus I need to fix something

2023-08-25 23:49 UTC, dougfabris submitted a review, later dismissed

2023-08-26 03:49 UTC, ggazzo approved these changes

2023-08-26 04:03 UTC, ggazzo approved these changes

2023-08-26 04:04 UTC, ggazzo commented
![image](https://github.com/RocketChat/Rocket.Chat/assets/5263975/0f441c4e-359a-4380-90ad-a8310e145e04)

2023-08-26 04:09 UTC, merged