fix: Invalid date error on some non-roman languages.
RocketChat/Rocket.Chat pull request #30209
Opened 2023-08-29 15:53 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Persian language (used for tests) was showing a `Invalid date` where a date should be. This was because moment returns an string representing the formatted time and that string is based on user's language.
Fix is to use only numeric values for date calculation on these charts

2023-09-14 12:57 UTC, aleksandernsilva submitted a review, later dismissed

2023-09-25 20:23 UTC, tassoevan requested changes
Missing unit tests. Also, some odd string manipulations with localized text... Is it right?

2023-10-23 16:50 UTC, KevLehman commented
Hey @tassoevan , I'm quite new to FE things, wanna help me in how to do the tests?

2023-10-27 14:06 UTC, tassoevan approved these changes

2023-10-27 14:20 UTC, merged