fix: linkedin oauth broken
RocketChat/Rocket.Chat pull request #30252
Opened 2023-09-01 16:57 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-09-01 22:26 UTC, matheusbsilva137 submitted a review, later dismissed

2023-09-04 14:01 UTC, pierre-lehnen-rc requested changes

2023-09-04 14:01 UTC, pierre-lehnen-rc commented on apps/meteor/packages/linkedin-oauth/linkedin-server.js
> +
```suggestion
		if (!response.ok) {
			throw new Error(responseContent.error_description);
		}

		responseContent = await response.json();
```

Check if it was sucessful before trying to read the json.

2023-09-04 14:01 UTC, pierre-lehnen-rc commented on apps/meteor/packages/linkedin-oauth/linkedin-server.js
> +		throw new Error(`Failed to complete OAuth handshake with Linkedin -- can't find access token in HTTP response. ${await response.text()}}`);
You can't call `response.text` after having called `response.json` already.

2023-09-05 20:55 UTC, pierre-lehnen-rc approved these changes

2023-09-06 12:05 UTC, merged