feat: push notification statistics
RocketChat/Rocket.Chat pull request #30269
Opened 2023-09-04 14:05 UTC by heitortanoue

## Proposed changes (including videos or screenshots)

Added two statistics `pushEnabled` and `pushGatewayChanged`

## Issue(s)

## Steps to test or reproduce

## Further comments

TC-875

2023-09-12 21:08 UTC, matheusbsilva137 submitted a review, later dismissed

2023-09-14 16:59 UTC, PedroRorato approved these changes

2023-09-15 12:29 UTC, sampaiodiego requested changes
regarding the reasoning behind the need to have this information added to the statistics, I do think it makes more sense to track `Push_enable_gateway` than if the gateway was changed or not.. because usually people will either use our apps with our gateway or change do not use our gateway with their own mobile apps.

and since we've been adding too much information to the statistics recently, I'd like to encourage some thinking on how to improve it.. for example, if we're tracking many different push related settings, maybe we can use a binary value? like:

we want to track 3 different settings, each one of them receives receives a bit:

```
1 1 1
| | |
| | +- push enabled = 0b1 = 
| +--- push gateway enabled = 0b10 = 2
+----- push gateway changed = 0b100 = 4
```

this way we could have a single value sent to the statistics using bitwise operators, like this:

```js
const pushEnabled = settings.get('Push_enable') ? 1 : 0;
const pushGatewayEnabled = settings.get('Push_enable_gateway') ? 2 : 0;
const gatewayChanged = hasGatewayChanged() ? 4 : 0;

statistics.push = pushEnabled | pushGatewayEnabled | gatewayChanged;
```

just an idea I think we should consider =)

2023-09-15 12:29 UTC, sampaiodiego commented on apps/meteor/app/statistics/server/lib/statistics.ts
> +		const defaultGateway = (await Settings.findOneById('Push_gateway'))?.packageValue;
if you're looking for `packageValue` field only, add a projection:
```suggestion
		const defaultGateway = (await Settings.findOneById('Push_gateway', { projection: { packageValue: 1 } }))?.packageValue;
```

2023-09-25 18:46 UTC, matheusbsilva137 requested changes

2023-09-25 18:46 UTC, matheusbsilva137 commented on apps/meteor/client/views/admin/info/UsageCard.stories.tsx
> +			pushEnabled: false,
```suggestion
```
I think you forgot to remove this line :thinking: please re-add it if I'm wrong

2023-09-25 18:46 UTC, matheusbsilva137 commented on .changeset/nice-chairs-add.md
> + - `pushGatewayChanged`: a boolean value to indicate whether the `Push_gateway` setting is set as default or not;
Please update this description

2023-10-02 21:01 UTC, matheusbsilva137 approved these changes

2023-10-03 14:21 UTC, sampaiodiego approved these changes

2023-10-03 15:44 UTC, yash-rajpal approved these changes

2023-10-03 15:44 UTC, merged