fix: empty vertical bar for administration menu when admin disable 'access-marketplace'
RocketChat/Rocket.Chat pull request #30297
Opened 2023-09-06 06:36 UTC by Ninad3721

## Proposed changes (including videos or screenshots)

The administration dropdown on the user side was showing an empty vertical bar when there is no content present in it (when admin disable the access marketplace for user there is no content in the dropdown of administration), by this PR the administration dropdown will be removed if there is no content in it.
https://www.loom.com/share/c117f6f00412496c8ee500375bd9c54c?sid=5a93297b-b200-42cc-81aa-3b9caec0b5af

## Issue(s)

https://github.com/RocketChat/Rocket.Chat/issues/30159
## Steps to test or reproduce

1.Disable 'access-marketplace' permission for users
2.Log in as a normal user
3.Click on the 'Administration' menu

## Further comments

2023-09-06 13:13 UTC, dougfabris requested changes

2023-09-06 13:13 UTC, dougfabris commented on apps/meteor/client/sidebar/header/actions/Administration.tsx
I think would be better to render a disabled `Button` instead of a `Menu`

2023-09-07 11:37 UTC, Ninad3721 commented on apps/meteor/client/sidebar/header/actions/Administration.tsx
Okay I will replace

2023-09-11 14:31 UTC, closed without merging

2023-09-11 14:31 UTC, dougfabris commented
Hi there, thanks for the contribution! 🚀 💯 

Closing this PR because it's stale now and it will be fixed here: #30319.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there