fix: disabled generic menu button when relevant user permissions are disabled
RocketChat/Rocket.Chat pull request #30319
Opened 2023-09-07 07:49 UTC by anjy7

## Proposed changes (including videos or screenshots)

![Screenshot from 2023-09-07 01-51-22](https://github.com/RocketChat/Rocket.Chat/assets/92802904/04440653-87d9-4e34-a1b2-40b3da5bf21b)
The "Create new" button is disabled as it should be when the user doesn't have those permissions

## Issue(s)

Fixes #30312 
## Steps to test or reproduce

1.Disable ''Create Private Channels", "Create Public Channels", "Create Team", "Start Discussion", "Start Discussion (Other-User)" and "Create Direct Messages" permissions for users
2.Log in as a normal user
3.Click on the "Create new" menu
## Further comments

2023-09-07 07:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=30319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=30319) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=30319) it.</sub>

2023-09-07 08:14 UTC, anjy7 commented
Fixes #30159 as well

2023-09-07 19:21 UTC, anjy7 commented
@dougfabris could you please have a look at this

2023-09-08 13:48 UTC, dougfabris requested changes

2023-09-08 13:48 UTC, dougfabris commented on apps/meteor/client/components/GenericMenu/GenericMenu.tsx
The `GenericMenu` should render conditionally an `IconButton` disabled when there are no sections and no items as well

2023-09-08 22:23 UTC, anjy7 commented on apps/meteor/client/components/GenericMenu/GenericMenu.tsx
Yup, done

2023-09-10 12:11 UTC, anjy7 commented
Hey @dougfabris,  I have made the requested changes. Please have a look

2023-09-11 14:28 UTC, dougfabris requested changes

2023-09-18 16:00 UTC, anjy7 commented
> @anjy7 Can you sign the CLA, please?

done, thank you

2023-09-19 15:41 UTC, merged