fix: Custom translations do not work
RocketChat/Rocket.Chat pull request #30383
Opened 2023-09-13 13:22 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Call `applyCustomTranslations` when extracting the keys.

## Issue(s)

Introduced in #29097

## Steps to test or reproduce

## Further comments

TC-953

2023-09-13 17:14 UTC, yash-rajpal approved these changes

2023-09-13 17:29 UTC, tassoevan requested changes
Is ignoring the prefix (instead of assuming it's `core`) a good idea? Also, what about server-side translations?

2023-09-13 17:43 UTC, yash-rajpal commented
> Is ignoring the prefix (instead of assuming it's `core`) a good idea? Also, what about server-side translations?

The final `results` doesn't contain the namespace prefix, we remove the namespace prefix before adding it to the final translations object. In this case it wasn't working for custom-translations not having namespace prefix so this fix handles that case.

2023-09-21 15:05 UTC, tassoevan approved these changes

2023-09-21 17:50 UTC, merged