feat: `feat/cloud-announcements`
RocketChat/Rocket.Chat pull request #30401
Opened 2023-09-15 00:55 UTC by tassoevan

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-09-29 19:20 UTC, ggazzo approved these changes

2023-09-29 20:06 UTC, sampaiodiego requested changes

2023-09-29 20:06 UTC, sampaiodiego commented on apps/meteor/server/models/raw/CloudAnnouncements.ts
> +		return [{ key: { status: 1, expireAt: 1 } }];
are these indexes supposed to be used any time in the future?

2023-09-29 20:06 UTC, sampaiodiego commented on apps/meteor/server/models/raw/CloudAnnouncements.ts
> +		super(db, 'cloud_announcements', trash);
I think we won't need `thrash` for this collection

2023-09-29 20:06 UTC, sampaiodiego commented on packages/core-typings/package.json
> +		"mongodb": "^4.12.1",
4.17?

2023-09-29 20:06 UTC, sampaiodiego commented on packages/core-typings/src/cloud/Announcement.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
should we remove this rule?

2023-09-29 20:15 UTC, ggazzo commented on packages/core-typings/src/cloud/Announcement.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
please

2023-09-29 20:33 UTC, sampaiodiego approved these changes

2023-09-29 20:34 UTC, ggazzo approved these changes

2023-09-29 21:21 UTC, merged

2023-09-30 16:21 UTC, zahidhussain998 commented
hey, i would like to work on this issue