chore: Change plan name Enterprise to Premium on marketplace
RocketChat/Rocket.Chat pull request #30487
Opened 2023-09-25 16:16 UTC by csuadev

Because of the new NBJ, the Enterprise plan is going to be renamed to Premium, this introduce this change on the marketplace UI. 

## Proposed changes (including videos or screenshots)
![image](https://github.com/RocketChat/Rocket.Chat/assets/72958726/9e5f08f2-9ed2-422c-85dd-81502e8b0040)

## Issue(s)
[https://rocketchat.atlassian.net/browse/AECO-368](https://rocketchat.atlassian.net/browse/AECO-368)

## Steps to test or reproduce

## Further comments

2023-09-26 23:06 UTC, tassoevan requested changes

2023-09-26 23:06 UTC, tassoevan commented on apps/meteor/client/views/marketplace/components/MarketplaceHeader.tsx
> +	const handleMarketplacePremiumTitle = title === t('Enterprise') ? t('Premium') : title;
Better handle this is the component above this one, avoiding match **translated** strings.

2023-09-26 23:06 UTC, tassoevan commented on apps/meteor/client/views/marketplace/BundleChips.tsx
> +				const handleBundleName = bundleName === 'Enterprise' ? 'Premium' : bundleName;
`question` Why not apply this "patch" on the REST endpoints that serve this information (`apps/meteor/ee/server/apps/communication/rest.ts`) instead?

2023-10-02 17:03 UTC, hugocostadev commented
maybe this is outdated... I guess that the Enterprise plan continue with the same name

2023-10-02 18:50 UTC, AlenDavid submitted a review, later dismissed
LGTM!

2023-10-03 20:23 UTC, tassoevan approved these changes

2023-10-06 14:41 UTC, AlenDavid approved these changes

2023-10-09 14:03 UTC, AlenDavid approved these changes
LGTM

2023-10-09 16:08 UTC, tassoevan approved these changes

2023-10-09 18:25 UTC, merged