fix: processWebhookMessage & chat.postMessage types
RocketChat/Rocket.Chat pull request #30652
Opened 2023-10-16 21:07 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-10-17 16:12 UTC, pierre-lehnen-rc submitted a review, later dismissed

2023-10-17 16:39 UTC, tassoevan requested changes

2023-10-17 16:39 UTC, tassoevan commented on apps/meteor/app/lib/server/functions/processWebhookMessage.ts
> +	user: IUser & { username: Exclude<IUser['username'], undefined> },
We have a utility type for it:

```suggestion
	user: RequiredField<IUser, 'username'>,
```

2023-10-17 16:39 UTC, tassoevan commented on apps/meteor/app/lib/server/functions/processWebhookMessage.ts
> +	msg?: IMessage['msg']; // overrided if text is present
```suggestion
	msg?: IMessage['msg']; // overridden if text is present
```

2023-10-17 16:39 UTC, tassoevan commented on apps/meteor/app/lib/server/functions/processWebhookMessage.ts
> +				const attachment = message.attachments[i] as Exclude<IMessage['attachments'], undefined>[number] & { msg?: string };
Why not skip the loop cycle if `message.attachments[i]` is undefined?

2023-10-19 13:53 UTC, tassoevan submitted a review, later dismissed

2023-10-20 13:45 UTC, tassoevan approved these changes

2023-10-26 15:14 UTC, merged