chore: hide marketplace categories when hidden property comes as true
RocketChat/Rocket.Chat pull request #30752
Opened 2023-10-25 22:20 UTC by csuadev

Frontend change to introduce the new property added in the marketplace-api that sends a `hidden` property inside the categories endpoint when we don't want to show any category inside the marketplace. 

## Issue(s)
[https://rocketchat.atlassian.net/browse/AECO-421](https://rocketchat.atlassian.net/browse/AECO-421)

## Steps to test or reproduce

## Further comments

2023-10-25 22:27 UTC, AllanPazRibeiro reviewed
LGTM

2023-10-25 22:27 UTC, AllanPazRibeiro submitted a review, later dismissed

2023-10-26 02:29 UTC, d-gubert requested changes
Please consider the guidelines on writing changesets https://developer.rocket.chat/contribute-to-rocket.chat/modes-of-contribution/participate-in-rocket.chat-development/development-workflow#4.-adding-changeset-to-your-pull-request

As per documentation:
> Similarly, refrain from merely replicating the PR title in the changeset, as PR titles are designed for developers, not customers.

> Since changesets are not for devs, refactors and chore tasks should generally not include one.

2023-10-26 18:29 UTC, tiagoevanp approved these changes

2023-10-26 19:09 UTC, aleksandernsilva approved these changes

2023-10-26 19:10 UTC, d-gubert approved these changes

2023-10-27 01:03 UTC, merged