feat: endpoints to new users panel
RocketChat/Rocket.Chat pull request #30869
Opened 2023-11-06 20:59 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

[WM-185](https://rocketchat.atlassian.net/browse/WM-185)

2023-11-08 15:09 UTC, MarcosSpessatto requested changes

2023-11-08 15:09 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/01-users.js
> +		});
Can we add some cases for the permissions as well?

2023-11-08 15:09 UTC, MarcosSpessatto commented on packages/rest-typings/src/v1/users/UsersListStatusParamsGET.ts
> +export const isUsersListStatusProps = ajv.compile<UsersListStatusParamsGET>(UsersListStatusParamsGetSchema);
I think we are forgetting to use this on the endpoint 😬

2023-11-08 15:09 UTC, MarcosSpessatto commented on apps/meteor/app/api/server/v1/users.ts
> +			if (!email) {
Couldn't we create an Ajv validation for this instead?

2023-11-13 14:02 UTC, tapiarafael commented on apps/meteor/app/api/server/v1/users.ts
> +			if (await sendWelcomeEmail(email)) {
I agree. I used an old file as an example to create mine and didn´t think about it.

2023-11-28 15:49 UTC, MarcosSpessatto approved these changes

2023-11-28 18:14 UTC, merged