fix: change the push sound sent when the push is from video conference
RocketChat/Rocket.Chat pull request #30910
Opened 2023-11-09 18:50 UTC by GleidsonDaniel

## Proposed changes (including videos or screenshots)

Corrects the push sound when the push is from videoconf, currently the system default sound, however videoconf has a specific sound for pushes.

## Issue(s)

## Steps to test or reproduce

## Further comments

Jira: [VC-155]

[VC-155]: https://rocketchat.atlassian.net/browse/VC-153

2023-11-09 18:57 UTC, MarcosSpessatto approved these changes

2023-11-09 19:49 UTC, GleidsonDaniel commented
> Please add the change set

I don't think there should be a changeset, it's a fix of a PR that was merged two days ago and they left this detail in the PR, the original PR that should have the changeset.

2024-01-03 17:34 UTC, pierre-lehnen-rc approved these changes
For reference: The push gateway will change `sound` to `soundname` automatically on android notifications.

The code that sends android notifications directly from rocket.chat also reads the `sound` attribute to fill the `soundname`.

2024-01-03 17:45 UTC, pierre-lehnen-rc requested changes
missing changeset

2024-01-15 17:18 UTC, pierre-lehnen-rc approved these changes

2024-01-23 00:09 UTC, merged