chore!: remove unused oauth setting
RocketChat/Rocket.Chat pull request #31102
Opened 2023-11-29 13:11 UTC by hugocostadev

## Proposed changes (including videos or screenshots)

The settings  `Accounts_OAuth_Custom_Button_Label_Color` , `Accounts_OAuth_Custom_Button_Color` , `*_button_label_color` and `*_button_color`  was not being used anymore for oauth buttons

## Issue(s)

## Steps to test or reproduce

## Further comments

https://rocketchat.atlassian.net/browse/SUP-395

2023-12-13 07:49 UTC, elfajriharsuda approved these changes

2024-03-14 20:21 UTC, ggazzo requested changes
how about a migration to delete? otherwise old instances will show the setting with no translations

2024-04-01 13:22 UTC, hugocostadev commented
> how about a migration to delete? otherwise old instances will show the setting with no translations

Good idea! I'll work on that! Thanks 🚀

2024-04-12 17:20 UTC, ggazzo requested changes

2024-04-12 17:20 UTC, ggazzo commented on apps/meteor/server/startup/migrations/v305.ts
> +		}
why not just a `deleteMany`?

2024-04-15 18:17 UTC, hugocostadev commented on apps/meteor/server/startup/migrations/v305.ts
> +		}
Much better indeed! Thanks

2024-04-15 18:49 UTC, ggazzo commented
/bark

2024-10-16 00:47 UTC, ggazzo submitted a review, later dismissed

2024-10-16 13:05 UTC, debdutdeb submitted a review, later dismissed

2024-10-16 17:13 UTC, ggazzo approved these changes

2024-10-16 17:13 UTC, merged