fix: connected users search on spotlight for user mentions
RocketChat/Rocket.Chat pull request #31134
Opened 2023-12-01 13:08 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2023-12-01 14:06 UTC, matheusbsilva137 submitted a review, later dismissed

2023-12-04 19:32 UTC, matheusbsilva137 approved these changes

2023-12-12 06:08 UTC, elfajriharsuda approved these changes

2023-12-12 21:02 UTC, matheusbsilva137 requested changes

2023-12-12 21:02 UTC, matheusbsilva137 commented on apps/meteor/server/lib/spotlight.js
> +			const exactMatch = await Users.findOneByUsernameIgnoringCase(usernames, {
```suggestion
		if (users.length === 0 && canListOutsiders && text) {
			const exactMatch = await Users.findOneByUsernameIgnoringCase(text, {
```

If I correctly understood the flow for this function, this block is supposed to retrieve exact matches for what the user has typed -- so we should keep using the `text` param here. Also, `findOneByUsernameIgnoringCase` first param should be a string, not an array (such as `usernames`).
Just checking if text is defined should avoid the error thrown in this model method, so all the rest will work fine.

2023-12-13 16:20 UTC, matheusbsilva137 approved these changes

2023-12-15 15:34 UTC, merged