feat: Hide UI elements through window postmessage
RocketChat/Rocket.Chat pull request #31184
Opened 2023-12-07 14:43 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-01-05 19:44 UTC, tassoevan requested changes

2024-01-05 19:44 UTC, tassoevan commented on apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
> +const MessageBoxActionsToolbarBuilder = ({
```suggestion
const MessageBoxActionsToolbar = ({
```

2024-01-05 19:44 UTC, tassoevan commented on apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/MessageBoxActionsToolbar.tsx
> +					icon={action.icon as ComponentProps<typeof MessageComposerAction>['icon']}
Why assert it?

2024-01-05 19:44 UTC, tassoevan commented on apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/ToolbarAction.ts
> +	icon: string;
Why not the union of icon names?

2024-01-05 19:44 UTC, tassoevan commented on apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useCreateDiscussionAction.tsx
> +export const useCreateDiscussionAction = (room?: IRoom): ToolbarAction => {
Keep in mind the hooks can't be conditionally called, while components can.

2024-01-08 13:26 UTC, tassoevan approved these changes

2024-01-08 18:25 UTC, merged

2024-02-14 02:33 UTC, MHFDoge commented
Small question, Is there a reason this was introduced **strictly** for users who embed via iframe, and not just made to work with the existing role-based permission system? I have personally run into several issues over multiple years with things on my workspace that could be quickly solved if a variation of this feature was made available to those who use the standard web interface provided by the server application itself.

2024-04-15 20:42 UTC, gabriellsh commented
@MHFDoge it's actually not exclusive to iframe, you can use it anywhere you can inject a custom script. This comes from common user requests that try to embed rocket.chat in another application, so it fits this need without being to complex. Coupling the UI to the role-based permission system is not something we want to do.