fix: Prevent `Fallback forward departments` feature to go on loop when configured as circular chain
RocketChat/Rocket.Chat pull request #31328
Opened 2023-12-27 18:05 UTC by KevLehman

[SUP-449](https://rocketchat.atlassian.net/browse/SUP-449)

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-01-11 14:22 UTC, lmauromb approved these changes

2024-01-16 13:49 UTC, lmauromb approved these changes

2024-01-19 18:47 UTC, MarcosSpessatto requested changes
Would it be possible to add some test cases for the maximum number of depth?

2024-01-19 18:47 UTC, MarcosSpessatto commented on apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
> +		department: AtLeast<ILivechatDepartment, '_id' | 'fallbackForwardDepartment'>;
Isn't `name` required as well?

2024-01-19 18:47 UTC, MarcosSpessatto commented on apps/meteor/lib/callbacks.ts
> +			department: AtLeast<ILivechatDepartmentRecord, '_id' | 'fallbackForwardDepartment'>;
Isn't `name` required as well?

2024-01-19 20:10 UTC, KevLehman commented on apps/meteor/ee/app/livechat-enterprise/server/hooks/onTransferFailure.ts
> +		department: AtLeast<ILivechatDepartment, '_id' | 'fallbackForwardDepartment'>;
```suggestion
		department: AtLeast<ILivechatDepartment, '_id' | 'fallbackForwardDepartment' | 'name'>;
```

2024-01-19 20:10 UTC, KevLehman commented on apps/meteor/lib/callbacks.ts
> +			department: AtLeast<ILivechatDepartmentRecord, '_id' | 'fallbackForwardDepartment'>;
```suggestion
			department: AtLeast<ILivechatDepartmentRecord, '_id' | 'fallbackForwardDepartment' | 'name'>;
```

2024-01-19 20:12 UTC, KevLehman commented
Tests are definitely possible. The test would take some time however to create the number of departments required for properly testing depth, so at the end I didn't do it 🤔 

I can include it on a separate PR too.

2024-01-22 15:26 UTC, lmauromb approved these changes

2024-01-22 17:43 UTC, MarcosSpessatto approved these changes

2024-01-22 19:36 UTC, sampaiodiego approved these changes

2024-01-22 21:23 UTC, merged