feature: Added modal confirmation before pinning message
RocketChat/Rocket.Chat pull request #31348
Opened 2024-01-01 06:04 UTC by Sayan4444

Proposed changes (including videos or screenshots)

AFTER THE FIX
https://github.com/RocketChat/Rocket.Chat/assets/112304873/2e74a44f-e168-48af-817d-c7b945d1f5b0

REASON BEHIND CHANGES
Made the same changes as done by DISCORD to tackle this issue.

Issue(s)
This should close issues :-
https://github.com/RocketChat/Rocket.Chat/issues/30777

Steps to test or reproduce

1. Go to Teams/Channel
2. Click on any of the teams/Channels where you are participant.
3. Try to Send a Text to the Team/Channel
4. Try to Edit the Text and See that there is no Cancel Button for Edit Text if the user wants to continue without editing the Text.]

2024-01-02 14:05 UTC, dougfabris requested changes

2024-01-02 14:05 UTC, dougfabris commented on apps/meteor/client/startup/actionButtons/pinMessage.ts
> +					title: 'Are you sure you want to pin this message?',
avoid using raw texts, let's use translations instead

2024-01-02 14:05 UTC, dougfabris commented on apps/meteor/client/startup/actionButtons/pinMessage.ts
Let's add the message that will be pinned in the Modal body

2024-01-02 16:23 UTC, hugocostadev commented on apps/meteor/client/startup/actionButtons/pinMessage.ts
@Sayan4444 you can check the Forward message modal to check how you can accomplish that

2024-01-02 16:26 UTC, Sayan4444 commented on apps/meteor/client/startup/actionButtons/pinMessage.ts
Thanks a lot I was also looking for an example

2024-01-03 14:04 UTC, dougfabris requested changes
@Sayan4444 This is the desired result shared by our design team, please check if you can achieve it using `<GenericModal />`, if you have any questions, let me know!

<img width='420px' src='https://github.com/RocketChat/Rocket.Chat/assets/27704687/13985c64-9aa4-4c41-be53-22070fccbb0e' />

Also, can you check what happened with the `en.i18n.json`?

2024-01-03 17:21 UTC, Sayan4444 commented
@dougfabris Is this good enough or do you want me to add or correct anything esle??

![Screenshot 2024-01-03 224853](https://github.com/RocketChat/Rocket.Chat/assets/112304873/a940fe21-5b3f-4b10-8237-7ca2cffb3544)

Can you tell me what is wrong about en.i18n.json, it will be of greate help

2024-01-04 19:31 UTC, dougfabris approved these changes
@Sayan4444 Thank you so much for the contribution, it was very precise and valuable. 
About the `en.json` file I think it was some issue syncing your code or with lint.
I made some small changes, just to match our standards and code organization.
Thanks again and I hope to see you contributing more 🚀

2024-01-04 19:42 UTC, dougfabris submitted a review, later dismissed

2024-01-04 22:10 UTC, Sayan4444 commented
@dougfabris Yep I will be contributing more as much as I can as I love solving issues which directly impact the end user experience. Do you have an issue which u are also waiting long time to see someone working on it?

2024-01-04 22:21 UTC, dougfabris commented
@Sayan4444 That's awesome to hear from you. 
Feel free to navigate through our repository and have fun with whatever you want, we found your choices amazing and we'll be reviewing them as soon as possible!

2024-01-05 14:25 UTC, hugocostadev approved these changes

2024-01-05 15:45 UTC, merged