fix: Link enclosed in parentheses is not clickable, but link preview is shown
RocketChat/Rocket.Chat pull request #31355
Opened 2024-01-02 14:42 UTC by Devansht420

## Proposed changes (including videos or screenshots)

BEFORE THE FIX:
![image](https://github.com/RocketChat/Rocket.Chat/assets/124887084/4c9d7fd1-5b02-450a-924a-79daf0f9d365)

AFTER THE FIX:
![image](https://github.com/RocketChat/Rocket.Chat/assets/124887084/066da0e4-c757-4c00-be8e-c12a0749ac6b)

REASON BEHIND CHANGES:
Earlier when a url was contained in parentheses or apostrophes i wasnt clickable and still showed a preview of the link to fix this i made the changes in the regex so that now to doesnt show the preview if the url isnt passed properly.

## Issue(s)
This should close issues :-
closes [#30710](https://github.com/RocketChat/Rocket.Chat/issues/30710)
## Steps to test or reproduce
Navigate to any channel.
Write a message containing `(https://rocket.chat/)` (make sure to include the parentheses!) and submit it.

## Further comments

2024-01-02 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=31355) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=31355) before we can accept your contribution.<br/><hr/>**Devansh Tyagi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=31355) it.</sub>

2024-01-12 19:15 UTC, hugocostadev requested changes

2024-01-12 19:15 UTC, hugocostadev commented on apps/meteor/lib/getMessageUrlRegex.ts
> +/(?:\(|'|^)(\w+:\/\/[-A-Za-z0-9\.]+(:\d+)?(\/[-\+=&?:%#\.\/\w]*)?)(?:\)|'|$)|(?:\(|'|^)(https?:\/\/[-A-Za-z0-9\.]+(:\d+)?(\/[-\+=&?:%#\.\/\w]*)?)(?:\)|'|$)/g;
This regex blocks preview for links with spaces in it's boundaries...

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/981b7659-b4e1-40ba-9481-b30f3d3ac561)

2024-01-15 12:30 UTC, Devansht420 commented
Hey @hugocostadev I'll look into it, will try to come up with some better changes. Will update you.

2024-01-15 12:47 UTC, hugocostadev commented
> Hey @hugocostadev I'll look into it, will try to come up with some better changes. Will update you.

Thanks a lot @Devansht420 ! Keep making your amazing contributions! 🚀

2024-01-19 13:59 UTC, hugocostadev commented
> Hey @hugocostadev , I did some research and found out that the parsing is done via a grammar file in Fuselage, shouldn't the correct fix be by updating the file here -> https://github.com/RocketChat/fuselage/blob/91e502a0c43c90d589bd96039b5a671a21336876/packages/message-parser/src/grammar.pegjs#L243 ?
> 
> The regex is only used for generating preview, which I believe is working anyways.

But the issue is the preview... The link shouldn't be clickable in this scenario

2024-01-22 09:19 UTC, Devansht420 commented
@hugocostadev , should i rectify the regex so that it solves the issue and the problem that you pointed out or should i work on a different approach?

2024-01-28 07:44 UTC, Devansht420 commented
Hey @hugocostadev , I've pushed the changes in the regex, I think now its working fine. Please let me know your thoughts.

2024-02-10 08:23 UTC, Devansht420 commented
hey @hugocostadev any update?
i just replaced spaces in the tab to an actual tab in the last commit to fix the lint but now its showing errors in CI which was not happening earlier.

2026-02-24 22:02 UTC, closed without merging