fix: hide archived rooms in room.autocomplete endpoint
RocketChat/Rocket.Chat pull request #31383
Opened 2024-01-05 14:51 UTC by heitortanoue

## Proposed changes (including videos or screenshots)

Issue with the create option discussion, the list when you choose the Channel or Group is showing Archived Teams/groups/channels

## Issue(s)

## Steps to test or reproduce

- Create at least one channel/group/team and then archive them

- Choose to create a discussion and then you will be able to pick this archived channel from the drop down suggestion list for parent channel

## Further comments

SUP-286

2024-01-09 14:49 UTC, matheusbsilva137 requested changes

2024-01-09 14:49 UTC, matheusbsilva137 commented on apps/meteor/server/models/raw/Rooms.ts
> +			],
```suggestion
			$and: [{ federated: { $ne: true } }, { archived: { $ne: true } }],
```
Your suggestion works, but I think it's more concise and readable like this.

2024-01-09 14:56 UTC, matheusbsilva137 reviewed
Also, I think we should consider this a **breaking change** since this changes the output of the `rooms.autocomplete.channelAndPrivate` endpoint. I'll approve it for now since it looks fine to me, but I'll mark it as a major change.
Please tell me if you agree, @MarcosSpessatto

2024-01-09 15:03 UTC, matheusbsilva137 submitted a review, later dismissed

2024-01-10 13:36 UTC, MarcosSpessatto commented
> Also, I think we should consider this a **breaking change** since this changes the output of the `rooms.autocomplete.channelAndPrivate` endpoint. I'll approve it for now since it looks fine to me, but I'll mark it as a major change. Please tell me if you agree, @MarcosSpessatto

Yes, I agree. Let's keep this as a breaking change then. 👍

2024-01-10 13:42 UTC, MarcosSpessatto approved these changes

2024-04-09 17:38 UTC, ggazzo requested changes

2024-04-09 17:38 UTC, ggazzo commented on .changeset/three-avocados-search.md
> +Fixed archived rooms returned in `rooms.autocomplete.channelAndPrivate` endpoint
the description does not explain to me what changes for this to be a break change

2024-10-16 17:21 UTC, ggazzo approved these changes

2024-10-16 17:21 UTC, merged