chore: test
RocketChat/Rocket.Chat pull request #31468
Opened 2024-01-17 03:10 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-01-17 17:14 UTC, KevLehman commented on apps/meteor/ee/app/livechat-enterprise/server/business-hour/Multiple.ts
> +		const [agentsWithDepartment, [agentsOfDepartment]] = await Promise.all([
```suggestion
		const [agentsWithDepartment, [agentsOfDepartment] = []] = await Promise.all([
```

2024-01-18 19:55 UTC, MarcosSpessatto requested changes

2024-01-18 19:55 UTC, MarcosSpessatto commented on apps/meteor/app/livechat/server/business-hour/AbstractBusinessHour.ts
> +	onDepartmentDisabled(department?: AtLeast<ILivechatDepartment, '_id' | 'businessHourId'>): Promise<any>;
Can we change this to `Promise<void>` returning type?

2024-01-18 19:55 UTC, MarcosSpessatto commented on apps/meteor/ee/server/models/raw/LivechatDepartment.ts
> +		findAgentsByBusinessHourId(businessHourId: string): AggregationCursor<{ agents: string[] }>;
Would not it be better to change it to `agentIds`?

2024-01-18 19:55 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
> +			/* const avgWaitingTimeValue = moment.duration(avgWaitingTime.value).asSeconds();
Any reason to comment this?

2024-01-19 14:06 UTC, sampaiodiego approved these changes

2024-01-19 14:40 UTC, lmauromb approved these changes

2024-01-19 14:49 UTC, MarcosSpessatto approved these changes

2024-01-19 15:45 UTC, merged