fix: Fix the "Invalid settings provided" Error message while updating Archive Status in Room Information #31502
RocketChat/Rocket.Chat pull request #31503
Opened 2024-01-20 21:35 UTC by shivang-16

## Issue(s) - #31502 

Fixed the "Invalid settings provided" Error message while updating Archive Status in Room Information 

## Proposed changes (including videos or screenshots)

https://github.com/RocketChat/Rocket.Chat/assets/125182653/de8932c0-c9ab-41a8-ba2c-80a104fc3612

## Steps to test or reproduce

1. Go to -> app > meteor > app > channel-settings > server > methods > saveRoomSettings.Ts
2. Update the RoomSettings type definition to incorporate the 'archive' status.
3.  Update the fields array in the RoomSettings to include the 'archive' key.

2024-01-20 21:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=31503) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=31503) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=31503) it.</sub>

2024-01-25 01:22 UTC, rique223 reviewed
This looks like a nice solution. I'll verify with engineering if there's a reason for this field not to exist and if everything is correct I'll approve it.

2024-01-25 21:09 UTC, MarcosSpessatto requested changes
@shivang-16 ~~This doesn't fix the issue, you have only added it as a valid parameter, that's why the error stopped being thrown, but there is no function to save the `archived` parameter nor a validator for it (the users must have a specific permission to be able to archive rooms).~~

The client is handling the room archive in a specific endpoint, the client should not send the `archived` property to the saveRoomSettings endpoint since it's being handled separately.

2024-01-26 16:24 UTC, dougfabris submitted a review, later dismissed
@shivang-16 I've added the proper fix. Nice catch and thanks for contributing 🚀

2024-01-26 16:27 UTC, MarcosSpessatto submitted a review, later dismissed

2024-01-26 16:50 UTC, rique223 approved these changes

2024-01-26 17:43 UTC, MarcosSpessatto approved these changes

2024-01-26 18:07 UTC, rique223 approved these changes

2024-01-26 19:03 UTC, merged