chore: Remove endpoints dependency on meteor/check
RocketChat/Rocket.Chat pull request #31530
Opened 2024-01-24 22:01 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

TC-1090

2024-01-24 22:16 UTC, ggazzo requested changes
since this is supposed to be huge because there is no other way to go, avoid different changes, stick with meteor/check removal, if you can split into commits/pr each endpoint would be great also

2024-01-24 22:16 UTC, ggazzo commented on apps/meteor/app/api/server/v1/permissions.ts
> +	{ authRequired: true, permissionsRequired: ['access-permissions'] },
not related please move to a different pr

2024-01-24 22:16 UTC, ggazzo commented on apps/meteor/app/api/server/v1/channels.ts
> +			GET: { permissions: ['view-c-room', 'view-joined-room'], operation: 'hasAny' },
same

2024-01-31 15:40 UTC, matheusbsilva137 commented
Closed in favor of #31579 and #31576
Thanks for the reviews, @ggazzo ! Please check the new PRs later

2024-01-31 15:40 UTC, closed without merging