i18n: German translation switches 'conversation' and 'discussion'
RocketChat/Rocket.Chat pull request #31595
Opened 2024-01-31 20:00 UTC by hardikbhatia777

## Proposed changes (including videos or screenshots)

German translation files don't differentiate between 'Unterhaltung' (meaning entertainment / conversation) and 'Diskussion' (Discussion). This creates inconsistencies in labels and tool tips across the UI and should be streamlined.

I've replaced all appropriate occurances of the same to match the exact translation of English (and verified them using Google Translate). 

If I replaced something that's inappropriate, please let me know :) I'll change it right away.
## Issue(s)

#31587 

## Steps to test or reproduce

## Further comments

2024-01-31 21:14 UTC, david-uhlig requested changes
Thank you again for providing a quick fix @hardikbhatia777! 

I marked three occurences where we need to use the plural. Apart from these the changes look fine to me. Could you also please change the de-IN and de-AT translation files. They have the same inconsistencies. Appreciated!

2024-01-31 21:14 UTC, david-uhlig commented on apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
> +  "No_Discussions_found": "Keine Diskussion gefunden",
This needs to be plural: Diskussionen

2024-01-31 21:14 UTC, david-uhlig commented on apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
> +  "No_discussions_yet": "Keine Diskussion vorhanden",
This needs to be plural: Diskussionen

2024-01-31 21:14 UTC, david-uhlig commented on apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json
> +  "Total_Discussions": "Anzahl aller Diskussions",
This needs to be plural: Diskussionen

2024-02-01 10:37 UTC, david-uhlig approved these changes
Looks good to me! There seems to be a fallback to de.i18n.json for the missing de-AT.i18n.json lines, so this works out fine. Well done.

2024-02-01 20:41 UTC, rique223 approved these changes
Great work folks. Looks good to me.

2024-02-09 21:11 UTC, merged