feat: Trigger chat-visitor-registered on 'new chat' after closing
RocketChat/Rocket.Chat pull request #31718
Opened 2024-02-09 18:26 UTC by MartinSchoeler

This will allow the `after-guest-registration` trigger to run when starting a new chat after finishing a chat when the `clear guest data when chat ended` setting is set to false

REQUIRES https://github.com/RocketChat/Rocket.Chat/pull/31268

2024-03-12 18:30 UTC, MarcosSpessatto requested changes
Can we add a changeset please?

2024-03-13 11:26 UTC, MarcosSpessatto approved these changes

2024-03-14 14:12 UTC, KevLehman submitted a review, later dismissed

2024-03-14 19:14 UTC, ggazzo commented on apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
> +	});
```suggestion
	test.describe('OC - Livechat New Chat Triggers - After Registration', async () => {
		await test('expect trigger message after registration', async () => {
			await expect(poLiveChat.txtChatMessage(triggerMessage)).toBeVisible();
		});
	});
```

2024-03-14 19:15 UTC, ggazzo commented on apps/meteor/tests/e2e/omnichannel/omnichannel-triggers.spec.ts
> +	});
```suggestion
	test.describe('OC - Livechat New Chat Triggers - After Registration, clear Local storage', async () => {
		test.beforeEach(async ({ page, api }, testInfo) => {
			await api.post('/settings/Livechat_clear_local_storage_when_chat_ended', { value: true });
		});
	
		await test('expect trigger message after registration', async () => {
			await poLiveChat.page.reload();
			await poLiveChat.sendMessage(newUser, false);
			await expect(poLiveChat.txtChatMessage(triggerMessage)).toBeVisible();
		});
	});
```

2024-03-14 19:18 UTC, aleksandernsilva submitted a review, later dismissed

2024-03-14 21:18 UTC, ggazzo commented
as expected both tests are failing before the fix:
```
✘  60 omnichannel/omnichannel-triggers.spec.ts:229:13 › OC - Livechat New Chat Triggers › OC - Livechat New Chat Triggers - After Registration › expect trigger message after registration (5.0s)
Sending test result to Rocket.Chat: {"name":"expect trigger message after registration","status":"failed","duration":5028,"branch":"refs/pull/31718/merge","draft":false,"run":17995}
  ✘  61 omnichannel/omnichannel-triggers.spec.ts:248:13 › OC - Livechat New Chat Triggers › OC - Livechat New Chat Triggers - After Registration, clear Local storage › expect trigger message after registration (5.3s)
```

2024-03-15 20:02 UTC, ggazzo approved these changes

2024-03-15 21:20 UTC, merged