fix: setDepartment not persisting on chat closed
RocketChat/Rocket.Chat pull request #31792
Opened 2024-02-20 13:30 UTC by MartinSchoeler

SUP-484

2024-02-26 16:03 UTC, MarcosSpessatto submitted a review, later dismissed

2024-03-04 16:29 UTC, MarcosSpessatto submitted a review, later dismissed

2024-03-08 13:43 UTC, ggazzo requested changes
please provide some test to make sure we never face this again

2024-03-11 21:25 UTC, ggazzo approved these changes

2024-03-11 23:33 UTC, merged