fix: CRM integration mismatch on callback type
RocketChat/Rocket.Chat pull request #31880
Opened 2024-03-04 15:04 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-03-06 17:01 UTC, MarcosSpessatto requested changes

2024-03-06 17:01 UTC, MarcosSpessatto commented on .changeset/slow-jobs-think.md
> +fix: CRM integration mismatch on callback type vs code validation
Can we explain this more instead of just the PR title?

2024-03-08 18:09 UTC, MarcosSpessatto requested changes

2024-03-08 18:09 UTC, MarcosSpessatto commented on apps/meteor/app/livechat/server/hooks/sendToCRM.ts
> +const getAdditionalFieldsByType = (type: CRMActions, room: OmnichannelRoomWithExtraFields): AdditionalFields => {
Since this is almost impossible to end-to-end test, what about creating a unit test for this specific function?

2024-03-12 15:37 UTC, MarcosSpessatto approved these changes

2024-03-12 15:44 UTC, lmauromb approved these changes

2024-03-12 17:35 UTC, merged