Fix: Multiple type of BH making bots not available on opening
RocketChat/Rocket.Chat pull request #31881
Opened 2024-03-04 15:44 UTC by KevLehman

https://rocketchat.atlassian.net/browse/SUP-468

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-03-08 19:04 UTC, MarcosSpessatto requested changes
Would it be possible to add a test case for this?

2024-03-12 13:20 UTC, KevLehman commented on apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
> +			await openOrCloseBusinessHour(defaultBusinessHour, false);
```suggestion
			await openOrCloseBusinessHour(defaultBusinessHour, true);
```

2024-03-12 18:53 UTC, MarcosSpessatto requested changes

2024-03-12 18:53 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
> +			await setUserActiveStatus(agent._id, false);
Do we need this? Isn't this making the agent inactive instead of active?

2024-03-12 18:53 UTC, MarcosSpessatto commented on apps/meteor/tests/data/livechat/department.ts
> +export const createDepartmentWithAnOnlineAgent = async (overrideUser?: OnlineAgent): Promise<{department: ILivechatDepartment, agent: OnlineAgent }> => {
I think it would be better to create another function for this, something like `createDepartmentUsingExistingOnlineAgent`. WDYT?

2024-03-12 18:53 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
> +		});
Shouldn't we create a test case with the BH feature off, and then turn it on and check if it's behaving properly? According to what we have in the changeset, it looks like this only happens when the feature is turned on. Or is this already covered with the above test case?

2024-03-12 19:23 UTC, KevLehman commented on apps/meteor/tests/end-to-end/api/livechat/19-business-hours.ts
> +			await setUserActiveStatus(agent._id, false);
```suggestion
			await setUserActiveStatus(agent._id, false);
			await setUserActiveStatus(agent._id, true);
```

2024-03-13 11:22 UTC, MarcosSpessatto approved these changes

2024-03-18 19:20 UTC, sampaiodiego approved these changes

2024-03-18 20:26 UTC, merged