feat: Remove upsert users capability through the `users.update` endpoint
RocketChat/Rocket.Chat pull request #31889
Opened 2024-03-04 19:41 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Remove user upsert behavior from `users.update` endpoint (by making `_id` field required);
 - Fix `users.update` and `users.create` params check to accept the `settings` field, which was already expected by them internally (this allow users to set their language preference, for example);
 - Fix `IUserSettings` type to have an optional `profile`, as set through the API.

## Issue(s)

## Steps to test or reproduce

## Further comments

[CORE-79](https://rocketchat.atlassian.net/browse/CORE-79?atlOrigin=eyJpIjoiN2QwYmYyNGEyYzMwNDAzMmE5OWUzMWM0YjQ2MDc3MjUiLCJwIjoiaiJ9)

2024-03-11 19:56 UTC, MarcosSpessatto requested changes
Can we add one test case for each case just to ensure the behavior?

2024-03-14 19:41 UTC, MarcosSpessatto submitted a review, later dismissed

2024-04-25 13:51 UTC, KevLehman commented
@matheusbsilva137 think your branch got crazy

2024-04-25 15:32 UTC, matheusbsilva137 reviewed
A sync fixed it, @KevLehman ! Tks for the heads up

2024-08-08 15:07 UTC, MarcosSpessatto submitted a review, later dismissed

2024-10-11 12:25 UTC, MarcosSpessatto approved these changes

2024-10-11 15:16 UTC, merged