fix: language overwriting in workspace settings
RocketChat/Rocket.Chat pull request #31897
Opened 2024-03-05 17:03 UTC by csuadev

Fix language priority order in the workspace settings that was causing losing the workspace language when refreshing the browser given that the browser language was having a higher priority over the language chosen by the user. 

## Proposed changes (including videos or screenshots)

## Issue(s)
[https://rocketchat.atlassian.net/browse/SUP-493](https://rocketchat.atlassian.net/browse/SUP-493)

## Steps to test or reproduce
1. Go to workspace settings.
2. Go to general.
3. Change the language and restart the page.

## Further comments

2024-03-06 17:06 UTC, MarcosSpessatto requested changes
Can we create a UI end-to-end test case to cover this scenario?

2024-03-13 11:56 UTC, MarcosSpessatto commented
> Can we create a UI end-to-end test case to cover this scenario?

This was not possible due to test framework limitations

2024-03-13 19:28 UTC, MarcosSpessatto submitted a review, later dismissed

2024-03-18 13:05 UTC, yash-rajpal approved these changes

2024-04-10 16:52 UTC, gabriellsh commented
Closing in favor of #32170

2024-04-10 16:52 UTC, closed without merging