chore: split scalability EE module into two
RocketChat/Rocket.Chat pull request #31942
Opened 2024-03-08 19:17 UTC by pierre-lehnen-rc

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-03-12 14:58 UTC, sampaiodiego requested changes
may you please change the module name to just `unlimited-presence`?

2024-03-12 20:40 UTC, geekgonecrazy approved these changes

2024-03-12 21:06 UTC, sampaiodiego submitted a review, later dismissed

2024-03-13 03:25 UTC, ggazzo submitted a review, later dismissed

2024-03-13 03:49 UTC, geekgonecrazy commented on ee/packages/presence/src/Presence.ts
> +			if (module === 'unlimited-presence') {
```suggestion
			if (module === 'unlimited-presence' || module === 'scalability') {
```

why not this and prevents breaking change?

2024-03-13 11:04 UTC, MarcosSpessatto reviewed
Shouldn't this be considered a `feat` instead of a `chore`?

2024-03-13 15:40 UTC, geekgonecrazy commented on ee/packages/presence/src/Presence.ts
> +			if (module === 'unlimited-presence') {
Though does mean would have to be updated in the other hasLicense place

2024-03-13 15:41 UTC, geekgonecrazy commented on ee/packages/presence/src/Presence.ts
> +			this.hasLicense = await License.hasModule('unlimited-presence');
Not sure the cleanest way here.  But if accepting the other to prevent breaking changes then would need to accept either here as well

2024-03-14 13:05 UTC, pierre-lehnen-rc commented
> Shouldn't this be considered a `feat` instead of a `chore`?

Maybe. I used `chore` because there's no feature change on the product itself - the feature is the same it's just activated by a different license module.

2024-03-14 13:06 UTC, pierre-lehnen-rc commented on ee/packages/presence/src/Presence.ts
> +			if (module === 'unlimited-presence') {
I've updated the code to add backwards compatibility

2024-03-15 00:24 UTC, geekgonecrazy approved these changes
LGTM

2024-03-18 14:20 UTC, ggazzo approved these changes

2024-03-18 15:03 UTC, merged