chore: Fix some check/lint warnings
RocketChat/Rocket.Chat pull request #32048
Opened 2024-03-21 17:03 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-04-04 10:09 UTC, MarcosSpessatto requested changes

2024-04-04 10:09 UTC, MarcosSpessatto commented on packages/livechat/src/components/Composer/index.tsx
> +	if (target?.nodeValue != null && isTargetFocused) {
```suggestion
	if (target?.nodeValue !== null && isTargetFocused) {
```

2024-04-05 11:29 UTC, MarcosSpessatto submitted a review, later dismissed

2024-04-05 20:35 UTC, tassoevan approved these changes

2024-04-09 12:19 UTC, MarcosSpessatto approved these changes

2024-04-09 14:43 UTC, tassoevan approved these changes

2024-04-09 17:34 UTC, merged