chore: bump apps engine version
RocketChat/Rocket.Chat pull request #32064
Opened 2024-03-25 18:21 UTC by AllanPazRibeiro

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-03-25 20:02 UTC, sampaiodiego requested changes

2024-03-25 20:02 UTC, sampaiodiego commented on .changeset/chatty-suits-dance.md
> +This updated version addresses issues with all applications utilizing the OAuth 2 library from Apps Engine, ensuring that apps like Google Drive and Google Calendar are operational once more.
```suggestion
Fix an issue affecting Rocket.Chat Apps utilizing the OAuth 2 library from Apps Engine, ensuring that apps like Google Drive and Google Calendar are operational once more.
```

2024-03-25 20:21 UTC, sampaiodiego approved these changes

2024-03-25 20:21 UTC, merged

2024-03-26 07:11 UTC, swat-ordbogen commented
Still issue with Google Calendar App

https://forums.rocket.chat/t/google-calendar-url-is-not-defined-at-oauth2client/19342

2024-03-26 18:03 UTC, sampaiodiego commented
hi @swat-ordbogen .. just making sure, did you update to 6.6.6 and still had the issue with the google calendar app?

2024-03-26 18:10 UTC, swat-ordbogen commented
> hi @swat-ordbogen .. just making sure, did you update to 6.6.6 and still had the issue with the google calendar app?

yes :-) 

Version
6.6.6
Apps Engine Version
1.41.1
Node Version
v14.21.3
Database Migration
304 (26. marts 2024 08:04)
MongoDB
6.0.6 / wiredTiger (oplog Enabled)