fix: Team mention triggering bot message for users not in room
RocketChat/Rocket.Chat pull request #32112
Opened 2024-04-02 16:08 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

Check if mention is for a team
## Issue(s)

[CORE-121](https://rocketchat.atlassian.net/browse/CORE-121)
## Steps to test or reproduce

## Further comments

2024-04-03 11:26 UTC, MarcosSpessatto requested changes

2024-04-03 11:26 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/message-mentions.spec.ts
> +				team = await createTargetTeam(api);
Is it possible to delete the created team afterAll?

2024-04-05 15:44 UTC, MarcosSpessatto approved these changes

2024-04-09 18:07 UTC, yash-rajpal approved these changes
LGTM!

2024-04-11 13:49 UTC, merged