fix!: Update statuses for stuck Omnichannel rooms via migration
RocketChat/Rocket.Chat pull request #32131
Opened 2024-04-04 15:49 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

Migration will do 3 steps:
- Remove the inquiries of closed rooms
- Update the status of inquiries that are queued, but the related room is already served
- Remove inquiries that point to a room that no longer exists

Since at the time a room is closed the inquiry is removed, we'll assume rooms that are already closed have all the data they require set, so we're only removing the inquiry to fix the status and unblock processing.

Queue will do the same steps for each of the inquiries it touches. Generally speaking, unless someone updates directly to this version or has been using manual selection all the time, this migration will do nothing.

2024-05-31 22:19 UTC, geekgonecrazy commented on apps/meteor/server/startup/migrations/v305.ts
> +		const closedRooms = await LivechatRooms.find({ closedAt: { $exists: true } }, { projection: { _id: 1 } }).toArray();
This query takes a long time for cases with a lot of omnichannel conversations.  Example with 1 million.

2024-05-31 22:21 UTC, geekgonecrazy commented on apps/meteor/server/startup/migrations/v305.ts
> +		const { deletedCount } = await LivechatInquiry.deleteMany({ rid: { $in: closedRooms.map((room) => room._id) } });
With same case above this could fail because of the size of the array being returned

2024-05-31 22:23 UTC, geekgonecrazy commented on apps/meteor/server/startup/migrations/v305.ts
> +		const openAndServedRooms = await LivechatRooms.find({ servedBy: { $exists: true } }, { projection: { _id: 1 } }).toArray();
Again will take a long time.  While servedBy does exist as index too with a lot of records this still takes a long time when has a lot of records

2024-05-31 22:23 UTC, geekgonecrazy requested changes
This will take a really long time to get responses from mongo on these queries for large omnichannel use cases

2024-06-03 13:44 UTC, KevLehman commented
Yep, that's a known thing, as i said over there, that's why this is still a draft 👀

2024-06-05 22:03 UTC, KevLehman commented
Closing as no longer needed

2024-06-05 22:03 UTC, closed without merging