feat: Add `CheckOption` on Omnichannel's departments multi selects
RocketChat/Rocket.Chat pull request #32193
Opened 2024-04-12 10:04 UTC by csuadev

Change the Option component in favor of CheckOption component to improve the UX to the end user and allow them to see already selected elements when using MultiSelects avoiding confusion when there are multiple items. 

## Proposed changes (including videos or screenshots)
Before: 
<img width="438" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/72958726/14eea247-17c3-4708-aaeb-02ce47466268">

<img width="666" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/72958726/27641a5e-cac3-4e47-8d0b-6747627d6128">

After: 
<img width="424" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/72958726/5511a006-24ab-4216-bf41-c52a94108ba5">

<img width="658" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/72958726/37f5b8dd-ce70-4998-88f0-26eddd3e51aa">

## Issue(s)
[https://rocketchat.atlassian.net/browse/SUP-400](https://rocketchat.atlassian.net/browse/SUP-400)

## Steps to test or reproduce

## Further comments

2024-04-12 13:37 UTC, dougfabris commented
what is a `CheckPoint` component man?

2024-04-24 13:22 UTC, MarcosSpessatto submitted a review, later dismissed

2024-04-26 17:04 UTC, jessicaschelly submitted a review, later dismissed

2024-04-29 13:30 UTC, MartinSchoeler submitted a review, later dismissed

2024-04-29 14:04 UTC, MartinSchoeler requested changes
Can you check the latest build, it seems there is a flaky test related to omnichannel units, let's check if its related to any of the changes done to tests in this PR

![Screenshot 2024-04-29 at 11 02 56](https://github.com/RocketChat/Rocket.Chat/assets/20868078/b674a151-3334-42de-bfec-ef69a6a77a3f)

2024-05-03 13:10 UTC, jessicaschelly submitted a review, later dismissed

2024-05-03 18:02 UTC, MarcosSpessatto requested changes

2024-05-03 18:02 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
> +		const department2 = await createDepartment(api);
Can we delete this department afterAll?

2024-05-07 14:29 UTC, dougfabris requested changes

2024-05-07 14:29 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
> +		await page.reload();
why reloading this page?

2024-05-07 14:29 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
> +			await poOmnichannelUnits.inputSearch.isVisible()
there's no need to await this input to be visible, the locator already does it

2024-05-07 14:29 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
> +			await test.step('expect to confirm delete', async () => {
these amount of stuff is unnecessary, left just the test on the list of units after deleting it

2024-05-07 14:29 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
> +		await page.reload();
why reloading it?

2024-05-08 16:02 UTC, dougfabris submitted a review, later dismissed

2024-05-08 16:55 UTC, MarcosSpessatto approved these changes

2024-05-09 00:48 UTC, dougfabris approved these changes

2024-05-09 13:07 UTC, MarcosSpessatto approved these changes

2024-05-09 13:52 UTC, KevLehman approved these changes

2024-05-09 14:19 UTC, jessicaschelly approved these changes

2024-05-09 14:29 UTC, merged