feat: added cloud workspace id to workspace statistics
RocketChat/Rocket.Chat pull request #32298
Opened 2024-04-23 13:22 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)
Added "Cloud Workspace ID" to the workspace statistics page.

![Screenshot 2024-04-23 at 10 16 49](https://github.com/RocketChat/Rocket.Chat/assets/6494543/9e1649e5-d5b9-4dad-a45f-af5f141f9435)

## Issue(s)

[CONN-124](https://rocketchat.atlassian.net/browse/CONN-124)

## Steps to test or reproduce
- Sign in
- Go to `Admin > Workspace`
- Should have "Cloud Workspace ID" in the list if available.

2024-04-25 05:04 UTC, tassoevan requested changes

2024-04-25 05:04 UTC, tassoevan commented on packages/i18n/src/locales/en.i18n.json
> +  "Cloud_Workspace_Id": "Cloud Workspace ID",
```suggestion
  "Cloud_Workspace_Id": "Rocket.Chat Cloud Workspace ID",
```

2024-04-25 05:04 UTC, tassoevan commented on packages/i18n/src/locales/pt-BR.i18n.json
> +  "Cloud_Workspace_Id": "ID do espaço de trabalho na nuvem",
```suggestion
  "Cloud_Workspace_Id": "ID do Espaço de Trabalho na Rocket.Chat Cloud",
```

2024-04-26 17:23 UTC, tassoevan approved these changes

2024-04-29 15:55 UTC, hugocostadev approved these changes

2024-05-02 14:17 UTC, merged