feat: `ReadReceiptIndicator` a11y improvement
RocketChat/Rocket.Chat pull request #32317
Opened 2024-04-25 23:40 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-04-26 01:07 UTC, tiagoevanp requested changes
Adding here for historical proposes. This proposal will have another improvements regarding the readiness of the `check/double check` state... waiting for that!

2024-04-26 12:10 UTC, MarcosSpessatto submitted a review, later dismissed

2024-04-27 00:41 UTC, tiagoevanp submitted a review, later dismissed

2024-05-16 15:10 UTC, ggazzo approved these changes

2024-05-16 15:56 UTC, merged