chore: Improve permissions check on groups endpoints
RocketChat/Rocket.Chat pull request #32332
Opened 2024-04-29 21:12 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Improve permissions check on `groups` endpoints by using the `permissionsRequired` property.

## Issue(s)

[CORE-339](https://rocketchat.atlassian.net/browse/CORE-339)

## Steps to test or reproduce

## Further comments

**The intention for this PR is to improve code readability and make unauthorized erros more standardized. No side effects are expected. We're considering this a breaking change since unauthorized errors are being changed to follow the same standard when possible.**

2024-05-06 19:10 UTC, KevLehman requested changes

2024-05-06 20:32 UTC, matheusbsilva137 commented on apps/meteor/app/api/server/v1/groups.ts
> +		authRequired: true,
We do have some tests already and I improved/fixed them [here](https://github.com/RocketChat/Rocket.Chat/pull/32332/files#diff-9f10141d5c3e967cd65a788b45104ae1379261de64c800ff856e4f8b16c1514fR1267)

2024-05-06 21:12 UTC, KevLehman submitted a review, later dismissed

2024-05-06 21:14 UTC, KevLehman commented on apps/meteor/app/api/server/v1/groups.ts
> +		authRequired: true,
Would be nice to cover this endpoint with more tests, but not sure if this task/PR is the proper place. Wanna create a new task for that?

2024-05-07 14:23 UTC, KevLehman approved these changes

2024-05-07 14:26 UTC, matheusbsilva137 commented on apps/meteor/app/api/server/v1/groups.ts
> +		authRequired: true,
Sure, I'll create a task
Tks man!

2024-05-07 15:54 UTC, merged