fix: Moderators with `Bypass Time limits` permission cannot edit messages
RocketChat/Rocket.Chat pull request #32376
Opened 2024-05-06 18:19 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-05-06 18:23 UTC, KevLehman commented
Note: the bypass actions are minimum 1min, so i decided to not to add UI tests on this one.

If you know a way i can do them, lmk 😄

2024-05-09 20:11 UTC, MarcosSpessatto requested changes
We have more usage of this permission check, can we verify if the same fix needs to be applicable for the other cases?

https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/methods/updateMessage.ts#L53
https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/views/room/contextualBar/RoomFiles/hooks/useMessageDeletionIsAllowed.ts#L12

We also have the same check on the server side.
https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/authorization/server/functions/canDeleteMessage.ts#L37
https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/lib/server/methods/updateMessage.ts#L56

Shouldn't this be fixed there as well?

Finally, can we add some UI tests to ensure this behavior? And the same for API if there are no tests yet?

2024-05-13 14:40 UTC, KevLehman commented
Hey, fixed the other places, thanks 🤗 i didn't notice we had that much usages of this permission.

On the tests part, i placed a comment just before yours 😬 about testability. Basically, for "testing" that the feature works, the minimum time allowed for this setting is 1min, and honestly I don't want to "wait" for one minute on the CI for testing this.

Was thinking on some Units, but since none of the files have Units, if we go this way, I'd prefer to have them as a separate task, wdyt?

2024-05-20 17:43 UTC, MarcosSpessatto approved these changes

2024-06-06 10:44 UTC, merged