fix: E2EE thread main message reactivity
RocketChat/Rocket.Chat pull request #32381
Opened 2024-05-07 18:53 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

The encrypted thread main message was having reactivity issues, and was not being decrypted properly. This PR fixes that by calling necessary functions to decrypt the thread main message in thread contextual bar.
## Issue(s)

## Steps to test or reproduce

## Further comments

[E2EE-16](https://rocketchat.atlassian.net/browse/E2EE2-16)

[E2EE-16]: https://rocketchat.atlassian.net/browse/E2EE-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-10 18:22 UTC, hugocostadev requested changes
LGTM, just missing a test 🫣

2024-06-12 16:56 UTC, MarcosSpessatto requested changes
Can we add a description to the PR please?

2024-06-16 17:53 UTC, MarcosSpessatto approved these changes

2024-06-17 14:14 UTC, hugocostadev approved these changes

2024-06-17 20:35 UTC, merged