fix: Monitors dissapearing from Unit upon edit
RocketChat/Rocket.Chat pull request #32393
Opened 2024-05-09 15:40 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-05-10 18:16 UTC, MarcosSpessatto submitted a review, later dismissed

2024-05-10 18:16 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
> +
Can we add a new test case removing one user from the list (of 2), save it, and see if it behaves correctly?

2024-05-14 20:50 UTC, dougfabris requested changes

2024-05-14 20:50 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
this amount of assertion checking if the elements are visible is really necessary?

eg: checking if the contextualBar is visible. Theres a step to to click in a button on contextualBar, the test you fail if its no visible, so what's the purpose of the assertion? I don't see a real value using this approach, kinda repetitive in my point of view

2024-05-14 21:25 UTC, KevLehman commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
Good question. IDK. I copied the pattern from the tests above it and adapted my checks 😬

2024-05-14 21:36 UTC, KevLehman commented on apps/meteor/tests/e2e/omnichannel/omnichannel-units.spec.ts
BUT, removed the unneeded expects

2024-05-14 22:17 UTC, dougfabris submitted a review, later dismissed
LGTM!

2024-05-17 13:49 UTC, KevLehman commented
Hey @dougfabris i forgot to add a changeset before, mind to review this one again? 😬

2024-05-17 13:50 UTC, dougfabris approved these changes

2024-05-17 20:10 UTC, MartinSchoeler approved these changes

2024-05-17 22:09 UTC, merged