fix: Link image preview not opening in gallery
RocketChat/Rocket.Chat pull request #32391
Opened 2024-05-09 04:47 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

Images preview provided by links will open in gallery mode when clicked

## Issue(s)

## Steps to test or reproduce

## Further comments

[SUP-570](https://rocketchat.atlassian.net/browse/SUP-570?atlOrigin=eyJpIjoiN2Y1NzUzZDIxY2QzNDJhYmFkMjU4ODFmNjc1YzE5MTkiLCJwIjoiaiJ9)

2024-05-09 19:50 UTC, MarcosSpessatto requested changes
Is there any way of adding some UI (or unit) tests to cover the fix?

2024-05-17 14:47 UTC, juliajforesti commented on apps/meteor/client/providers/ImageGalleryProvider.tsx
> +	const [imageUrl, setImageUrl] = useState<string>();
maybe a more descriptive name like `singleImagePreviewUrl` | `singleImageUrl` ...?

2024-05-17 17:13 UTC, MarcosSpessatto approved these changes

2024-05-17 18:55 UTC, juliajforesti approved these changes

2024-05-17 21:32 UTC, merged