feat: Add LDAP group validation strategy setting to channels and roles sync
RocketChat/Rocket.Chat pull request #32436
Opened 2024-05-14 20:37 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

- Added "Group membership validation strategy" settings to "Sync Channels" and "Sync Roles" LDAP sections -- they may enable a **faster** sync process when combined with a good LDAP search filter;

**Available strategies:**
 - **Apply filter for each group**: apply the LDAP user group filter for each group (key) defined in the LDAP group channel map. This is slower, but can be useful in case you need to use the `#{groupName}` replacement tag to define membership (e.g. when filtering by the `memberOf` field in groups);
 - **Apply filter once to get all memberships**: apply the LDAP user group filter once for each user. A given user will be considered a member of all groups returned by the LDAP search. This is a **faster** option that can be applied in case the `#{groupName}` replacement tag is not used by the filter (e.g. when filtering by the `member` field in groups).

## Issue(s)

## Steps to test or reproduce

The new "Group membership validation strategy" setting is available under both "Sync Channels" and "Sync Roles" sections in LDAP Premium settings. Both features should work just the same as in previous version when using the default "Apply filter for each group" search strategy or the new and faster "Apply filter once to get all memberships" strategy -- the only difference here is the amount of LDAP search requests triggered by RC.

<details>
  <summary><strong>Sample configuration</strong></summary>
  
<strong>Sample configuration for using the "Apply filter once to get all memberships" search strategy:</strong>
![Captura de tela de 2024-05-14 17-09-13](https://github.com/RocketChat/Rocket.Chat/assets/36537004/e06825ab-86e3-4866-bde6-ce32a97636e0)

<strong>Sample configuration for using the "Apply filter for each group" search strategy:</strong>
![Captura de tela de 2024-05-14 17-09-51](https://github.com/RocketChat/Rocket.Chat/assets/36537004/f20377e5-40ce-4b3e-8471-c7accab8fbfa)
  
</details>

> [!CAUTION]
> Switching to the new and faster "Apply filter once to get all memberships" search strategy may not work with the currently configured LDAP search filter!
> When switching to the new strategy, make sure to update the user group filter so as to get **all groups at once** in a single query with it

## Further comments

[CORE-402](https://rocketchat.atlassian.net/browse/CORE-402)

2024-05-17 15:42 UTC, pierre-lehnen-rc requested changes
~~The PR should still be flagged as a breaking change since it'll no longer be possible to use both strategies at the same time.~~

~~There should also be a migration to select the right strategy automatically if only one of them is currently being used.~~

Ignore this review, I see now that the PR is making a different change than the one we had discussed last time.

2024-05-17 17:35 UTC, pierre-lehnen-rc approved these changes

2024-05-17 17:42 UTC, matheusbsilva137 commented on apps/meteor/ee/server/lib/ldap/Manager.ts
> +			logger.error(`The following LDAP teams are not mapped in Rocket.Chat: "${unmappedLdapGroups.join(', ')}".`);
Oops, thank you!

2024-05-20 15:04 UTC, pierre-lehnen-rc approved these changes

2024-06-21 02:38 UTC, merged