feat: E2EE room setup header
RocketChat/Rocket.Chat pull request #32446
Opened 2024-05-16 11:30 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

[E2EE-27](https://rocketchat.atlassian.net/browse/E2EE2-27)

2024-05-20 19:12 UTC, hugocostadev submitted a review, later dismissed

2024-06-11 18:09 UTC, MarcosSpessatto requested changes

2024-06-11 18:09 UTC, MarcosSpessatto commented on apps/meteor/client/views/room/Header/Header.tsx
> +	if (room.t === 'd' && (room.uids?.length ?? 0) < 3) {
There is a helper for this check `isDirectMessageRoom`: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/core-typings/src/IRoom.ts#L139

Also, what uids being greater than 3 mean? Would it be better to have this in a named variable maybe?

2024-06-11 18:09 UTC, MarcosSpessatto commented on apps/meteor/client/views/room/Header/RoomHeaderE2EESetup.tsx
> +	if (room.t === 'd' && (room.uids?.length ?? 0) < 3) {
Let's use the helper here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/core-typings/src/IRoom.ts#L139

Also, what uids being greater than 3 mean? Would it be better to have this in a named variable maybe?

2024-06-12 16:59 UTC, MarcosSpessatto commented on .changeset/gold-flowers-shake.md
> +'@rocket.chat/meteor': patch
```suggestion
'@rocket.chat/i18n': minor
'@rocket.chat/meteor': minor
```

2024-06-12 16:59 UTC, MarcosSpessatto commented on apps/meteor/client/views/room/Header/Header.tsx
> +	const unencryptedMessagesAllowed = useSetting('E2E_Allow_Unencrypted_Messages');
```suggestion
	const unencryptedMessagesAllowed = useSetting<boolean>('E2E_Allow_Unencrypted_Messages');
```

2024-06-16 17:54 UTC, MarcosSpessatto approved these changes

2024-06-17 12:09 UTC, hugocostadev approved these changes

2024-06-17 21:28 UTC, merged