chore: Change UserInfo.tsx to subcomponents
RocketChat/Rocket.Chat pull request #32470
Opened 2024-05-22 20:33 UTC by rique223

## Proposed changes (including videos or screenshots)

Changed the UserInfo.tsx components from dot notation to subcomponents
## Issue(s)

## Steps to test or reproduce

## Further comments

2024-06-21 19:14 UTC, dougfabris submitted a review, later dismissed
Do you mind changing this notation to all places that uses InfoPanel subcomponents, so we can remove the exported object from `apps/meteor/client/components/InfoPanel/index.ts`

also prefer using `import { subComponents } from '../InfoPanel/'`

Btw, why so many commits?

2024-06-21 19:23 UTC, rique223 commented
> Do you mind changing this notation to all places that uses InfoPanel subcomponents, so we can remove the exported object from `apps/meteor/client/components/InfoPanel/index.ts`
> 
> also prefer using `import { subComponents } from '../InfoPanel/'`
> 
> Btw, why so many commits? 

Sure, will do. About the commits I am not entirely sure, this branch was checked out of the feat/new-user-panel-pending branch that was recently merged and when it happened git automatically rebased this branch to the develop and duplicated a lot of the commits that were merged in the other branch. I assumed that since the git diff is correct it wouldn't be a problem, but if there's anyway to remove those commits I'd like do know, I'll do a little research on this as well.

2024-06-21 19:43 UTC, tassoevan approved these changes

2024-06-21 22:28 UTC, rique223 commented
> > Do you mind changing this notation to all places that uses InfoPanel subcomponents, so we can remove the exported object from `apps/meteor/client/components/InfoPanel/index.ts`
> > also prefer using `import { subComponents } from '../InfoPanel/'`
> > Btw, why so many commits?
> 
> Sure, will do. About the commits I am not entirely sure, this branch was checked out of the feat/new-user-panel-pending branch that was recently merged and when it happened git automatically rebased this branch to the develop and duplicated a lot of the commits that were merged in the other branch. I assumed that since the git diff is correct it wouldn't be a problem, but if there's anyway to remove those commits I'd like do know, I'll do a little research on this as well.

For Future Reference:

The problem Doug mentioned was caused by squash merging the feat/new-user-panel-pending branch. When a branch is squash merged, all the commits in the pull request (PR) are combined into a single commit on the base branch. Because of this, Git loses the ability to track the individual commits from the original branch. If a child branch was created from the feat/new-user-panel-pending branch before the squash merge, it still contains those individual commits. As a result, when the child branch is compared or a PR is created from it, Git will not recognize that those commits were already merged, leading to duplicate commit history in the PR just like happened here;

2024-06-24 15:48 UTC, tassoevan submitted a review, later dismissed

2024-06-24 18:22 UTC, aleksandernsilva submitted a review, later dismissed

2024-06-24 20:13 UTC, tiagoevanp requested changes

2024-06-24 20:13 UTC, tiagoevanp commented on apps/meteor/client/components/UserInfo/index.ts
> +export { UserInfo, UserInfoAction, UserInfoAvatar, InfoPanelText as UserInfoText, InfoPanelLabel as UserInfoLabel, UserInfoUsername };
Why not export directly? Like:

`export { default as UserInfo } from './UserInfo';`

And why InfoPanel components are importing to export with another name? How about to have one single generic component on top of both places used by the User and Panel? InfoText and InfoLabel?

2024-06-25 15:24 UTC, tiagoevanp approved these changes

2024-06-25 19:09 UTC, tassoevan approved these changes

2024-06-26 19:12 UTC, aleksandernsilva approved these changes

2024-07-05 18:05 UTC, dougfabris requested changes

2024-07-05 18:05 UTC, dougfabris commented on apps/meteor/client/components/InfoPanel/InfoPanel.stories.tsx
> -// export const Archived = () => <Contextualbar height={800}>
??

2024-07-05 18:06 UTC, dougfabris approved these changes

2024-07-09 17:56 UTC, merged