refactor!: removed roomNameExists method
RocketChat/Rocket.Chat pull request #32484
Opened 2024-05-23 21:12 UTC by abhinavkrin

## Proposed changes (including videos or screenshots)

Removed roomNameExists method as it has been replaced by rooms.nameExists endpoint
## Issue(s)

## Steps to test or reproduce

## Further comments

[CORE-351](https://rocketchat.atlassian.net/browse/CORE-351)

2024-05-24 12:00 UTC, MarcosSpessatto requested changes
Can we take a look at this test case? I think there's something weird since it's expecting an error when no room is found...

https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/tests/end-to-end/api/09-rooms.js#L425

2024-06-03 10:59 UTC, abhinavkrin commented
> Can we take a look at this test case? I think there's something weird since it's expecting an error when no room is found...
> 
> https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/tests/end-to-end/api/09-rooms.js#L425

I looked at it, the test was for an invalid roomId which should not be there as we dont accept a roomId for this endpoint.
So I changed this test to check for invalid params which makes the test more clear.
Also, I added a test to check if false is returned if roomName is not found.

2024-06-03 20:16 UTC, MarcosSpessatto requested changes

2024-06-03 20:16 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/09-rooms.js
> +		it('should return an error when send an invalid param', (done) => {
```suggestion
		it('should return an error when the require parameter (roomName) is not provided', (done) => {
```

2024-06-07 18:53 UTC, MarcosSpessatto approved these changes

2024-08-17 00:46 UTC, ggazzo approved these changes

2024-08-17 00:47 UTC, merged