fix: Blocked login when dismissed 2FA modal
RocketChat/Rocket.Chat pull request #32482
Opened 2024-05-23 20:28 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

Fix infinite loading button in login page when 2FA dismissed.
PR introduces the possibility of a function trigger to Modal dismiss (outside click and escape key).

Before:
![bad](https://github.com/RocketChat/Rocket.Chat/assets/17487063/b49e5450-a470-4e8f-9ed8-dbe3c5897f99)

After:
![cool](https://github.com/RocketChat/Rocket.Chat/assets/17487063/ed8b3ac1-18c8-4d7f-9e21-fa4f1d92d72a)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-05-24 11:52 UTC, MarcosSpessatto requested changes
I know the steps to reproduce the issue are complex, but would it be possible to add some UI tests to ensure the behavior? Executing exactly the steps you attached in the GIF, enabling 2FA, typing user name and pass, pressing ESC, and checking if the login button is enabled?

2024-05-24 11:52 UTC, MarcosSpessatto commented on .changeset/soft-donkeys-thank.md
> +fix blocked login when dismissed 2FA modal by clicking outside of it or pressing escape key
```suggestion
Fixed an issue with blocked login when dismissed 2FA modal by clicking outside of it or pressing the escape key
```

2024-07-05 11:35 UTC, MarcosSpessatto approved these changes

2024-07-08 17:09 UTC, tassoevan submitted a review, later dismissed

2024-07-17 19:17 UTC, tassoevan approved these changes

2024-07-19 19:36 UTC, merged