fix: Force highlighted code language registration
RocketChat/Rocket.Chat pull request #32507
Opened 2024-05-27 23:15 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-05-30 16:52 UTC, MarcosSpessatto requested changes
Can we add a PR description?

2024-05-30 16:52 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/administration.spec.ts
> +			await setSettingValueById(api, 'Message_Code_highlight', messageCodeHighlightDefault)
Can we set the "real" default value here instead of the value before the executed test?

2024-06-03 13:32 UTC, MarcosSpessatto approved these changes

2024-06-03 14:20 UTC, yash-rajpal submitted a review, later dismissed
LGTM!

2024-06-03 18:07 UTC, MarcosSpessatto submitted a review, later dismissed

2024-06-17 13:42 UTC, MarcosSpessatto approved these changes

2024-06-17 14:00 UTC, yash-rajpal approved these changes

2024-06-17 14:46 UTC, merged