chore!: Remove `meteor/check` from `cloud` endpoints
RocketChat/Rocket.Chat pull request #32533
Opened 2024-05-31 18:16 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Remove `meteor/check` from `cloud` endpoints by using the `validateParams` property.

## Issue(s)

[CORE-317](https://rocketchat.atlassian.net/browse/CORE-317)

## Steps to test or reproduce

## Further comments

**The intention for this PR is to improve code readability and make invalid params errors more standardized. No side effects are expected. We're considering this a breaking change since invalid params errors are being changed to follow the same standard when possible.**

2024-06-03 14:02 UTC, MarcosSpessatto requested changes
Can we create some API tests to validate at least the cases without the expected parameters? Since successful cases are not possible at this time...

2024-06-07 20:04 UTC, MarcosSpessatto approved these changes

2024-08-15 20:17 UTC, ggazzo submitted a review, later dismissed

2024-08-15 20:23 UTC, KevLehman approved these changes

2024-08-16 17:59 UTC, ggazzo approved these changes

2024-08-16 18:55 UTC, KevLehman approved these changes

2024-08-17 00:44 UTC, merged