chore: Disable slash commands for encrypted rooms
RocketChat/Rocket.Chat pull request #32548
Opened 2024-06-03 20:08 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

Currently, several apps and bots don’t work properly in E2EE rooms
So, it is needed to make clear to users that it is not possible to use apps and slash commands if E2EE is enabled in the room.
## Issue(s)

## Steps to test or reproduce

## Further comments

[E2EE-24](https://rocketchat.atlassian.net/browse/E2EE2-24)

2024-06-05 05:51 UTC, geekgonecrazy commented
don't some slash commands work just fine?  Like those that generate google meet etc.  The messages generated of course aren't encrypted.. but won't it still work?

2024-06-05 14:32 UTC, yash-rajpal commented
You are right @geekgonecrazy but in latest versions we introduced a new setting and behavior that un-encrypted messages won't be allowed in encrypted rooms.

Also, currently we have no way of knowing which apps and slash-commands won't work with encrypted messages and channels, so we decided to block all apps and slashcommands.

2024-06-07 13:27 UTC, hugocostadev commented
I also think that we need to revisit this, maybe encrypt messages sent by apps/bots if the settings that allow unencrypted messages are disabled.

2024-06-07 13:30 UTC, hugocostadev requested changes
Allow bots and apps if the "Unencrypted messages in encrypted rooms" is enabled

2024-06-10 16:07 UTC, yash-rajpal commented
> I also think that we need to revisit this, maybe encrypt messages sent by apps/bots if the settings that allow unencrypted messages is enabled

I don't think that is something possible with current architecture. Also, we don't want to provide slash commands even if sending un-encrypted messages are allowed because, the room may contain encrypted messages and apps/bots won't play nice with such messages.

2024-06-10 18:36 UTC, hugocostadev requested changes
LGTM, but it's missing tests too 🫣

2024-06-11 16:25 UTC, hugocostadev requested changes
Slash commands are not working in not encrypted channels/DMs

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/1afb65a9-e3fe-4745-970a-bc34bb6b76ef)

2024-06-11 16:56 UTC, yash-rajpal commented on apps/meteor/tests/e2e/e2e-encryption.spec.ts
> +			await expect(page.locator('#popup-item-contextualbar')).toHaveClass(/disabled/)
had already fixed 🤔

2024-06-12 19:25 UTC, hugocostadev submitted a review, later dismissed

2024-06-19 15:44 UTC, hugocostadev approved these changes

2024-06-19 19:46 UTC, merged