chore: Disable some message menu items for encrypted messages.
RocketChat/Rocket.Chat pull request #32559
Opened 2024-06-05 09:37 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

Currently, it is not possible to properly share the content of encrypted messages outside the room.The forwarded message, message link, or quote appears in the destination room as a hash.
So, it is needed to make clear to users that it is not possible to share encrypted messages content.

<img width="275" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/58601732/1e12cdfb-0c1a-430a-850b-538952d1d0df">

## Issue(s)

## Steps to test or reproduce

## Further comments

[E2EE2-25](https://rocketchat.atlassian.net/browse/E2EE2-25)

2024-06-10 18:40 UTC, hugocostadev requested changes
Missing tests 🫣

You can create just one test to check disabled items

2024-06-10 18:40 UTC, hugocostadev commented on .changeset/plenty-buses-kneel.md
> +Disable some message menu items for encrypted messages as they don't apply to encrypted messages and also disable apps menu items and show a warning.
Since this is user focus, add the items that were disable, please

2024-06-10 19:04 UTC, hugocostadev requested changes
Would be nice to have the tooltip instead of the title of the action, and a tooltip in the disabled buttons too :D 

And add tests, please 🫣

2024-06-13 12:01 UTC, yash-rajpal commented on packages/i18n/src/locales/en.i18n.json
> +  "Not_available_for_encrypted_messages": "Not available for encrypted messages",
Was left out by mistake, removed it.

2024-06-17 14:13 UTC, hugocostadev submitted a review, later dismissed

2024-06-19 15:45 UTC, hugocostadev approved these changes

2024-06-19 19:37 UTC, hugocostadev approved these changes

2024-06-19 22:30 UTC, merged