Fix(Omnichannel): Contact Center sort by date
RocketChat/Rocket.Chat pull request #32566
Opened 2024-06-06 20:00 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

[SUP-578](https://rocketchat.atlassian.net/browse/SUP-578)

2024-06-11 13:41 UTC, MarcosSpessatto requested changes
Can we add a description and a changeset to the PR?

Also, it would be awesome to have a UI test covering the solution, do you think it's possible to add it?

2024-06-11 16:20 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
I know the pain, but is good to have the proper lint formation for the files, take the advantage of adjusting this in a simple PR like this sounds ok to me... I don't think is really hard to see what is formatting vs related changes I mean...

2024-06-14 13:40 UTC, tiagoevanp commented
About the UI test: It's very expensive to create another test than the API integration one and there is no necessity of testing in the UI the same thing was tested from integration (if the API result is right). The fix here is not in the UI, but the API not receiving the right query string parameters.

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +	const userId = agentCredentials ? agentCredentials['X-User-Id'] : credentials['X-User-Id'];
```suggestion
    const userId = agentCredentials ? agentCredentials['X-User-Id'] : credentials['X-User-Id'];
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> + */
```suggestion
*/
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +	departmentId,
```suggestion
    departmentId,
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +	departmentId?: string;
```suggestion
    departmentId?: string;
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +	agent?: IUserCredentialsHeader;
```suggestion
    agent?: IUserCredentialsHeader;
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +		await updateSetting('Livechat_Routing_Method', 'Manual_Selection');
```suggestion
    const currentRoutingMethod = await getSettingValueById('Livechat_Routing_Method');
    let routingMethodChanged = false;
    if (currentRoutingMethod !== 'Manual_Selection') {
        await updateSetting('Livechat_Routing_Method', 'Manual_Selection');
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +	}
```suggestion
        // wait for routing algorithm to stop
        await sleep(1000);
    }
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +		await updateSetting('Livechat_Routing_Method', currentRoutingMethod);
```suggestion
    if (routingMethodChanged) {
        await updateSetting('Livechat_Routing_Method', currentRoutingMethod);
```

2024-06-14 14:10 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
> +	}
```suggestion
        // wait for routing algorithm to start
        await sleep(1000);
    }
```

2024-06-14 14:11 UTC, tiagoevanp commented on apps/meteor/tests/data/livechat/rooms.ts
Since there is a PR fixing prettier for tests, reverting all

2024-06-16 15:53 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
> +		await updateSetting('Livechat_enabled', false);
```suggestion
		await updateSetting('Livechat_enabled', true);
```

2024-06-18 20:30 UTC, MarcosSpessatto approved these changes

2024-06-19 13:57 UTC, dougfabris approved these changes
LGTM!

2024-06-19 14:40 UTC, merged