refactor!: removed setAsset, unsetAsset, refreshClients method
RocketChat/Rocket.Chat pull request #32564
Opened 2024-06-05 19:05 UTC by abhinavkrin

Removed setAsset, unsetAsset, refreshClients method as they are now replaced with assets.setAsset and assets.unsetAsset endpoint

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

[CORE-356](https://rocketchat.atlassian.net/browse/CORE-356)

2024-06-10 13:13 UTC, MarcosSpessatto requested changes

2024-06-14 11:40 UTC, abhinavkrin commented on apps/meteor/app/assets/server/assets.ts
> +	public async setAsset(binaryContent: string | Buffer, contentType: string, asset: string): Promise<void> {
Agreed, creating separate methods will improve clarity and maintainability. I have refactored accordingly.

2024-06-16 16:36 UTC, MarcosSpessatto approved these changes

2024-08-17 00:42 UTC, ggazzo approved these changes

2024-08-17 00:43 UTC, merged