fix: Inconsistent Markdown Formatting in Custom Status Field
RocketChat/Rocket.Chat pull request #32574
Opened 2024-06-08 16:19 UTC by Kishn0109

## Proposed changes (including videos or screenshots)

https://github.com/RocketChat/Rocket.Chat/assets/85572761/808e9770-590d-45dc-a33d-519049c8b8f3

## Issue(s)

#32544

## Steps to test or reproduce

1. Navigate to the Profile section.
2. Enter a Custom Status using * (asterisk) and _ (underscore) signs.
3. Observe that the text enclosed within * (asterisk) marks will be displayed in bold

## Further comments

For now, I have successfully tested this with input containing * (asterisk) and _ (underscore) signs. It would be better if I could have more test cases.

2024-06-11 17:45 UTC, Kishn0109 commented
https://github.com/RocketChat/Rocket.Chat/assets/85572761/8e47fbaf-0133-428d-af81-6370686bfa56

@csuadevI have test the updated code with the specified markdown inputs to ensure all cases are handled correctly.

2024-06-12 12:51 UTC, MarcosSpessatto requested changes
Can we add tests to ensure the behavior? cc @csuadev

2024-06-12 12:51 UTC, MarcosSpessatto commented on .changeset/kind-drinks-joke.md
> +'@rocket.chat/meteor': major
```suggestion
'@rocket.chat/meteor': patch
```

2024-08-15 15:58 UTC, MarcosSpessatto approved these changes

2024-08-21 03:05 UTC, merged