chore!: remove deprecated meteor eraseRoom method
RocketChat/Rocket.Chat pull request #32648
Opened 2024-06-20 19:39 UTC by AllanPazRibeiro

## Proposed changes (including videos or screenshots)
This PR removes the eraseRoom to use the room.delete endpoint

## Issue(s)

[CORE-350](https://rocketchat.atlassian.net/browse/CORE-350)

## Steps to test or reproduce

## Further comments

[CORE-350]: https://rocketchat.atlassian.net/browse/CORE-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-21 11:27 UTC, abhinavkrin requested changes
I think we should also move away from using `Meteor.Error` in the `eraseRoom` function and instead use `Error` object. This will be a step from moving away from meteor. Wdys?

intead of
https://github.com/RocketChat/Rocket.Chat/blob/2d06f5e986edc5f5b6fb9c332009f7ec4f8b69b8/apps/meteor/server/methods/eraseRoom.ts#L14
using
```
throw new Error('error-invalid-room')
```

2024-08-15 20:20 UTC, ggazzo commented
> I think we should also move away from using `Meteor.Error` in the `eraseRoom` function and instead use `Error` object. This will be a step from moving away from meteor. Wdys?
> 
> intead of
> 
> https://github.com/RocketChat/Rocket.Chat/blob/2d06f5e986edc5f5b6fb9c332009f7ec4f8b69b8/apps/meteor/server/methods/eraseRoom.ts#L14
> 
> 
> using
> ```
> throw new Error('error-invalid-room')
> ```

Meteor error and Error are handled differently by the api, `Error` is not exposed to final users.

2024-08-15 20:22 UTC, ggazzo approved these changes

2024-08-16 17:41 UTC, ggazzo submitted a review, later dismissed

2024-08-16 22:49 UTC, KevLehman approved these changes

2024-08-17 00:32 UTC, merged