fix(UiKit): Modal validation not working
RocketChat/Rocket.Chat pull request #32679
Opened 2024-06-26 19:12 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

Bring back modal validations response to inputs:

<img width="680" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/17487063/88006b2a-4e66-4eae-917d-bfca84e2230c">

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-06-27 13:16 UTC, MarcosSpessatto requested changes
Can we add tests to ensure it?

2024-07-05 11:40 UTC, MarcosSpessatto approved these changes

2024-07-17 19:42 UTC, MarcosSpessatto approved these changes

2024-07-19 16:54 UTC, MartinSchoeler requested changes

2024-07-19 16:54 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/apps/apps-modal.spec.ts
> +		page = await browser.newPage();
Close this page after all

2024-07-19 16:54 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/apps/apps-contextualbar.spec.ts
> +		page = await browser.newPage();
Close this page after all

2024-07-19 16:54 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/page-objects/fragments/home-content.ts
> +		await this.page.locator('[name="msg"]').fill(text);
if these are not required in this PR, lets remove it and add in a new one

2024-07-19 17:01 UTC, MartinSchoeler approved these changes

2024-07-22 03:47 UTC, merged