feat: Added Creation Date col in Rooms Table in Admin Panel.
RocketChat/Rocket.Chat pull request #32709
Opened 2024-07-02 08:54 UTC by heet434

## Proposed changes (including videos or screenshots)
Added a column that displays the room creation date. 
<img width="1512" alt="Screenshot 2024-07-02 at 2 16 14 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/118350153/f252cc33-2e4e-45b6-889f-e705462e0450">

Also added a ts field to retrieve the creation date from the database.

## Issue(s)

Here's the link: https://github.com/RocketChat/feature-requests/issues/893

## Steps to test or reproduce

Open the Rooms section in Admin Panel. Need for a creation date column there.

## Further comments

2024-07-02 16:51 UTC, hugocostadev commented
> Hi @hugocostadev , I have resolved the typecheck and lint errors, and used the useFormatDate function for formatting the date, but I can't find out as to what exactly is failing the unit test in @rocket.chat/license:testunit . Could you please help me out here?

Hey @heet434 I'll review it again! Thanks! 

Related to the unit test, don't worry... it's expected, we are going to fix this internally

2024-07-02 16:58 UTC, heet434 commented
> > Hi @hugocostadev , I have resolved the typecheck and lint errors, and used the useFormatDate function for formatting the date, but I can't find out as to what exactly is failing the unit test in @rocket.chat/license:testunit . Could you please help me out here?
> 
> Hey @heet434 I'll review it again! Thanks!
> 
> Related to the unit test, don't worry... it's expected, we are going to fix this internally

@hugocostadev  Thank you! I'll add the commits that resolve the prev issue.

2024-07-02 18:36 UTC, hugocostadev requested changes

2024-07-02 19:32 UTC, heet434 commented on apps/meteor/client/views/admin/rooms/RoomsTable.tsx
> +								<RoomRow key={room._id} room={{ ...room, ts: room.ts ? new Date(room.ts) : undefined }} />
Hi, thank you for the review. If I remove the constructor, typescipt starts throwing type errors as the 'ts' is taken in as a string initially, and if I use 'Date | string' as its type when defining the type in IRoom.ts, there's again another type error in another file. Is there a quick fix for this?
<img width="789" alt="Screenshot 2024-07-03 at 12 17 29 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/118350153/cfb3fc49-c5a7-4f41-88d3-e786d27f3cfd">
<br/>
And here's the error listed after running yarn turbo run typecheck.
<img width="1180" alt="Screenshot 2024-07-03 at 12 58 05 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/118350153/251e36ec-078b-4373-b8a0-d2a8b480b4b9">

2024-07-03 13:25 UTC, hugocostadev commented on apps/meteor/client/views/admin/rooms/RoomsTable.tsx
> +								<RoomRow key={room._id} room={{ ...room, ts: room.ts ? new Date(room.ts) : undefined }} />
Yep @heet434 indeed this TS error appears...
This happens due to the JSON deserialization, the JS transforms type Date to String in the process... 

I'll do a commit that simulates this and bypass this error

2024-07-03 16:14 UTC, heet434 commented on apps/meteor/client/views/admin/rooms/RoomsTable.tsx
> +								<RoomRow key={room._id} room={{ ...room, ts: room.ts ? new Date(room.ts) : undefined }} />
Okay thank you @hugocostadev , is there anything else I should change or add ?

2024-07-03 17:11 UTC, hugocostadev commented on apps/meteor/client/views/admin/rooms/RoomsTable.tsx
> +								<RoomRow key={room._id} room={{ ...room, ts: room.ts ? new Date(room.ts) : undefined }} />
No need! Thanks

2024-07-04 15:39 UTC, hugocostadev submitted a review, later dismissed

2024-07-15 19:44 UTC, hugocostadev approved these changes

2024-07-18 14:44 UTC, tassoevan approved these changes

2024-08-21 03:00 UTC, merged