chore: Replicate IPreRoomUserLeave and IPostRoomUserLeave event in meteor method and added removedBy to IRoomUserLeaveContext
RocketChat/Rocket.Chat pull request #32724
Opened 2024-07-04 22:38 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

[CORE-498](https://rocketchat.atlassian.net/browse/CORE-498)
Depends on https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/779
## Steps to test or reproduce

## Further comments

2024-07-10 00:06 UTC, d-gubert submitted a review, later dismissed

2024-07-10 00:08 UTC, d-gubert commented
This doesn't strictly require the PR on the Apps-Engine side, it will trigger the event in the new place and send the new context, even if the app won't get to see the info yet. We can treat those as separate (it does not need to wait for the new alpha version of the apps-engine and then update)

2024-07-11 13:32 UTC, pierre-lehnen-rc requested changes

2024-07-11 17:00 UTC, pierre-lehnen-rc approved these changes

2024-07-11 18:19 UTC, d-gubert approved these changes

2024-07-11 20:13 UTC, d-gubert requested changes
Just missing the change set

2024-07-12 17:18 UTC, pierre-lehnen-rc approved these changes

2024-07-16 03:07 UTC, merged