fix: validate username before registering user
RocketChat/Rocket.Chat pull request #32743
Opened 2024-07-08 13:32 UTC by ricardogarim

As per [CORE-544](https://rocketchat.atlassian.net/browse/CORE-544) and as discussed internally at [#rocketchat-dev](https://open.rocket.chat/channel/rocketchat-dev?msg=zGLpHpcKHLAJ65WBL), creating a new user with an invalid username (containing special characters) results in an error message, but the user is still created. This leads to an error when attempting to register again using the same email, as it is already registered.

To address this issue, I introduced a new method to validate usernames before registering users, ensuring that invalid usernames prevent user creation.

https://github.com/RocketChat/Rocket.Chat/assets/9621276/c6fa6408-bde5-4cf4-9c25-701b47d9a796

[CORE-544]: https://rocketchat.atlassian.net/browse/CORE-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-10 12:34 UTC, MarcosSpessatto requested changes
I think there are more places that require this change to be applied (or at least reviewed)...

https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/server/methods/registerUser.ts#L31 is one of them, but I think we should revisit all the places where users are being created, like LDAP, SAML, admin panel, etc.

2024-07-10 12:34 UTC, MarcosSpessatto commented on apps/meteor/app/lib/server/functions/validateUsername.ts
> +	const usernameRegExp = settingsRegExp ? new RegExp(`^${settingsRegExp}$`) : new RegExp('^[0-9a-zA-Z-_.]+$');
I think an invalid regex could throw an error here, right?

2024-07-10 12:34 UTC, MarcosSpessatto commented on apps/meteor/app/lib/server/functions/validateUsername.ts
> +export const validateUsername = (username: string): boolean => {
Can we create a unit test for this?

2024-08-16 20:44 UTC, KevLehman requested changes
add a changeset

2024-08-16 20:44 UTC, KevLehman commented on apps/meteor/tests/unit/app/lib/server/functions/validateUsername.spec.ts
> +			return null;
You can declare a stub for this (with sinon) and then use `stub.withArgs('UTF...').returns('')`

2024-08-16 20:44 UTC, KevLehman commented on apps/meteor/tests/unit/app/lib/server/functions/validateUsername.spec.ts
> +			proxySettings.settings.get = (key: string) => {
Use an stub

2024-08-20 20:03 UTC, KevLehman approved these changes

2024-08-21 12:03 UTC, MarcosSpessatto approved these changes

2024-08-21 21:01 UTC, merged