fix: use correct setting object for cache when not actually overwritten
RocketChat/Rocket.Chat pull request #32742
Opened 2024-07-08 12:19 UTC by debdutdeb

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-07-12 14:35 UTC, KevLehman commented on apps/meteor/ee/tests/unit/server/settings/SettingsRegistry.spec.ts
settingsregistry is ce but your tests are on ee 🤔 expected?

2024-07-12 14:40 UTC, debdutdeb commented on apps/meteor/ee/tests/unit/server/settings/SettingsRegistry.spec.ts
ouch no :p

2024-07-17 12:32 UTC, ggazzo requested changes
IMO too many modifications to a simple regression. the fix/regression has by far more changes than the original fix.

To be honest, I can't understand exactly what error is being corrected. I didn't find explanations in the task or in the pull request. It seems to me that the original correction was not so correct?

The only thing that catches my attention is the 
```
const settingFromCodeOverwritten = overwriteSetting(settingFromCode);
const settingOverwrittenDefault = overrideSetting(settingFromCode);
```
and then
```
const updatedSettingAfterApplyingOverwritten = isOverwritten ? settingFromCodeOverwritten : settingOverwrittenDefault;
```

In my idea, both should have the same value

I would like to see a revert of what was done and the same correction again on top of the original code, this way the original code is completely modified, to the point that I no longer remember that we wanted to update the cache at the time of the overwrite

2024-07-17 12:32 UTC, ggazzo commented on apps/meteor/app/settings/server/SettingsRegistry.ts
> +// NOTE(debdut): not really "metadata" - but yeah. I don't have a better name
I don't think this is in any way relevant or useful to the codebase

2024-07-17 12:32 UTC, ggazzo commented on apps/meteor/tests/unit/app/settings/server/functions/settings.tests.ts
> -		const settingsRegistry = new SettingsRegistry({ store: settings, model: Settings as any });
Let's keep each test with its instance? to ensure it does exactly what it's supposed to do without interference? you can also test the clear cases, but as a specific case

2024-07-17 12:32 UTC, ggazzo commented on apps/meteor/app/settings/server/SettingsRegistry.ts
> +export const compareSettingsMetadata = compareSettingsIgnoringKeys([
keeping the old name would not interfere in the final result

2024-07-17 13:27 UTC, KevLehman submitted a review, later dismissed

2024-07-17 13:51 UTC, debdutdeb commented on apps/meteor/app/settings/server/SettingsRegistry.ts
> +		await this.model.insertOne(setting); // no need to emit unless we remove the oplog
Apparently not, checked a while ago. I still left the comment for evidence.

2024-07-17 13:51 UTC, debdutdeb commented on apps/meteor/app/settings/server/SettingsRegistry.ts
> +				throw new Error('No document returned after setting was updated due to metadata change, something is wrong with code');
suggestion? 🙈  this is unreachable, so just tried to be verbose

2024-07-17 13:52 UTC, debdutdeb commented on apps/meteor/app/settings/server/SettingsRegistry.ts
> +export const compareSettingsMetadata = compareSettingsIgnoringKeys([
```suggestion
export const compareSettings = compareSettingsIgnoringKeys([
```

2024-07-17 13:52 UTC, debdutdeb commented on apps/meteor/app/settings/server/SettingsRegistry.ts
> +			// we need to update the setting metadata here
```suggestion
		if (settingStored && !compareSettings(settingStored, settingFromCodeOverwritten)) {
```

2024-07-17 13:53 UTC, debdutdeb commented on apps/meteor/tests/unit/app/settings/server/functions/compareSettingsMetadata.tests.ts
> +		}),
```suggestion
import { compareSettings } from '../../../../../../app/settings/server/SettingsRegistry';
import { getSettingDefaults } from '../../../../../../app/settings/server/functions/getSettingDefaults';

const testSetting = getSettingDefaults({
	_id: 'my_dummy_setting',
	type: 'string',
	value: 'dummy',
});

describe('#compareSettings', () => {
	const ignoredKeys = ['value', 'ts', 'createdAt', 'valueSource', 'packageValue', 'processEnvValue', '_updatedAt'];

	ignoredKeys.forEach((key) =>
		it(`should return true if ${key} changes`, () => {
			const copiedSetting: any = { ...testSetting };

			if (['ts', 'createdAt', '_updatedAt'].includes(key)) {
				copiedSetting[key] = new Date();
			} else {
				copiedSetting[key] = 'random';
			}

			expect(compareSettings(testSetting, copiedSetting)).to.be.true;
		}),
```

2024-07-17 14:04 UTC, debdutdeb commented
@ggazzo @KevLehman https://github.com/RocketChat/Rocket.Chat/pull/32814

2024-07-19 16:19 UTC, debdutdeb commented on apps/meteor/app/settings/server/SettingsRegistry.ts
> +			const { value: _value, ...settingOverwrittenProps } = settingFromCodeOverwritten; // settingStoredOverwrite not used since we need the updated props, that is in code not db
```suggestion
			const { value: _value, ...settingOverwrittenProps } = settingFromCodeOverwritten;
```

2024-07-19 19:14 UTC, ggazzo commented
I ran your new tests with the old code, and they passed. This makes me believe that we don't have a test covering exactly what you are fixing

2024-07-19 21:12 UTC, ggazzo approved these changes

2024-07-20 02:55 UTC, merged