fix: Client crashing on firefox private window
RocketChat/Rocket.Chat pull request #32807
Opened 2024-07-17 04:33 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

#32758 
## Steps to test or reproduce

## Further comments

2024-07-17 19:35 UTC, KevLehman commented on .changeset/new-balloons-speak.md
> +Fixed web client crashing on firefox private window. We use serviceWorkers for end to end encrypted file messages, this service worker is not available for firefox private window, so handled that.
```suggestion
Fixed web client crashing on Firefox private window. Firefox disables access to service workers inside private windows. Rocket.Chat needs service workers to process E2EE encrypted files on rooms. These types of files won't be available inside private windows, but the rest of E2EE encrypted features should work normally
```

wdyt?

2024-07-17 20:13 UTC, MartinSchoeler requested changes
As mentioned via chat, the channel files tab is crashing the browser too, we need to check if there any other places that tries to access the problematic property

2024-07-18 13:48 UTC, MartinSchoeler approved these changes

2024-07-19 18:32 UTC, merged

2024-07-29 21:19 UTC, sampaiodiego commented
/patch

2024-07-31 00:12 UTC, d-gubert commented
/patch

2024-07-31 18:59 UTC, sampaiodiego commented
/patch

2024-07-31 19:06 UTC, sampaiodiego commented
/patch