refactor: move broadcastMessageFromData to notifyListener
RocketChat/Rocket.Chat pull request #32843
Opened 2024-07-19 02:18 UTC by ricardogarim

As per [CORE-575](https://rocketchat.atlassian.net/browse/CORE-575), the `broadcastMessageFromData` function has been moved to the `notifyListener` handler file to align with existing functions that handle server-to-listener communication. This change does not affect any use cases, inputs, or outputs of the existing function.

[CORE-575]: https://rocketchat.atlassian.net/browse/CORE-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-24 12:14 UTC, MarcosSpessatto requested changes

2024-07-24 12:14 UTC, MarcosSpessatto commented on apps/meteor/tests/unit/app/lib/server/lib/notifyListener.spec.ts
> +                description: 'should return undefined if message is hidden or imported',
Can we have one case for each message? This one is the hidden one, can we create a specific one for the imported one?

2024-07-24 12:14 UTC, MarcosSpessatto commented on apps/meteor/tests/unit/app/lib/server/lib/notifyListener.spec.ts
> +                description: 'should return the message with real name if useRealName is true',
Can we create a new case for mentions using a real name as well?

2024-07-24 12:14 UTC, MarcosSpessatto commented on apps/meteor/tests/unit/app/lib/server/lib/notifyListener.spec.ts
> +                description: 'should not broadcast the message if dbWatchersDisabled is false',
What about a new case when there is no message to broadcast? Does it make sense?

2024-07-25 11:28 UTC, MarcosSpessatto approved these changes

2024-07-25 13:22 UTC, KevLehman approved these changes

2024-07-26 14:29 UTC, merged