feat: unknown contacts
RocketChat/Rocket.Chat pull request #32865
Opened 2024-07-23 14:07 UTC by tapiarafael

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-09-04 12:33 UTC, MarcosSpessatto approved these changes
It's worth noting that these PRs don't contain changesets because the feature is not fully enabled yet; it's under a feature flag (test).

2024-09-05 15:04 UTC, tassoevan approved these changes

2024-09-05 17:35 UTC, KevLehman requested changes

2024-09-06 17:28 UTC, KevLehman commented on apps/meteor/app/livechat/server/api/v1/contact.ts
> +			if (process.env.TEST_MODE?.toUpperCase() !== 'TRUE') {
Since this will be removed in next release, we're going to stick with this one for now.

2024-09-06 17:28 UTC, KevLehman approved these changes

2024-09-09 15:24 UTC, merged