chore: Update Omnichannel's room closing mechanism to use transactions.
RocketChat/Rocket.Chat pull request #32896
Opened 2024-07-24 21:35 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-07-29 13:29 UTC, MarcosSpessatto requested changes
I wouldn't like to start to spread MongoDB (or any other DB) transaction mechanism into business rules code, this could open a wormhole to dark places, but I understand your point here. For this specific case I'm okay with it, but for sure we need a more concrete and robust solution for using DB transactions.

2024-07-29 13:39 UTC, KevLehman commented on apps/meteor/app/livechat/server/lib/LivechatTyped.ts
> +	(params as CloseRoomParamsByVisitor).visitor !== undefined;
Not really sure. These types are not used outside of this file 🤔 maybe if someone ever needs to use them, it's a good indicator that they should be in core typings (not even the CloseRoomParams or CloseRoomParamsByVisitor are in core typings)

2024-07-29 13:39 UTC, KevLehman commented on apps/meteor/app/livechat/server/lib/LivechatTyped.ts
> +		let chatCloser: any;
Can try. I wasn't sure of the effort of typing this one just to be passed on the other func but yeah.

2024-07-31 11:31 UTC, MarcosSpessatto approved these changes

2024-08-09 14:39 UTC, sampaiodiego approved these changes

2024-08-12 16:27 UTC, MartinSchoeler submitted a review, later dismissed

2024-08-21 21:24 UTC, sampaiodiego submitted a review, later dismissed

2024-08-22 12:33 UTC, MartinSchoeler submitted a review, later dismissed

2024-08-22 12:41 UTC, MarcosSpessatto approved these changes

2024-08-22 15:39 UTC, MarcosSpessatto approved these changes

2024-08-22 17:17 UTC, MartinSchoeler approved these changes

2024-08-22 18:57 UTC, sampaiodiego approved these changes

2024-08-22 20:14 UTC, merged