test: Add unit test for RoomMenu options
RocketChat/Rocket.Chat pull request #32891
Opened 2024-07-24 17:31 UTC by csuadev

This task add pending unit tests for the RoomMenu to validate a task related to Omnichannel conversations where we removed the option to hide a conversation when its an Omnichannel.

Related to this PR: https://github.com/RocketChat/Rocket.Chat/pull/32691

## Proposed changes (including videos or screenshots)

## Issue(s)
[https://rocketchat.atlassian.net/browse/CORE-579](https://rocketchat.atlassian.net/browse/CORE-579)
[https://rocketchat.atlassian.net/browse/SUP-599](https://rocketchat.atlassian.net/browse/SUP-599)

## Steps to test or reproduce

## Further comments

2024-07-29 13:09 UTC, MarcosSpessatto approved these changes

2024-08-21 13:18 UTC, yash-rajpal requested changes
Can we add more test cases, to cover more cases?

Example, only showing favorites option, based on the setting value?

2024-08-21 14:00 UTC, yash-rajpal submitted a review, later dismissed
Lets move forward with this for now and we will add more cases in future.

2024-08-21 17:26 UTC, dougfabris submitted a review, later dismissed

2024-08-21 17:26 UTC, dougfabris commented on apps/meteor/tests/unit/client/views/room/RoomMenu.spec.tsx
let's try to mock using `mock-providers`

2024-08-21 19:04 UTC, dougfabris commented on apps/meteor/tests/unit/client/views/room/RoomMenu.spec.tsx
The unit tests are broken

2024-08-28 11:46 UTC, MarcosSpessatto requested changes

2024-08-28 11:46 UTC, MarcosSpessatto commented on apps/meteor/client/sidebar/RoomMenu.spec.tsx
> +	it('should display the menu options', async () => {
When should it be displayed? When it's a regular room? 🤔

2024-08-28 11:46 UTC, MarcosSpessatto commented on apps/meteor/client/sidebar/RoomMenu.spec.tsx
> +	it('should display the menu options mark unread and favorite', async () => {
An omnichannel room? 🤔

2024-08-28 16:17 UTC, MarcosSpessatto submitted a review, later dismissed

2024-08-29 13:30 UTC, MarcosSpessatto approved these changes

2024-08-29 13:42 UTC, dougfabris approved these changes

2024-08-29 14:21 UTC, merged