refactor: insertOrUpdateEmoji uploadEmojiCustom emoji-custom
RocketChat/Rocket.Chat pull request #32925
Opened 2024-07-29 07:31 UTC by abhinavkrin

## Proposed changes (including videos or screenshots)

This pr refactors insertOrUpdateEmoji uploadEmojiCustom methods by extracting the logic to separate function and using theme in emoji-custom endpoint instead of the methods.
## Issue(s)

## Steps to test or reproduce

## Further comments

2024-07-29 16:00 UTC, MarcosSpessatto requested changes
Can we add some API tests to cover this?

Also, can we rewrite the PR title to be clearer?

2024-07-29 19:56 UTC, abhinavkrin commented
> Can we add some API tests to cover this?
> 
> Also, can we rewrite the PR title to be clearer?

We already have tests for the emoji-custom endpoint. I will be adding tests along with my next pr for the fix.

2024-07-30 11:44 UTC, MarcosSpessatto submitted a review, later dismissed

2024-08-07 15:49 UTC, KevLehman approved these changes

2024-08-08 12:57 UTC, MarcosSpessatto approved these changes

2024-08-08 13:33 UTC, merged