fix: Mark as unread not working
RocketChat/Rocket.Chat pull request #32939
Opened 2024-07-30 17:17 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

- Fixed issue where when you marked a room as read and you were part of it, sometimes it would mark it as read right after
- Fixed issue where you were redirected to `/home` even if you don't have the room open
- Removed outdated meteor.startup code

## Issue(s)

closes #27274

[SUP-567](https://rocketchat.atlassian.net/browse/SUP-567)

## Steps to test or reproduce

This seems to happen only on busier servers, you can reproduce it on open.rocket.chat if you have the room open and mark it as unread, soon after it is marked as read again

2024-08-02 11:46 UTC, MarcosSpessatto requested changes

2024-08-02 11:46 UTC, MarcosSpessatto commented on apps/meteor/app/message-mark-as-unread/client/actionButton.ts
Do we need to delete this in this PR? Would it be possible to be removed in another one?

2024-08-02 11:46 UTC, MarcosSpessatto commented on apps/meteor/client/sidebar/RoomMenu.tsx
> +			}
Is this related to the original issue? If not, let's create a specific PR for that

2024-08-02 11:46 UTC, MarcosSpessatto commented on apps/meteor/client/sidebarv2/RoomMenu.tsx
> +			}
Same

2024-08-02 11:46 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/channels-sidebar.spec.ts
> +	});
Can we add a test case using the mark as unread from the message action as well?

2024-08-05 15:02 UTC, dougfabris commented on apps/meteor/tests/e2e/page-objects/fragments/home-sidenav.ts
> +		return sidebarItem;
I would suggest avoiding returning the sidebarItem here, and in order to get it use the `getSidebarItemByName` where you need

2024-08-05 15:04 UTC, dougfabris commented on apps/meteor/tests/e2e/mark-unread.spec.ts
> +			await expect(sidebarItem.locator('.rcx-badge')).toBeVisible();
create the badge locator in page objects to re-use it across the tests

2024-08-05 15:05 UTC, dougfabris commented on apps/meteor/tests/e2e/mark-unread.spec.ts
> +			await poHomeChannel.page.locator('role=menuitem[name="Mark Unread"]').click();
create the markUnread locator in page objects to re-use it across the tests

2024-09-02 15:57 UTC, MarcosSpessatto submitted a review, later dismissed

2024-09-03 11:43 UTC, dougfabris commented
We should investigate more, mark unread feature through the message seems to be working partially. 
Sometimes the e2e is failing locally!

2024-09-03 18:20 UTC, dougfabris approved these changes
<img src='https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExb3o4MW93N29tcTFlMjkxdG1xaG1ldGNoOGp2cW14OTAxM203YnQwZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QBd2kLB5qDmysEXre9/giphy.webp' />

2024-09-03 19:30 UTC, ggazzo commented
> Fixed issue where when you marked a room as read

UNread rigth?

2024-09-03 21:23 UTC, dougfabris submitted a review, later dismissed

2024-09-04 16:54 UTC, MarcosSpessatto approved these changes

2024-09-17 17:00 UTC, tiagoevanp approved these changes

2024-09-18 11:06 UTC, MarcosSpessatto approved these changes

2024-09-18 15:21 UTC, merged