fix(fuselage-ui-kit): `MultiStaticSelectElement` not working as expected using `dispatchActionConfig: ['on_item_selected']`
RocketChat/Rocket.Chat pull request #32999
Opened 2024-08-07 09:47 UTC by tiagoevanp

## Proposed changes (including videos or screenshots)

Change actionFunction in useUiKitState to update the state value correctly when using MultiStaticSelectElement with a config dispatchActionConfig from UiKit

## Issue(s)

## Steps to test or reproduce

## Further comments

[SUP-629](https://rocketchat.atlassian.net/browse/SUP-629)

2024-08-08 12:54 UTC, MarcosSpessatto approved these changes

2024-08-16 01:29 UTC, tassoevan requested changes
Passing `'on_item_selected'` or not passing it makes no difference to the unit test. Even reverting the `useUiKitState` hook just fail the test in both scenarios.

2024-09-02 13:50 UTC, MarcosSpessatto approved these changes

2024-09-04 18:33 UTC, tassoevan approved these changes

2024-09-05 11:35 UTC, merged