feat: VoIP freeswitch UI internals
RocketChat/Rocket.Chat pull request #33005
Opened 2024-08-07 21:09 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-09-17 14:28 UTC, pierre-lehnen-rc requested changes

2024-09-17 14:28 UTC, pierre-lehnen-rc commented on apps/meteor/ee/app/api-enterprise/server/voip-freeswitch.ts
> +	{ authRequired: true, validateParams: isVoipFreeSwitchExtensionGetDetailsProps },
Why are you removing the permission?

2024-09-23 22:14 UTC, tassoevan approved these changes

2024-09-24 14:14 UTC, pierre-lehnen-rc approved these changes
backend

2024-09-24 14:15 UTC, merged