feat: VoIP freeswitch admin UI
RocketChat/Rocket.Chat pull request #33004
Opened 2024-08-07 21:05 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-08-22 14:47 UTC, tassoevan requested changes

2024-08-22 14:47 UTC, tassoevan commented on apps/meteor/client/views/admin/users/UsersTable/UsersTable.spec.tsx
> +jest.mock('../../../../components/UserStatus', () => ({ UserStatus: () => null }));
Why is this needed?

2024-08-22 14:47 UTC, tassoevan commented on apps/meteor/client/views/admin/users/voip/AssignExtensionModal.spec.tsx
> +// TODO: it('should load with default extension', async () => {});
```suggestion
it.todo('should load with default user', async () => {});

it.todo('should load with default extension', async () => {});
```

2024-08-22 14:47 UTC, tassoevan commented on apps/meteor/client/views/admin/users/voip/AssignExtensionModal.tsx
> +										data-testid='input-free-extension-numbers'
Why it cannot be queried by role?

2024-09-17 13:13 UTC, MartinSchoeler approved these changes

2024-09-17 14:13 UTC, pierre-lehnen-rc approved these changes
backend

2024-09-23 13:46 UTC, merged