fix(i18n): fixes onboarding.component.emailCodeFallback translation
RocketChat/Rocket.Chat pull request #33029
Opened 2024-08-12 18:49 UTC by lucas-a-pelegrino

## Proposed changes (including videos or screenshots)

This PR fixes a translation text typo for German, where **einmal** was written as **einemal**. It also includes the missing hyperlinks for **Resend** and **Change Email**.
## Issue(s)

[https://rocketchat.atlassian.net/browse/SUP-632](SUP-632)

## Steps to test or reproduce

1. Set language to German
2. Go through the four steps of workspace registration

## Further comments

N/a

2024-08-12 18:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=33029) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=33029) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=33029) it.</sub>

2024-08-12 20:18 UTC, dougfabris approved these changes
LGTM!

2024-08-12 20:28 UTC, KevLehman requested changes
Pls add a changeset

2024-08-12 20:28 UTC, KevLehman commented on yarn.lock
No need

2024-08-12 20:36 UTC, lucas-a-pelegrino commented on yarn.lock
I've emoved the change to yarn.lock.

2024-08-12 21:42 UTC, dougfabris approved these changes

2024-08-13 19:17 UTC, KevLehman approved these changes

2024-08-13 20:48 UTC, merged