fix: Missing department names on OC edit agent view
RocketChat/Rocket.Chat pull request #33033
Opened 2024-08-13 13:27 UTC by csuadev

When an omnichannel agent has more than 50 assigned departments, it wasn't showing some department names since the endpoint is paginated and UI only brings first 50 elements, new property was added and this is the frontend change to introduce it and check for missing department names when needed.

## Proposed changes (including videos or screenshots)

## Issue(s)
[https://rocketchat.atlassian.net/browse/SUP-640](https://rocketchat.atlassian.net/browse/SUP-640)

## Steps to test or reproduce

## Further comments

2024-08-14 13:38 UTC, MarcosSpessatto requested changes
Let's add a changeset please.

2024-08-14 13:38 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/omnichannel/omnichannel-agents.spec.ts
> +			await page.route(new RegExp('/api/v1/livechat/department.*'), async (route) => {
Wouldn't this mock all the endpoints `department.`? I think this could be a problem when running tests concurrently.

2024-08-14 19:41 UTC, MarcosSpessatto approved these changes

2024-08-15 18:44 UTC, MartinSchoeler approved these changes

2024-08-15 20:01 UTC, merged