feat: Return `departmentsAllowedToForward` property in `livechat/config` endpoint
RocketChat/Rocket.Chat pull request #33060
Opened 2024-08-14 22:39 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-08-23 23:25 UTC, lucas-a-pelegrino submitted a review, later dismissed

2024-09-02 16:13 UTC, MarcosSpessatto approved these changes

2024-09-03 20:15 UTC, sampaiodiego commented on apps/meteor/tests/end-to-end/api/livechat/11-livechat.ts
> +				deleteDepartment(emptyDepartment._id),
what about moving the creation and deletion to before/after hooks?

2024-10-10 17:56 UTC, MartinSchoeler requested changes
Is it possible to add some UI e2e tests? I know we didn't change any client files, but there are some behavior changes on the UI, I think we can add one to this file https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/tests/e2e/omnichannel/omnichannel-livechat-department.spec.ts or even a livechat API test to check if the widget api is respecting the fowarding limits implemented here

2024-12-23 14:21 UTC, MartinSchoeler approved these changes

2024-12-26 11:56 UTC, MarcosSpessatto approved these changes

2024-12-26 12:32 UTC, merged