test(Omnichannel): Fix department flaky test
RocketChat/Rocket.Chat pull request #33091
Opened 2024-08-19 17:28 UTC by MartinSchoeler

[FLAKY-735](https://rocketchat.atlassian.net/browse/FLAKY-735)

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-08-20 16:25 UTC, dougfabris requested changes

2024-08-20 16:25 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
> -		await expect(statusCode).toBe(200);
why?

2024-08-20 16:25 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
> +				await poOmnichannelDepartments.btnCloseToastSuccess.click();
Indeed, no need to close this `ToastBar`

2024-08-20 16:25 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
> +					await expect(poOmnichannelDepartments.modalConfirmDelete).toBeVisible();
```suggestion

```

No need to do this assertion

2024-08-20 18:03 UTC, ggazzo approved these changes

2024-08-20 18:04 UTC, merged

2024-08-21 15:51 UTC, dougfabris commented on apps/meteor/tests/e2e/omnichannel/omnichannel-departaments.spec.ts
> +				await poOmnichannelDepartments.btnCloseToastSuccess.click();
fixed!