refactor: Replace proxy functions from `LivechatTyped` class with direct calls
RocketChat/Rocket.Chat pull request #33110
Opened 2024-08-20 16:45 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-08-21 15:42 UTC, ggazzo commented on apps/meteor/app/livechat/server/api/lib/livechat.ts
> +export function findGuest(token: string, includeActivity = true): Promise<ILivechatVisitor | null> {
create a new function

2024-08-21 16:20 UTC, KevLehman commented on apps/meteor/app/livechat/server/api/lib/livechat.ts
> +export function findGuest(token: string, includeActivity = true): Promise<ILivechatVisitor | null> {
done, thanks!

2024-08-21 17:38 UTC, matheusbsilva137 requested changes

2024-08-21 17:38 UTC, matheusbsilva137 commented on apps/meteor/app/livechat/server/api/v1/config.ts
> +			const enabled = serverSettings.get('Livechat_enabled');
```suggestion
			const enabled = serverSettings.get<boolean>('Livechat_enabled');
```
Not a big deal, but it'd be good to have correct typing here as we had before

2024-08-21 17:54 UTC, matheusbsilva137 approved these changes

2024-08-22 21:07 UTC, sampaiodiego approved these changes

2024-08-22 21:16 UTC, aleksandernsilva approved these changes

2024-08-22 23:20 UTC, merged