fix: VideoConf message not considers display avatar pref
RocketChat/Rocket.Chat pull request #33141
Opened 2024-08-23 22:21 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2025-01-24 15:36 UTC, MarcosSpessatto requested changes

2025-01-24 15:36 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/video-conference.spec.ts
> +		test('should not render avatars in video conference message block', async () => {
Does it make sense to have different combinations like: should render the avatars if the user preference is true, also, what should happen when the list contains user with and without avatars?

2025-01-24 15:43 UTC, dougfabris commented on apps/meteor/tests/e2e/video-conference.spec.ts
> +		test('should not render avatars in video conference message block', async () => {
I don't see why making a test to check the default assertion for this preference, we already have a test to check if the message block is there and the preference is true by default, so I added a test just to check if its ignoring the avatars properly when changing the preference. 

> what should happen when the list contains user with and without avatars
Basically what I'm testing, if the avatars are there or not

2025-01-24 16:06 UTC, gabriellsh requested changes

2025-01-24 16:06 UTC, gabriellsh commented on packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
> +  const getMessageFooterText = useCallback(
I don't think this has to be a useCallback, since it's just called below, it won't trigger rendering.

Maybe instead we could have a useMemo, or define this function outside the component?

2025-01-24 16:06 UTC, gabriellsh commented on packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
> +    .map(({ name, username }) => (showRealName ? name : username))
Name can be undefined here.

2025-01-24 16:06 UTC, gabriellsh commented on packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
> +      : t('__usernames__joined', { usernames: joinedUsernames });
Shouldn't this respect the `useRealName` setting aswell?

2025-01-24 16:10 UTC, gabriellsh commented on apps/meteor/tests/e2e/video-conference.spec.ts
> +		test('should not render avatars in video conference message block', async () => {
There's never "users without avatar" afaik. If the user has no avatar it's the default one...

2025-01-24 18:05 UTC, dougfabris commented on packages/ui-video-conf/src/VideoConfMessage/VideoConfMessageUserStack.tsx
> +							<Avatar size='x28' alt={username || ''} title={showRealName ? name : username} url={getUserAvatarPath(username as string)} />
yep, let's replace it with the hook we're isolating in `ui-client`

2025-01-24 18:06 UTC, dougfabris commented on packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
> +    .map(({ name, username }) => (showRealName ? name : username))
yep, let's replace it with the hook we're isolating in `ui-client`

2025-01-24 18:06 UTC, dougfabris commented on packages/fuselage-ui-kit/src/blocks/VideoConferenceBlock/VideoConferenceBlock.tsx
> +      : t('__usernames__joined', { usernames: joinedUsernames });
> Shouldn't this respect the `useRealName` setting aswell?

yep, let's replace it with the hook we're isolating in `ui-client`

2025-01-27 19:50 UTC, gabriellsh submitted a review, later dismissed

2025-01-27 19:57 UTC, gabriellsh approved these changes

2025-01-31 20:06 UTC, MarcosSpessatto submitted a review, later dismissed

2025-02-08 02:16 UTC, merged