fix: resolve avatar download issue on setUsername by refining service selection logic
RocketChat/Rocket.Chat pull request #33193
Opened 2024-09-02 03:14 UTC by ricardogarim

As per [CORE-650](https://rocketchat.atlassian.net/browse/CORE-650), this pull request addresses the issue where the avatar blob image was not being correctly set in the `setUserAvatar` method, resulting in an undefined error for the user. The root cause was identified as incorrect handling of avatar service selection, which led to errors during the avatar setting process.

Key changes:
- Corrected the service handling logic to ensure the avatar blob is properly set from the first available service.
- Enhanced the process to prioritize non-gravatar services while maintaining a fallback to gravatar if no other service is available.

[CORE-650]: https://rocketchat.atlassian.net/browse/CORE-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-03 09:40 UTC, MarcosSpessatto requested changes
Is there any way we could add some tests here?

2024-09-09 12:47 UTC, MarcosSpessatto requested changes

2024-09-09 12:47 UTC, MarcosSpessatto commented on apps/meteor/tests/unit/app/lib/server/functions/setUsername.spec.ts
> +		it('should not set avatar if Accounts_SetDefaultAvatar is disabled', async () => {
Ca we add a case when there is no `!previousUsername`?

2024-09-16 20:46 UTC, sampaiodiego approved these changes
for a further optimization, when calling `setUsername` we don't need to call `getAvatarSuggestionForUser` which will fetch avatar for EVERY SERVICE available, we just need the first one =)

2024-09-17 20:56 UTC, merged