fix: `LivechatSessionTaken` webhook event called without `agent` param
RocketChat/Rocket.Chat pull request #33209
Opened 2024-09-04 17:11 UTC by KevLehman

## Proposed changes (including videos or screenshots)

Basically, the call to `assignAgent` was updating the room object as expected, but when calling `afterTakeInquiry` callback we were passing the room _before_ it was updated.
## Issue(s)

https://rocketchat.atlassian.net/browse/SUP-654
## Steps to test or reproduce

## Further comments

2024-09-05 09:22 UTC, MarcosSpessatto approved these changes

2024-09-05 13:36 UTC, ggazzo requested changes

2024-09-05 13:36 UTC, ggazzo commented on apps/meteor/app/livechat/server/lib/RoutingManager.ts
> +				// @eslint-disable-next-line @typescript-eslint/no-non-null-assertion
nop

2024-09-05 13:36 UTC, ggazzo commented on apps/meteor/app/livechat/server/lib/RoutingManager.ts
> +				// @eslint-disable-next-line @typescript-eslint/no-non-null-assertion
remove the eslint/ts disable

2024-09-05 13:41 UTC, KevLehman commented on apps/meteor/app/livechat/server/lib/RoutingManager.ts
> +				// @eslint-disable-next-line @typescript-eslint/no-non-null-assertion
ah, remanent of first fix.

2024-09-16 12:50 UTC, MarcosSpessatto requested changes
~~Is there any way of adding tests?~~ Just saw the description

2024-09-16 15:15 UTC, MarcosSpessatto approved these changes

2024-09-17 14:53 UTC, sophia-devs commented
Can we get an update on this?

2024-09-17 18:32 UTC, MartinSchoeler approved these changes

2024-09-18 18:24 UTC, merged