fix: Apply message character limit to file upload description
RocketChat/Rocket.Chat pull request #33218
Opened 2024-09-05 21:04 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

Added the message character limit restriction to the file upload description field, before this, you could send a message bigger than the limit by sending a file with a large description

## Issue(s)

[SUP-620](https://rocketchat.atlassian.net/browse/SUP-620)

2024-09-23 11:51 UTC, abhinavkrin requested changes
Hello @MartinSchoeler,

Would it be a good idea to implement the check on the backend as well? Currently, users can send long messages through the API bypassing the character limit.

2024-10-22 16:59 UTC, abhinavkrin submitted a review, later dismissed

2024-10-22 17:14 UTC, tiagoevanp submitted a review, later dismissed

2024-10-22 22:36 UTC, gabriellsh requested changes
The title should describe the issue and not the solution. I'll change that for you.

2024-10-24 18:16 UTC, gabriellsh submitted a review, later dismissed

2024-10-28 12:55 UTC, MarcosSpessatto requested changes
Can we add some UI

2024-10-28 12:55 UTC, MarcosSpessatto commented on apps/meteor/tests/e2e/file-upload.spec.ts
> +
```suggestion
```

2024-10-28 12:55 UTC, MarcosSpessatto commented on apps/meteor/app/api/server/v1/rooms.ts
I think we need to add the same validation for the `rooms.upload` endpoint, even if it's deprecated...

2024-11-05 13:06 UTC, MartinSchoeler commented on apps/meteor/tests/e2e/file-upload.spec.ts
> +
https://github.com/RocketChat/Rocket.Chat/pull/33218#discussion_r1811521745

2024-11-11 12:52 UTC, MarcosSpessatto approved these changes

2024-11-15 13:37 UTC, dougfabris approved these changes
Great work here!

2024-11-18 13:47 UTC, merged