fix: livechat stuck unread counter on new messages
RocketChat/Rocket.Chat pull request #33229
Opened 2024-09-07 22:24 UTC by ricardogarim

This pull request addresses the issue described in [CORE-674](https://rocketchat.atlassian.net/browse/CORE-674), where the unread message counter does not update when a livechat visitor, with the widget minimized, receives their first response from an agent. The problem occurs because the `lastReadMessageId` is absent from the livechat client's state, and the `getUnreadMessages` function does not handle this situation correctly.

Shoutout to @ggazzo for helping address the changes correctly within the widget code!

[CORE-674]: https://rocketchat.atlassian.net/browse/CORE-674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-10 17:26 UTC, MarcosSpessatto approved these changes

2024-09-12 12:57 UTC, ggazzo requested changes
Missing tests ;)

2024-09-12 12:57 UTC, ggazzo commented on packages/livechat/src/lib/main.js
> +	const lastReadMessage = getLastReadMessage();
I know that return early looks better, but doing this during a fix it may be not the ideal.
it chan prevent/conflict during backports

2024-09-23 11:33 UTC, abhinavkrin approved these changes

2024-10-01 01:45 UTC, ggazzo approved these changes

2024-10-09 19:24 UTC, MarcosSpessatto approved these changes

2024-10-09 23:19 UTC, merged