feat: New outdated marketplace empty state
RocketChat/Rocket.Chat pull request #33238
Opened 2024-09-09 17:37 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

Adds a new empty state to the marketplace when a workspace is out of the support window

![Screenshot 2024-09-09 at 14 14 53](https://github.com/user-attachments/assets/5105fefb-4411-4261-a9fb-dddf127afd89)

Requires https://rocketchat.atlassian.net/browse/CONN-334 to work

## Issue(s)

[PASLR-6](https://rocketchat.atlassian.net/browse/PASLR-6)

2024-10-14 19:32 UTC, MartinSchoeler commented
Moving this to draft since we decided to merge this into develop

2024-10-14 20:35 UTC, aleksandernsilva requested changes

2024-10-15 12:35 UTC, MartinSchoeler commented on apps/meteor/client/apps/orchestrator.ts
> +			}
This one should cover, I guess the name of the function is misleading, it's just a typeguard to satisfy TS, I'll change the name of the function to better reflect its use

2024-10-15 17:42 UTC, aleksandernsilva approved these changes

2024-10-15 20:12 UTC, merged