fix(federation-v2): await bridge startup
RocketChat/Rocket.Chat pull request #33253
Opened 2024-09-11 11:53 UTC by debdutdeb

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

[SUP-584](https://rocketchat.atlassian.net/browse/SUP-584)

2024-09-11 11:54 UTC, debdutdeb commented on apps/meteor/ee/server/local-services/federation/service.ts
>  		return super.created();
```suggestion
		return super.started();
```

2024-10-17 09:43 UTC, MarcosSpessatto requested changes
Can we add a changeset?

2024-10-17 13:33 UTC, debdutdeb commented on .changeset/green-queens-end.md
> +Fixes an issue with Federation startup where the bridge would intermittently fail to start causing errors being thrown "Matrix Bridge isn't running yet".
```suggestion
Fixes an issue with Federation startup where the bridge would intermittently fail to start causing error being shown "Matrix Bridge isn't running yet".
```

2024-10-22 09:07 UTC, MarcosSpessatto approved these changes

2024-12-11 12:58 UTC, merged