fix: correctly display emoji aliases in custom emoji list
RocketChat/Rocket.Chat pull request #33278
Opened 2024-09-13 07:20 UTC by abhinavkrin

## Proposed changes (including videos or screenshots)

This PR fixes the issue where emoji aliases were not displayed properly in the custom emoji list. The change ensures that `emojis.aliases` is checked to be an array before displaying and joined with a comma. 

<img width="1393" alt="Screenshot 2024-09-13 at 12 47 39 PM" src="https://github.com/user-attachments/assets/33826dae-7c1f-40e5-9b19-7ea51e23b87a">

## Issue(s)

## Steps to test or reproduce

## Further comments

[CORE-691](https://rocketchat.atlassian.net/browse/CORE-691)

2024-09-13 11:37 UTC, MarcosSpessatto requested changes
Can we add test here?

Also, lets add a changeset.

2024-09-13 16:25 UTC, gabriellsh requested changes
Please update the title as per [Our docs](https://developer.rocket.chat/v1/docs/pull-requests-tags)

> The title should describe what's being fixed, not how it was fixed.

Here's a suggestion: `fix: no spaces between emoji aliases`

Also both in the task and PR, the issue is not well described, since it is presented that there is an issue but it does not convey what is happening. I had to look at the code to be able to discover what the actual issue was.

2024-10-31 12:48 UTC, MarcosSpessatto requested changes

2024-10-31 12:48 UTC, MarcosSpessatto commented on apps/meteor/client/views/admin/customEmoji/CustomEmoji.spec.tsx
> +describe('CustomEmoji Component', () => {
Can we add a test case for when the aliases are not an array?

2024-11-07 16:24 UTC, MarcosSpessatto approved these changes

2024-11-14 11:45 UTC, MarcosSpessatto approved these changes

2024-11-14 16:04 UTC, yash-rajpal approved these changes
LGTM

2024-11-15 12:41 UTC, merged