feat(FE): Private apps limititations
RocketChat/Rocket.Chat pull request #33316
Opened 2024-09-18 17:15 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-09-24 17:00 UTC, aleksandernsilva requested changes
Hey @MartinSchoeler 👋  
Could you also add context to the PR description (images, task, etc)?
Adding tests to cover this new scenario is also a good idea.

2024-09-26 18:51 UTC, aleksandernsilva requested changes
I just noticed that the title of the PR might need adjusting as well.
https://developer.rocket.chat/docs/pull-requests-tags

2024-09-26 18:51 UTC, aleksandernsilva commented on .changeset/brown-pants-press.md
> +Changed some displays to reflect new Private Apps rules and added a new modal before uploading a private app
According to https://developer.rocket.chat/docs/development-workflow#adding-changeset-to-your-pull-request
> Verb: Start with a verb in the third-person singular present tense.

2024-09-30 17:37 UTC, tassoevan submitted a review, later dismissed

2024-10-01 01:00 UTC, tassoevan approved these changes

2024-10-01 05:14 UTC, merged