chore!: removed mailer.sendMail mailer:unsubscribe methods
RocketChat/Rocket.Chat pull request #33358
Opened 2024-09-25 13:47 UTC by abhinavkrin

## Proposed changes (including videos or screenshots)

removed mailer.sendMail mailer:unsubscribe methods as they have been replaced by mailer and mailer.unsubscribe endpoints
## Issue(s)

## Steps to test or reproduce

## Further comments

[CORE-358](https://rocketchat.atlassian.net/browse/CORE-358)
[CORE-359](https://rocketchat.atlassian.net/browse/CORE-359)

2024-09-25 17:58 UTC, tiagoevanp approved these changes

2024-09-25 18:09 UTC, tiagoevanp requested changes
Can you add a changeset to declare what is happening here? If we are removing some methods (sound like a deprecation) it's better to have something in the release changelog...

2024-09-26 18:10 UTC, tiagoevanp approved these changes

2024-10-15 19:17 UTC, KevLehman commented on apps/meteor/app/api/server/v1/mailer.ts
> +			const result = await sendMail({ from, subject, body, dryrun: Boolean(dryrun), query });
wonder if this one should have a stronger rate limit as well

2024-10-15 22:06 UTC, KevLehman approved these changes

2024-10-15 22:06 UTC, KevLehman commented on apps/meteor/app/api/server/v1/mailer.ts
> +			const result = await sendMail({ from, subject, body, dryrun: Boolean(dryrun), query });
Will be done in separate task

2024-10-16 09:00 UTC, MarcosSpessatto approved these changes

2024-10-16 16:48 UTC, merged