chore: Update default E2EE settings behavior
RocketChat/Rocket.Chat pull request #33361
Opened 2024-09-25 17:01 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

We introduced two new E2EE settings with 6.x releases, E2E_Enable_Encrypt_Files and E2E_Allow_Unencrypted_Messages. Earlier their default value was kept in a way to not change the default behavior.

We decided to change this default behavior in the major 7.0.0 release and now by default users shouldn't be allowed to send un-encrypted messages in encrypted rooms and all files and attachments would be encrypted.
## Issue(s)

## Steps to test or reproduce

## Further comments

2024-09-26 17:03 UTC, hugocostadev requested changes

2024-10-16 10:27 UTC, MarcosSpessatto submitted a review, later dismissed
The suggestion from @hugocostadev for the changeset is valid @yash-rajpal, I would recommend the same as he did. Can we rewrite that?

2024-10-16 12:17 UTC, hugocostadev approved these changes

2024-10-16 13:04 UTC, KevLehman requested changes
Did we change the setting creation code in another PR? The `this.add(...` cause otherwise the code for new workspaces will retain the current behavior as migrations won't run on clean envs

2024-10-16 13:04 UTC, KevLehman commented on apps/meteor/server/startup/migrations/v314.ts
> +					value: false,
Why not changing just the packageValue? So if someone has it as `true` and likes it being `true`, we don't break his workflow

2024-10-16 14:13 UTC, KevLehman commented on apps/meteor/server/startup/migrations/v314.ts
> +					value: false,
This should be said to the customer support team too, so if they receive comments from customers they know what to do 👀

2024-10-16 14:14 UTC, KevLehman approved these changes

2024-10-16 15:29 UTC, MarcosSpessatto approved these changes

2024-10-16 20:09 UTC, merged