fix: E2EE room > thread list with attachment
RocketChat/Rocket.Chat pull request #33375
Opened 2024-09-26 12:22 UTC by hugocostadev

## Proposed changes (including videos or screenshots)

The thread title is not showing on the threads list if the thread starts with an image or a file

Before:
![image](https://github.com/user-attachments/assets/8c7dcd0d-b435-4167-921e-47e8c34c3e2a)

Now:
![image](https://github.com/user-attachments/assets/5d1968f4-eb52-4378-b852-faace5234242)

## Issue(s)

## Steps to test or reproduce

1. Open an E2EE channel
2. Send an image or file to the channel
3. Hover the image → Start the thread
4. Send a message inside the thread
5. On the top of the channel, click on “Threads” to see the threads list

## Further comments

https://rocketchat.atlassian.net/browse/E2EE2-51

2024-09-26 19:42 UTC, aleksandernsilva requested changes
Hey @hugocostadev , I tested the branch and everything seem to be working fine 👌 
Just the minor adjustment to the changeset. 

Btw, I belive we could improve this PR's title to be a bit more descriptive (e.g `fix: Title missing in thread list for threads starting with attachment in E2EE rooms`)

_I know my title suggestion is a bit long but it's just an example_ 😉

2024-09-26 19:42 UTC, aleksandernsilva commented on .changeset/moody-phones-admire.md
> +Fixed thread list contextual bar when the first message is an attachment
https://developer.rocket.chat/docs/development-workflow
> Verb: Start with a verb in the third-person singular present tense.

2024-09-27 10:51 UTC, hugocostadev commented on .changeset/moody-phones-admire.md
> +Fixed thread list contextual bar when the first message is an attachment
much better! thanks man

2024-09-27 15:18 UTC, aleksandernsilva requested changes

2024-09-27 15:18 UTC, aleksandernsilva commented on .changeset/moody-phones-admire.md
> +"@rocket.chat/meteor": minor
```suggestion
"@rocket.chat/meteor": patch
```

2024-09-27 18:27 UTC, aleksandernsilva approved these changes

2024-10-03 14:18 UTC, merged