feat: Update private apps cap on Community Edition
RocketChat/Rocket.Chat pull request #33399
Opened 2024-09-30 04:33 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

- Update private apps cap on CE from 3 to 0;
- Add end-to-end tests for private apps upload on CE and EE.

## Issue(s)

## Steps to test or reproduce

## Further comments

[PASLR-2](https://rocketchat.atlassian.net/browse/PASLR-2)

2024-09-30 12:12 UTC, reetp commented
This looks like a breaking change and may affect a lot of people - you know better than me as you have stats.

What has brought this about?

Where is this news published?

2024-09-30 19:26 UTC, lucas-a-pelegrino submitted a review, later dismissed

2024-10-01 20:20 UTC, aleksandernsilva requested changes

2024-10-01 20:20 UTC, aleksandernsilva commented on apps/meteor/tests/e2e/page-objects/marketplace.ts
> +	}
Instead of `data-qa-id` could it be possible to use a combination of role and name here?

2024-10-01 20:20 UTC, aleksandernsilva commented on apps/meteor/tests/e2e/page-objects/marketplace.ts
> +	}
For consistency I'd recommend starting this getter with `btn` (e.g `btnConfirmAppUploadModal` ). Also, if possible I recommend using a combination of role and name to find this element.

2024-10-01 22:03 UTC, matheusbsilva137 commented
The new UI tests in this PR will only pass after #33416 gets merged (fixing a UI issue)

2024-10-02 12:45 UTC, lucas-a-pelegrino approved these changes

2024-10-02 13:35 UTC, aleksandernsilva approved these changes

2024-10-02 14:27 UTC, tassoevan approved these changes

2024-10-02 20:13 UTC, tapiarafael approved these changes

2024-10-02 20:25 UTC, merged