feat: add setting to map an ldap attribute to the user's voice extension
RocketChat/Rocket.Chat pull request #33598
Opened 2024-10-15 22:52 UTC by pierre-lehnen-rc

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-10-16 16:01 UTC, matheusbsilva137 requested changes

2024-10-16 16:04 UTC, pierre-lehnen-rc commented on apps/meteor/server/settings/ldap.ts
> +				});
displayQuery is used as a trick to have different default values for AD and non-AD; The other mapping settings are duplicated with one of them being visible only when it's AD and other being visible only when it's not. This new setting doesn't have a defalut value for either so there was no need to duplicate it.

2024-10-16 16:15 UTC, matheusbsilva137 approved these changes

2024-10-17 16:14 UTC, MarcosSpessatto approved these changes

2024-10-18 02:38 UTC, merged