feat!: Restrict livechat visitors to their source type scope
RocketChat/Rocket.Chat pull request #33760
Opened 2024-10-24 15:01 UTC by pierre-lehnen-rc

Restoring PR #33569 which got reverted on 7.0;

## Proposed changes (including videos or screenshots)

 - Added `source` field to `ILivechatVisitor` type, which stores the channel (eg API, widget, SMS, email-inbox, app) that's been used by the visitor to send messages. Each visitor can now only be linked to a single source, and each user that has already been linked to a source can't be reused in another channel. 
 - This change is required for the SCI project, but is otherwise unrelated as it works independently.
 - This is a breaking change because apps will no longer have access to visitors not created by them.

## Issue(s)

## Steps to test or reproduce

## Further comments

[SCI-88](https://rocketchat.atlassian.net/browse/SCI-88)

[SCI-88]: https://rocketchat.atlassian.net/browse/SCI-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-24 17:06 UTC, matheusbsilva137 requested changes

2024-10-24 17:06 UTC, matheusbsilva137 commented on apps/meteor/ee/server/apps/communication/uikit.ts
Please remove the changes applied to this file. We decided not to apply restrictions here (this has been reverted in our feature branch)

2024-10-24 17:25 UTC, matheusbsilva137 requested changes

2024-10-24 17:25 UTC, matheusbsilva137 commented on .changeset/fuzzy-pans-share.md
> +"@rocket.chat/model-typings": minor
```suggestion
"@rocket.chat/meteor": major
"@rocket.chat/apps": major
"@rocket.chat/core-typings": minor
"@rocket.chat/model-typings": minor
```
Some changes should be tagged as major now, shouldn't they? Not sure about core and model typings

2024-10-29 15:42 UTC, pierre-lehnen-rc commented
Closing in favor of https://adr.rocket.chat/0114

2024-10-29 15:42 UTC, closed without merging