refactor: Normalize the usage of the `useSetting` hook
RocketChat/Rocket.Chat pull request #33779
Opened 2024-10-25 03:41 UTC by tassoevan

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-10-25 13:59 UTC, aleksandernsilva requested changes

2024-10-25 13:59 UTC, aleksandernsilva commented on apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useVideoMessageAction.ts
> +	const fileUploadMediaTypeBlackList = useSetting('FileUpload_MediaTypeBlackList', '');
The default value for this setting is `'image/svg+xml'`. Should it be reflected here?

2024-10-25 13:59 UTC, aleksandernsilva commented on apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useAudioMessageAction.ts
> +	const isAudioRecorderEnabled = useSetting('Message_AudioRecorderEnabled', false);
The default value for this setting is `true`. Should it be reflected here?

2024-10-25 14:13 UTC, dougfabris reviewed
Overall looks greats, just thinking about some missing fallbacks

2024-10-25 14:13 UTC, dougfabris commented on apps/meteor/client/views/room/composer/messageBox/MessageBoxActionsToolbar/hooks/useShareLocationAction.tsx
no fallback for this?

2024-10-25 14:13 UTC, dougfabris commented on apps/meteor/client/views/room/body/RoomBodyV2.tsx
fallback?

2024-10-25 14:13 UTC, dougfabris commented on apps/meteor/client/views/omnichannel/installation/Installation.tsx
fallback?

2024-10-25 14:13 UTC, dougfabris commented on apps/meteor/client/hooks/useTimeAgo.ts
fallback?

2024-10-25 17:59 UTC, dougfabris approved these changes
LGTM!

2024-10-25 19:02 UTC, aleksandernsilva approved these changes

2024-11-04 17:36 UTC, ggazzo approved these changes

2024-11-04 19:15 UTC, merged