fix: check queue settings to take inquiry
RocketChat/Rocket.Chat pull request #33782
Opened 2024-10-25 12:50 UTC by Gustrb

## Proposed changes (including videos or screenshots)

Whenever an agent tried to take a specific inquiry, we were checking the shouldTriggerVerificationApp method. That method, should only be used to avoid adding a visitor inquiry to the queue, not everytime, because of that we were having a few issues such as:

If the Livechat_Require_Contact_Verification setting was set to always, no conversation would ever be available to pick, even though the visitor might have been verified

This commit introduces the isAgentAvailableToTakeContactInquiry method, that should be used in those scenarios, also removes the check for Livechat_Block_Unknown_Contacts inside the bot call, since it does not do anything there, we now only check inside the isAgentAvailableToTakeContactInquiry method, along with a new setting to block unverified contacts (that was removed for some reason)

## Issue(s)

## Steps to test or reproduce

## Further comments

[SCI-117]

2024-10-28 13:07 UTC, Gustrb commented
I don't really know how would we do it, the shouldTriggerVerificationApp is supposed to be used before assigning a room to an agent, while the isAgentAvailableToTakeContactInquiry is supposed to be used on conversations that already have a room (might have an agent or not).

So like, we have the queue settings and the contact verifications settings, the mistake this PR fixes is that those settings should've been separate all together, but since no one really understood that we only had the check for before assigning the room

2024-10-31 12:32 UTC, MarcosSpessatto requested changes
Would it be possible to add some tests to ensure the behavior?

2024-11-06 20:16 UTC, tapiarafael approved these changes

2024-11-07 12:49 UTC, MarcosSpessatto requested changes

2024-11-07 12:49 UTC, MarcosSpessatto commented on apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/isAgentAvailableToTakeContactInquiry.spec.ts
> +		settingsMock.get.withArgs('Livechat_Block_Unverified_Contacts').returns(true);
Can we add more cases to cover when these settings are false?

2024-11-07 16:14 UTC, MarcosSpessatto approved these changes

2024-11-07 19:59 UTC, merged

2024-11-07 20:09 UTC, KevLehman commented on apps/meteor/ee/tests/unit/apps/livechat-enterprise/server/lib/shouldTriggerVerificationApp.spec.ts
> +		settingsMock.get.returns('');
```suggestion
		settingsMock.get.withArgs('Livechat_Contact_Verification_App').returns('');
```