fix: broken client-side updates for recent emoji list
RocketChat/Rocket.Chat pull request #33808
Opened 2024-10-28 08:55 UTC by abhinavkrin

## Proposed changes (including videos or screenshots)

This PR fixes the broken client-side updates for recent emoji list when custom emojis are modified.

Currently, we are calling updateRecent with hard coded string value 'rocket' which inserts the rocket emoji whenever a custom emoji changes. Instead, the update in the recent emoji list should reflect an updated custom emoji or remove a deleted custom emoji from the recent list:
https://github.com/RocketChat/Rocket.Chat/blob/5fddfcc99ea6d17eb63cd33772dc7388a1d7fba8/apps/meteor/app/emoji-custom/client/lib/emojiCustom.ts#L52
same here:
https://github.com/RocketChat/Rocket.Chat/blob/5fddfcc99ea6d17eb63cd33772dc7388a1d7fba8/apps/meteor/app/emoji-custom/client/lib/emojiCustom.ts#L97
## Issue(s)

## Steps to test or reproduce

## Further comments

[CORE-690](https://rocketchat.atlassian.net/browse/CORE-690)

2024-10-28 13:00 UTC, MarcosSpessatto requested changes

2024-10-28 13:00 UTC, MarcosSpessatto commented on apps/meteor/app/emoji/client/helpers.ts
> +export const replaceEmojiInRecent = (oldEmoji: string, newEmoji: string) => {
I think using an object here would be better, so the caller can know whats needs to be provided. WDYT?

2024-10-28 16:41 UTC, abhinavkrin commented on apps/meteor/app/emoji/client/helpers.ts
> +	const pos = recentPkgList.indexOf(oldEmoji);
Actually, we do need the index to replace the old emoji.

2024-10-31 15:47 UTC, MarcosSpessatto approved these changes

2024-11-07 17:23 UTC, merged