feat: cancel subscription confirmation modal
RocketChat/Rocket.Chat pull request #33814
Opened 2024-10-28 18:18 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)
This PR adds a confirmation modal to the cancel subscription action available for workspaces with cancellable licenses.

## Issue(s)
[CONN-370](https://rocketchat.atlassian.net/browse/CONN-370)

## Steps to test or reproduce
- Access a workspace with Starter license
- Go to `/admin/subscriptions`
- Go to the bottom of the page and click "Cancel subscription"
- A confirmation modal should appear

## Further comments

2024-10-29 21:14 UTC, tassoevan requested changes

2024-10-29 21:14 UTC, tassoevan commented on apps/meteor/client/views/admin/subscription/hooks/useCancelSubscriptionModal.spec.tsx
> +			.withLatency(100)
"Test" and "latency" are two words that should never be together. Why is this necessary here?

2024-10-31 18:23 UTC, tassoevan approved these changes

2024-11-01 23:20 UTC, tassoevan approved these changes

2024-11-18 20:31 UTC, MartinSchoeler approved these changes

2024-11-18 21:13 UTC, merged