refactor: `pinMessage` method
RocketChat/Rocket.Chat pull request #33852
Opened 2024-10-31 17:07 UTC by KevLehman

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-11-06 16:53 UTC, abhinavkrin requested changes

2024-11-06 16:53 UTC, abhinavkrin commented on apps/meteor/app/message-pin/server/pinMessage.ts
> +	if (!(await hasPermissionAsync(userId, 'pin-message', originalMessage.rid))) {
Hey, I think we should have the check for already pinned message after this part. 
If the user does not have permission and the message is already pinned, they will get the original message which they should not.

2024-11-06 17:01 UTC, abhinavkrin approved these changes

2024-11-18 13:11 UTC, MarcosSpessatto requested changes
Can we create a Jira task for it?

2024-11-19 11:58 UTC, MarcosSpessatto approved these changes

2024-11-19 12:40 UTC, merged