chore: change oauth apps authorize page message
RocketChat/Rocket.Chat pull request #33952
Opened 2024-11-13 17:15 UTC by abhinavkrin

## Proposed changes (including videos or screenshots)

This PR updates the authorization message on the OAuth Apps authorization page to make it clearer to users that the app will have full, unrestricted access to their account. The new message explicitly informs users that the app can perform any action on their behalf, emphasizing the importance of authorizing only trusted applications.
<img width="615" alt="Screenshot 2024-11-13 at 10 43 07 PM" src="https://github.com/user-attachments/assets/2cca88c8-04c8-4304-b3af-fe34532805a0">

## Issue(s)

## Steps to test or reproduce

## Further comments

[VLN-24](https://rocketchat.atlassian.net/browse/VLN-24)
[CORE-644](https://rocketchat.atlassian.net/browse/CORE-644)

2024-11-13 17:36 UTC, julio-cfa submitted a review, later dismissed
Looks good to me. The message is clear and explains well the risks of trusting shady third-party apps.

2024-11-14 11:42 UTC, MarcosSpessatto submitted a review, later dismissed

2024-11-14 16:20 UTC, yash-rajpal requested changes
I see we are not using `access_your_basic_information` translation anywhere else, so we can remove this translation as well.

What do you think?

2024-11-14 16:33 UTC, yash-rajpal approved these changes

2024-11-15 11:32 UTC, merged