chore: Use visitor activity to define if its contact is unknown
RocketChat/Rocket.Chat pull request #33993
Opened 2024-11-19 15:27 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - Do not tag visitor contact as unknown if it has already been active

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-11-25 18:08 UTC, pierre-lehnen-rc submitted a review, later dismissed

2024-11-25 19:23 UTC, MarcosSpessatto requested changes

2024-11-25 20:01 UTC, matheusbsilva137 commented on apps/meteor/app/livechat/server/lib/contacts/mapVisitorToContact.ts
> +		unknown: !visitor.activity?.length,
Done!

2024-11-26 10:24 UTC, MarcosSpessatto approved these changes

2024-11-26 13:42 UTC, KevLehman approved these changes

2024-11-26 13:46 UTC, merged