fix: livechat appearance not savable on CE servers
RocketChat/Rocket.Chat pull request #34013
Opened 2024-11-21 15:08 UTC by MartinSchoeler

## Proposed changes (including videos or screenshots)

Fixes issue that caused servers that never had an EE license not being able to save livechat appearance, this was caused due the server never generating the EE settings, thus there were no default values to assign to the fields on the FE

## Issue(s)

closes #33407

## Steps to test or reproduce

2024-11-21 16:07 UTC, MartinSchoeler commented
<img width="1284" alt="Screenshot 2024-11-21 at 13 07 01" src="https://github.com/user-attachments/assets/f1c0cecf-0604-4c05-9903-77748b0f27d1">
As expected the test failed without the fix

2024-11-21 16:56 UTC, tiagoevanp approved these changes

2024-11-25 13:16 UTC, dougfabris requested changes

2024-11-25 13:16 UTC, dougfabris commented on apps/meteor/client/views/omnichannel/appearance/AppearancePage.tsx
why not take the advantage of the map you're already doing and check if the value is empty instead of filtering again?

2024-11-25 14:32 UTC, dougfabris approved these changes
LGTM!

2024-11-25 18:40 UTC, merged