chore: remove meteor.startup from permalink-star
RocketChat/Rocket.Chat pull request #34022
Opened 2024-11-21 18:42 UTC by MartinSchoeler

[ARCH-1369](https://rocketchat.atlassian.net/browse/ARCH-1369)

2024-11-21 19:52 UTC, dougfabris requested changes

2024-11-21 19:52 UTC, dougfabris commented on apps/meteor/client/components/message/toolbar/usePermalinkStar.tsx
> +			// classes: 'clipboard',
```suggestion

```

2024-11-21 19:52 UTC, dougfabris commented on apps/meteor/client/components/message/toolbar/usePermalinkStar.tsx
> +				try {
what do you think about using our `useClipboard`

2024-11-22 19:31 UTC, dougfabris approved these changes
LGTM!

2024-11-22 22:24 UTC, tassoevan approved these changes

2024-11-25 05:17 UTC, merged