regression: Do not throw an error on custom fields validation when migrating visitors to contacts
RocketChat/Rocket.Chat pull request #34030
Opened 2024-11-21 21:20 UTC by matheusbsilva137

## Proposed changes (including videos or screenshots)

 - In case an invalid custom field is found when migrating a visitor to a contact, we should just not use it instead of failing the whole process.

## Issue(s)

## Steps to test or reproduce

## Further comments

[SCI-179]

2024-11-22 21:47 UTC, KevLehman approved these changes

2024-11-23 05:49 UTC, KevLehman requested changes
Pls fix tests

2024-11-25 12:55 UTC, pierre-lehnen-rc requested changes
If an invalid value is already saved on the visitor, we shouldn't just discard it.
Let's register that value as a conflict for the custom field instead.

Also: we probably need to do the same thing on the merge process.

2024-11-26 13:43 UTC, KevLehman approved these changes

2024-11-26 19:07 UTC, merged