chore: Hide discussions created for Video Conference Calls
RocketChat/Rocket.Chat pull request #34128
Opened 2024-12-05 20:18 UTC by lucas-a-pelegrino

## Proposed changes (including videos or screenshots)

This PR adds logic to hide discussions created for Video Conference Calls (Persistent Chat) by default.

## Issue(s)

[CORE-804](https://rocketchat.atlassian.net/browse/CORE-804)

## Steps to test or reproduce

1. Install an app provider for video calls;
2. Setup Conference Calls in the workspace's settings.
3. Enable Persistent Chat in the Conference Calls settings.
4. Make a call to someone and see that the discussions will be created hidden (in the sidebar) by default.

## Further comments

2024-12-05 23:17 UTC, pierre-lehnen-rc requested changes

2024-12-05 23:17 UTC, pierre-lehnen-rc commented on apps/meteor/app/lib/server/functions/createRoom.ts
> +		const extra: Partial<ISubscriptionExtraData> = options?.subscriptionExtra || { open: true };
```suggestion
		const extra: Partial<ISubscriptionExtraData> = { open: true, ...options?.subscriptionExtra };
```

2024-12-06 21:19 UTC, KevLehman commented on apps/meteor/tests/end-to-end/apps/video-conferences.ts
> +				it('should have created the discussion room with hidden subscription flag', async function () {
not sure if there's a `hidden` subscription flag, maybe we can name it just `should have created a subscription with open = false`

2024-12-06 21:19 UTC, KevLehman commented on apps/meteor/server/services/video-conference/service.ts
> +			await Room.addUserToRoom(rid, { _id: uid }, undefined, { skipAlertSound: true, skipSystemMessage: true, createAsHidden: true });
In the code you're assinging `false` to alert when `createAsHidden` is true, so passing `skipAlertSound` is not needed.

2024-12-13 17:36 UTC, MarcosSpessatto approved these changes

2024-12-13 17:50 UTC, KevLehman approved these changes

2024-12-16 20:59 UTC, merged