feat: `rooms.close` endpoint
RocketChat/Rocket.Chat pull request #34208
Opened 2024-12-17 23:04 UTC by aleksandernsilva

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2025-02-04 14:21 UTC, KevLehman commented on apps/meteor/app/api/server/v1/rooms.ts
> +				return API.v1.failure('Invalid user');
This is a breaking change :/

(Not removing the Meteor error, but changing the error message. We should go with the `error-invalid-user` as it can be used to translate it on UI)

2025-02-04 14:21 UTC, KevLehman commented on apps/meteor/tests/end-to-end/api/rooms.ts
> +			void request
write tests with promises instead :)

2025-02-04 15:14 UTC, KevLehman commented on apps/meteor/app/api/server/v1/rooms.ts
> +				return API.v1.failure('Invalid user');
nvm im dum

2025-02-04 15:51 UTC, KevLehman requested changes

2025-02-04 15:51 UTC, KevLehman commented on apps/meteor/app/api/server/v1/rooms.ts
> +	'rooms.close',
wonder why this is called `.close` if we call `hideRoom` inside 🤔

2025-02-04 15:51 UTC, KevLehman commented on apps/meteor/app/api/server/v1/rooms.ts
> +			const subscription = await Subscriptions.findOneByRoomIdAndUserId(roomId, this.userId);
You can pass a projection here iirc (not sure if the method accepts)

2025-02-04 16:06 UTC, aleksandernsilva commented on apps/meteor/app/api/server/v1/rooms.ts
> +	'rooms.close',
I wondered the same thing on the FE. Client-side it is "hide room", server side "close room" (`channels.close`, `dm.close`), probably as a counterpart to the "open room" (`channels.open`, `dm.open`).

Considering this is an old name convention, do you think it is worth it renaming it to `rooms.hide` and align FE and BE?

2025-02-10 16:54 UTC, aleksandernsilva commented on apps/meteor/app/api/server/v1/rooms.ts
> +	'rooms.close',
Going with `rooms.hide` to keep the endpoint name true to its function.

2025-02-10 17:35 UTC, KevLehman requested changes

2025-02-10 17:35 UTC, KevLehman commented on apps/meteor/app/api/server/v1/rooms.ts
> +				return API.v1.failure('error-room-already-closed');
```suggestion
				return API.v1.failure('error-room-already-hidden');
```

2025-02-10 17:35 UTC, KevLehman commented on apps/meteor/app/api/server/v1/rooms.ts
> +			const subscription = await Subscriptions.findOneByRoomIdAndUserId(roomId, this.userId, { projection: { open: 1 } });
I'm thinking you could create a new subs method called `findOneOpenByRoomIdAndUserId` that checks if open is true, so you don't fetch the Sub if it's already closed

2025-02-10 17:35 UTC, KevLehman commented on apps/meteor/app/api/server/v1/rooms.ts
> +			const user = await Users.findOneById(this.userId, { projections: { username: 1 } });
Don't see you using the username, you can just pass `_id: 1` to the projection

2025-02-13 14:20 UTC, KevLehman approved these changes

2025-02-13 18:26 UTC, MarcosSpessatto requested changes

2025-02-13 18:26 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/rooms.ts
> +			roomB = (await createRoom({ type: 'd', username: memberB.username })).body.room;
Shouldn't we delete this room too?

2025-02-14 13:29 UTC, MarcosSpessatto approved these changes

2025-02-14 13:57 UTC, KevLehman approved these changes

2025-02-14 22:59 UTC, merged