chore: refactor new room sound
RocketChat/Rocket.Chat pull request #34207
Opened 2024-12-17 21:13 UTC by ggazzo

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2024-12-18 14:07 UTC, aleksandernsilva requested changes
Considering the current PR title, changing it to `refactor: new room sound` might be a better fit.

2024-12-18 18:44 UTC, ggazzo commented on apps/meteor/client/hooks/useOmnichannelContinuousSoundNotification.ts
> +	const hasUnreadRoom = userSubscriptions.length > 0 && queue.length > 0;
yep sorry

2024-12-18 18:45 UTC, ggazzo commented on apps/meteor/client/hooks/useOmnichannelContinuousSoundNotification.ts
> +	const hasUnreadRoom = userSubscriptions.length > 0 && queue.length > 0;
```suggestion
	const hasUnreadRoom = userSubscriptions.length > 0 || queue.length > 0;
```

2024-12-18 18:47 UTC, ggazzo commented on apps/meteor/client/hooks/useNotifyUser.ts
> +			KonchatNotification.newRoom();
not anymore the rid was used to be added to Session, but I removed that `Session`

2024-12-19 12:28 UTC, aleksandernsilva approved these changes

2024-12-19 13:25 UTC, merged