feat: Adds setting to ignore automatic messages on metrics
RocketChat/Rocket.Chat pull request #34274
Opened 2024-12-20 18:36 UTC by lucas-a-pelegrino

## Proposed changes (including videos or screenshots)

This PR adds a new setting to consider or not automatic messages (bot messages) on response time metrics.
## Issue(s)

[CORE-668](https://rocketchat.atlassian.net/browse/CORE-668)
## Steps to test or reproduce

## Further comments

2025-01-07 14:21 UTC, matheusbsilva137 requested changes

2025-01-07 14:21 UTC, matheusbsilva137 commented on apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
> +		((await isMessageFromBot(message)) && settings.get<boolean>('Omnichannel_Metrics_Ignore_Automatic_Messages'))
```suggestion
		(settings.get<boolean>('Omnichannel_Metrics_Ignore_Automatic_Messages') && (await isMessageFromBot(message)))
```
Not a big deal, but I believe it's better to delay `isMessageFromBot` as much as we can since it requires a DB call

2025-01-07 14:21 UTC, matheusbsilva137 commented on apps/meteor/app/livechat/server/hooks/saveAnalyticsData.ts
> +			((await isMessageFromBot(message)) && settings.get<boolean>('Omnichannel_Metrics_Ignore_Automatic_Messages'))
```suggestion
			(settings.get<boolean>('Omnichannel_Metrics_Ignore_Automatic_Messages') && (await isMessageFromBot(message)))
```
Same here

2025-01-07 14:21 UTC, matheusbsilva137 commented on apps/meteor/tests/unit/app/livechat/server/lib/isMessageFromBot.spec.ts
> +describe('isMessageFromBot', () => {
Please add a test case for when `findOneById` returns `undefined` (user doesn't exist)

2025-01-07 14:29 UTC, lucas-a-pelegrino commented on apps/meteor/app/livechat/server/hooks/markRoomResponded.ts
> +		((await isMessageFromBot(message)) && settings.get<boolean>('Omnichannel_Metrics_Ignore_Automatic_Messages'))
That actually is a big deal, good catch, bro!

2025-01-23 11:54 UTC, MarcosSpessatto requested changes

2025-01-23 11:54 UTC, MarcosSpessatto commented on .changeset/funny-turtles-hunt.md
> +"@rocket.chat/i18n": patch
```suggestion
"@rocket.chat/meteor": minor
"@rocket.chat/i18n": minor
```

2025-01-23 11:54 UTC, MarcosSpessatto commented on apps/meteor/tests/end-to-end/api/livechat/04-dashboards.ts
> +			await updateSetting('Omnichannel_Metrics_Ignore_Automatic_Messages', true);
Can we put this on `before` and reset it on `after`?

2025-01-23 11:54 UTC, MarcosSpessatto commented on apps/meteor/tests/unit/server/livechat/hooks/markRoomResponded.spec.ts
> +	it('should return void if message is from bot and setting is enabled', async () => {
Can we add a case for when the message is from a bot but the message is disabled?

2025-01-23 11:54 UTC, MarcosSpessatto commented on packages/i18n/src/locales/en.i18n.json
> +  "Airgapped_workspace_restriction": "This air-gapped workspace is in read-only mode. <2>Connect it to the internet or upgrade to a premium plan to restore full functionality.</1>",
Is this change related? If not, please remove it

2025-01-23 11:54 UTC, MarcosSpessatto commented on packages/i18n/src/locales/en.i18n.json
> -  "Omnichannel_allow_force_close_conversations_alert": "Only enable if your workspace has issues with rooms with invalid states.",
Is this intentional?

2025-01-23 11:54 UTC, MarcosSpessatto commented on packages/i18n/src/locales/en.i18n.json
> -  "Install_Zapier_from_marketplace_new_workspaces": "Install the Zapier app from Marketplace to configure new integrations",
Is this intentional?

2025-01-23 14:23 UTC, lucas-a-pelegrino commented on apps/meteor/tests/unit/server/livechat/hooks/markRoomResponded.spec.ts
> +	it('should return void if message is from bot and setting is enabled', async () => {
You mean "the setting is disabled"?

If that's the case, it should sum the message along with non bot users, that should be covered already. But I can double check.

2025-01-23 14:24 UTC, lucas-a-pelegrino commented on packages/i18n/src/locales/en.i18n.json
> +  "Airgapped_workspace_restriction": "This air-gapped workspace is in read-only mode. <2>Connect it to the internet or upgrade to a premium plan to restore full functionality.</1>",
That shouldn't be here... I'll check what happened.

2025-01-23 16:07 UTC, KevLehman requested changes

2025-01-23 16:07 UTC, KevLehman commented on apps/meteor/app/livechat/server/lib/isMessageFromBot.ts
> +export async function isMessageFromBot(message: IMessage): Promise<boolean> {
Why not use `Users.isUserInRole`?

2025-01-23 16:41 UTC, lucas-a-pelegrino commented on apps/meteor/app/livechat/server/lib/isMessageFromBot.ts
> +export async function isMessageFromBot(message: IMessage): Promise<boolean> {
I wasn't aware of this method, definitely worth to use it.

2025-01-24 20:02 UTC, MarcosSpessatto requested changes

2025-01-24 20:02 UTC, MarcosSpessatto commented on apps/meteor/app/livechat/server/lib/isMessageFromBot.ts
> +export async function isMessageFromBot(message: IMessage): Promise<boolean> {
Why not use the model method directly instead of creating this new template method (function)?

2025-01-24 20:04 UTC, lucas-a-pelegrino commented on apps/meteor/app/livechat/server/lib/isMessageFromBot.ts
> +export async function isMessageFromBot(message: IMessage): Promise<boolean> {
Mainly, for readability.

2025-01-29 12:23 UTC, MarcosSpessatto approved these changes

2025-01-29 18:45 UTC, KevLehman approved these changes

2025-02-18 17:45 UTC, merged