feat: Audit users.update API endpoint
RocketChat/Rocket.Chat pull request #34494
Opened 2024-12-24 00:36 UTC by gabriellsh

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

2025-01-27 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=34494) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat?pullRequest=34494) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: gabriellsh<br/>:x: Gabriel Henriques<br/><hr/>**Gabriel Henriques** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat?pullRequest=34494) it.</sub>

2025-03-18 14:37 UTC, gabriellsh commented
@kody start-review

2025-03-19 11:14 UTC, MarcosSpessatto requested changes

2025-03-19 11:14 UTC, MarcosSpessatto commented on apps/meteor/app/api/server/v1/users.ts
> +				_id: this.bodyParams.userId,
Is this correct? I mean, shouldn't it be the logged user id instead? Otherwise the `actor` will mix the information from the users with the _id of the user that was edited and the username of the use who edited it.

```
 "actor" : {
        "_id" : "rocket.cat",
        "IP" : "...",
        "useragent" : "...",
        "username" : "marcos.defendi",
        "type" : "user"
    },
```

2025-03-19 15:44 UTC, MarcosSpessatto submitted a review, later dismissed

2025-03-19 19:05 UTC, pierre-lehnen-rc requested changes
Not a big deal but I'd prefer if extra data like the `active` here was passed on from outside instead of adding it automatically whenever the function gets called.
As it is, you're assuming that any place that calls saveUser will also call setUserActiveStatus.

2025-03-19 19:05 UTC, pierre-lehnen-rc commented on apps/meteor/app/lib/server/functions/saveUser/saveUser.ts
> +				if (userData.active) {
```suggestion
				if (userData.active !== undefined) {
```
Should log deactivations too, no?

2025-03-19 19:12 UTC, pierre-lehnen-rc commented on apps/meteor/server/lib/auditServerEvents/userChanged.ts
> +			if (key === 'email2fa') {
For future reference, once we started auditing users created/updated from external services, we might want to expand this with an extended list of useful information from the services that shouldn't be censored out.

2025-03-19 19:39 UTC, pierre-lehnen-rc approved these changes

2025-03-19 20:43 UTC, MarcosSpessatto approved these changes

2025-03-25 17:09 UTC, merged