fix: Inactive Clients Not Refreshing Action Buttons After App Deployment
RocketChat/Rocket.Chat pull request #34849
Opened 2024-12-30 17:17 UTC by Gustrb

## Proposed changes (including videos or screenshots)

Currently, when the app is redeployed, active clients properly fetch and display the updated action buttons (via GET /apps/actionButtons). However, any clients that were inactive during the deployment (e.g., a laptop in sleep mode) do not fetch the updated list upon becoming active again. As a result, these inactive clients continue using outdated actionIds, causing inconsistent and potentially broken interactions.

So now, everytime the client goes offline, we invalidate the cache, since the buttons might have changed in the meantime

## Issue(s)

## Steps to test or reproduce

Start with the client active and confirm it fetches updated action buttons upon deployment.
Put the client into an inactive state (e.g., close laptop lid or simulate a network disconnection), then redeploy the app.
Reactivate the client and verify that it immediately retrieves the updated action buttons list.
Repeat steps 2-3 for multiple clients to ensure consistent behavior across different endpoints and environments.

Note: You can use `Meteor.disconnect` to test socket reconnection

## Further comments

[CONN-434](https://rocketchat.atlassian.net/browse/CONN-434)

2024-12-30 17:33 UTC, Gustrb commented on apps/meteor/client/hooks/useAppActionButtons.ts
> +			const isOffline = !Meteor.status().connected;
Hey @tassoevan we were talking about trying to have some kind of less-indirect way of telling when the socket disconnected, I found that Meteor.status is what we used in similar situations so I decided to try to implement using it here, but if you thing this approach is not good I guess we can try to find something different

2025-01-09 13:09 UTC, Gustrb commented
@Harmeet221 gave us her blessing on this one.

2025-01-09 13:45 UTC, gabriellsh requested changes

2025-01-09 13:45 UTC, gabriellsh commented on apps/meteor/client/hooks/useAppActionButtons.ts
> +	useEffect(() => {
You can use `useStatusConnection` hook for this. It's pretty much the same thing

2025-01-09 14:23 UTC, gabriellsh requested changes

2025-01-09 14:23 UTC, gabriellsh commented on apps/meteor/client/hooks/useAppActionButtons.ts
> +	const { status } = useConnectionStatus();
Please use `status` in the query key and disable the query if `status !== 'connected;` as we discussed in dm

2025-01-10 22:19 UTC, tassoevan approved these changes

2025-01-13 14:24 UTC, merged