fix: Retain selected language for presence status in User Status settings after saving.
RocketChat/Rocket.Chat pull request #34857
Opened 2024-12-31 13:18 UTC by AyushKumar123456789

## Proposed changes (including videos or screenshots)

## Issue(s)
Closes #34856 
## Steps to test or reproduce
### Before : 

https://github.com/user-attachments/assets/f683e8a9-c50c-454b-9c23-585a0fe5930a

### After :
![image](https://github.com/user-attachments/assets/00476c94-c08d-4edb-b54b-0b12ba6ec480)
 
## Further comments

2024-12-31 15:15 UTC, gabriellsh submitted a review, later dismissed

2024-12-31 15:15 UTC, gabriellsh commented on .changeset/seven-otters-worry.md
> +Fixes an issue where the language preference was not being applied to the custom user status page, specifically for the status options in the table. The fix ensures the status options are translated
```suggestion
Fixes an issue where custom status' values in the custom status page table were not being properly translated
```

2024-12-31 15:48 UTC, tassoevan approved these changes

2024-12-31 15:51 UTC, yash-rajpal approved these changes

2024-12-31 17:47 UTC, AyushKumar123456789 commented
I'm not an expert in this, but are these errors during the merge happening with every PR, or could there be another issue causing them ?

2025-01-08 13:33 UTC, yash-rajpal submitted a review, later dismissed

2025-01-20 19:36 UTC, dougfabris requested changes
we already have a enum for the statuses: `UserStatus` you can get it from `@rocket.chat/core-typings` instead of creating a new one

2025-02-08 21:16 UTC, merged