fix: Files contextual bar reactivity
RocketChat/Rocket.Chat pull request #34860
Opened 2024-12-31 17:55 UTC by yash-rajpal

## Proposed changes (including videos or screenshots)

## Issue(s)

## Steps to test or reproduce

## Further comments

[SUP-609](https://rocketchat.atlassian.net/browse/SUP-609)

2024-12-31 18:12 UTC, gabriellsh requested changes

2024-12-31 18:12 UTC, gabriellsh commented on .changeset/nasty-shirts-rule.md
> +Fixes an issue with incoming file messages on files contextual bar
```suggestion
Fixes an issue where the room's file list wouldn't display new files in real time
```

2024-12-31 18:12 UTC, gabriellsh commented on apps/meteor/client/hooks/lists/useStreamUpdatesForMessageList.ts
> +			onMessage?.(message);
maybe we need one for removed messages also?

2025-01-17 16:49 UTC, yash-rajpal commented on apps/meteor/client/hooks/lists/useStreamUpdatesForMessageList.ts
> +			onMessage?.(message);
Not needed now, product team decided to go the other way and not support reactivity on Files Tab.

2025-01-17 20:37 UTC, MarcosSpessatto approved these changes

2025-01-20 13:24 UTC, merged

2025-02-27 18:28 UTC, scuciatto commented
/backport 7.0.9

2025-02-27 18:30 UTC, scuciatto commented
/backport 7.1.5

2025-02-27 18:32 UTC, scuciatto commented
/patch 7.2.5

2025-02-27 18:34 UTC, scuciatto commented
/backport 7.2.5